### ISSUE TITLE
TechNotes not found for outstanding PNS scans / ISSUE #1000

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1000]
Hi guys,

The TechNotes aren't linked to the QC html pages for all of the outstanding PNS scans.

Could you please fix and regenerate the QC pages?

Thanks! 
:)

**Comment by DESm1th** [comment]
I'll look into this one

**Comment by DESm1th** [comment]
As an update: I've finished modifying datman to link the resources and to copy over checklist and blacklist entries when a subject is linked, but I'm going to write tests for this tomorrow before I merge it into our repo so I don't break new things.

**Comment by tomwright01** [comment]
This was issue 1000. Next time i think we should have a better title!

**Comment by DESm1th** [comment]
Done! Changes are merged into our github repo. I can't pull to our local one though, still, so after Tom's next merge I'll regenerate the broken pages.

Side note: We're up to 110 unit tests in total now! Woohoo. Test all of the things!

**Comment by DESm1th** [comment]
Pages are regenerated, and everything is working as it should be. Only 3 PNS scans actually need to be signed off on.
