### ISSUE TITLE
Repeat data not represented on QC pages?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1001]
It seems to be the case that the data from 'repeated' scans (e.g., _01_02) is not represented on the QC pages. Said alternately, the QC pages only display data from the repeat value = 01, and none from repeat value = 02.

Example: QC page for SPN01_MRP_0082_01, which should combine data from SPN01_MRP_0082_01_01 and SPN01_MRP_0082_01_02, but only has data from SPN01_MRP_0082_01_01.

Not sure if this was always the case, or if it's a known issue(?)

**Comment by DESm1th** [comment]
Hey Navona,

This is due to the fact that qc-report doesn't attempt to generate a page if an html page exists in the qc folder already. So in this case the _01_02 data was added after an html page had been generated for just the _01_01 data, and so the page hasn't been rewritten/updated to reflect the new data. I'm regenerating the page now.

In order to avoid this in the future we'll either have to change the way we organize things a bit, or else run the --rewrite flag every night in our cron job.

**Comment by navonacalarco** [comment]
Thanks Dawn!

If it's not a huge undertaking, my opinion is that it would be good to have the QC pages regenerate in the instance of a repeat scan.

There's a few instances I can see where the repeat scan has been signed off on though the QC page was never regenerated - while perhaps the data was reviewed directly by our staff, we should make things as easy and automatic as possible as the Dashboard is increasingly shared with people without access to the file system, etc. 

Maybe we can discuss at our next meeting?

On a related note, does the repeat data make it into the cross-participant metrics?

**Comment by DESm1th** [comment]
I haven't looked at the dashboard at all so I'm not sure about cross-participant metrics. The repeat scans appearing signed off is probably a reflection of the fact that we only have the one page entry in checklist.csv so any repeat sessions coming in will automatically appear 'signed off' if the original session has been. 

I think it would be a good idea to discuss this next time we all meet. There are a few weird quirks like this resulting from how we organize our data and our code that might be good to talk about.

**Comment by navonacalarco** [comment]
Thanks again Dawn.

@djoverton @tomwright01 Let's discuss potential of QC pages to automatically regenerate in cases of repeats, and a couple of other things, that will be important as we make the Dashboard available to external users.
