### ISSUE TITLE
Dashboard: Add X-axis labels to 'Subjects' tab

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1004]

**Comment by tomwright01** [comment]
Is done (kinda). There is no simple way to add axis labels, especially when plotting multiple site data on the same figure. 
Modified the mouse-over function to display the session name.

**Comment by navonacalarco** [comment]
It might just be me, but I don't see the session name in the mouse-over function... am I doing something wrong?

![screenshot - 01192017 - 05 03 49 pm](https://cloud.githubusercontent.com/assets/13733654/22127313/6e93b9a0-de69-11e6-9a3e-8387bd81e86b.png)

**Comment by tomwright01** [comment]
Good point, needs a hard reload (ctrl-f5 in chrome).

**Comment by navonacalarco** [comment]
Thank you! This is beautiful!

**Comment by djoverton** [comment]
One possible downside to this solution is that the exact y value is no longer displayed on mouseover. Is it possible to do both, Tom?

**Comment by tomwright01** [comment]
It is, I'll add it back.

**Comment by tomwright01** [comment]
Done.
This change may need a 'hard reload' in some browsers.
Usually this is achieved with ctrl + f5 (windows) or command + R (mac).
@navonacalarco - would you share this information with other people.

**Comment by navonacalarco** [comment]
@tomwright01 Sure, thanks!

Just for the record, I'm planning on sharing (1) new tags and need to hard reload, and (2) new automatic blacklist (no need to file an issue).

Is there anything I'm forgetting?
