### ISSUE TITLE
Invalid subject ID PRE01_IWA_04008_02

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1006]
@edickie @josephdviviano 

This subject has sessions:
a) PRE01_IWA_04008_01_01
b) PRE01_IWA_04008_02
c) PRE01_IWA_R04008_02
posted to XNAT. Sessions b & c are incorrectly labelled, I assume they should be PRE01_IWA_X04008_02_01 but in the absence of PRE01_IWA_R04008_01_01 I thought I should check.

Thanks,
tom

**Comment by edickie** [comment]
the scan dates confirm that b and c are indeed year 2 scans - updating data
in XNAT now
