### ISSUE TITLE
Dashboard database locking

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1018]
Dashboard database select  are failing due to 'Database locked' errors. This error indicates the database is busy (i.e. trying to select while an insert is occurring on the same table).

Write-ahead-logging [WAL](https://www.sqlite.org/wal.html) is a potential solution. To enable this the database will need moving for NFS filesystem (/archive/code) to somewhere local to the insert / select processes. 

Suggest moving dashboard.sqlite from /archive/code/dashboard to somewhere local on tigrsrv.

Any thoughts?

**Comment by DESm1th** [comment]
Hmm that could work. Looking into the error, it seems that SQLite's timeout is set to 4-5 seconds by default. Which means whenever this occurs something is trying to write and taking a really long time to do it... The write ahead log should stop this from causing crashes in the select statements but it might still be worth figuring out what is causing certain writes to hold on to the database for so long, since it could be indicative of a deeper problem.

**Comment by tomwright01** [comment]
@DESm1th @djoverton @josephdviviano @edickie 

I think the deeper problem is probably NFS :-(

Unfortunately moving the database is a bit more complex than I thought. We need database access from:
tigrsrv - (parse_qc.py) main source of insert / select statements
srv-dashboard - (website) primarily select statements, low frequency but could increase
desktops - (data analysis) primarily select statements

To move the db local to tigrsrv will require:
- copying the db e.g. to /dashboard-database
- creating an nfs export on tigrsrv
- mounting the nfs export on srv-dashboard and desktops

Alternately we could switch up and move to a 'proper' network db (postgres). Good news is the flask framework should just support the transition without any (major) code changes.
This will involve:
- installing postgres 
- migrating database schema and data
- modifying dashboard to point to the new db.

Pls vote on your prefered solution:
1. Move the sqlite db to tigrsrv.
2. Install postgres on tigrsrv. :+1: 
3. Install postgres on srv-dashboard.
4. Install postgres on a new virtual machine.

**Comment by tomwright01** [comment]
DB has been moved to postgres running on a virtual server srv-dashboard. 
Closing, please re-open if locking issues are seen in logs.
