### ISSUE TITLE
Three VIPR scans not being pulled from MR server

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1019]
The following scans were uploaded a while ago (two of them about two weeks ago), but haven't been picked up and moved to the file system yet for some reason. 

VIPR_CMH_2115_01_01
VIPR_CMH_2113_02_01
VIPR_CMH_2114_01_01

**Comment by navonacalarco** [comment]
Gah. I actually have a meeting with the VIPR RA to QC this bunch today, at 3:30. Any way we can get these in by then?

**Comment by DESm1th** [comment]
.. oh! Er. Ok, I'll start working on this now then. I can't say when it'll be fixed since I'm not sure what the issue actually is but I'll do my best

**Comment by DESm1th** [comment]
Tom is working on a fix for dm2-sftp.py

**Comment by DESm1th** [comment]
The zipfiles are on our system now, and a linking issue with VIPR_CMH_2115_01_01 has been fixed, so the outputs should appear tomorrow.

**Comment by JessDArcey** [comment]
Hi All! I can see the scans now and the structural data looks good but on all 3 new scans the spiral/run data says missing even though they were completed - could this be related?

**Comment by tomwright01** [comment]
This should all be good now.
