### ISSUE TITLE
Dashboard: QC to-do checklist generation sometimes gives error

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1026]
The following message is displayed occasionally after clicking on a QC to-do list tab: "An error occured getting the QC list. The admins have been notified". Seems to occur more frequently when filesystem slowdown is obvious; I'm guessing it has to do with the page fully loading before the QC checklist file can be read.

**Comment by navonacalarco** [comment]
@JessDArcey Tom and Dawson are working to fix this now - can you try refreshing and see if it's fixed for you?

**Comment by djoverton** [comment]
Server was reset and have been unable to replicate this since then; closing for now, will reopen if the problem appears again.
