### ISSUE TITLE
No passwd entry for user 'clevis'

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1027]
Our stuff broke! The log for Saturday came out ok but for some reason our passwd entry for clevis seems to have gone missing for Sunday and Today causing nothing to run at all... Investigating it now :(

**Comment by DESm1th** [comment]
Looks like the IPA server might be down

**Comment by tomwright01** [comment]
This was a long standing problem that was being hidden. sssd was failing to authenticate users against the ipa server, instead we were being authenticated against an out of date cache.

Symptom:
`$getent passwd <username>` would not return anything for users who had never logged into a particular system.

Solution:
1. Login as admin user to a console (not terminal).
2. `$ipa-client-install --uninstall`
3. `$ipa-client-install --uninstall` (don't ask, just do it twice).
4. Reboot
5. Login as admin user
6. `$ipa-client-install --server=rprshipav01.camhres.ca --domain=camhres.ca` N.B. you need permission to add hosts to IPA for this step.

**Comment by DESm1th** [comment]
Wow nice catch! I don't have permission to add anything to IPA :( Are you guys completing these steps?

**Comment by tomwright01** [comment]
I'm completing the steps on the desktops as they become available.

Outstanding:
[] Crick
[] Franklin
[] Penfield
 All in the other room.

**Comment by tomwright01** [comment]
@josephdviviano the above process didn't fix mansfield. Any ideas?

**Comment by josephdviviano** [comment]
Looking into this further --

The problems regarding home directories not being available at `/imaging/kimel/yadda/yadda` is because `/etc/sssd/sssd.conf` is not configured correctly.

Ansible manages this normally using the following line `override_homedir = /home/%u`.

I'm apprehensive to run ansible on the machines with Qing offsite -- Tom's fix seems to be working, so hold on for now.

**Comment by josephdviviano** [comment]
also potentially interesting during `ipa-client-install`:

```
iscovery was successful!
Hostname: mansfield.camhres.ca
Realm: CAMHRES.CA
DNS Domain: camhres.ca
IPA Server: rprshipav01.camhres.ca
BaseDN: dc=camhres,dc=ca

Continue to configure the system with these values? [no]: yes
Removed old keys for realm CAMHRES.CA from /etc/krb5.keytab
User authorized to enroll computers: jviviano
Synchronizing time with KDC...
Unable to sync time with IPA NTP server, assuming the time is in sync. Please check that 123 UDP port is opened.
```

**Comment by tomwright01** [comment]
I got the NTP error on ~50% of machines. I put it down to network timeouts
but have no evidence to back that idea.

**Comment by josephdviviano** [comment]
Confirmed that `nscd` was broken... uninstalled / reinstalled using

```
apt-get remove --purge nscd
apt-get install nscd
````

Now attempting to unenroll / re-enrol mansfield using `--force-join`.

**Comment by josephdviviano** [comment]
@tomwright01 and I just figured it out, sort of.

What we did:

+ removed `certmonger sssd* freeipa-client krb5-config krb5-locales libnss3`
+ cleaned up: `apt-get autoremove`
+ reboot
+ `apt-get install freeipa-client` (which brought in all of the dependencies automatically)
+ on the freeipa web GUI, went to the mansfield 'host' entry, and selected 'unprovision' from the options. The kerberos entry near the bottom should say 'unprovisioned'.
+ `sudo ipa-client-install --server=rprshipav01.camhres.ca --domain=CAMHRES.CA`
+ test: `getent passwd jviviano`

**Comment by josephdviviano** [comment]
@tomwright found it!!

**Comment by TomWright** [comment]
@josephdviviano You tagged the wrong tomwright... @tomwright01 Check the above.

**Comment by josephdviviano** [comment]
:D
