### ISSUE TITLE
Dashboard: problem with VIPR scans 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1029]
Hey guys,

A couple issues with VIPR:

1. All of the VIPR scans show up on the checklist, including those that have been signed off on.

2. And, when we look at the scans that should be on the QC list (i.e., haven't been signed off on; 2113_02_01, 2114_01_01, 2115_01_01) the scan images are missing.

Mentioning @JDarcey

**Comment by DESm1th** [comment]
I'm not sure what happened but somehow a bunch of VIPR QC pages got deleted. I had noticed the deletion yesterday but hadn't gotten a chance to investigate. I'll regenerate the pages now and look into it.

**Comment by djoverton** [comment]
Was checklist.csv also deleted somehow? It appears to be there now.

**Comment by tomwright01** [comment]
I recently updated the regexs to link all (6) SPRL scans. I also added the --rewrite flag to dm-qc-report.py in the script to update the html.

**Comment by DESm1th** [comment]
Ok! I'm still not sure why the pages were deleted but I figured out why they wouldn't regenerate and fixed the bug. I'm regenerating/testing this now. I'll keep an eye out to make sure they don't mysteriously disappear again

**Comment by djoverton** [comment]
Missing QC pages alone wouldn't explain the incorrect QC to-do list though (which appears to still be incorrect, and shows all 22 sessions).

**Comment by djoverton** [comment]
Update: QC to-do list appears to correctly only list the 4 sessions that aren't sign off on now; did you change something that would have affected this, Dawn?

**Comment by DESm1th** [comment]
I regenerated all the VIPR QC pages that had mysteriously disappeared. I haven't changed anything else though. I think Tom made some modifications to the dashboard error messages with respect to the QC checklist, maybe his modifications cause missing QC pages to show up as not signed off?

**Comment by navonacalarco** [comment]
This seems to be corrected. Closing. Thanks guys!
