### ISSUE TITLE
DBDC_CMH_HDBD013_02_01 not in system

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1031]
Participant DBDC_CMH_HDBD013_02_01 (scan completed [here](https://edc.camhx.ca/redcap/redcap_v6.11.4/DataEntry/index.php?pid=441&page=tigrlab_scan_completed&id=104&event_id=2374&editresp=1)) was scanned last Monday.

The scans exists on the MR server (20170109_Ex06501_DBDC1MR_DBEL019.zip) but not in XNAT or our file system (and thus, not the Dashboard).

Not sure why! @DESm1th, could you help investigate?

**Comment by DESm1th** [comment]
Ah! I think this is a result of our IPA server issue causing our run scripts not to run. I'll check tomorrow, and if it's still missing after the run completes I'll investigate more.

**Comment by DESm1th** [comment]
Oops, I broke the run scripts with something tiny, so nothing ran last night :( I'll check on this tomorrow after they've run.

**Comment by DESm1th** [comment]
There was a small typo in the runscript that was causing a broken path to be generated when looking for the DBDC run script, so nothing was being run for the study. I've fixed this.
