### ISSUE TITLE
Cron jobs not running

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1033]
Since Jan 16th.
I think it's because the datman environment is not loaded when run.sh tries to start the log server.
@DESm1th could you take a look please?

**Comment by DESm1th** [comment]
Oops! I added the module load just before the log server call. I'll close this tomorrow if things are working again.

**Comment by DESm1th** [comment]
Hrm. Fixing the Clevis home directory and the datman module load issues didn't resolve this. The cron jobs still arent running. Investigating further.

**Comment by DESm1th** [comment]
I'm running the job manually as root on tigrsrv now, just because it's been about 5 days since it's run successfully. So today's (Jan 19th) logs are from my manual run.

**Comment by DESm1th** [comment]
Ok, I've investigated everything I can think of that might be wrong with our cron jobs and things seem ok. I also got cron to recognize a test job I added to /etc/cron.d/data and that worked. So if things fail again tomorrow I'm officially out of ideas!

**Comment by DESm1th** [comment]
Things are working again! Hurray.
