### ISSUE TITLE
Broad task ideas for new co-op student ?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1034]
Saba has arranged for us to have an undergrad co-op student for 5-7 hours a week. I believe the student has programming experience, and is interested in fMRI.

Does anyone have tasks they could add to this list?

- QC outstanding PASS study data
- help create Dashboard QC standardized training set (#980) and system of inter-rater agreement  (#981)

**Comment by DESm1th** [comment]
There are QC pages in a lot of the pipeline folders (such as for dtifit and enigmadti) that mostly don't get looked at or signed off on. It could be good to have someone check on those.

**Comment by navonacalarco** [comment]
FYI, Christian arrived and has a computer account!

@tomwright01 Before next Thursday, can we please add Christian to the Dashboard. For now, can he have access to the `PASS study` and the `Test study` - I will work on paperwork for anything else, if required

@edickie Can you please think of criteria for QCing  

- /dtifit/QC/qc_BET.html
- /dtifit/QC/qc_directions.html
- /enigmaDTI/QC/... AD?FA?MD?RD?

and for which studies, and where the checklist is kept?

Thanks!
N.
