### ISSUE TITLE
SPINS MRC 0007 Observe

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#1035]
In data/nii this scan has 100 TRs, in pipelnes/fmri/imob it has 16. Should be 100 and 106 respectivly. 

Something went wrong somewhere. Should be blacklisted?

**Comment by josephdviviano** [comment]
Colin, can you please watch what you type, you are reliably inaccurate and waste people's time.

Scans **should** have 110 TRs in their raw form and have 106 TRs when they are complete pre-processing.

You are correct that this subject is truncated (i.e., the raw data isn't complete), but those numbers are 100 and 96.

 I checked all scans and found two truncated scans:

```
SPN01_MRC_0007_01/SPN01_MRC_0007_01_01_OBS_12_EPI-2x2x3xTR3-Observation_MNI-nonlin.nii.gz: dim4 96

SPN01_MRP_0077_01/SPN01_MRP_0077_01_01_OBS_14_EPI-2x2x3xTR3-Observation_MNI-nonlin.nii.gz: dim4 49
```

blacklisting and deleting them now.
