### ISSUE TITLE
Dashboard: can't sign in

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1038]
Hey guys,

I can't sign into the Dashboard. I get this error:

![screenshot - 01182017 - 01 28 19 pm](https://cloud.githubusercontent.com/assets/13733654/22077393/037b870c-dd82-11e6-85bb-70a71b7568a6.png)

I've logged out and back in a few times. No luck. Any ideas?

**Comment by djoverton** [comment]
Just tried and it worked for me. It could be a timeout due to the general network slowdown that's been present for a couple of days. Try clearing your cache and logging in a few more times.

**Comment by navonacalarco** [comment]
Thanks! Was something about permissions, but Tom gave them back. :)
