### ISSUE TITLE
Dashboard: add column for 'repeat' to main participant page?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1039]
Hey guys,

I QC'd a scan with a repeat today, and I thought it would be helpful to add a column to the participant page that reflects `Repeat number`, in addition to `Series`. This is because, when a repeat scan has occurred, two scans will have the same `Series` number.

![screenshot - 01182017 - 03 09 05 pm](https://cloud.githubusercontent.com/assets/13733654/22081314/1960037c-dd91-11e6-8f80-e82f6d618cc9.png) (Example from SPN01_CMH_0107_01)

Not urgent, but would add clarity and I think lessen the likelihood that the wrong scan is blacklisted.

What do you think?

**Comment by djoverton** [comment]
Changed the session page to generate repeat number in the table.

**Comment by navonacalarco** [comment]
Thanks!
