### ISSUE TITLE
Dashboard: add sample data to a training project

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1043]
@djoverton will get back to you with subject IDs soon

**Comment by navonacalarco** [comment]
SPN01_CMH_0054_01
SPN01_CMH_0113_01
SPN01_CMH_0016_01
SPN01_CMH_P001_01
SPN01_CMH_P001_02
SPN01_CMH_P001_03

I think it's ok to get this ready. Will email P's and let you know if anyone disagrees.

**Comment by djoverton** [comment]
Sounds good.

**Comment by djoverton** [comment]
Fixed permissions for the TRAIN project README.md and listed the above subjects there for reference. I'll keep this project open in case data is added in the future that is used strictly for QC purposes, but in retrospect there's no sense duplicating the SPINS data (in fact that might be confusing).
