### ISSUE TITLE
SPN01_CMH_0104_01 rest pipeline data

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1046]
Colin can't find it, track it down.

**Comment by colinhawco** [comment]
There are two resting scans in the nii folder /archive/data/SPINS/data/nii/SPN01_CMH_0104_01/. The second is truncated at 150 TRs and should be removed. 

If SPN01_CMH_0104_01_01_RST_13_Ax-Obl-Resting-State.nii.gz is blacklisted and removed I believe this should solve the problem. 

Though you might refer to tech notes to figure out why an apparently second resting scan was run but then truncated. The short scan, I believe, was series 13, while the original was series 07, if I am understanding the file names correctly. This implies they collected a full resting state, and then did a second one later which they cancelled part way through. Again, if I am understanding the file names correctly. 

colin@tesla:/archive/data/SPINS/data/nii/SPN01_CMH_0104_01$ fslinfo SPN01_CMH_0104_01_01_RST_13_Ax-Obl-Resting-State.nii.gz
data_type      INT16
dim1           64
dim2           64
dim3           37
**dim4           150**
datatype       4
pixdim1        3.437500
pixdim2        3.437500
pixdim3        4.000014
pixdim4        2.000000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

**Comment by navonacalarco** [comment]
@colinhawco. Thanks. You were right; there's an extra scan in there for no clear reason. I blacklisted it. So, this participant's data should appear in he pipeline output tomorrow. :)
