### ISSUE TITLE
PASAD and RTMSAD have incorrect subject names - obtain or create a mapping

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1048]

**Comment by tomwright01** [comment]
Bumping this as there are another 5 scans that can't be processed.

`dm2-link.py` cannot extract study identifier from dicom headers for several subjects in this study. Entries cannot be made manually as we don't know if they are follow-up visits. @djoverton hit this problem earlier. Was a solution worked out?

**Comment by djoverton** [comment]
Regenerated the scans.csv to include the 5 new scans. A reminder that I have written a simple tool `generate_scanslist.py` in `/archive/code/datman/datman` that will do this.
