### ISSUE TITLE
/pipelines/fmri/rest/ for PNSC data missing some subjects

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#1050]
Hi @josephdviviano,

Thanks for preprocessing the fMRI scans for the PNSC dataset. I noticed that only 3 folders out of the 7 in the /pipelines/fmri/rest/ folder have data in it. The other 4 subjects had an error message. I looked into it and found that those subjects do not have a subject-specific folder in the /pipelines/hcp/ folder. Also, there were a few subjects in the /pipelines/hcp/ folder that I did not see in the /pipelines/fmri/ folder. 

These are all the subjects that I am hoping to get scans for. Please let me know if you are able to run the pipeline on the remaining subjects in the HCP folder and if you know where we could get the 2 scans that do not have folders in the HCP folder.

<ul>
<li>PNS_CMH_0003 (can't find in both HCP and fmri/rest folders)</li> 
<li>PNS_CMH_0006 (can't find in fmri/rest folder)</li>
<li>PNS_CMH_0019</li>
<li>PNS_CMH_0020 (can't find in fmri/rest folder)</li>
<li>PNS_CMH_0023</li>
<li>PNS_CMH_0025 (can't find in fmri/rest folder)</li>
<li>PNS_CMH_0029</li>
<li>PNS_CMH_0030 (can't find in fmri/rest folder)</li>
<li>PNS_CMH_0032 (can't find in fmri/rest folder)</li>
<li>PNS_CMH_0038 (can't find in hcp folder, folder in /fmri/rest/ only has error.log)</li>
<ul/>

**Comment by navonacalarco** [comment]
@sabashahab @josephdviviano 

With one exception (PNS_CMH_0020 = SPN01_CMH_0098), the subject IDs that Saba listed are the relatively few PNS subjects who don't share an MRI with SPINS, so that might be a clue.

**Comment by sabashahab** [comment]
Thanks for pointing that out @navonacalarco. I forgot to mention that these are all the the IDs that do not overlap with SPINS. The list was put together by Marzena. We may need some clarification on CMH_0020 - I'll email Marz.

**Comment by sabashahab** [comment]
Sorry for posting this so late. I emailed Marz and this was her response: 

"PNS_CMH_0020 was initially shared with SPINS but they were withdrawn after their screening visit due to medication change and have completed their scan for PNS only."

**Comment by navonacalarco** [comment]
@sabashahab  No problem. Has the preprocessing for the fMRI scans been done now that the scans have been located, or does this still need to be done?

**Comment by josephdviviano** [comment]
@sabashahab can you confirm that the freesurfer outputs for the missing subjects now exist?

**Comment by sabashahab** [comment]
Sorry for the late reply. I confirm that the outputs for the missing subjects now exist in the freesurfer folder.
