### ISSUE TITLE
backups are full

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1053]
+ reminder that we need to move a bunch of stuff from `/projects` to `/scratch`.

**Comment by DESm1th** [comment]
It turns out I had somehow accumulated 1.2 TB between the ABIDE data, maget, etc. Sorry :( It's all in scratch now.

**Comment by josephdviviano** [comment]
Great, thanks!

**Comment by josephdviviano** [comment]
Backups have some free space (2TB... for now).
