### ISSUE TITLE
rename PACTMD_CMH_03060077_02_01

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1055]
```
Participant ID entered: PACTMD_CMH_03060077_02_01
Correct Participant ID: PACTMD_CMH_3060077_02_01
```

Who is the RA for this study we should contact?

**Comment by navonacalarco** [comment]
There's 4 of them and they all want to be contacted:

Alexandra Minea; Rhea Harduwar; Sara Gambino; Shima Ovaysikia

https://docs.google.com/spreadsheets/d/1MTuU7Y7hqAHbiHMP2NsnrW1wZ9UZrmz4AQpJCQ1-_BQ/edit?usp=sharing

**Comment by josephdviviano** [comment]
Done.
