### ISSUE TITLE
Pull select SPINS demographic data into our file system

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1056]
We've got permission from DL to pull some basic SPINS demographic variables into our system so we can review the participants for whom data exists before sending in Data Requests. 

These variables are 

variable | REDCap variable name
---|---
subject ID | (record_id)
site | (redcap_data_access_group)
<s>date of MRI | <s>(mri_doa)
sex | (demo_sex_birth)
age | (demo_age_study_entry)
education | (demo_highest_grade_self)
diagnosis | (redcap_event_name)
termination | (term_premature_yn)

We're going to pull the data (nightly? weekly?) with the REDCap API and @DESm1th is going to set up a cron job.

It looks like the best place to keep the csv is in /archive/data/SPINS/data/clinical. Does anyone disagree? Are there any other variables anyone wants?

**Comment by edickie** [comment]
This is really great!

Might be good to add a site column as well. Even if it's already in the
subject ID, it will be faster to use for sub-setting if it's already a
separate column..
​
One issue, does including the date of MRI and age in the same table make it
PHI?? (because year of birth is easily calculated....) Is this an issue?

**Comment by navonacalarco** [comment]
Thanks @edickie!

Sure, we'll add a site column.

I don't _think_ that including date of MRI and age is a problem here, because it's not in the same "place" (usually interpreted as folder, I think) with the same permissions as the actual MRI images. However, I will certainly double check! If so, do you agree we should remove MRI date, as that information is available to us elsewhere?

**Comment by navonacalarco** [comment]
Done, thanks to @DESm1th! Integrated with datman, and output goes to  /archive/data/SPINS/data/clinical. Will email lab.
