### ISSUE TITLE
Find missing HDBD scan

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1058]
From @leepropp

Just going through scans to date and noticed that HDBD001_02 is not on qc monitor. There is one called HDBD_02 with no id #, but that one says no qc doc available… or maybe it just didn’t get pushed through? This scan should have been ~June 2016.

**Comment by DESm1th** [comment]
This has been located. The QC page should show up tomorrow after the pipelines run this evening. I'll close this tomorrow once I've double checked everything ran ok

**Comment by leepropp** [comment]
Thanks!

**Comment by DESm1th** [comment]
This is fixed now
