### ISSUE TITLE
MRSROI.zips

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1059]
Message below from Nancy:

"anything with _MRSROI on the end contains our first attempt at creating a mask 
to be used for CSF-correction for MRS data from the same exam. Turns out there 
were issues with some of the oblique MRS voxels that the code couldn't handle, 
so the data are likely incorrect.  You can ignore/delete anything with *_MRSROI 
as the folder name.  (not sure how it was misplaced in the SPIN1MR directory)
Nancy"

Do we just add these to scans.csv as <ignore> or should we do something more cleverer?

**Comment by djoverton** [comment]
For now, I have added "<ignore>" to all _MRSOI sessions in PASAD's scans.csv file.
