### ISSUE TITLE
Blacklist SPINS ZHP 0079 IM/OB scans

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1061]
patient could not see experiment due to mirror malfunction!

**Comment by josephdviviano** [comment]
still isn't exported. @tomwright01 , worth noting that dm2-xnat-export.py is getting jammed somehow..

**Comment by tomwright01** [comment]
Data was exported March 1st, not sure why it was delayed, Phillips scanner requiring dcm2niix?
Scans have been blacklisted.

**Comment by josephdviviano** [comment]
Yes I think the HPs were getting held up when we were using the old `dcm2nii`
