### ISSUE TITLE
dtifit pipeline QC: STOPPD_PMC_R360023_01 and STOPPD_PMC_360023_01

### ISSUE THREAD

**Issue by Christianlee19** [TIGRLab/admin#1063]
Not found in /archive/data/STOPDD/pipelines/freesurfer/

**Comment by navonacalarco** [comment]
All of the other ones have recon_all_done.

@edickie, would you have time to meet with Christian and I next week to discus/clarify next steps?

**Comment by josephdviviano** [comment]
@edickie please respond.
