### ISSUE TITLE
go through these packages and identify useful ones to set up in the lab

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1064]
+ https://github.com/VUIIS/dax
+ https://github.com/cookpa/pipedream 
+ https://github.com/petemcw/ansible-role-postfix
+ https://github.com/poldrack/myconnectome
+ https://github.com/jeffduda/NeuroBattery
+ https://github.com/FCP-INDI/C-PAC
+ https://github.com/aestrivex/bctpy
+ https://github.com/the-virtual-brain/tvb-framework
+ https://github.com/ccraddock/cluster_roi
+ https://github.com/demianw/tract_querier
+ https://github.com/PrincetonUniversity/fcma-toolbox

@djoverton @edickie @DESm1th @tomwright01 if you have any thoughts on these let me know! I just found them all hiding among my github stars as I was clearing them out. Some of them might be useful for our pipelines etc.

**Comment by edickie** [comment]
Maybe we should built this list into the wiki somewhere? - We might as well
wait to install untill somebody expresses a plan to use one...that way we
can have the latest version at that time...?
