### ISSUE TITLE
set up FTP server on xnat.imaging-genetics.ca for data transfer from mikilos

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1071]

**Comment by tomwright01** [comment]
Would be helpful to get a source IP address from Mikilos. Since it's a firewalled hospital a quick google for "whatsmyip" should be enough.

**Comment by josephdviviano** [comment]
done and working, see `/projects/admin/secrets/sftp.md` for details

**Comment by tomwright01** [comment]
Looks like a comprehensive solution. Is the sftp user configured in ansible?
