### ISSUE TITLE
check quality SPINS phantoms with new balls 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1075]
CAMH should be using. ZHH and MRC will be using soon.

**Comment by navonacalarco** [comment]
Hey guys,

Following a recommendation from Erin, I used the `slicerdir` utility in FSL to generate a single image of all the ADNI phantoms in the SPINS/data/nii folder. The output is in `/projects/navona/Kimel_lab/SPINS/FSL_phantoms/slicesdir`.

We did this in an effort to see the new ADNI phantom at CAMH. But, everything from CAMH pretty much looks like this:

![_archive_data_spins_data_nii_spn01_cmh_pha_adn0001_spn01_cmh_pha_adn0001_t1_02_sagt1-bravo-adni-only](https://cloud.githubusercontent.com/assets/13733654/23718024/0cd95f4c-0404-11e7-970d-1313d517f28f.png)

I was expecting to see a drastic difference in the appearance of the phantoms, which would indicate that the new ADNI phantom has been put in effect.

What am I missing?

**Comment by edickie** [comment]
I would guess that if you can see the original ADNI case (all the black
lines) that they are not scanning the ADNI balls on their own yet??

We may need to discuss with with downstairs - maybe clarify with AV?

**Comment by edickie** [comment]
Update from AV: no one has started scanning balls yet but they should be
soon..

**Comment by josephdviviano** [comment]
I went over this ... they look OK for the specific cases I checked. Will need to track them ongoing with the dashboard.
