### ISSUE TITLE
subjects graphs not working

### ISSUE THREAD

**Issue by leepropp** [TIGRLab/admin#1077]
Trying to get an idea of how much usable data there is so far, the graphs for movement metrics are not showing up in the subjects tab when options are selected.

**Comment by djoverton** [comment]
Hey @leepropp, can you be a bit more specific? Which project(s) are you looking at, and which metrics are you selecting?

**Comment by DESm1th** [comment]
Hi Lee, I just looked into it. The graphs show up for me, are you checking the site tag even though CMH is the only site? I noticed the graphs wouldnt show unless I did that

**Comment by leepropp** [comment]
Project DBDC; hmm that's odd because I can't see any. I only see the 'remove outliers' button, no graphs, and I did select the site

**Comment by leepropp** [comment]
Project DBDC; hmm that's odd because I can't see any. I only see the 'remove outliers' button, no graphs, and I did select the site

**Comment by djoverton** [comment]
I just checked and all metrics appear to be working for DBDC. As Dawn said, are you selecting the site as well? All options must be selected for the chart to appear.

**Comment by leepropp** [comment]
Yes, I'm selecting: scan type, site, scan subtype and metric. Is there something else I should be doing? Also, options for fMRI are limited to RST, there is no button for the tasks... Thanks for all the help!

**Comment by navonacalarco** [comment]
Weird!

@leepropp just so you know what we're seeing, here's a screenshot of what things should look like (looking at FD as an indication of motion).

![screenshot - 03012017 - 11 38 59 am](https://cloud.githubusercontent.com/assets/13733654/23470158/b3db39e6-fe73-11e6-8c66-3c47f8f0c144.png)

Can you try CTRL F5 (hard refresh)? There were some updates about a month ago that required as much. Let us know if that works.

**Comment by leepropp** [comment]
nope, not seeing that. I did a hard refresh and cleared the cache...

**Comment by navonacalarco** [comment]
I reset your permissions in case that's it. Can you try once more (log out of the Dashboard and GitHub)?

**Comment by djoverton** [comment]
Also, which browser and version are you using?

**Comment by leepropp** [comment]
chrome. think it is most recent version

**Comment by leepropp** [comment]
just tried explorer and it seems to work! Thanks

**Comment by djoverton** [comment]
It should work in Chrome, can you try again to verify if the other changes are what fixed it?

**Comment by leepropp** [comment]
still not working on chrome, explorer seems to work

**Comment by leepropp** [comment]
31.0.1650.59 m

**Comment by djoverton** [comment]
Alright, that is a very old version of Chrome (from 2013), so that is almost certainly the problem (displaying the charts uses functions in Javascript that it doesn't support). We are only supporting the latest versions of Chrome and Firefox, so you'll need to either update Chrome or use a different browser (sounds like you're using Explorer already which is working).
