### ISSUE TITLE
SPINS scans not being brought into file system from MRI server

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1078]
Missing scans:

subject ID  | exam ID | date
------------|-------------|---------
SPN01_CMH_0119_01_01   |   6680   |  2017-02-21
SPN01_CMH_0118_01_01   | 6709   | 2017-02-28

If someone could help me get SPN01_CMH_0119_01_01 in particular, it would be much appreciated - participant is coming in for return visit for tomorrow, and has requested a printout.

**Comment by josephdviviano** [comment]
@navonacalarco I had to restart `nginx` to get 0119 in. I'll try 0118 now.

**Comment by josephdviviano** [comment]
nvm, 0118 isn't on the MR server yet. Since I got 0119 in let's consider this closed, and we can reopen if 0118 remains missing for some time.
