### ISSUE TITLE
Dashboard: add MID and SID (fMRI) scans to cross-subjects comparison

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1081]
requested by lee; helpful to compare across all metrics.

**Comment by tomwright01** [comment]
I've modified my local version of dashboard to enable scans to be over-layed. There are a few implications I want to work through before I push this to srv-dashboard. Changes can be previewed at http://hebb.camhres.ca:5001 (If you get a connection error message I'm probably not running the webserver, let me know and I'll start it for you).

**Comment by tomwright01** [comment]
Fixed by a4a49d8
