### ISSUE TITLE
image rendering weirdness in SPN01_MRP_0087_01_01

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1086]
Not sure what's going on here, but there's two oddities in the SPN01_MRP_0087_01_01 QC document. 

First, the `B0 montage`in the QC image file SPN01_MRP_0087_01_01_DTI60-1000_26_DTI-60Dir-5B0.nii.gz failed to select particular image files, and is showing the whole shebang.

Second, the `bvec directions` is not rendering.

Just wanted to note this in case it's a bug that has any important ramifications (?). Other outstanding QC documents look find, though.

Anyone have any ideas, or can this just be ignored?

**Comment by DESm1th** [comment]
Not sure of the cause, but just wanted to add that I checked the logs and this series has been causing the following error when it's extracted:

[dm2-xnat-extract.py] ERROR : Failed getting series:26, session:SPN01_MRP_0087_01_01 from xnat
2017-03-04 07:14:11,303 - dm2-xnat-extract.py - SPINS - ERROR - Failed getting series:26, session:SPN01_MRP_0087_01_01 from xnat

**Comment by josephdviviano** [comment]
Their upload was truncated. Emailing them to reupload.

**Comment by navonacalarco** [comment]
Ah, thanks JDV! Sorry for missing that.
