### ISSUE TITLE
need tigrlab mount? halp?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1087]
![1](https://cloud.githubusercontent.com/assets/13733654/23712225/43867e26-03f0-11e7-9dee-e1206d247597.png)

**Comment by josephdviviano** [comment]
on it

**Comment by josephdviviano** [comment]
fixed.

**Comment by navonacalarco** [comment]
Thank you! I feel like I should know how to do that - are there instructions somewhere?

**Comment by josephdviviano** [comment]
`sudo mount -a`

**Comment by navonacalarco** [comment]
Thanks!
