### ISSUE TITLE
MRI Scan Missing for tDCS-VR CHR 

### ISSUE THREAD

**Issue by JessDArcey** [TIGRLab/admin#1088]
Hi All; 

I'm missing a scan for id tDCS_cmh_3005_01-01, scan was completed on Feb 22nd 2017. 

Let me know if there's anything I need to do on my end! 
Jess

**Comment by navonacalarco** [comment]
Thanks Jess! We'll take a look! :dancer:

**Comment by navonacalarco** [comment]
OK, it looks like the TDCS_CMH_3005_01_01 scan isn't in the Dashboard, or our file system `data/nii` folder, but it is in the `data/zips` (and of course on the MR server). 

The relevant file in `data/zips` is 20170222_Ex06682_VRNS1MR_VRMD002.zip

The scan isn't being ignored in scans.csv, so I'm not sure what's happening here.... (perhaps it's the 4 digit <subject> string?)

@DESm1th.... would you have a spare second to help us out?

**Comment by DESm1th** [comment]
The PatientName field in the scan wasnt correct (was missing the time point and session number) and so it wasn't being linked. I've added an entry to scans.csv and it's now been linked so the rest of the pipeline should run without problems tonight.

**Comment by navonacalarco** [comment]
Dawn wisdom: use dm2-link.py --debug TDCS to check naming/ error message in zip.

@JessDArcey you will see your scan on the Dashboard tomorrow! Please make sure that the MRI Tech includes the <session> and <timepoint> information in the participant ID, otherwise, the scans will not be linked correctly.

Thanks!

**Comment by edickie** [comment]
@dawn errors like this used (and should still) to show up in the run logs
so we catch them earlier. If their not...can we update datman so that they
are? (I.e. set the log level for this type of message to "error" or
"critical"

**Comment by DESm1th** [comment]
The error is still being reported in the logs, it just got missed. I haven't been checking the logs too closely this past week+, sorry D:

**Comment by JessDArcey** [comment]
Sorry I'm a little confused - was there something I inputted incorrectly in the naming convention? Also the scan still isn't appearing for me. Thanks for your help everyone!

**Comment by navonacalarco** [comment]
Hey @JessDArcey, 

Regarding naming: No, you didn't input the name incorrectly yourself. But, the MRI Tech failed to include the <`session` > and <`timepoint`> part of `TDCS_CMH_3005_01_01`, when the participant was named on their system, before scanning commenced. In my (limited) experience, the MRI Tech copies the participant ID from the top of the consent form that's submitted to / printed by the MRI Centre - so, if you only recorded a partial MRI ID there (which I realize is the participant's full ID as it's referred to in your study), then the MRI Tech would likely have copied only a partial ID.

Does that make sense? Basically, it's import to refer to the participant by the full MRI ID (i.e.`TDCS_CMH_3005_01_01`) on any documentation the MRI Centre will see, so there's no confusion.

**Comment by JessDArcey** [comment]
Ah ok, makes sense - I did not fill out that form so I'll pass the info on - Thanks!

**Comment by navonacalarco** [comment]
And we'll figure out why the scan is still missing after all that - super sorry!

**Comment by DESm1th** [comment]
Hey guys, it's not there because the changes to the dashboard that were made yesterday caused a small bug so nothing got updated. I don't think there's any problem with this specific scan but I'll try to manually push it through now

**Comment by DESm1th** [comment]
Ok, it can't be manually pushed through at the moment but the bug should be fixed by tomorrow. Will close this Monday after I confirm it's in the dashboard.

**Comment by DESm1th** [comment]
This is fixed now (for realsies). The page is viewable on the dashboard.
