### ISSUE TITLE
Explore setting default logging directory to the current folder in fsl_sub

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#109]
@colinhawco has run TBSS but his jobs failed for whatever reason, and is now stuck trying to chase down the SGE log files to fine out why. I *think* fsl_sub is defaulting to putting log files in the user's `$HOME` folder (either explicitly or because of an SGE default), which is troublesome with our unshared home folders because you have to figure out which machines the jobs failed on and look on those home folders.

Even when /home was shared, this was still annoying behaviour, so I'm filing this issue so that we explore setting the default folder for logs to be whatever folder you were in when you ran fsl.

**Comment by josephdviviano** [comment]
I can't seem to reproduce this behaviour, so I'm closing the ticket. Feel free to reopen if it pops up. Might only happen with old versions of fsl_sub.

In any case, the log directory is set by the programs that reference fsl_sub, so it might require editing multiple (many) fsl programs.
