### ISSUE TITLE
header differences PNS scans

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1090]
I think that these are important:

![screenshot - 03082017 - 03 28 18 pm](https://cloud.githubusercontent.com/assets/13733654/23722581/e5070b12-0413-11e7-8eb7-f8c04ed9de3d.png)

Going to double check everything is as it appears and compare to SPINS gold standards (should be identical), and will email Sophia if required.

Affected subjects:

PNS_CMH_0036_01_01 
PNS_CMH_0038_01_01
PNS_CMH_0035_01_01
PNS_CMH_0040_01_01

**Comment by navonacalarco** [comment]
Update: most/all have these differences, and I have a vague memory of this being a noted issue already discussed with MRI Centre .... will dig through archive.

**Comment by josephdviviano** [comment]
@navonacalarco which scans are these from?

**Comment by navonacalarco** [comment]
I think we see these differences only for participants that are just in PNS, not PNS in SPINS (in the latter case, the SPINS protocol is always followed). 

So, for example, you'll see these differences on the 4 PNS scans that I missed and were QC'd in a batch yesterday: 
PNS_CMH_0036_01_01
PNS_CMH_0038_01_01
PNS_CMH_0035_01_01
PNS_CMH_0040_01_01

**Comment by josephdviviano** [comment]
@navonacalarco what kind of MRI data are they from

**Comment by navonacalarco** [comment]
Oh. They're all T1s. No differences elsewhere.

**Comment by josephdviviano** [comment]
Thanks. Worth flagging to the MR unit ... they've swapped their T1 protocol by mistake (slightly different resolution acquisitions).

The effect on SNR should be almost 0 from such a small change, though, so these images are fine.

**Comment by navonacalarco** [comment]
Thanks, JDV! Will cc you on email - will send later today / tomorrow.

**Comment by josephdviviano** [comment]
great thanks!
