### ISSUE TITLE
motion quantification for DBDC (Lee) 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1092]
Follow up from meeting with @leepropp and @rachaellyon:

- [x] dtiprep on DBDC
- [ ] fMRI motion metric on DBDC
- [x] make html images larger, if possible, mainly for fMRI SFNR map
- [x] as per issue #1081, add MID and SID fMRI scans to DBDC 'subjects' tab

**Comment by josephdviviano** [comment]
@navonacalarco @tomwright01 

head motion is quantified per subject using the mean_fd metric for fMRI data. It's there.
