### ISSUE TITLE
Changes to dashboard, datman to deal with repeat scans

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1093]
Made modifications to datman and dashboard to deal with repeat scans (i.e. SPN01_CMH_0002_01_01 & SPN01_CMH_0002_01_02). Addresses issues #1051 and #1003

# Datman

- `dm2-xnat-extract.py` Will identify repeat sessions when downloading from xnat and update the dashboard database `session` record.
- `dm-qc-report.py` Now finds technotes from both sessions and links them in the qc.html page. _Still need some way to trigger rerunning with --rewrite flag_!

# Dashboard

- Database now has structures to monitor for an unlimited number of repeat sessions. Also records which session was last QC'd

- Added additional information to the *QC - Todo* tab. Identifies scans needing QC from the database (instead of by running `dm-qc-todo.py`). _Suggest the original `dm-qc-todo.py` information can now be removed._

**Comment by navonacalarco** [comment]
Hey @tomwright01 This is awesome, thanks again for doing this! Do you think that any of these changes need to be communicated to the non-Kimel QC'ers, or is this sufficiently behind-the-scenes stuff?

**Comment by tomwright01** [comment]
Added a warning to dashboard qc page indicating dm-qc-report should be manually re-run.
