### ISSUE TITLE
Ensure all Ansible playbooks run without errors

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1096]
Noticed minor errors running site.yml; possibly others as well (will update as I test them).

**Comment by josephdviviano** [comment]
@djoverton one heads up: ansible tends to choke on `apt-get` periodically. You'll notice on some machines what haven't been updated in while, that during a full `upgrade`, the process required user input. This tends to block ansible.

If we're noticing other things that choke ansible, let's document them here.

**Comment by djoverton** [comment]
Going to keep this issue open since it will be ongoing.

**Comment by josephdviviano** [comment]
Could you document the errors you continue to see?

**Comment by djoverton** [comment]
Ran site.yml today, no errors that exist for all machines -- every error that is still occurring is machine specific. I've listed them below (I left only the machine name and relevant stderr/stdout/msg).

- [ ] fatal: [bulbasaur.camhres.ca]: FAILED! => "stderr": "Host object \"bulbasaur.camhres.ca\" is still referenced in cluster queue \"main.q\".\nexechost \"bulbasaur.camhres.ca\" already exists"

- [ ] failed: [bulbasaur.camhres.ca] "msg": "No package matching 'libnetcdfc++4' is available"

- [ ] failed: [cajal.camhres.ca] "msg": "No package matching 'libxp6' is available"

- [ ] failed: [kandel.camhres.ca] "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"  --force-yes   install 'software-properties-common' 'sssd-tools' 'unattended-upgrades' 'ansible' --allow-unauthenticated' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. \n"

- [ ] failed: [nissl.camhres.ca] "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"  --force-yes   install 'ntp' 'ansible' --allow-unauthenticated' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. \n"

- [ ] failed: [higgs.camhres.ca] "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_76RcF7/ansible_module_apt.py\", line 239, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"/tmp/ansible_76RcF7/ansible_modlib.zip/ansible/module_utils/urls.py\", line 155, in <module>\r\n  File \"/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/__init__.py\", line 53, in <module>\r\n    from .packages.urllib3.contrib import pyopenssl\r\n  File \"/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py\", line 62, in <module>\r\n    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,\r\nAttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'\r\n", "msg": "MODULE FAILURE"

- [ ] failed: [srv-sge.camhres.ca] "stderr": "unable to resolve host \"groups[fileserver]\"

**Comment by josephdviviano** [comment]
I fixed this.
