### ISSUE TITLE
DTIfit pipeline should ensure the correct number of directions before running?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1098]
It seems DTIfit runs happily on corrupted DTI scans (where the patient hit the panic button mid way through the sequence and we do not collect all directions). Often times, these don't even reconstruct to 4D.

I think our DTI pipelines should either assert A) the exact number of directions (using the BVAL file) [strict], or B) the dimensionality (must be 4D) [lax]. The dimensionality criteria should catch pretty much all corrupt scans due to early termination, but won't catch events where the scanner itself was programmed to collect the wrong number of directions / B0 values.

In my experience the latter happens often, and shouldn't render the data unusable, though that kind of inconsistency is undesirable.

Thoughts? @tomwright01 @edickie  @navonacalarco

**Comment by navonacalarco** [comment]
Hrrrmm. I'm not entirely sure. But, one thing that might be relevant is that we do have useful info about how many directions were collected, visible in the Dashboard's overview:

![screenshot - 03132017 - 11 32 14 am](https://cloud.githubusercontent.com/assets/13733654/23861593/ea8a0eba-07e0-11e7-860d-a06cd01f3e82.png)

So, maybe we could put a flag here (or elsewhere) if there's a mismatch between number of directions expected and received, but enforce the dimensionality criteria? Is that the best of both worlds?

**Comment by edickie** [comment]
Yeah, actually this is one of the reason's why I prefer for pipeline (like
dtifit) to run after manuall QC and blacklisting...because situation A)
should be blacklisted..

**Comment by edickie** [comment]
yes @navona it does make sense to build the expected length into the config
files and have dm-qc-report write a warning message when the length is not
the one expected?

On Mon, Mar 13, 2017 at 11:38 AM, Erin W. E. Dickie <erin.w.dickie@gmail.com

**Comment by tomwright01** [comment]
Is the DTIPrep pipeline more sensitive to these types of errors? 
Tractography only needs a minimum of 6 directions (and a B0), DTIPrep actually excludes 'noisy' directions and will still process the file if not too many directions are excluded.

Do you have some examples where this has occurred? I can take a look at the DTIPrep outputs.

**Comment by josephdviviano** [comment]
@tomwright01 I just deleted the last example, which was so corrupt that it reconstructed as a nonsense 2-D image (dtiprep would likely choke on that).

OK, in light of @edickie 's comment, I'll just have the program A) ensure the data was QC'ed, and B) ensure the data is 4D. That should catch pretty much all of the errors.
