### ISSUE TITLE
pdt2 split is trying to parse .json files

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1099]
I'm a little confused though, because line 105 in `dm2-proc-split-pdt2.py` explicitly filters:

```
        ext = datman.utils.get_extension(f)
        if tag == 'PDT2' and 'nii' in ext:                                      
            images.append(os.path.join(base_dir, f)) 
```

and the error messages look like this:

```
2017-03-12 15:04:28,955 - /archive/code/datman/bin/dm2-proc-split-pdt2.py - ERROR - /archive/data/DBDC/data/nii/DBDC_CMH_CDBD019_01/DBDC_CMH_CDBD019_01_01_PDT2_18_OblAxT2-DEfseXL.json: Expected exactly 2 volumes, got:  in tempfile: /tmp/dm2-proc-split-pdt2bjjs7D on system :tigrsrv.camhres.ca
```

is it picking up the nii from the directory, instead of the extension?

**Comment by josephdviviano** [comment]
@tomwright01 if you know something i dont

**Comment by DESm1th** [comment]
I just added the filtering lines about 20 minutes ago. Is it still having problems? I've noticed it still crashes when trying to parse certain PDT2s

**Comment by josephdviviano** [comment]
Ah, that explains it! Thanks @DESm1th .

Can you give an example of a nifti it crashes on?

**Comment by josephdviviano** [comment]
Wait, found one: `/archive/data/ASDD/data/nii/ASDD_CMH_EF049_01/ASDD_CMH_EF049_01_01_PDT2_11_OblAx-T2DEfseXL.nii.gz`

**Comment by DESm1th** [comment]
Yeah, I'm not sure why it's crashing on those, though. I had just started to look into that when you posted this. Any ideas?

**Comment by josephdviviano** [comment]
It can't split an image with only one volume. I'll add a check for the right number of volumes (4th dimension)

**Comment by josephdviviano** [comment]
see 224dfd3
