### ISSUE TITLE
Need singularity engine configuring on computenodes

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1100]
The containerisation framework [Singularity](singularity.lbl.gov) requires installation on computenodes.
Currently I have manually installed this but ansible should be updated:

I have created an apt-package to install the latest stable version: '/projects/twright/singularity-container_2.2-1_amd64.deb'
Installation command: `ansible -m command -a 'sudo dpkg -i /projects/twright/singularity-container_2.2-1_amd64.deb' computenodes`

**Comment by josephdviviano** [comment]
Hey both,

Would be good to add this to the `/projects/admin/ansible-playbooks/roles/quarantine/tasks/main.yml` role, as we keep all quarantine dependencies we need installed en-masse there.

**Comment by djoverton** [comment]
I was going to add it to the Workstation role, why do you think it should be added to Quarantine?

**Comment by josephdviviano** [comment]
Because not all machines on the queue (that need to see the quarantine) are workstations (i.e., the compute nodes).

**Comment by tomwright01** [comment]
I don't really have strong views here but:

1. The singularity engine doesn't need to be version controlled
2. Except for development purposes, I doubt individuals will be running singularity without submitting Q jobs.

With this in mind I think the compute role is the best place to install it.

**Comment by djoverton** [comment]
@jdv right, I forgot about com02, com03 (etc.), but then wouldn't a more appropriate role be `gridengine-exec`?

**Comment by josephdviviano** [comment]
@djoverton the appropriate role is quarantine, because it a role we can use to deploy software to anything that uses the quarantine, whether or not it is on the queue.

You will notice that gridengine-exec does not configure any analysis software.

**Comment by josephdviviano** [comment]
@tomwright01 the engine does not need to be version controlled, but the dtiprep container does.
