### ISSUE TITLE
compare PRISMA ZHH & MRC human/phantom protocols

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1101]
From ZHH:  
[SPINS_ZHH_20161026.pdf](https://github.com/TIGRLab/admin/files/839773/SPINS_ZHH_20161026.pdf)
[SPINS_Phantoms_20170308.pdf](https://github.com/TIGRLab/admin/files/839775/SPINS_Phantoms_20170308.pdf)

@DESm1th I am happy to do this, but I  know you did this before, so any memory of where past differences lay might be helpful. :)

**Comment by DESm1th** [comment]
Ok here's my terrible table of differences:

![image](https://cloud.githubusercontent.com/assets/10541496/23909384/f87dab0e-08ac-11e7-8278-f49e21b0e054.png)


Note that I only looked at the fields previously identified by Colin as being important (FoV, TR, TE, Flip Angle, Slice order, Slice thickness, and voxel size).

**Comment by navonacalarco** [comment]
Thank you again, Dawn. This is so helpful. Sending verbatim to SPINS imaging google group.
