### ISSUE TITLE
blacklisting to incorrect phase encoding direction (fmri)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1103]
Noticed this in SPINS:

```
SPN01_ZHH_0034_01_01_EMP_16_fMRI-Emp-Acc-277                          phase-encode-direction-wrong
SPN01_ZHH_0031_01_02_EMP_05_fMRI-Emp-Acc-277                          phase-encode-direction-wrong
SPN01_ZHH_0034_01_01_RST_07_Resting-State-212.dcm                     phase-encode-direction-wrong
SPN01_ZHH_0036_01_01_RST_06_Resting-State-212.dcm                     phase-encode-direction-wrong
SPN01_ZHH_0036_01_01_OBS_07_fMRI-Observation-110.dcm                  phase-encode-direction-wrong
SPN01_ZHH_0036_01_01_OBS_07_fMRI-Observation-110	phase-encode-direction-wrong
SPN01_ZHH_0036_01_01_RST_06_Resting-State-212	phase-encode-direction-wrong
SPN01_ZHH_0034_01_01_RST_07_Resting-State-212	phase-encode-direction-wrong

```

I'm on the fence about this ... these scans should be usably by all  means. Did we blacklist these scans on the recommendation of the MRI center, Aristotle, or Peter? Would be worth checking... they should have slightly different geometric distortions, but should be otherwise fine.

**Comment by josephdviviano** [comment]
@edickie @navonacalarco

**Comment by navonacalarco** [comment]
Hey @josephdviviano,

Sorry not to be able to be more helpful with this one, but it was before my time. I searched my mail to see if there was some discussion about it, and don't have anything - but of course that doesn't mean it wasn't discussed.

**Comment by edickie** [comment]
Sorry, I don't remember anything about that..

**Comment by josephdviviano** [comment]
thanks -- odd. I don't have anything in my email either.

I guess we'll keep the blacklisted, I'm sure that decision came from one of the physicists or whatever.
