### ISSUE TITLE
Many PRELAPSE data upload fails

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#1107]
Sent to Prelaspe TXS site

It looks like you were uploading quite a bit of PRELAPSE data to our XNAT database last week.

Unfortunately it also looks like most of you uploads failed in some way because the series look incomplete...

Can you re-upload the data?

subid	sequences uploaded
PRE01_TXS_38003_02_01	3D T1 PRE(1), 3D_T2(1), B0-Map(1), DTI_60dir(2), Survey(1), unknown(1)
PRE01_TXS_38004_02_01	DTI_60dir(1)
PRE01_TXS_38006_02_01	DTI_60dir(1), unknown(1)
PRE01_TXS_38007_02_01	DTI_60dir(1), unknown(1)
PRE01_TXS_38008_02_01	3D T1 PRE(1)
PRE01_TXS_38008_02_02	DTI_60dir(1), unknown(1)
PRE01_TXS_38012_01_01	DTI_60dir(1), unknown(1)

**Comment by josephdviviano** [comment]
@edickie what is the status here?

**Comment by edickie** [comment]
yeah those are all fine now
