### ISSUE TITLE
Diagnose why cancelled print jobs remain in queue

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1108]
Not sure if others have noticed this, but when I log in to any machine I get a bunch of dialog boxes to confirm print jobs that have already been cancelled. Cancelling these dialog boxes seems to have no effect; when I log in the same dialogs for the same jobs appear.

**Comment by navonacalarco** [comment]
I know how to fix this!  Basically, typing in some url (something like localhost:2002) into a browser will bring you to a page where you can see and selectively cancel outstanding jobs.

Except I can't bring the string to mind. It's written down on a sticky note on my computer.

Tom was the source of this wisdom; if he doesn't get to you first, I can show you the sticky on Monday.

**Comment by DESm1th** [comment]
Should be localhost:631 if memory serves

**Comment by josephdviviano** [comment]
@DESm1th has the correct answer. It's the web interface for CUPS

**Comment by djoverton** [comment]
Thanks guys.
