### ISSUE TITLE
SPINS medication data converted to chlorpromazine units for PK

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1109]
Check in with @edickie @josephdviviano for which paper they were following for conversion on other datasets - there seems to be a couple options.

From Laura: 
[Equivtext.pdf](https://github.com/TIGRLab/admin/files/853421/Equivtext.pdf)

**Comment by josephdviviano** [comment]
Hey @navonacalarco happy to help, but I've never worked with the medication data before (seem messy)!

**Comment by navonacalarco** [comment]
Thanks @josephdviviano! I'm going to look at ERin's script from ENIGMA and see if I can figure out how to adapt that! :) 

It would be awesome if you and Erin can take a peak at what I do before it gets sent off.

**Comment by josephdviviano** [comment]
Does ENIGMA do this at all? I don't think any of our pipelines deal with the drug data.

**Comment by edickie** [comment]
The ENIGMA SZ group analyses include drug data covariates. They didn't give
that much info (just a reference) on how to do this.

While I was calculating the CPZ equizalent scores for the DTI 1.5T sample,
for ENIGMA upload, I wrote an R script to share with the ENIGMA SZ group
(and a little doc with ENIGMA style usage instructions).

The scripts are in:
/projects/edickie/analysis/DTI_ENIGMA/ENIGMA_sep2015/ClinicalVariables/CPZcalc
