### ISSUE TITLE
srv-web boot order problems

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1110]
We have a few moving parts on `srv-web` that prevent it from coming up cleanly.

+ `/etc/fstab` tries to start two bind mounts to patch directories from a ZFS `tank/` to `/usr/xnat/` and `/home/sftpuser/home/sftpuser`, respectively. This happens before `ZFS` is loaded.
+ `tomcat7` starts, which creates a temporary directory `/usr/xnat/tmp-tomcat`.
+ `zfs` starts, instantiating `/tank` but not `/usr/xnat`, which can't be automounted because `tomcat7` wrote to the directory `/usr/xnat`.

We need to come up with a mounting solution that has `zfs` bind these mounts to the appropriate directory, not `fstab`.

This might be a clue: https://wiki.archlinux.org/index.php/ZFS#Bind_mount

```
/mnt/zfspool		/srv/nfs4/music		none	bind,defaults,nofail,x-systemd.requires=zfs-mount.service	0 0
```

**Comment by DESm1th** [comment]
Hmm maybe I'm misunderstanding the problem, but couldn't we specify the start up order for these services to change this? http://askubuntu.com/questions/753922/how-to-change-the-order-of-execution-of-services-at-startup

**Comment by josephdviviano** [comment]
We might be able to, but I don't think we can put zfs before fstab.

**Comment by josephdviviano** [comment]
My bet is zfs has some sort of internal function that mimics the bind mounts I currently have in fstab...

**Comment by DESm1th** [comment]
Hey Joe, not sure if this has been fixed yet but if not this may help: https://github.com/zfsonlinux/zfs/wiki/Ubuntu-ZFS-mountall-FAQ-and-troubleshooting

It looks like mountall is what is handling ZFS mounting in addition to fstab. I think you'd have to change the mountpoint setting to legacy to get it to stop and rely fully on fstab.

**Comment by josephdviviano** [comment]
@DESm1th thank you!

**Comment by josephdviviano** [comment]
plan of attack:

+ `mv /tanksftp /tank/sftp-bkup`
+ `sudo zfs create tank/sftp`
+ `sudo zfs set mountpoint=/home/sftpuser/home/sftpuser tank/sftp`
+ `sudo rsync -av /tank/sftp-bkup/* /home/sftpuser/home/sftpuser`

**Comment by josephdviviano** [comment]
This works. I've synced the sftp data. and am now syncing the xnat data (xnat server is offline). Will likely run overnight.

**Comment by josephdviviano** [comment]
... or 3-4 days. Anyhow, I've created two new ZFS datasets and set their mountpoints accordingly:

```
localadmin@srv-web:~$ sudo zfs list
NAME                    USED  AVAIL  REFER  MOUNTPOINT
tank                   7.07T  6.96T  1.82T  /tank
tank/archive           3.44T  6.96T  66.2M  /tank/archive
tank/archive/data       440G  6.96T   440G  /tank/archive/data
tank/archive/data-2.0  3.01T  6.96T  3.01T  /tank/archive/data-2.0
tank/sftp              17.6G  6.96T  17.6G  /home/sftpuser/home/sftpuser
tank/xnat              1.80T  6.96T  1.80T  /usr/xnat
```
Note our original copy of everything from the XNAT database is in /tank/xnat-bkup -- we can keep this around until Tom's resource folder cleanup is successful (and check), as well as just in case anything went wrong with the rsync.
