### ISSUE TITLE
selectively turn off auto-forwarding from tigrlab to our personal Outlook emails

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1111]
Going to do this (at least from cron job emails) for me and Erin; if anyone else wants in, let me know!

**Comment by josephdviviano** [comment]
You will miss out on fun facts

**Comment by navonacalarco** [comment]
At the risk of missing out on fun facts and fire sales from Linda, I removed the auto-forwarding rules from tigrlab@camh.ca

However, I think the worst culprit is Cron Daemon, from servers.tigrlab@camhpet.ca. 

@josephdviviano @tomwright01, could you please remove forwarding to Erin and I from this address? I don't have access to it.

Thanks!

**Comment by tomwright01** [comment]
I'd do this but....
Damned if I can find where these emails are coming from.

Ok what I think is happening:
* cron on tigrsrv sends emails to admins@tigrsrv (defined in the cron jobs). Emails will appear to come from root@tigrsrv
* admins@tigrsrv is configured in /etc/aliases to point to @josephdviviano @edickie  and me.
_BUT_
* postfix on tigrsrv is configured to convert @tigrsrv to @tigrsrv.kimel.ric (/etc/mailname)
* postfix is also configured to forward emails sent to @tigrsrv.kimel.ric to servers.tigrlab@camhpet.ca (/etc/postfix/virtual)
_SO_
* all emails destined for local accounts get sent to this camhpet.ca account.
My guess is edickie and navona are configured as recipients on this account.

Will do more tomorrow.

**Comment by navonacalarco** [comment]
![image](https://cloud.githubusercontent.com/assets/13733654/24781076/de7db4f4-1b0a-11e7-8da7-8331cb70c4a6.png)

**Comment by navonacalarco** [comment]
Oh! I think - at least for some of the emails - we might want to modify the configuration file in /etc/logcheck/logcheck.conf

**Comment by tomwright01** [comment]
OK, reconfigured tigrsrv so it now accepts email from itself tigrsrv, tigrsrv.camhres.ca
As (legacy) protection it also accepts email for tigrlab.camhres.ca and kimel.ric

As before email is delivered to local users. This can be modified by use of the .forward file.

Some aliases have been configured in /etc/aliases. Currently 
admins jviviano, edickie, twright, doverton
logs jviviano, twright, doverton

@navonacalarco I think you should stop getting all system emails now.
If anyone wants more emails let me know.
