### ISSUE TITLE
fmri analysis for PASAD study

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1114]
frmi analysis pipeline is defined in `PASAD_management.sh` but fmri options are not defined in `PASAD_settings.yml`.

Should the settings be added or can the pipeline be removed?

**Comment by josephdviviano** [comment]
Removed (by me just now), no fmri is in this study afaik.

**Comment by djoverton** [comment]
I created those files, and yes, the fMRI pipeline options should be removed (I was given no information about pipelines from the people involved in that study when I requested more information).
