### ISSUE TITLE
ASDD_CMH_EF049_01 QC Page error?

### ISSUE THREAD

**Issue by rachaellyon** [TIGRLab/admin#1116]
Incorrect scans on QC page, checked on XNAT, no missing scans... seems to be an error in tags. Also: images on the QC page are excessively repeating or do not show up at all.

**Comment by DESm1th** [comment]
Just as an update: This was due to a corrupted download from xnat. It's been fixed now, so all the data is on our filesystem and the page has been updated (and renders correctly). But the dashboard isn't updating to reflect this. Working on that now.

**Comment by DESm1th** [comment]
Oops! Turns out the browser had cached the page. If you still see the old version of the page just hit the refresh buttom on your browser.
