### ISSUE TITLE
RTMSAD patient names being entered incorrectly

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1119]
Contact relevant RA(s).

**Comment by djoverton** [comment]
Have reached out to them; awaiting response.

**Comment by djoverton** [comment]
Got a response referring me to someone else; waiting on that now.

**Comment by djoverton** [comment]
Followed up again.

**Comment by djoverton** [comment]
Still nothing. I've saved my email chain to a text file (/projects/admin/emails/RTMSAD naming correspondence - Aug 1, 2017.txt) -- all the relevant email addresses are there if someone needs to followup in the future.

**Comment by navonacalarco** [comment]
Looks OK to me now. Will open if naming issues persist.
