### ISSUE TITLE
Freesurfer 6.0.0 missing license file

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1120]

**Comment by djoverton** [comment]
I have copied the 5.3.0 license file into the 6.0.0 build directory for now; let me know if a new license is needed.

**Comment by josephdviviano** [comment]
Thanks. I just applied for a new one, though it shouldn't matter. Does 6.0.0 seem to work with the copied license file?

**Comment by djoverton** [comment]
Yes, seems to work fine so far!
