### ISSUE TITLE
update admin wiki on RDoCdb Data Upload

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1126]
ZHH has a new study that will do the same reporting; going to update our content here so it's a more useful aid to them.

**Comment by navonacalarco** [comment]
Done!

@josephdviviano there's going to be a call with ZHH's imaging lead for their new study next week - I think I can handle the basic stuff especially re: the RDoC requirements and interface ... but not other things, especially those related to best to script the image03 required fields (scanner characteristics, image descriptions), etc. I'll let you know the time - will be either W or F at 11am -  would be great if you could join.

**Comment by josephdviviano** [comment]
OK I'll join.

**Comment by navonacalarco** [comment]
Great, it's next Friday March 31st at 11am.
