### ISSUE TITLE
Some sessions exist in dashboard database despite no data

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1131]
For example, PASAD_CMH_DP26A0_01 (http://srv-dashboard.camhres.ca/session/2379). Has no folder in data directory, but a blank session page exists.

**Comment by tomwright01** [comment]
This session exists on the file system:
`data/dicom/PASAD_CMH_DP26A0_01_01.zip` this links to `../zips/20140210_Ex02097_PASA1MR_MRSROI.zip`

As such it should be excluded (see #1059).

I also notice there is a timepoint 02 session for the same subject `PASAD_CMH_DP26A0_02_01.zip`. This has the same date, and contains the actual data. This should be renamed to `PASAD_CMH_DP26A0_01_01.zip`.

**Comment by djoverton** [comment]
Renamed PASAD_CMH_DP26A0_01_01.zip to PASAD_CMH_DP26A0_01_01_backup.zip and PASAD_CMH_DP26A0_02_01.zip to PASAD_CMH_DP26A0_01_01.zip.
