### ISSUE TITLE
Pull leftover DTI15T subjects from XNAT into our filesystem

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#1132]
There are a handful (more like > 20) sessions for DTI15T that were never pulled from XNAT into our filesystem.  I think this is because these were the last one's we were able to find when we reorganized? (the data folders only included the concatenated DTI files Saba used in her analysis last summer). 

Anyway, I need these sessions for an ENIGMA longitudinal study..so we got to pull and convert them..

**Comment by tomwright01** [comment]
`dm2-xnat-extract.py` is not in the `DTI15T_management.sh` script.
Running it manually, everything should be there tomorrow.

**Comment by edickie** [comment]
Urg it looks like they still didn't come down..
DTI_TGH_H065_01

**Comment by tomwright01** [comment]
I think part of the problem was '(' and ')' in some of the file names that caused utils.run() to fail.
Added code to escape special characters. Hopefully this will fix the problem.

**Comment by edickie** [comment]
hooray!! done
