### ISSUE TITLE
COGBDY_CMH_27B056_01 Tech Notes not found

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1135]
However, the Tech Notes do exist in XNAT Resources > NO LABEL folder (TechNotes6460.­pdf).

@DESm1th @tomwright01 Can you remind me of the best way to deal with this? I've downloaded directly from XNAT so I can QC, but what's the way to get the Tech Notes visible to the Dashboard?

**Comment by DESm1th** [comment]
You'd have to run dm-qc-report with the rewrite flag to get it to update the page with the pdf

**Comment by navonacalarco** [comment]
Thanks Dawn! It was permissions :(
