### ISSUE TITLE
Dashboard: figure out what to do with SPINS RA notes from external sites

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1136]
Not needed asap, but would be nice to incorporate in some way:

At the moment, SPINS RAs - from CAMH, MPRC, and ZHH - are completing an analogue to our 'scan completed' survey in the SPINS REDCap database (redcap.smh.ca, which is not managed at CAMH, but fully accessible to us in terms of API, tokens, etc).

The reason we have SPINS 'scan completed' surveys from Judy at CAMH is because she clicks through that as well as the analogue in the redcap.smh.ca database. We do not have 'scan completed' surveys from MPRC or ZHH.

So, my thought is that:

We should figure out a way to get the redcap.smh.ca data piped into our database, OR if that's too complicated, we should ask the other SPINS sites to fill out our CAMH scan completed form (and scrap the form in their database).

Any thoughts?

**Comment by tomwright01** [comment]
Would be great if we can get the external redcap instances to talk to dashboard using the API mechanism we already have setup for CAMH redcap.

This will require: 
[ ] poking a hole in the CAMH firewall. This could be limited to a single webpage 
`http://srv-dashboard/redcap`
[ ] Add an API trigger to the remote redcap survey.

Who is the best contact in ResearchIT, IMG to start conversations about firewall holes?

**Comment by josephdviviano** [comment]
I'm closing this unless people have strong feelings about the feature.
