### ISSUE TITLE
SPINS: recent MPRC participants have tilted heads (?)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1137]
Hey @josephdviviano 

Here's a pic of T1s from recent MPRC participants. Am I right in thinking that it looks like all of their heads are pretty significantly tilted? Does this matter?

![mprc_ears](https://cloud.githubusercontent.com/assets/13733654/24619873/8c9628f4-1869-11e7-9624-63210c3bc66c.png)

**Comment by josephdviviano** [comment]
I think you're right, but it shouldn't matter. We need to realign the subjects in general. The trick to just to make sure they actually collect the entire head... we can't deal with cropping.

**Comment by navonacalarco** [comment]
Thanks JDV!
