### ISSUE TITLE
Dashboard: blacklisting *appears* erased if hit browser back button

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1138]
@djoverton @tomwright01 

Hey guys,

Sorry for several issues. I'm QCing today after a bit of an, err,  hiatus, and noticed that when I blacklist a scan by writing a `Blacklist comment`, clicking the `Update` button, and then clicking the browser's `back` button (as opposed to navigating back via the Dashboard link), the blacklist does not _appear_ to take (though metadata/blacklist.csv shows that it has, and my notes are visible when refreshing the browser).

Is it possible to get the Dashboard page to refresh upon hitting the browser's back button? Or is this browser-dependent?

**Comment by tomwright01** [comment]
Modified so updating the blacklist returns to the session page.
