### ISSUE TITLE
dm2-xnat-upload.py wrong error messafe if xnat credential files do not exist or are wrong

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1140]
currently if you don't have a `metadata/xnat-credentials` file, `dm2-xnat-upload.py` reports:

```
2017-04-03 17:52:33,545 - dm2-xnat-upload.py - SPN00 - ERROR - Study:SPN00, Site:ZHH, xnat archive:SPN00 not found with reason:Project:SPN00 not found
ERROR:dm2-xnat-upload.py:Study:SPN00, Site:ZHH, xnat archive:SPN00 not found with reason:Project:SPN00 not found
``` 

there should be an explicit check and error thrown if the credentials fail or don't exist instead.

**Comment by tomwright01** [comment]
Can check if credentials don't exist. Can't check if they are wrong (response from xnat is the same for "cant find record" and "cant login"). Updated error message to be more informative.
