### ISSUE TITLE
MRI QC: clarify how to accommodate incidental findings

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1141]
Hi all. We learned of a couple of incidental findings in SPINS participants today. Thankfully it's relatively uncommon, but made me realize that we should clarify how we accommodate incidental findings in the lab. We should:

- [x] Decide where to keep PDF reports (from MRI Centre) in our file system
- [x] Decide if we always/never/sometimes blacklist affected scans 
- [ ] Discussion: is "incidental finding" worthwhile button to add to the Dashboard?
- [x] Clarify protocol for contacting study RAs - this is necessary, as will impact RMR / recruitment (as scan is primary outcome measure)

@DESm1th @djoverton @josephdviviano @edickie @tomwright01 Is there anything else? What are your thoughts?

I will add our decisions to our QC wiki - I don't think we have anything much there at the moment.

**Comment by josephdviviano** [comment]
The hypointensity scan is a legit concern and it is good that the subject is following up with the doctor. No way I would have spotted that one though.

The hyperintensity is a non issue imho.

**Comment by josephdviviano** [comment]
As a start I've collected some images of incidental findings here:

`/projects/admin/scan-review/incidental-findings/`

Most of them are sort of severe, but should give us a sense of what is out there.

**Comment by tomwright01** [comment]
Re extra PDF reports (Navona's item 1), these can be uploaded to XNAT, placed in the resources folder. They would then be downloaded to the file system automatically.

**Comment by edickie** [comment]
I think we need to be careful of where do put this info, because it is a
pretty serious form of PHI.

**Comment by navonacalarco** [comment]
Good point @edickie . The extra information included in the details from Nancy is sex, age, and group (patient v. control).

I'm not sure if this meets the level of details for not being able to store in the same folder as the data - certainly name, address, emails, etc., would fall into that category, but I'm not sure about this.

I will brush up on that and get back to you.

**Comment by josephdviviano** [comment]
Good point @edickie, because of this I vote redcap. Does it have a file attachment option?

**Comment by navonacalarco** [comment]
@josephdviviano Yes! I think this is the best option. I will add a field with the file upload, confirm it's OK with DL/AV, and then add the info for this participant there. We'll make the field invisible to other sites so there's no confusion.

**Comment by navonacalarco** [comment]
Update from DL: she wants all the 'official' documentation re: incidental findings kept in the official study folder, in the T-Drive. So, the onus is off the lab for that.

So, all that's left is the question of if we want some kind of "incidental finding" tracking in the Dashboard. Would we ever want to be able to quickly draw out a list of all participants across studies for whom that is true, or is that meaningless info for us?

**Comment by josephdviviano** [comment]
Hi @navonacalarco , I think it would be interesting to track incidental findings for research purposes. A) because we could quickly exclude all incidental findings from our analysis (in cases where it's not clear whether to blacklist them), and B) one interesting project would be to analyse these incidental findings in a case study manner.

**Comment by navonacalarco** [comment]
Since nearly all of this has been discussed and resolved, I'm going to close and open a new issues for the single remaining item:  add an "incidental finding"  button to the Dashboard.
