### ISSUE TITLE
ubuntu-x-swat/x-updates no longer supports 14.04

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1146]
Noticed the same error in the Ansible logs occurring (failed: [mansfield.camhres.ca] (item=ppa:ubuntu-x-swat/x-updates) => {"failed": true, "item": "ppa:ubuntu-x-swat/x-updates", "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}), did some reading and found that this PPA is not supporting 14.04 anymore (thus the 404). 14.04 is, however, officially supported until April 2019.

Removed this line for now (wasn't doing anything anyway); currently looking for alternative PPA.

**Comment by josephdviviano** [comment]
Hi @djoverton ,

If the PPA isn't supported anymore, we can just get rid of it. It just gives us access to slightly different NVIDIA drivers that we don't necessarily need.

**Comment by djoverton** [comment]
Fine by me, I wasn't sure why it was there in the first place, assumed some sort of historical issue.

**Comment by josephdviviano** [comment]
Yeah I imagine we needed it for something way back when, but if the PPA isn't maintained any longer, we likely get the most appropriate nvidia drivers straight from Ubuntu. They're actually pretty good about that (thanks to Nvidia).
