### ISSUE TITLE
find out of NIH considers Hong Kong a city or a state

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1151]
:'(

**Comment by josephdviviano** [comment]
:musical_note: let's get political, po-lit-i-cal :musical_note:

**Comment by tomwright01** [comment]
Now I am British again (not European), I hold it's a colony and I want it back!!!!

**Comment by navonacalarco** [comment]
They're agnostic: use whatever one the birth certificate (even if it language differs for participants born in same physical location with different birth certificate language pre-post 1997).
