### ISSUE TITLE
Trouble submitting to queue

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#1152]
Hi, 

I'm having trouble running code on the queue. 

<b>Code:</b>
<code>module load SGE-extras/1.0</code>

`while read SID; do sge_batch /projects/saba/Useful_Scripts/HCP_fMRI_reg.sh /archive/data/RTMSWM/pipelines/fmri/rest/ /projects/saba/HCP_fMRI_SCZ/hcp_RTMSWM/ /projects/saba/HCP_fMRI_SCZ/RegOutput_RTMSWM $SID; done < /projects/saba/HCP_fMRI_SCZ/SubjID_RTMSWM.txt`

<b>Error:</b>
`Your job 654091 ("STDIN") has been submitted
print() on closed filehandle JOBSCRIPT at /opt/quarantine/SGE-extras/1.0/build/bin/sge_batch line 148.`

**Comment by josephdviviano** [comment]
@sabashahab :

can you run this

```
while read SID; do echo sge_batch /projects/saba/Useful_Scripts/HCP_fMRI_reg.sh /archive/data/RTMSWM/pipelines/fmri/rest/ /projects/saba/HCP_fMRI_SCZ/hcp_RTMSWM/ /projects/saba/HCP_fMRI_SCZ/RegOutput_RTMSWM $SID; done < /projects/saba/HCP_fMRI_SCZ/SubjID_RTMSWM.txt
```

and copy the output here

**Comment by josephdviviano** [comment]
Also, you don't need to use `sge_batch`. You could submit your script like this:

````
while read SID; do
    qsub -V -q main.q /projects/saba/Useful_Scripts/HCP_fMRI_reg.sh /archive/data/RTMSWM/pipelines/fmri/rest/ /projects/saba/HCP_fMRI_SCZ/hcp_RTMSWM/ /projects/saba/HCP_fMRI_SCZ/RegOutput_RTMSWM $SID
done < /projects/saba/HCP_fMRI_SCZ/SubjID_RTMSWM.txt
```

**Comment by sabashahab** [comment]
@josephdviviano Hi Joe, I just ran the code using qsub as you suggested and it's running just fine. Thanks for your help!

**Comment by josephdviviano** [comment]
no problem! sge_batch is pretty old.
