### ISSUE TITLE
python method going forward

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1155]
explored lots of options, but we decided on this:

the naming convention for python environments will be `${python_version}_${type}_${version_number}`

Two separate Miniconda python envs will be maintained. The one for science will be static, and the one for devops will be more fluid.

+ `/opt/quarantine/python/X.X.X_sci_XX` will contain the scipy stack only and will NOT change.
+ `/archive/code/python_X.X.X_datman_XX` will contain all of the backend / web / etc. packages required by datman and dashboard. This will likely evolve.

We also discussed project-specific virtual environments for the code in `/opt/quarantine` and `/archive/code`. Those should go in `/path/to/projectname/env`. 

For some pipelines (e.g., `dm_proc_fmri.py`, which calls `epitome` scripts, which in turn call other software we've written e.g., `ciftify`) it isn't possible for us to rely on project-specific virtual environments (you can only load one environment at a time). In these cases it would make sense to `module load /opt/quarantine/python/X.X.X_sci_XX`. However having the virtual environments around will help us run these bits of code ad-hoc, and works towards making our code more exportable.

Did I miss anything @tomwright01 @edickie @DESm1th @djoverton @navonacalarco ?

**Comment by tomwright01** [comment]
BTW: worth taking a look at [conda-forge](https://conda-forge.github.io/feedstocks). Has many packages not in the regular conda distro including nibabel.

**Comment by josephdviviano** [comment]
nice, thanks Tom!
