### ISSUE TITLE
Java error in matlab

### ISSUE THREAD

**Issue by NedaRR** [TIGRLab/admin#1156]
Error using ParforProgMon (line 37)
Java exception occurred:
java.lang.IllegalArgumentException: invalid range properties
	at javax.swing.DefaultBoundedRangeModel.<init>(Unknown Source)
	at javax.swing.JProgressBar.<init>(Unknown Source)
	at javax.swing.JProgressBar.<init>(Unknown Source)
	at ParforProgressMonitor$ProgServer.<init>(ParforProgressMonitor.java:89)
	at ParforProgressMonitor$ProgServer.<init>(ParforProgressMonitor.java:77)
	at ParforProgressMonitor.createServer(ParforProgressMonitor.java:16)

Error in batch_fitting (line 72)
ppm = ParforProgMon(['Fitting ' roifile, ' : '], numOfVoxels-current_split_start+1,...

If it helps:
matlab file line 36-42:
   % Normal construction
                o.JavaBit   = ParforProgressMonitor.createServer( s, N, progressStepSize, width, height );
                o.Port      = double( o.JavaBit.getPort() );
                % Get the client host name from pctconfig
                cfg         = pctconfig;
                o.HostName  = cfg.hostname;
            else

matlab line 67-75: 
% set up the PARFOR Progress Monitor
[mypath myname myext] = fileparts(mfilename('fullpath'));
mypath = [mypath '/../ParforProgMonv2/java'];
pctRunOnAll(['javaaddpath '  mypath]);
progressStepSize = 100;
ppm = ParforProgMon(['Fitting ' roifile, ' : '], numOfVoxels-current_split_start+1,...
                    progressStepSize, 400, 80);
tic

**Comment by josephdviviano** [comment]
this is somehow a problem with matlab's `parfor` / `parpool` implementation. the non-parallel option ('_single`) works well, it's just the parallel version that's borked.

@NedaRR is going to contact the authors here https://groups.google.com/forum/#!forum/noddi for guidance.

**Comment by josephdviviano** [comment]
@NedaRR -- any luck posting an issue?

**Comment by NedaRR** [comment]
Didnt try again. Seems most have the same problem. For now running with
single.

**Comment by josephdviviano** [comment]
OK, I'm going to close this issue if you don't want to pursue it.
