### ISSUE TITLE
Dashboard: discuss which acquisition types should be interactive v. static

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1157]
Posting here so don't forget:

Currently, all acquisitions in the Dashboard have been moved to interactive viewer for testing. But it might make more sense to have only some be interactive, and others as static. 

My sense would be to the T1 and FLAIR (and maybe T2) as interactive, but all the rest static - but I really don't know.

@DESm1th @edickie @josephdviviano @djoverton @tomwright01 any thoughts?

**Comment by josephdviviano** [comment]
I'd leave them all interactive.

Additionally, I'd make it possible to view the SFNR maps etc. for the fmri images in the interactive viewer.

**Comment by navonacalarco** [comment]
Thanks JDV.

My own thoughts are that (1) I think there's an overabundance of information here, which is overwhelming for anyone who isn't highly trained, and (2) it takes a really long time, which I think will result in people blasting through this too quickly and missing things that might be more easily observed in the static docs.

Also, are these visualizations of Field Maps at all meaningful?

**Comment by djoverton** [comment]
@navonacalarco on the contrary (in my opinion), Aristotle's impression seemed to be that static images were too tempting to blast through quickly and were hard to notice subtle differences in. I think the idea of the viewer was to force people to look at each slice along all axes. It does take longer, but that was the intention I believe.

**Comment by djoverton** [comment]
To make my opinion/interpretation of Artistotle's preference more explicit, I think there is value in having the viewer for all acquisition types, except maybe the Field Map ones (as you pointed out). We should also make a point of showing anyone who will be doing QC how to use the tool, and methodically go through each axis (rather than haphazardly scrolling in 3 dimensions), in addition to providing visual examples of what to look for (we've already collected a few of these).

**Comment by navonacalarco** [comment]
Ok. I wasn't here when you had that meeting with AV after the incidental finding was missed. Did anyone take minutes? 

Given that this viewer has already been implemented - but RAs haven't yet been trained on how to use it- I think we need to do this training asap, on the points you describe. I'm drafting an email re: all the recent changes and trying to update the documentation. Would you @djoverton or someone else feel comfortable leading the demo about how to use this tool and what to look for?

**Comment by djoverton** [comment]
Sure, I don't mind showing people.

**Comment by josephdviviano** [comment]
One only needs to do an extensive overview of a single T1 / FLAIR to catch incidental findings. The rest of the scanning can be more 'haphazard', which allows us to figure out problems with the scanner. I think it takes a little longer with the interactive viewer, but not much longer.

I'm in favor of all images being viewed the same way for simplicity sake. We can look at the SFNR images, or field maps, if we want, but we don't have to.

**Comment by navonacalarco** [comment]
Ok all, thanks for the detailed responses. Let's leave everything as it is, then, with the exception of 
changing the Dashboard to remove the viewer for the Field Maps (will go back to having no visualization of those).

I'll update the Wiki documentation, and update the drafted email for Dashboard for users, to announce these changes.

Sometime next week, we'll have the external QC'ers over the lab. Tom can show everyone around the updated Dashboard, and Dawson can explain how best to navigate through the T1/FLAIR.

Sound good to everyone?

**Comment by navonacalarco** [comment]
One last question: are we going to continue to generate the html pages, even if they're not used as the primary means of QC? I can see them being useful for sharing QC-related findings with groups that don't have access to the Dashboard (e.g., MRI centre). But I'm not sure if that's useful enough given the space they'd take.

**Comment by josephdviviano** [comment]
Navona, we should also add viewers for the SFNR maps etc for the fMRI images.

**Comment by josephdviviano** [comment]
As fro the html: the MRI center and people like them don't find the HTML pages that useful ... they prefer to see the raw data and typically just want a screenshot in a email and the session name.

As disappointing as it is, after we've found a problem, a screenshot is the best option. The HTML etc. was really more about figuring out what was worth screenshotting.

Though, some of you could go ask Nancy what she would want to see as a feature. They never really cared about the PDF or HTML reports that much. In fact the general review from all of the physicists was 'meh'.

**Comment by navonacalarco** [comment]
re: adding viewers for SFNR: whoops, sorry, added that in above!

re: html. Ah, I see. That makes sense, I guess, thanks. Maybe we _should_ touch base with Nancy et al. - the last time we met with them, the Dashboard was just a glimmer in Tom's eye. It would be good to show them what's been done, at least, and see if they have any helpful feedback. 

:)

**Comment by josephdviviano** [comment]
@navonacalarco I agree they have great insight into what's useful / a waste of time when it comes to looking at quality and incidental findings.

**Comment by navonacalarco** [comment]
Update: everyone will have this in their email, but we're meeting with QC staff/students on:

Friday April 21st           3-4pm
Tuesday April 25th       1-2pm

Thanks :)

**Comment by tomwright01** [comment]
Back to the original question. As it stands papaya can only show 3D images, not 4D. This means only the 1st volume is displayed, e.g. for a DTI only the first B0. 

I'm going to take a look to see if I can hack papaya to become 4D otherwise this limits the usefulness of this visualisation for DTI and FMRI images.

**Comment by josephdviviano** [comment]
@tomwright01  : the purpose of the fMRI correlation and SFNR images is to summarize the 4d information in a 3d image. Similarly, the head motion metrics for fmri and the spike count metrics for DTI are meant to replace watching all volumes in 4D. Does that make sense?

**Comment by tomwright01** [comment]
@josephdviviano Of course that makes sense, what doesn't make sense is looking at only the first volume of a 4D MRI, which is what the papaya interface is currently showing. It can give a false sense of security.
I'm also not sure that looking at the correlation and SFNR images is more useful than looking at the 2D sampled slice images. 
Take a look at a couple yourself, it's easy enough to use the file menu in any of the papaya viewers to open other nii files.

**Comment by josephdviviano** [comment]
@tomwright01 looking at the first image of many is good for detecting warping in the image. For example, if someone has a metal retainer, every image will we warped in approximately the same way, so looking at the first image is enough.

The correlation and SFNR images are statistics taken from the entire time series, and are therefore sensitive to abnormalities at any timepoint. So in the case that there are strange events throughout the timeseries, those stat maps will show problenms from any time point in a 2D sampled slice image.

For example, both are highly sensitive to large head motion events, or the spiral artifact. Neither of these are apparent on the first time point.

**Comment by josephdviviano** [comment]
@tomwright01 as an aside, the best alternative to only looking at the first volume of a 4D image is something akin to FSLview's 'movie mode'. If you can think of a good way to do that in a browser maybe it's worth doing, but it is extremely time consuming to watch the full movie for every image, which is why I think trying to find metrics that are sensitive to fluctuations in time is more fruitful.

You're welcome to do what you please, though. At this point I feel more like an observer of how the QC system is evolving than an active participant.

**Comment by tomwright01** [comment]
Added a warning to non T1 / T2 scans that only the first volume can be viewed.
