### ISSUE TITLE
SPINS: review & fix data quality issues flagged by RDoC

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1159]
deadline: April 24th SPINS call.

**Comment by josephdviviano** [comment]
need help?

**Comment by navonacalarco** [comment]
I think I should be ok. All the issues seem to be "MISCALCULATED AGE - INTERVIEW AGE INCONSISTENT WITH DATE" or "MISSING SUBJECTS FOR DATA STRUCTURE PROVIDED" propagated across several subjects and forms....

Here's the CSV if you're interested:
[Collection_2098.csv.zip](https://github.com/TIGRLab/admin/files/922907/Collection_2098.csv.zip)

How about I try to get through it and let you know if I get stuck?

**Comment by navonacalarco** [comment]
OK, I stuck. I emailed RDoC Tuesday morning, and no response yet, so maybe JDV - if you have time - you can take a quick look. 

We have 3 types of errors:

1. "MISCALCULATED AGE - INTERVIEW AGE INCONSISTENT WITH DATE" 
2. "MISCALCULATED AGE - INTERVIEW DATE INCONSISTENT WITH AGE"
3. "MISSING SUBJECTS FOR DATA STRUCTURE PROVIDED"

I have "solved" the first 2 (which are just errors for two participants across multiple forms). However, the 3rd error I don't quite understand. 

Here's more info about what (I think?) is going wrong. I'll also forward you the email I sent to RDoC.

[NIH_RDoC.Rmd.zip](https://github.com/TIGRLab/admin/files/943191/NIH_RDoC.Rmd.zip)

No worries if you can't get to this, though - I can return to it tomorrow. 

:)

**Comment by josephdviviano** [comment]
`SUBMITTED_SRC_SUBJECT_ID` is missing for all of these subject, along with other important things like age.

**Comment by josephdviviano** [comment]
navona im not sure how you expect me to debug this, i have no idea where the raw data is and you sent me a disgusting r markdown file instead of a working script :)

**Comment by navonacalarco** [comment]
Hey JDV, you're seeing everything that we've got: they give a spreadsheet, not a script. There is nothing to "debug".

The "disgusting" file I sent you is my attempt at summarizing what's wrong. 

I'll do this tomorrow, thanks.

**Comment by josephdviviano** [comment]
Right, I can't figure out from what you sent me what's wrong. Looks like they're complaining about the data uploaded by MRC and or ZHH? Your script can't really be executed, and it seems to be filling in values in the .csv you sent me, based on information you gleaned from elsewhere, so I can't really figure out what is going on.

**Comment by navonacalarco** [comment]
Error flags were incorrect. Haah!
