### ISSUE TITLE
Problems with Resources folder

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1163]
As expected I am running into problems with multiple copies of the resources folders.

# Background: 
* Originally (pre datman 2.0) The original name of the zip file was removed when the files were uploaded to xnat. Resources were extracted from xnat by extracting the files.
* When xnat extract moved to the REST interface the folder name on XNAT was preserved (BEHAV) but the zip folder name was deleted. Files not existing within an XNAT sub-folder (identified as `NO LABEL` on XNAT) were placed within a `misc` folder.
* Conversation with Nancy indicated the zip file name contains important information. Xnat upload was modified to preserve the original zip file name as an XNAT folder. At the same time upload was modified to place files in a default XNAT folder (`RESOURCES/MISC/` rather than `RESOURCES/NO LABEL`)

# Current situation:
XNAT can have up to 3 copies of the same data:

1.  `RESOURCES/NO LABEL/<files>`
2.  `RESOURCES/NO LABEL/<archive>/<files>`
3.  `RESOURCES/MISC/<archive>/<files>`

the file system can have up to 4 copies of the data:
1.  `RESOURCES/<files>`
2.  `RESOURCES/misc/<files>`
3.  `RESOURCES/misc/<archive>/<files>`
4.  `RESOURCES/MISC/<archive>/<files>`

Apart from wasted disk space, this situation is causing other problems. 
Duplicate SPRL scans are being linked multiple times (e.g. `PACTMD_CMH_3060084_01`). Attempts to insert these duplicate scans into dashboard fail.

# Solution:
1. Modify `dm2-xnat-upload.py` to find, and delete duplicate files in XNAT, which exist in the archive but which would not be added by the script.
* Limiting files to be deleted to those existing in the archive will avoid deleting files that have been manually added to XNAT (BEHAV data).
2. Modify `dm2-xnat-extract.py` to find and delete duplicate files on the filesystem, which do not exist in XNAT.
3. Delete any broken symlinks in the `nii/` subfolders on the file system.

Before I start to implement this, can anyone forsee any problems? I think the biggest risk is accidentally deleting data which has been manually uploaded to XNAT, or placed on the file system, as this will be hard to replace. By limiting deletion to just duplicate files that exist in the MRI archives this can be avoided.

@josephdviviano @edickie @DESm1th @djoverton Please let me know if you can see anything I have missed.

**Comment by josephdviviano** [comment]
Hi @tomwright01 sounds fine, but I'm worried about "Delete any broken symlinks in the nii/ subfolders on the file system."

I don't think symlinks you find will be only due to your linking scripts. I remember generating a bunch of links at one point. Might be worth reviewing the existing links to make sure that deleting everything won't require a bunch of manual labor.

**Comment by tomwright01** [comment]
Just checked, there are `currently` no broken links pointing at RESOURCES (there are some in the civet and freesurfer pipelines).

**Comment by josephdviviano** [comment]
Cool -- if you only delete broken links pointing at RESOURCES we should be safe.

**Comment by josephdviviano** [comment]
@tomwright01 fyi -- bad resources folders are preventing the empathic accuracy pipeline from running on SPINS, because the pipelines are finding too many log files (because there are duplicate copies of logs).

**Comment by tomwright01** [comment]
Ok, I'll stop procrastinating and `git err dun`!!

Tomorrow...

**Comment by josephdviviano** [comment]
no rush I don't think anyone needs those GLM outputs anytime soon

ps -- was that a git pun? :-D

**Comment by navonacalarco** [comment]
![6879e0a10fcf34d65cef49f9035d917b_funny-pun-memes-memesuper-funny-puns-meme_320-213](https://cloud.githubusercontent.com/assets/13733654/25595413/bc073bc0-2e92-11e7-91ab-327c224280b5.jpeg)

**Comment by josephdviviano** [comment]
@tomwright01 is this resolved?

**Comment by tomwright01** [comment]
Pretty sure this is now resolved and running nicely.
