### ISSUE TITLE
Dashboard: slight tweak to language re: PHI

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1166]
Language is currently copied verbatim from MRI Centre:

> By logging into this system, you agree to not upload/enter any information that has PHI. Screening forms and booking comments are to list only Participant Identifiers, without participant initials or other potentially identifying information. We reserve the right to restrict or terminate your access if misuse is discovered. 

But this doesn't really make sense for us: we don't have screening forms and booking comments.

How about: 

> By logging into this system, you agree to not upload/enter any information that has Personally Identifying Information (PII), such as participant initials or other potentially identifying information. We reserve the right to restrict or terminate your access if misuse is discovered.

**Comment by tomwright01** [comment]
Done
