### ISSUE TITLE
Dashboard: pull in REDCap RA notes for `COGBD`, not `COGBDO`

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1168]
I think different nomenclature is resulting in the Dashboard (COGBDO) not being able to match subject ID in REDCap RA notes (COGBD).

e.g., Dashboard participant COGBDO_CMH_216636_01not bringing in REDCap record 173.

**Comment by DESm1th** [comment]
An update to this issue: The dashboard has a second broken entry for this person under the ID 'COGBD_CMH_216636_01' (note the missing 'O').

**Comment by tomwright01** [comment]
Still not sure why this link is breaking on dashboard but there is a subject with this name in the file system (study COGBDO). I'm pretty sure it's `dashboard/parse_qc.py` that made the database entry. Unfortunately the filename passed all the datman scanid checks, we _could_ update these to ensure only valid study identifiers are accepted in future.
To fix this one we need to:

- [ ] Update scans.csv to name the zip file correctly
- [ ] Purge the file system of the incorrectly named files
- [ ] Update the sessions and scans tables in the database to reflect the correct name

@navonacalarco Should RedCap also be updated to reflect the change?
