### ISSUE TITLE
link for spiral scans failed on  COGBDO_CMH_216636_01_01

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1169]
Spiral data is in XNAT (MISC folder), but not in our file system.

**Comment by navonacalarco** [comment]
Update: sorry, it doesn't look like spiral scan data is in the Dashboard for several (all?) COGDBO participants, though it exists in the file system data/RESOURCES/ as sprl.nii.

**Comment by tomwright01** [comment]
Regex was wrong in config. Corrected.
