### ISSUE TITLE
Dashboard: TechNotes "click here" link downloading instead of opening in new tab

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1170]

**Comment by tomwright01** [comment]
I think this is browser specific. Seems fine on mine.

**Comment by navonacalarco** [comment]
![d3df579be7c488d09d42da41fea28cd6_thanks-meme-thank-you-cat-cat-meme-thank-you_485-510](https://cloud.githubusercontent.com/assets/13733654/25590419/7d1735e6-2e7e-11e7-9219-8045c45a71d2.jpeg)
