### ISSUE TITLE
PNSC: link "missing" scans

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1174]
The following PNS IDs should have scans linked from SPINS, but _do not_ have data in /archive/data/PNSC/data/nii:

PNS_CMH_0001  >  SPN01_CMH_0079
PNS_CMH_0002  >  SPN01_CMH_0076
PNS_CMH_0008  >  SPN01_CMH_0087
PNS_CMH_0009  >  SPN01_CMH_0059
PNS_CMH_0015  >  SPN01_CMH_0094   
PNS_CMH_0016  >  SPN01_CMH_0095
PNS_CMH_0017  >  SPN01_CMH_0096
PNS_CMH_0018  >  SPN01_CMH_0097
PNS_CMH_0022  >  SPN01_CMH_0100

@akhairullah will need soon.

**Comment by navonacalarco** [comment]
Manually added the mappings above (plus session and repeat number) to the PNSC/metadata/external-links.csv, as these participants were not captured in the Scan Completed survey.

Leaving open until they appear...

**Comment by DESm1th** [comment]
I think you have to run dm-link-project-scans.py manually with the link file as the input. That one was never run as part of the cron job, and dm_link_shared_ids.py, which is run nightly, only looks at the REDCap shared ids.

**Comment by navonacalarco** [comment]
Oh, thanks Dawn! Will do.

**Comment by navonacalarco** [comment]
It worked! Thanks, Dawn! :)

@akhairullah, all the PNSC data is now in the archive/data/PNSC folder.

**Comment by navonacalarco** [comment]
@akhairullah says a few still missing:

missing | why 
--------- | -----------
PNS_CMH_0004 |
PNS_CMH_0005 |
PNS_CMH_0007 |
PNS_CMH_0010 |
PNS_CMH_0011 |
PNS_CMH_0012 |
PNS_CMH_0013 |
PNS_CMH_0014 |
PNS_CMH_0021 |
PNS_CMH_0039 |
PNS_CMH_0042 |
PNS_CMH_0046 |
PNS_CMH_0047 |
PNS_CMH_0048 |
PNS_CMH_0050 | 
PNS_CMH_0052 |
PNS_CMH_0053  |
PNS_CMH_0054  |
PNS_CMH_0055 |
PNS_CMH_0056 |
