### ISSUE TITLE
Install FSL 5.0.10 on our system

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#1176]
Marion says the newer version has better !CA scoring tools...So it will probably be useful for Erika

**Comment by josephdviviano** [comment]
k

**Comment by josephdviviano** [comment]
started workin on this at `/projects/jviviano/code/fsleyes`, but I can;t seem to bootstrap the signularity container, it is complaining with...

```
tar: var: Cannot mkdir: Read-only file system
tar: var/log/apt/term.log: Cannot open: No such file or directory
tar: var: Cannot mkdir: Read-only file system
tar: var/log/dpkg.log: Cannot open: No such file or directory
tar: var: Cannot mkdir: Read-only file system
tar: var/log/fontconfig.log: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
ERROR:python:Error extracting image: /home/jviviano/.singularity/docker/sha256:493308ce80fdb67ef261c97859bc477d61ba7f3cb16dd5dd06be4fdce4a4d97e.tar.gz
ERROR  : Something went wrong during build module: Interrupted system call. 
ERROR  : Container does not have a valid /bin/sh
ABORT  : Retval = 255
```

@tomwright01 any insights here? the docker image is read only, and should be if i understand this process correctly, but I never asked the singularity container to be read only...

**Comment by DESm1th** [comment]
Hey Joe,

Not sure how the singularity engine differs from the docker one but I think it has to make local directories to hold information about the running container and by default it might be trying to do that in one of the root only directories (i.e. wherever singularity is installed). Also, I think you need to supply a base operating system in the docker file for the FSL application to run (but I'm not sure if that latter error is just a consequence of not being able to write anywhere).

**Comment by josephdviviano** [comment]
Hey @DESm1th :

**Comment by josephdviviano** [comment]
from @tomwright01 

missing

```
lib-gl-mesa-dri
i965-va-driver # which I think is probs specific to this system
```

**Comment by josephdviviano** [comment]
Fun news! We're on 16.04 and can install this like normal in the quarantine ... so I did.

PS -- it includes `FSLeyes`.
