### ISSUE TITLE
Datman / dashboard 'permission denied' crashes due to log file

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1178]
When datman scripts that interact with the dashboard are run as a non-root user, the scripts crash on import with the following exception and stack trace:

/mnt/tigrlab/projects/dawn/modules/datman/datman/dashboard.py in <module>()
      2 from __future__ import absolute_import
      3 import logging
----> 4 import dashboard
      5 #from dashboard.models import Study, Session, Scan, ScanType
      6 import datman.scanid

/archive/code/dashboard/dashboard/__init__.py in <module>()
     29                                        'a',
     30                                        1 * 1024 * 1024,
---> 31                                        10)
     32     file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
     33     app.logger.setLevel(logging.DEBUG)

/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/logging/handlers.pyc in __init__(self, filename, mode, maxBytes, backupCount, encoding, delay)
    115         if maxBytes > 0:
    116             mode = 'a'
--> 117         BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
    118         self.maxBytes = maxBytes
    119         self.backupCount = backupCount

/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/logging/handlers.pyc in __init__(self, filename, mode, encoding, delay)
     62         if codecs is None:
     63             encoding = None
---> 64         logging.FileHandler.__init__(self, filename, mode, encoding, delay)
     65         self.mode = mode
     66         self.encoding = encoding

/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/logging/__init__.pyc in __init__(self, filename, mode, encoding, delay)
    911             self.stream = None
    912         else:
--> 913             StreamHandler.__init__(self, self._open())
    914 
    915     def close(self):

/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/logging/__init__.pyc in _open(self)
    941         """
    942         if self.encoding is None:
--> 943             stream = open(self.baseFilename, self.mode)
    944         else:
    945             stream = codecs.open(self.baseFilename, self.mode, self.encoding)

IOError: [Errno 13] Permission denied: '/mnt/tigrlab/archive/code/dashboard/logs/dashboard.log'

**Comment by tomwright01** [comment]
I added logserver logging. Lets let it go for a couple of days before I remove the file handling.

**Comment by tomwright01** [comment]
File logging is disabled.
