### ISSUE TITLE
SPINS: get MRP Tech Notes into QC html

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1180]
We recently got MPRC to upload Tech Notes into XNAT alongside their scans, which is great!

The Tech Notes are being added alongside the EA behavioural files in the Resources folder. See  `SPN01_MRP_0097_01_01` as an example.

However, the Tech Notes aren't being recognized by our system - I _think_ because MPRC seems to be uploading a `docx` file, not a PDF.

Can we simply change the html QC pages code to look for a docx in addition to a PDF, or would this cause problems?

**Comment by josephdviviano** [comment]
another option: we auto convert any .doc / .docx files to PDF and then link those to the dashboard:

`soffice --headless --convert-to pdf filename.doc`
