### ISSUE TITLE
Same volume mounted repeatedly on multiple machines

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1184]
![multiple_mount](https://cloud.githubusercontent.com/assets/1835885/25755441/1680c4c6-3191-11e7-846b-937b2d7a316e.png)

I've noticed this myself on a couple of machines, and Colin has had this problem as well. Did some cursory research and still not sure what's causing it. I don't think it's a serious problem, but it's annoying.

**Comment by josephdviviano** [comment]
All I know is that I had this problem on `14.04`, and on the same machine with `16.04`, I have no such issue.

**Comment by josephdviviano** [comment]
@djoverton is there a plan for dealing with this

**Comment by djoverton** [comment]
I've been using 16.04 as well for a while now and haven't noticed it happen. I'll make the assumption that it was "fixed" in 16 and close this for now.
