### ISSUE TITLE
Freesurfer pipeline outputs corrupted

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1186]
Looks like the formatting for the freesurfer outputs is messed up. See SPINS/pipelines/freesurfer/CorticalMeasuresENIGMA_ThickAvg.csv

Apparently these are needed middling urgent.

**Comment by DESm1th** [comment]
I wonder if that may have been caused by someone running the local copy of dm_proc_freesurfer on the SPINS project. The other projects look fine, and the SCC copy hasnt changed (at all, as far as I know) in a year or so.

**Comment by josephdviviano** [comment]
Strange. Shouldn't the SCC version replace the spreadsheet nightly?

**Comment by edickie** [comment]
The spreadsheet only updates after new subjects are run..in version dawn 2.0. it will update more frequently.

Anyway, rerunning the post_freesurfer.sh script fixes it.
