### ISSUE TITLE
Some ASDD fmri NBACK preprocessing errors

### ISSUE THREAD

**Issue by lyoganathan** [TIGRLab/admin#1192]
Hey, most of the NBACK subjects ran fine, but there were some who had errors. I have attached a file with subject names and related errors, most seem to be due to not finding correct number of fMRI inputs.

I was wondering if someone could help me with this?

Thanks,
Laagi

[errors_list.txt](https://github.com/TIGRLab/admin/files/993469/errors_list.txt)

**Comment by josephdviviano** [comment]
I fixed everyone except for the following:

+ ASDD_CMH_HEF020_01 expected anatomical aparc+aseg.nii.gz not found in /archive/data/ASDD/pipelines/hcp/ASDD_CMH_HEF020_01/T1w nissl.camhres.ca 
+ ASDD_CMH_HEF021_02 expected anatomical aparc+aseg.nii.gz not found in /archive/data/ASDD/pipelines/hcp/ASDD_CMH_HEF021_02/T1w penfield.camhres.ca  
+ ASDD_CMH_EF050_02 expected anatomical aparc+aseg.nii.gz not found in /archive/data/ASDD/pipelines/hcp/ASDD_CMH_EF050_02/T1w penfield.camhres.ca 

These need to be QC'ed
