### ISSUE TITLE
fix error re: WTAR std score in spins-clean.py

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1194]
Should equate:
CMH/ZHH variable: `wtar_raw_score`  > MRC variable: `wtarsum_total`
CMH/ZHH variable: `wtar_std_score`  > MRC variable: `wtarsum_std`

**Comment by navonacalarco** [comment]
Done. Problem wasn't with the script, but rather with the raw data. Incorrect values have been fixed.

**Comment by josephdviviano** [comment]
RIP MRC?

**Comment by navonacalarco** [comment]
Haven't killed anyone yet.
