### ISSUE TITLE
Misnamed data in SPINS

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1198]
Somehow PRELAPSE data has gotten mixed in with SPINS data for at least one participant (SPN01_CMH_0104_01). The file SPN01_CMH_0104_01_01_T1_11_Sag-T1-BRAVO-256x256x25.5x1.0.dcm actually belongs to PRE01_SFD_32014_01_01

What I'm doing:

1. Removing the wrongly labeled data (after confirming that it's correctly exported to where it should be)
2. Doing a search to confirm that no other data is hiding in SPINS that shouldn't be there.
3. Investigating a bit to try to figure out how the heck this happened.

**Comment by navonacalarco** [comment]
Thanks Dawn!

**Comment by DESm1th** [comment]
Ok, it looks like the only mislabelled data in SPINS is for SPN01_CMH_0104_01 and just the two series:

SPN01_CMH_0104_01_01_DTI60-1000_14_Ax-DTI-60plus5.dcm
SPN01_CMH_0104_01_01_T1_11_Sag-T1-BRAVO-256x256x25.5x1.0.dcm

Both of which belong to participant PRE01_SFD_32014_01_01. But the series 11 and 14 don't exist for that participant (they're not in XNAT). Looking into that now.

**Comment by DESm1th** [comment]
Ok, those two series belong to the repeat session (PRE01_SFD_R32014_01_01) and are there in XNAT for that repeat ID. The misnamed copies in SPINS were deleted. No further problems should arise related to this.
