### ISSUE TITLE
myelin mapping for PRELAPSE baseline scans

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1199]
build basic pipeline using Grydeland H. et al J Neurosci 2013

**Comment by josephdviviano** [comment]
Turns out the best solution to this is running the complete HCP pipeline from start to end. @DESm1th has some working code.

@DESm1th -- can you close this issue once we have the pipeline somewhat packaged and up on our github? Thanks (let me know if I can help out).

**Comment by DESm1th** [comment]
I've added this to datman. Will move the PRELAPSE outputs into the archive once the last few jobs have finished.
