### ISSUE TITLE
how to name SPINS participant - originally a PNS participant - but now shared?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1203]
Hi guys, 

I'd like your thoughts on how to deal with this situation, described by Judy:

> We had a participant recently complete a PNS scan (PNS_CMH_0054_01_01) that was not shared with SPINS at the time because they were on hold. They’re not on hold anymore so we are now trying to complete the parts of the SPINS scan that weren’t completed in PNS, but I was wondering how naming would work. Would we have you or Joe link the PNS scan to SPN01_CMH_0129_01_01 and we name the scan we will be completing with the parts for only SPINS SPN01_CMH_0129_01_02 or just keep to original naming?

My thought is:

- rename the existing PNS_CMH_0054_01_01 data as SPN01_CMH_0129_01_01
- alter the original 'scan completed' information so that SPN01_CMH_0129_01_01 properly links to PNS_CMH_0054_01_01
- when the participant comes back to complete the extra SPINS scans, name them SPN01_CMH_0129_02_01

Does that make sense, or is there a better way?

**Comment by DESm1th** [comment]
If you alter the scan completed for PNS_CMH_0054_01_01 so that it has SPN01_CMH_0129_01_01 as a secondary ID, the data can be linked that way. Then when the new scans come in, if a new scan completed form is filled out for SPN01_CMH_0129_01_01 that data would be extracted alongside the linked data. That would be easiest, unless there is some reason to prefer having the SPINS ID as the primary subject ID for the first portion of the data

**Comment by navonacalarco** [comment]
Ok, great! Altering the scan completed in that way makes sense. 

But just to clarify:

1. We want the data that is currently named PNS_CMH_0054_01_01 to be linked to SPN01_CMH_0129_01_01. We will achieve this using the modified scan completed form.

2. Then, the new data coming in - which is data only collected for SPINS - should be named SPN01_CMH_0129_0**2**_01, to reflect the fact that the scan is completed on a different day. If SPN01_CMH_0129_02_01 isn't linked to anything on the scan completed form, its data won't end up in PNS_CMH_0054_01_01. @DESm1th, is that right ? 

Thanks!

**Comment by DESm1th** [comment]
Yup, that's right.

**Comment by navonacalarco** [comment]
Done. Thanks @DESm1th
