### ISSUE TITLE
VIPR task scans preprocessing

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#1207]
Is there any chance we can get the 6 task blocks from the VIPR study to run though the standard preproc pipelines? 

it would make life nicer for George.

**Comment by josephdviviano** [comment]
What's the:

+ slice timing
+ number of TRs to remove

**Comment by navonacalarco** [comment]
I really think we did this before, but I can't find evidence of it. I do remember that he wanted the number of TRs removed should be identical to SPINS and TDCS.

**Comment by josephdviviano** [comment]
Hi Colin,

OK, I've set this study up to run.
