### ISSUE TITLE
Some SPINS Participants Missing EA Rating Files

### ISSUE THREAD

**Issue by loliver4** [TIGRLab/admin#1210]
I've managed to track down why some SPINS participants don't have EA and/or EA behavioural outputs, but there are a few cases that remain ambiguous. I've attached a list of these participants with the info I have for each one in case I'm missing something or they just haven't been processed yet, etc.

Thanks!
[SPINS_Missing_EA_Data_June-6-2017.xlsx](https://github.com/TIGRLab/admin/files/1055754/SPINS_Missing_EA_Data_June-6-2017.xlsx)

**Comment by josephdviviano** [comment]
Thanks!

**Comment by josephdviviano** [comment]
```
CMH_0096,"rating file for vid4 only, GLM outputs and log files there"
CMH_0097,"EA imaging files, but no log files or GLM/rating outputs"
CMH_0100,"EA imaging files, but no log files or GLM/rating outputs"
MRC_0043,"No resources folder, EA imaging but no GLM/ratings outputs"
MRP_0076,"EA imaging files, log files, but no GLM/ratings output"
MRP_0079,"EA imaging files, log files, but no GLM/ratings output"
MRP_0081,"EA imaging files, log files, but no GLM/ratings output"
MRP_0083,"EA imaging files, log files, but no GLM/ratings output"
MRP_0089,Error log but no processed files in ea folder (duplicate 'correction' log files)
MRP_0103,No Data or resources
ZHP_0060,"No behavioural/clinical data in spreadsheet, but imaging outputs and rating files there – blacklisted for fieldmap"
ZHP_0067,"rating file for only some vids, GLM outputs and log files there – blacklisted for fieldmap"
ZHP_0072,"EA imaging, but no log files, ratings, or GLM outputs – blacklisted for fieldmap"
ZHP_0081,"No behavioural/clinical data in spreadsheet, but fMRI outputs and rating files there"
```

**Comment by josephdviviano** [comment]
+ CMH_0096: logs in xnat
+ CMH_0097: no logs in xnat
+ CMH_0100: no logs in xnat
+ MRC_0043: no logs in xnat
+ MRP_0076: 2 sets of logs (which one is correct?)
+ MRP_0079: logs in xnat
+ MRP_0081: one too many logs in xnat (removed junk log)
+ MRP_0083: one too many logs in xnat (removed junk log)
+ MRP_0089: too many logs on file system?
+ MRP_0103: no data anywhere (likely dropped out)
+ ZHP_0060: should be fine...
+ ZHP_0072: incomplete task, no behavioural data in xnat
+ ZHP_0081: should be fine...

**Comment by loliver4** [comment]
Thanks so much Joe!

**Comment by josephdviviano** [comment]
@loliver4 no problem, still working on it, above is notes to myself

**Comment by josephdviviano** [comment]
# filesystem check + action
+ CMH_0096: funny dates in pipelines folder, deleted all outputs so they can be regenerated
+ CMH_0097: uploaded logs from `/archive/data/SPINS/data/bkup/behav`
+ CMH_0100: uploaded logs from `/archive/data/SPINS/data/bkup/behav`
+ MRC_0043: data is missing (new name MRC_0043, old name MRC_0042). 
 note that we have data for MRC_0043 (old name) here, but this is NOT the correct data. emailed Adriana to get a copy of the behavioural files : `bkup/spred/archive/SPN03/arc001/SPN01_MRC_0043_01_01/RESOURCES/BEHAV` (a backup)
+ MRP_0076: deleted logs starting with 99 -- were collected in 2014 though the subject was scanned in 2016. must have been accidental junk.
+ MRP_0081: removed junk log and backup folder (as this confuses the ea pipeline)
+ MRP_0089:  IDno_correction files are exact copies of the original logs with different file names, deleted the originals from xnat and the filesystem
+ MRP_0103: likely has not completed the scans yet
+ ZHP_0060: take this up with steve / navona
+ ZHP_0072: deleted everything on filesystem .. shouldn't regenerate (subject must have been named the wrong thing in xnat originally)
+ ZHP_0081: take this up with steve / navona

**Comment by josephdviviano** [comment]
@loliver4 I've resolved all of these except for `MRC_0043`, because we actually never received the data from MRC. I've emailed them.

**Comment by loliver4** [comment]
Amazing. Thanks!

**Comment by josephdviviano** [comment]
@loliver4 OK -- Adrianna got us the final data back, so I've uploaded. Over the next few days, the remaining data should become available in the pipelines folder. Feel free to reopen this issue if it does not.

**Comment by navonacalarco** [comment]
ZHP_0060 and ZHP_0081 should have EA files (according to REDCap, both participants completed EA without issues), so if we don't have them, we can contact ZHH.

**Comment by navonacalarco** [comment]
Ah, I see, they're missing clinical data.

ZHP_0060 is named ZHH_0060 in REDCap. It's the last participant to be ZHH vs. ZHP. Not sure what the label should be; will check what scanner their data is actually from, and correct.

ZHP_0081 is very recent; likely that we got scan before clinical data entered.

**Comment by josephdviviano** [comment]
```
,Rating Files,
./SPN01_CMH_0024_01       ,4,log files all there - completed task
./SPN01_CMH_0094_01       ,7,missing rating file for vid 10 (did complete)
./SPN01_CMH_0096_01       ,1,may not be regenerated yet (was in previous list)
./SPN01_CMH_0129_01       ,0,"came back for another scan for EA - log files there for that, but maybe not pulling from right folder"
./SPN01_MRC_0050_01       ,7,missing rating file for vid 10 and one glm pdf - looks like all runs completed – no tech notes
./SPN01_MRC_0069_01       ,5,missing some rating files and two glm pdf - looks like all runs completed – no tech notes
./SPN01_MRC_0075_01       ,0,no glm or ratings output - looks like all runs completed – no tech notes
./SPN01_MRP_0079_01       ,0,may not be regenerated yet (was in previous list)
./SPN01_MRP_0083_01       ,0,may not be regenerated yet (was in previous list)
./SPN01_MRP_0096_01       ,4,"Error - logs labeled as 0098, and one is blank"
./SPN01_MRP_0098_01       ,4,missing some rating files and two glm pdf – looks like all runs completed – no tech notes
./SPN01_ZHP_0067_01       ,2,log files all there and glm pdfs - looks like all runs completed - no tech notes
./SPN01_ZHP_0068_01       ,6,log files all there and glm pdfs - looks like all runs completed - no tech notes
```

**Comment by josephdviviano** [comment]
@loliver4 , looks like for these subjects, the other MRI outputs are already there. I'm going to guess that this is what is causing the problem. I'm going to delete and regenerate all of these subjects. Can you let me know in a few days if this resolves the issue?

Thanks

**Comment by loliver4** [comment]
Sure thing. Thanks!

**Comment by josephdviviano** [comment]
@loliver4 emailled about `MRP_0096`, you're right that the raw log data looks bad for this subject.

**Comment by josephdviviano** [comment]
@loliver4 I found a bug in the script that generates the logs ... some of these missing data should regenerate in full now (tested with the camh data) -- should only be 24 hours until they appear.

**Comment by loliver4** [comment]
Nice! Thanks!

**Comment by loliver4** [comment]
The only stragglers: MRP_0096 (had the wrong log files uploaded originally by MRC) and MRC_0075 (empty folder in fmri/ea - looks like it might have the wrong log files too 0067).

**Comment by josephdviviano** [comment]
+ had to wrangle the freesurfer checklist to work for `MRP_0096` -- should be a few days before fmri data is pre-processed.
+ ditto for `MRP_0075`

FYI @loliver4 -- helpful to copy the message contained in the `error.log` file, e.g., `/archive/data-2.0/SPINS/pipelines/fmri/ea/SPN01_MRP_0075_01/error.log` says: 

```
expected anatomical aparc+aseg.nii.gz not found in /archive/data/SPINS/pipelines/hcp/SPN01_MRP_0075_01/T1w                                                                              
cajal.camhres.ca                                                                
```

**Comment by loliver4** [comment]
Thanks! Will do in the future.
