### ISSUE TITLE
Recombine Spiral Data

### ISSUE THREAD

**Issue by eziraldo** [TIGRLab/admin#1211]
@josephdviviano 
Location:

/scratch/eziraldo/STOPPD_cleaning/2017_STOPPD_SpiralINOUT_cleaned/

**Comment by josephdviviano** [comment]
I have code that combines spiral data here `spiral-clean`

**Comment by josephdviviano** [comment]
@eziraldo completed this project, prototype here: https://github.com/TIGRLab/sprl-cleaning
