### ISSUE TITLE
Dashboard: scroll is wierd

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1212]
It seems there's something up with the Dashboard's scroll. In short, it doesn't allow to scroll to the bottom of text. 

So, for example, looking at Dawson's PASAD README on the 'Overview' tab, I can get this far:
![1](https://user-images.githubusercontent.com/13733654/26846792-d18f9a9e-4ac8-11e7-9966-cca334208ddf.png)

:(

**Comment by DESm1th** [comment]
May be a browser specific issue or something. I just tried on firefox on Golgi and was able to scroll to the bottom

**Comment by navonacalarco** [comment]
I'm using Firefox, so I guess it's specific to my system. I have lots of issues with the Dashboard like this, but not on other websites. 

What can I do other than using a different browser? I updated Firefox recently a couple of weeks ago...

**Comment by DESm1th** [comment]
Hmm! What version are you using? mine is 53.0.2 Also, are you using any plugins or anything? Is this on your Mac?

**Comment by djoverton** [comment]
Just tested on Firefox 53.0 and Chrome 58.0.3029.110 and it works fine for me -- could be a Mac issue.

**Comment by navonacalarco** [comment]
Thanks guys! I also have Firefox 53.0.2 (64-bit). I'm using MRSDTI, not my Mac. 

It's a bit silly because I can use Chrome, but would love to have an idea of what's going on, so I don't have to default to the use-a-different-browser solution. :)

**Comment by navonacalarco** [comment]
Alright I have resigned myself to the multi-browser solution. Thanks all.
