### ISSUE TITLE
PASAD and RTMSAD scans missing tech notes

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1213]
Cannot find PDF tech notes in XNAT for some of the PASAD or RTMSAD scans.

Edited: As Tom pointed out, some newer scans do have tech notes.

**Comment by tomwright01** [comment]
Technotes seem to exist for newer subjects (e.g PASAD_CMH_26A037_01_01)
Since updating resources, the links in the qc report sheet may be incorrect.

**Comment by josephdviviano** [comment]
Is this resolved?

**Comment by djoverton** [comment]
Just verified and it seems newer scans do have the tech notes, so assuming this has been resolved -- closing.
