### ISSUE TITLE
SPN01_ZHP_0093_01 T1 and FLAIR

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1218]
@josephdviviano When you have a moment, could you help me understand a few things I haven't seen before, in SPN01_ZHP_0093_01:

First, we have some kind of in-the-brain artefact in the bottom slices of the T1. I'm not sure how to deal with that; it's confined just to the first two slices:

![1](https://user-images.githubusercontent.com/13733654/26950252-0503dafe-4c6b-11e7-80bb-e87f8aec12ec.png)

Second, the FLAIR looks like something I've never seen before (outside of artistic sepia imaginings of raindrops):

![2](https://user-images.githubusercontent.com/13733654/26950336-447ebad2-4c6b-11e7-8273-1654a2d98d6b.png)

Any thoughts you have would be appreciated. Thanks!

**Comment by josephdviviano** [comment]
Hi @navonacalarco :

for the T1, that looks like wraparound from the patient's shoulders. Since it isn't in the brain, we're OK.

The FLAIR looks like atrocious head motion artefact (likely due it being at the end of a very long scanning session). Blacklist for sure.

**Comment by navonacalarco** [comment]
Hey @josephdviviano thanks! It looks like you ultimately QC'd this subject, but the Dashboard doesn't show the FLAIR to be blacklisted. Was this an oversight, or possibly a Dashboard problem?

**Comment by josephdviviano** [comment]
yes you're right i neglected to blacklist the flair, though it shouldn't matter because we don't actually use the flair in any of our pipelines

**Comment by navonacalarco** [comment]
Blacklisted just in case we ever change things to include FLAIR in our pipelines; feel free to reverse if desired.
