### ISSUE TITLE
SPINS Participants Missing Rating Files

### ISSUE THREAD

**Issue by loliver4** [TIGRLab/admin#1221]
I found some more SPINS participants that only some (or none) of the rating files have been generated for. Haven't been able to decipher why...
[SPINS_Missing_EA_Data_2017-06-12.xlsx](https://github.com/TIGRLab/admin/files/1069587/SPINS_Missing_EA_Data_2017-06-12.xlsx)

**Comment by josephdviviano** [comment]
Thanks!! Linking this over to the old issue #1210

**Comment by loliver4** [comment]
Oops, sorry. Didn't know you could do that!

**Comment by josephdviviano** [comment]
@loliver4 closing as I believe we are good on this?

**Comment by loliver4** [comment]
Yep, all good. Thanks!
