### ISSUE TITLE
dashboard asking for QC check of 4 sessions that don't exist

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1222]
QC check required for:SPN01_MRP_0071_01
QC check required for:SPN01_MRP_0073_01
QC check required for:SPN01_MRP_0074_01
QC check required for:SPN01_MRP_0075_01

Likely misnnamed entries in the database (these subjects are MR**C** not MR**P**.

Can these be removed manually?

**Comment by tomwright01** [comment]
These are being flagged by the old `qc-todo.py` therefore nothing to do with the database. 
For some reason there is an empty `data/nii/SPN01_MRP_0071_01` which is triggering the warning. There is also a resources dir for this subject. Can you check the contents, as the files in `RESOURCES/SPN01_MRC_0071_01_01` do not match those in `RESOURCES/SPN01_MRP_0071_01_01`.

**Comment by josephdviviano** [comment]
Sure thing -- I'm guessing this was due to the renaming of subjects.

**Comment by josephdviviano** [comment]
Thanks @tomwright01 , cleared em out.
