### ISSUE TITLE
ASDD 2.9688 x 2.9688 x 2.9000 voxel resolution

### ISSUE THREAD

**Issue by liulj2** [TIGRLab/admin#1231]
79/107 ASDD directories have 2.9688 x 2.9688 x 2.9000 resolution scans (*29iso38FOV_eddy_correct.nii.gz) in addition to 2 x 2 x 2 (*20iso_eddy_correct.nii.gz)

ASDD_CMH_EF007_02
ASDD_CMH_EF014_02
ASDD_CMH_EF017_01
ASDD_CMH_EF017_02
ASDD_CMH_EF018_01
ASDD_CMH_EF018_02
ASDD_CMH_EF019_02
ASDD_CMH_EF020_02
ASDD_CMH_EF021_01
ASDD_CMH_EF021_02
ASDD_CMH_EF022_01
ASDD_CMH_EF022_02
ASDD_CMH_EF023_01
ASDD_CMH_EF023_02
ASDD_CMH_EF024_01
ASDD_CMH_EF024_02
ASDD_CMH_EF025_01
ASDD_CMH_EF025_02
ASDD_CMH_EF026_01
ASDD_CMH_EF026_02
ASDD_CMH_EF027_01
ASDD_CMH_EF027_02
ASDD_CMH_EF028_01
ASDD_CMH_EF028_02
ASDD_CMH_EF029_01
ASDD_CMH_EF030_01
ASDD_CMH_EF030_02
ASDD_CMH_EF032_01
ASDD_CMH_EF032_02
ASDD_CMH_EF034_01
ASDD_CMH_EF035_01
ASDD_CMH_EF035_02
ASDD_CMH_EF036_01
ASDD_CMH_EF036_02
ASDD_CMH_EF037_01
ASDD_CMH_EF037_02
ASDD_CMH_EF038_01
ASDD_CMH_EF038_02
ASDD_CMH_EF039_01
ASDD_CMH_EF040_01
ASDD_CMH_EF040_02
ASDD_CMH_EF041_01
ASDD_CMH_EF041_02
ASDD_CMH_EF042_01
ASDD_CMH_EF042_02
ASDD_CMH_EF043_01
ASDD_CMH_EF043_02
ASDD_CMH_EF044_01
ASDD_CMH_EF044_02
ASDD_CMH_EF045_01
ASDD_CMH_EF045_02
ASDD_CMH_EF047_01
ASDD_CMH_EF047_02
ASDD_CMH_EF048_01
ASDD_CMH_EF048_02
ASDD_CMH_EF049_01
ASDD_CMH_EF049_02
ASDD_CMH_EF050_01
ASDD_CMH_EF050_02
ASDD_CMH_HEF009_01
ASDD_CMH_HEF010_01
ASDD_CMH_HEF011_01
ASDD_CMH_HEF012_01
ASDD_CMH_HEF013_01
ASDD_CMH_HEF014_01
ASDD_CMH_HEF015_01
ASDD_CMH_HEF016_01
ASDD_CMH_HEF016_02
ASDD_CMH_HEF017_01
ASDD_CMH_HEF017_02
ASDD_CMH_HEF018_01
ASDD_CMH_HEF019_01
ASDD_CMH_HEF019_02
ASDD_CMH_HEF020_01
ASDD_CMH_HEF021_01
ASDD_CMH_HEF021_02
ASDD_CMH_HEF022_01
ASDD_CMH_HEF023_01
ASDD_CMH_HEF024_01

**Comment by josephdviviano** [comment]
Thanks -- turns out this is a known issue (see http://srv-dashboard.camhres.ca/study/8).

One can use either the 20 or 29 files for their analysis, not both.
