### ISSUE TITLE
error while running qc-fmri

### ISSUE THREAD

**Issue by daytonmiranda** [TIGRLab/admin#1234]
I'm running: 
while read SID; do /projects/saba/Useful_Scripts/qcmon/bin/qc-fmri "/projects/dmiranda/saba/PNC/rawFMRI/"$SID".nii.gz" '/projects/dmiranda/saba/PNC/meanfd1'; done < /projects/dmiranda/saba/PNC/missedsubjects 

and get this error:
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

any ideas why ?

**Comment by josephdviviano** [comment]
What is your python environment?

**Comment by daytonmiranda** [comment]
dawn help me resolve the problem, thanks
