### ISSUE TITLE
Dashboard: 'blacklist' not working

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1236]
Hey guys,

Clicking on the Dashboard's 'blacklist' link (pencil icon) for a given session does not open up a text dialogue box. Instead, it opens the interactive viewer for that session.

I have tried to update the blacklist by using our metadata file/blacklist.csv file, but while the blacklist.csv file reflects my changes, the Dashboard does not appear to update.

As an example, I am trying to blacklist SPN01_CMH_0137_01_01_EMP_11_AxEPI-EATask2 as it is truncated.

Does anyone have time to take a look? Thanks.

**Comment by DESm1th** [comment]
We've discovered this is not actually bug, just an unintuitive gui problem :) The 'add to blacklist' button is visible on the interactive viewer page on the top right corner.
