### ISSUE TITLE
weekend shutdown / start up checklist

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1237]
+ disable all jobs in `/etc/cron.d` on `tigrsrv`.

**Comment by DESm1th** [comment]
Some users are still having trouble, they are:

- saba
- colin
- ewiljer
- navona

**Comment by josephdviviano** [comment]
Great. Email sent.

See `/projects/admin/ipa_changeover` for our current list. The script `update_uid_home.sh` was already run on all machines, but the list of users is incomplete. When we receive the complete list, I'll run `update_uid_shared.sh`.

**Comment by josephdviviano** [comment]
I'm also making clevis the owner of everything in `/archive` now (tmux on bulbasaur).

**Comment by josephdviviano** [comment]
It looks like an `sss_cache -E; service sssd restart` is helpful for getting the machines to respect their new UIDs
