### ISSUE TITLE
SPINS imaging report for Miklos / imaging group

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1239]
@josephdviviano @edickie 

On today's SPINS call, Miklos from ZHH asked for a bit more information about the CAMH QC procedures. We said we'd send him a report with some mention of (1) preprocessing steps, (2) what pipelines we run (structural, DTI, fMRI), and a brief look at how ZHP is vs. ZHH, and also MRP vs MRC, and some kind of overall comparison.

He seemed a bit concerned (?) about data quality, and I think is hoping for re-assurance (?).

The next call is on August 24th - it would be great if we could send this out in advance of that.

**Comment by josephdviviano** [comment]
fmri
----

data is qc'ed using this script: https://github.com/josephdviviano/qcmon/blob/master/bin/qc-fmri

All data is not preprocessed aside from basic motion correction.

references:

- [1] Friedman et al. Reducing interscanner variability of activation in a multicenter fMRI study: controlling for signal-to-fluctuation-noise-ratio (SFNR) differences. Neuroimage. 2006 Nov 1;33(2):471-81.
- [2] Power et al. Spurious but systematic correlations in functional connectivity MRI networks arise from subject motion. Neuroimage. 2012 Feb 1; 59(3): 2142-2154.
 
from the dashboard it appears we get lower SFNR from the fmri data at ZHP than ZHH, but this isn't true for MRC and MRP.

dti
---

all data is qc'ed using this script: https://github.com/josephdviviano/qcmon/blob/master/bin/qc-dti which runs https://github.com/josephdviviano/qcmon/blob/master/assets/qascripts_version2/qa_dti_v2.sh

All data is not preprocessed save motion correction + eddy current correction.

All data from the new scanners looks better than the old scanners.

- [1] Roalf et al. The impact of quality assurance assessment on diffusion tensor imaging outcomes in a large-scale population-based cohort. Neuroimage. 2016.

**Comment by navonacalarco** [comment]
@edickie I know you're super busy at the moment, but is there any way you could jot down something about structural/ FreeSurfer stuff, or point me towards something you might already have?

**Comment by edickie** [comment]
There is this...
https://github.com/TIGRLab/documentation/wiki/freesurfer

But actually, considering we don't have anyone checking those files on a
regular systematic basis, the documentation you already wrote up about the
QC dashboard (i.e. the RA QC guidelines) is the best to send him.

**Comment by navonacalarco** [comment]
Thanks Erin!
________________________________

**Comment by josephdviviano** [comment]
@navonacalarco what's the deal with this ticket?

**Comment by navonacalarco** [comment]
Emailed Miklos for more info about exactly what he wanted, no response.

**Comment by navonacalarco** [comment]
Closing. No response. Can revisit later if want more info. Methods sections of recent papers should suffice.

**Comment by josephdviviano** [comment]
:D
