### ISSUE TITLE
Fix kandel as a nis slave (perhaps set up others)

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#124]
NIS on `kandel` is misbehaving and not syncing properly with `kimsrv`. We may also want to set up other machines as slaves.

**Comment by pipitone** [comment]
Also, `kimsrv` still thinks it is the nis master, not `mrsdti`. :D

**Comment by pipitone** [comment]
I've checked each machine and made sure they all point to `mrsdti` as the NIS master. I've also stopped `ypserv` on all machines but `mrsdti`. 

I'm not going to set up any other slaves for the moment. With the nscd set up, I think we're good to go for now, and I'm feeling reluctant about adding more complexity to the system what with #139 and all. 

Reopen if you disagree.

**Comment by josephdviviano** [comment]
Thanks for doing this Jon. This particular problem really made my brain hurt.
