### ISSUE TITLE
MRS uploads for STOPPD

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1247]
Looks like we need to upload **all** of the STOPPD MRS data for the external sites (gulp).

I'll talk to Rutwick about this and report back here.

Key files are here `/archive/data/STOPPD/data/external-zips`

**Comment by josephdviviano** [comment]
NKI data here: `/archive/data/STOPPD/data/external-zips/NKI/spec_NKI.zip`

**Comment by rutwikb** [comment]
hey, are there any updates on pmc data?

**Comment by josephdviviano** [comment]
@rutwikb no, PMC and MAS have not sent us data yet.

I'll ping them

**Comment by josephdviviano** [comment]
@rutwikb MAS data here `/archive/data/STOPPD/data/external-zips/MAS/stoppd_mrs_MAS.zip`

Still waiting on PMC.

**Comment by josephdviviano** [comment]
For PMC, we need to extract the data from the `.dcm` files to `.rda` files using the York U MRI scanner. Will be done Tues morning. Data is here:

`/projects/jviviano/downloads/MRS_PMC`

**Comment by josephdviviano** [comment]
Data successfully extracted from `PMC` is here: `/archive/data/STOPPD/data/external-zips/PMC/spec_PMC.zip`

We're waiting on Joelle to determine if some of the very old scans from this site can be recovered.

**Comment by josephdviviano** [comment]
We have everything -- the files just need to be uploaded into the RESOURCES foldrers in XNAT.

**Comment by josephdviviano** [comment]
See related issue.
