### ISSUE TITLE
sssd not starting

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1250]
__Symptoms:__
Users cant logon
`getent passwd <username>` returns nothing
`sssd -i -d4 fails`

__Cause:__
apparmor has been enabled
`sudo service apparmor status` shows services in __enforce__ mode.

__Solution:__

Set apparmor to complain mode
Globally:
`sudo aa-complain /etc/apparmor.d/*`

sssd only:
`sudo aa-complain /etc/apparmor.d/usr.sbin.sssd`

**Comment by josephdviviano** [comment]
Nice. Does this continue to be an issue?

**Comment by tomwright01** [comment]
Life seems quiet. Closing.
