### ISSUE TITLE
Dashboard reports missing checklist entry for nonexistent session

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1261]
The dashboard lists 'STOPPD02_MAS_210030_02' under the needed QC for STOPPD, but this session does not exist. I think it's showing up because an empty nifti folder still exists for it.

To do list:

- [ ] Remove folder and ensure it doesn't regenerate
- [ ] Figure  out how the dashboard compiles its to-do list and possibly place subjects with no data under a different, more descriptive header

**Comment by tomwright01** [comment]
Dashboard currently has two different (but similiar) todo lists.
* QC to-do
* Outstanding QC

QC to-do is using `subprocess.Popen` to run `dm-qc-todo.py` The route is `dashboard/views.py` todo() which uses get_todo() function in `dashboard/utils.py`.

Outstanding QC is a database query. See study() in `dashboard/views.py` . This view uses sqlalchemy to query all the sessions for a study then renders `templates/study.html`

**Comment by DESm1th** [comment]
This will be fixed by later removing dm-qc-todo's report from the dashboard. Closing for now.
