### ISSUE TITLE
xnat nginx

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1263]
@tomwright01 / @DESm1th is `nginx` on `srv-web` off for a reason?

**Comment by josephdviviano** [comment]
sorry nevermind ... certbot was acting buggy.

**Comment by DESm1th** [comment]
I wasnt aware it was. Xnat seemed to be ok a few hours ago. Is it only needed for external access? If so it may have been off for a while without anyone noticing.

**Comment by josephdviviano** [comment]
nginx was always running -- at the time i was messing around, we had 2 simultaneous instances of nginx, which was strange (one of them was off, bamboozling me)

we use it because it's generally safer to have a proper webserver act as a proxy between the www and tomcat. PS i wrote a little something about the set up here http://www.viviano.ca/writing/xnat-nginx/
