### ISSUE TITLE
clevis not being resolved on all machines

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1267]
likely an NIS issue. will hopefully be resolved with the move to ubuntu 16.04 as sssd gets updated when we do that.

**Comment by tomwright01** [comment]
Looking at the queue errors this was only a problem with __com02__ (see 
`srv-sge:/var/spool/gridengine/qmaster/messages`)

Updated sssd on __COM02__, seems to be resolved.

**Comment by josephdviviano** [comment]
Nice!
