### ISSUE TITLE
ubuntu 16.04 upgrade schedule

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1268]
- [x] 172.26.216.65 com03.camhres.ca com03                                            
- [x] 172.26.216.64 com02.camhres.ca com02                                            
- [x] 172.26.216.71 nissl.camhres.ca nissl                                            
- [x] 172.26.216.74 kandel.camhres.ca kandel                                          
- [x] 172.26.216.77 cajal.camhres.ca cajal                                            
- [x] 172.26.216.83 bulbasaur.camhres.ca bulbasaur                                    
- [x] 172.26.216.84 mrsdti.camhres.ca mrsdti                                          
- [x] 172.26.216.85 higgs.camhres.ca higgs                                            
- [x] 172.26.216.87 crick.camhres.ca crick                                            
- [x] 172.26.216.88 franklin.camhres.ca franklin                                      
- [x] 172.26.216.91 mendel.camhres.ca mendel                                                                                              
- [x] 172.26.216.99 srv-sge.camhres.ca srv-sge                                        
- [x] 172.26.216.66 srv-dashboard.camhres.ca srv-dashboard         
- [x] 172.26.216.97 srv-docker.camhres.ca srv-docker                                                  
- [x] 172.26.216.98 kimsrv.camhres.ca kimsrv                                          
- [x] 172.26.216.101 tigrsrv.camhres.ca tigrsrv                                       
- [x] 172.26.216.79 tesla.camhres.ca tesla # needs full reinstall       
- [x] 172.26.216.70 lovelace.camhres.ca lovelace    **Tues 8th**                           
- [x] 172.26.216.72 darwin.camhres.ca darwin          **Tues 8th**                           
- [x] 172.26.216.73 strangelove.camhres.ca strangelove     **Wed 9th**                           
- [x] 172.26.216.75 davinci.camhres.ca davinci                    **Wed 9th**                   
- [x] 172.26.216.76 purkinje.camhres.ca purkinje                 **Thurs 10th**                     
- [x] 172.26.216.78 mansfield.camhres.ca mansfield            **Thurs 10th**                         
- [x] 172.26.216.80 golgi.camhres.ca golgi                            **Fri 11th**                
- [x] 172.26.216.81 milner.camhres.ca milner                        **Fri 11th**                  
- [x] 172.26.216.82 talairach.camhres.ca talairach                **Mon 14th**                    
- [x] 172.26.216.86 hebb.camhres.ca hebb                           **Mon 14th**                  
- [x] 172.26.216.89 penfield.camhres.ca penfield                  **Tues 15th**                    
- [x] 172.26.216.90 laplace.camhres.ca laplace                     **Tues 15th**                   
                                     
                                       

postpone

- [x] 192.168.216.2 srv-web.camhres.ca srv-web 
- [ ] 172.26.216.62 hopper.camhres.ca hopper       # dev01.tigr.camhres.ca hopper     
- [x] 172.26.216.63 com01.camhres.ca com01

**Comment by DESm1th** [comment]
Hey Joe, at least two of the computers that have been upgraded instead of given a fresh install (crick and franklin) are having issues with QT library incompatibility. The most obvious symptom of this is they can't open wb_view. In general an upgrade is messier than a fresh install so it might be worth it to invest the bit of extra time in a fresh install for the machines to avoid these sorts of issues.

**Comment by josephdviviano** [comment]
Some of the upgrades machines don't play well with `wb_view`. The cause is qt4. The fix is:

```
apt-get remove libqt4*
apt-get autoremove # removes a whole bunch of old software we used to use, might cause a lockup
reboot
apt-get install sssd
```

One might need to re-run ipa-enroll on these machines as well.

**Comment by josephdviviano** [comment]
I've added a feature to ansible that fixes #1171 in the quarantine role.

**Comment by tomwright01** [comment]
srv-dashboard and srv-postgres were both built as 16.04 so can be removed from the list.
I'm not sure about srv-docker. It doesn't seem to be online. I think it's probably just a virtual image that doesn't do anything. It should probably be deleted.

**Comment by josephdviviano** [comment]
@tomwright01 thanks for the help!

**Comment by tomwright01** [comment]
Another fun fact.
The virtualenv for ansible was built using python version 2.7.6. After upgrade the system version is 2.7.12

In the old version (2.7.6), the module datetime was an external file, for 2.7.12 it's compiled into the main binary.

Older virtualenvs relied on finding the module in the system libraries, after the upgrade they fail because it doesn't exist.

Solution: 
```
$ source env/bin/activate
$ cp /usr/bin/python2.7 $(which python2.7)
```

**Comment by josephdviviano** [comment]
Thanks for that fix tom!

**Comment by josephdviviano** [comment]
It is all done except for hopper who will stay 14.04 for the foreseeable future.
