### ISSUE TITLE
tigrsrv not a submit host

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1270]
Symptoms: datman jobs failing with `Unable to run job: denied: host "tigrsrv.camhres.ca" is no submit host.`

Cause: Is this an oversight from the srv-sge upgrade?

Solution: Add tigrsrv to list of submit hosts using qmon.

Just checking this isn't deliberate before I make the change.

**Comment by tomwright01** [comment]
Spooky, 
Checkout who assigned people to this issue!!!

I'm being possessed by @josephdviviano

**Comment by DESm1th** [comment]
Hey Tom, Joe took down the queue last week until the upgrades are done. I think this error might be related to the queue master being down

**Comment by tomwright01** [comment]
Added tigrsrv as submit host (using qmon)
