### ISSUE TITLE
error when viewing QC to-do

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1271]
When I look at the QC to-do list, I get this error:

![screenshot from 2017-08-10 18-13-01](https://user-images.githubusercontent.com/13733654/29194454-ad0ec0d4-7df7-11e7-918a-0f77fbbb9fbd.png)

Any ideas?

**Comment by DESm1th** [comment]
Hey Navona, this was noticed a week or so ago. We have to remove the part of the dashboard code that checks the checklist.csv instead of the database, but none of us have had time to get to it yet. Will take a look at the beginning of next week if no one beats me to it.

**Comment by navonacalarco** [comment]
Sorry I missed that issue - perhaps I was away. In the meantime, how are we QCing?

**Comment by DESm1th** [comment]
The issue should only affect one study (PNSC if memory serves). So for that one study I think it will just have to be put on hold for a few days. Also, the queue is temporarily down while we upgrade all our operating systems so new scans will not have QC pages generated at the moment anyway

**Comment by DESm1th** [comment]
Oh, or I guess we could do it the old school way using dm-qc-todo and manually entering things into checklist.csv

**Comment by navonacalarco** [comment]
Thanks Dawn! 

I got this error when trying to QC for SPINS.

Also, I think I remember that we can no longer manually update checklist.csv!

Please let me know if I'm mistaken. Otherwise, I'll wait until next week for the fix.

**Comment by DESm1th** [comment]
You should be able to manually update it. Ahh oh dear. Ok, I'll look at
that first thing Monday then, since we're all away for brainhack tomorrow.

**Comment by tomwright01** [comment]
Lots of apologies. This is my bad :-(
See issue #1274
