### ISSUE TITLE
check SPN01_CMH_0140

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1272]
@josephdviviano When you have a moment, could you look at SPN01_CMH_0140? The person has quite large ventricles and depleted matter. Not sure if it warrants special attention - can I have your opinion?

**Comment by navonacalarco** [comment]
Whoops, sorry, nevermind - I see you flagged this earlier and sent along to Nancy, who stated it's infrequent but not abnormal.

New question: this participant requested images - not for a doctor, but as a souvenir. Is there any reason not to provide as we usually would?

**Comment by josephdviviano** [comment]
I would maybe try to dodge sending it to them as they might get worried for no reason. People are sensitive about their brains.
