### ISSUE TITLE
HD dead in crick

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1273]
Crick seems to have suffered a HD crash. Checked with DELL support, it's out of warranty.
Not sure how to continue, credit card to canada computes?

**Comment by josephdviviano** [comment]
I think buying a cheap HD from canada computers is the way to go. Dielle's p card should do the trick.

**Comment by tomwright01** [comment]
Ok, seems to have magically resolved over the weekend. Crick is updated and seems fine.
