### ISSUE TITLE
Linked scans in dashboard

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1275]
Close one, open one.
I'm not going to move on this until friday so if anyone comes up with other thoughts let me know.

Scans that are linked across studies, that do not generate QC metrics are not entered into the dashboard.
e.g. (PNC_CMH_0027_01). See #1197 

# Background
## Filesystem

`dm_link_shared_ids.py` queries _RedCAP_ to find records for a given study that have multiple ids (participant is part of multiple studies). It updates _XNAT_ and uses:
`dm-link-project-scans.py` to create softlinks in the filesystem of the __target__ study.

`dm-link-project-scans.py` can also be called manually avoiding both _XNAT_ and _REDCap_.

__The process of linking scans avoids triggering either `dm2_xnat_extract.py` and, if no qc metrics are generated for a scan `parse_qc.py`.

## Database
Currently scans can be added to the dashboard either by `dashboard/parse_qc.py` or by `datman/bin/dm2_xnat_extract.py`
Currently sessions to scans is a 1:many relationship. Each scan can only have one parent session.

# Issues: 
Softlinks on the file system are renamed to reflect the target study. There is no mechanism for this in the dashboard system.

# solutions
Modify the session - scan relationship to become many:many
Modify `dm-link-project-scans.py` to make the new entries into the dashboard. 
Modify `parse_qc.py` to not create sessions.

# Questions:
1. Should scan metrics apply to the unique scan, or to the unique session:scan?
2. Do we want to rename scans according to the study they are part of? 
_This could be achieved by adding a scan name column to the session:scan linking table. Another option is to make it obvious the scan is linked, i.e changing the link colour, font, adding <linked> to the name._

**Comment by DESm1th** [comment]
Closing this because Tom's changes were pushed and the links are now being made, but some kinks still need to be worked out. See #1300 for more info.
