### ISSUE TITLE
PNS_CMH_0069 on MR server but not XNAT (6 days)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1277]
Hey guys,

Would any of the updates/changes to things recently have affected pulling scans from the MR server?

I specifically am looking for PNS_CMH_0069, scanned on August 9th (~ a week ago). Their scan is not in XNAT, but is on the MR server (20170809_Ex07357_PNSC1MR_PNOV022.zip ).                                           

And, should I transfer this scan manually or wait overnight? The participant is returning tomorrow and wants an image.

Thanks!

**Comment by DESm1th** [comment]
Hey Navona,

I just ran dm2-sftp for PNSC and it pulled the data to our filesystem without any issues. I think the disruption caused by our recent upgrade has just prevented this study's pipeline from being run for a very long time. All the outputs should be there tomorrow morning

**Comment by navonacalarco** [comment]
Thanks Dawn! 

Will leave open until we verify it arrives!

**Comment by navonacalarco** [comment]
Thanks again, Dawn.
