### ISSUE TITLE
PASS_CMH_PASSCZ048_02_01 aka 2014_0708_WK024.zip being uploaded every night

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1284]
Looks like the MRI unit did something funny downstairs which is causing our code to re-upload this subject every night, causing pollution in the prearchive on xnat.

2014_0708_WK024.zip contains two distinct 'experiments', which xnat does not like: `Ex02601` and `Ex02599`.

I'm going to ask them to split these into two different zip files. One of them will be mapped to `PASS_CMH_PASSCZ048_02_02`.

**Comment by josephdviviano** [comment]
Email sent to Nancy.

**Comment by josephdviviano** [comment]
done..
you should get two zip files tonight - using the current naming conventions:
20140708_Ex02599_PASS1MR_PAWK024
20140708_Ex02601_PASS1MR_PAWK024

**Comment by tomwright01** [comment]
See also #1256

**Comment by josephdviviano** [comment]
Fixed.
