### ISSUE TITLE
SPN01_MRP_0115 FOV off for IM/OBS scans?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1285]
@jdv It looks to me like the occipital lobe is cut off in the IM/OBS scans for  SPN01_MRP_0115_01_01.

Would you mind taking a look and comment on if this is a problem?

If so, I can contact MRC. Thanks!

**Comment by josephdviviano** [comment]
@navonacalarco come over and I show u?

**Comment by josephdviviano** [comment]
![bad](https://user-images.githubusercontent.com/4142570/29731139-561272ba-89b1-11e7-8f2b-76221e9c9966.png)

**Comment by navonacalarco** [comment]
Thanks @josephdviviano. Emailed MPRC, cc'd you.
