### ISSUE TITLE
Dashboard: REDCap RA notes not found when 'repeat' is '02' (?)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1287]
It looks like the Dashboard might not be finding REDCap 'scan completed' RA notes for scans for which 'repeat' = '02'.

For example, participant `COGBDY_CMH_27B071_01` is in the Dashboard, but the RA notes are not ("No Redcap record available"). The RA notes do exist in the 'scan completed' REDCap database, though, with the participant ID `COGBDY_CMH_27B071_01_02`.

In this particular case, there are no RA notes for that participant's first session (repeat = '01).

Is it possible to get both repeat '01' and '02' RA notes to display? I know we figured out a solution for the TechNotes.

**Comment by tomwright01** [comment]
Not sure why this comment didn't show. It was the case that new comments would over-write old comments. I've just changed that behaviour so they get appended.

Behaviour will update when I push these code changes.
