### ISSUE TITLE
Dashboard: can't access COGDBO

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1288]
When clicking the 'COGBDO' link from the main page, I get this error:

![screenshot_2017-08-25_18-24-40](https://user-images.githubusercontent.com/13733654/29734878-cba59f28-89c2-11e7-80d4-99e173ae11e1.png)

All other studies work. It doesn't seem to be a permissions thing, from what I can tell.

**Comment by tomwright01** [comment]
Works for me today.

**Comment by DESm1th** [comment]
And for me also. Not sure what happened, but it seems to have resolved itself. If it happens again reopen the issue and I'll take a close look.

**Comment by DESm1th** [comment]
As an update: Tom noticed a participant in COGBDO with a subject id that started with 'COGBD'. This was causing the 'unexpected error' message when clicked on and may have been responsible for this issue also. It's been purged and renamed now, and I'll look into implementing better checks for correctness for the study part of subject IDs.
