### ISSUE TITLE
Dashboard: REDCap 'scan completed' RA notes not linked between shared participants

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1289]
One last issue, sorry guys.

The 'scan completed' RA notes are not being linked in the Dashboard for participants shared between studies. 

For example, SPN01_CMH_0143_01_01 is also DTI_CMH_S161_02_01. Both have a QC page in the Dashboard, but only the former have a link the the RA notes.

Can the RA notes be linked to both?

**Comment by DESm1th** [comment]
Hey Navona, I think this might be a symptom of the issue Tom is working on: https://github.com/TIGRLab/admin/issues/1275

**Comment by navonacalarco** [comment]
Aha! Thanks Dawn.
