### ISSUE TITLE
Queue jobs failing due to 'No space left on device'

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1290]
After checking the space usage on srv-sge we still have about 30% of our space left. Checking the inode usage (df -i) shows we're all out of inodes on our root partition though!

Solution: Find the directories with the greatest number of tiny files (as per [this post](https://unix.stackexchange.com/questions/117093/find-where-inodes-are-being-used )) and clear out the unimportant ones to free up some inodes.

**Comment by DESm1th** [comment]
The culprit seems to have been the SSS cache, which was using about 250,000 inodes (more than half!) all on its own. Using sss_cache -E did not remove any of these files. As per this [page's instructions](https://www.rootusers.com/how-to-clear-the-sssd-cache-in-linux/) I just stopped the daemon and removed them manually.

I'm not sure why these files got so out of hand. I'll close this once I've investigated a bit more.

**Comment by DESm1th** [comment]
The files in the cache were actually empty credential cache files being created by kerberos. For whatever reason the ipa-client-install didn't correctly set up the krb5.conf file so it was trying to find credential and realm information over DNS (which doesnt seem to be set up), failing and generating these broken caches every few minutes (about 4 ever 2 minutes). 

Copying version of krb5.conf from a working computer to srv-sge seems to have stopped these files from being generated.

**Comment by josephdviviano** [comment]
Great work dawn  -- this was a very sneaky little bug.
