### ISSUE TITLE
Freesurfer module tcl execution failed

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1299]
This error popped up in the logs for today for SPINS:

> freesurfer/6.0.0(6):ERROR:102: Tcl command execution failed: set user             $::env(USER)

Not sure if it's the result of some recent change (any insight @josephdviviano ?) or if we're having more module issues (possibly only on one machine in the queue?)

**Comment by josephdviviano** [comment]
at least one of the machines on the queue couldn't load the quarantine

perhaps we have conflicting modules in the run script for SPINS

I'm looking into it now

**Comment by josephdviviano** [comment]
`$USER` is not set on non-login shells (which is true for cronjobs), so I'm going to try this approach in the modules:

```
# sets SUBJECTS_DIR if this is a login shell                                    
if { [info exists $::env(USER)] } {                                             
    set     user          $::env(USER)                                          
    setenv  SUBJECTS_DIR  /projects/${user}/data/freesurfer                     
}                                                                               
```

**Comment by DESm1th** [comment]
That looks good! I don't know if it would be possible, but another option might be to report that the directory isnt set when the module is loaded and refuse to load it. Can environment variables be listed as dependencies for module files?

**Comment by josephdviviano** [comment]
@DESm1th this is a good idea .. I'll look into that.

**Comment by josephdviviano** [comment]
@DESm1th doesn't look like it is possible from what I can see.

Let's just leave it as is. `recon-all` complains explicitly about `SUBJECTS_DIR` if it isn't set, so it shouldn't be too hard for the scientists to figure out why it isn't working.
