### ISSUE TITLE
wifi acting weird

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#130]
The wifi connection keeps dropping. It doesn't seem to be the wifi itself, since I'm always able to reconnect, but the connection with my laptop keeps dropping and I have to reconnect. This doesn't happen with other wifi connections so I don't think it's due to my laptop settings.

**Comment by josephdviviano** [comment]
I just reset it, let me know if you keep having trouble.

**Comment by mlevesque82** [comment]
It's happening again, it seems to be an afternoon problem.

**Comment by mlevesque82** [comment]
Same thing today. Judging from previous days, it should be fine in an hour or two.

**Comment by josephdviviano** [comment]
Can you log into camh 'transforminglives'?

**Comment by josephdviviano** [comment]
Is this still a problem?

**Comment by mlevesque82** [comment]
Yes, I think I will get an adapter to be able to connect to the internet the old fashioned way, with wires.

**Comment by josephdviviano** [comment]
I'm going to move the router your room.

**Comment by josephdviviano** [comment]
That worked.
