### ISSUE TITLE
New dashboard linking issues

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1300]
The changes made as a result of https://github.com/TIGRLab/admin/issues/1275 seem to have introduced some new bugs.

Firstly, whenever a linked spiral exists for a session all of the series get labeled as 'linked'. This is most notable in PACTMD. See PACTMD_CMH_0100066_01 or most other pactmd sessions for an example

Secondly, some series are now causing dm2-xnat-extract to raise IntegrityError exceptions because the scanid is consistently (somehow) being set to 'null' for some series when the dashboard attempts to add them to the database. See the PACTMD and SPINS logs for 2017-09-07 for examples.

**Comment by DESm1th** [comment]
Oh, and thirdly for some sessions the dashboard is now raising 'flask_sqlalchemy.BaseQuery' is not mapped errors. To see an example of this one run dm2-xnat-extract on PACTMD_CMH_0950029_01_01

**Comment by DESm1th** [comment]
Problem 1 is now fixed. 

Also, now that the dm2-xnat-extract isn't crashing from the previous IntegrityError, it's crashing from a new one on insertion of new series. From the run logs it seems to be affecting multiple studies, havent worked out why yet.

**Comment by DESm1th** [comment]
Ok the new integrity error has fixed by commit 4e8e95803028c10874cf4baf693a0150aa1729ed and some changes to the database schema. 

I've also noticed that parse_qc is raising integrity errors, likely because it's also referencing the now removed 'session' attribute for scans. So all that seems to be left to close this issue is to update dashboard/parse_qc.py and to stop dm2-xnat-extract from labeling all spirals as 'extra scans' and deleting them from the dashboard every night.

**Comment by DESm1th** [comment]
The nightly deletion of spiral scans (and, it turns out, all linked scans) has been fixed by this patch: https://github.com/TIGRLab/datman/commit/5d265bf8fd004626e4c2fdfb61971561c9313e2e

The parse_qc integrity errors have been fixed by this one: https://github.com/TIGRLab/dashboard/commit/942b2f0a556cd2770432011e2e8514e55d6f81d3 and this one: https://github.com/TIGRLab/dashboard/commit/e443cea6d459b39d9c5e7a27818b90c1a4f305b2

However, now that the integrity errors have stopped things further downstream are failing. New (hopefully last) issues:

- [ ] Scan blacklist updating is failing for certain scans. At a glance, the failing scans all seem to be links.
- [ ] dm-link-project-scans is failing to link scans now
- [ ] dm_link_shared_ids is raising 'no matching experiments' errors for linked sessions.

**Comment by DESm1th** [comment]
Ok! Looks like this is finally cleaned up. The last issue: 'dm_link_shared_ids' wasnt due to linking but due to a few scans that were either too new to have their data uploaded yet (and that only had redcap records as a result), a participant that aborted their scan due to claustrophobia, and that one weird spins participant that is both a shared ID and has its own redcap record. So, no bug fix needed (although it may be worth finding a way to filter out IDs like the last two later on... )

**Comment by navonacalarco** [comment]
If it would help with the "one weird spins participant that is both a shared ID and has its own redcap record", could we simply delete the REDCap scan completed record?

**Comment by navonacalarco** [comment]
After discussion, decided _not_ to delete. Thanks Dawn!
