### ISSUE TITLE
pactmd scans for shima

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1303]
PACt-MD participant (0110048)

**Comment by navonacalarco** [comment]
For sure. Is this a CD for a doctor, or a souvenir print out?

**Comment by navonacalarco** [comment]
@josephdviviano Is this a CD for a doctor, or a souvenir print out?

**Comment by josephdviviano** [comment]
CD sorry

**Comment by navonacalarco** [comment]
@josephdviviano last question: PACTMD_CMH_0110048_01 or PACTMD_CMH_0110048_02.

**Comment by josephdviviano** [comment]
both

**Comment by navonacalarco** [comment]
Alright. Done. On my desk for you or Shima, or I can see if a Slaight person can deliver to QS if it's pressing.
