### ISSUE TITLE
Assign new IP addresses to HAL

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#131]
`HAL` (the IBM Storwise array) needs to be configured with its new network addresses: 

| Hostname   | IP address   |
|----------------|-----------------|
| hal-admin1 | 172.25.9.80  |
| hal-admin2 | 172.25.9.81  |

**Comment by josephdviviano** [comment]
I'm on it, but will need to restart HAL, so I'm going to wait for the right moment.

**Comment by josephdviviano** [comment]
Done.
