### ISSUE TITLE
RTMSWM_CMH_WM080_01_01 & RTMSWM_CMH_WM080_02_01 CDs

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1313]
Samantha Barbosa needs 
RTMSWM_CMH_WM080_01_01 
and 
RTMSWM_CMH_WM080_02_01 
burned to a cd.

**Comment by josephdviviano** [comment]
Asking others to help as I will be out of town next week.

**Comment by navonacalarco** [comment]
@josephdviviano No problem, I can do this. Thanks.

**Comment by navonacalarco** [comment]
JDV did it.
