### ISSUE TITLE
DBDC Slicer FA analysis for Lee & Rachael

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1315]
Lee and Rachael need a bit of help with Slicer. They're stuck on step 2 in the PDF insructions in /projects/rlyon/DBDC_Tractography/Tractography_SOP_June_2016.pdf

There output from step 1 is in /projects/rlyon/DBDC_Tractography/Step2_Input/DTI_21

(Another question - average DTI_21, 22 and 23 now or later?)

Will look at later this week -if anyone has any immediate insight, please let me know!

**Comment by josephdviviano** [comment]
@navonacalarco are they stuck because of a computer error (like the software is crashing)? This could be because the modules for FSL and Slicer cannot be loaded at the same time.

**Comment by navonacalarco** [comment]
Good question! Will check.
