### ISSUE TITLE
im amy and i need remote access via remote.camh.ca

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1327]

**Comment by navonacalarco** [comment]
If the process remains unchanged from a few months ago:

She needs to fill out an IMG request and specially request access to the VPN (make sure to emphasis VPN). Cyrus Wang or one of that crew will contact her to send her a file to set up TFA on her phone,  which in combination will allow  her to sign in to a new folder called 'Applciations' on remove.camh.ca. 

Once she has that, she needs to contact David at Research IT to get access to MobaXTerm in her Applications folder, if she wants to open documentation outside of the terminal. The default is Putty, which will allow her to do anything she wants in the terminal, but not access external applications like PDFs.

However, this reminds me that we need to update the documentation here: https://github.com/TIGRLab/documentation/wiki/Remote-Access

**Comment by edickie** [comment]
Actually..there's a slightly better way.. if you can get to remote.camh.ca
(even the non-VPN version) you can open a terminal using jupyter.camhres.ca
..

**Comment by josephdviviano** [comment]
I've placed a request via IMG on behalf of AMY

**Comment by josephdviviano** [comment]
Amy got shrewsoft working on OSX.

I've copied all of the required files and her notes to `/projects/admin/software/shrewsoft`.
