### ISSUE TITLE
Newer mricron modules lack mricron

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1329]
A few people have gotten confused from the fact that the newer mricron modules dont include the mricron program. @edickie has suggested we add a symbolic link inside these modules to the most up to date mricron to help with this.

**Comment by DESm1th** [comment]
mricron/20170720 and mricron/20170221 each now have a symbolic link pointing to mricron/20150622's version of mricron. If this causes any problems (though it shouldnt), then maybe we'll have to talk about a different naming scheme for the later versions that drop mricron.

**Comment by josephdviviano** [comment]
@DESm1th @edickie shouldn't the link just point to `MRIcroGL`?

**Comment by DESm1th** [comment]
Hey Joe, newer modules have MRIcroGL, but not the mricron binary. Erin told me these are different?

**Comment by josephdviviano** [comment]
@DESm1th -- it just the newer version of software intended for the same purpose -- see here: https://github.com/neurolabusc/MRIcron

"""
MRIcron development has moved to MRIcroGL
NPM development has been moved to NiiStat
dcm2nii development has been moved to dcm2niix
"""

**Comment by DESm1th** [comment]
Erin says "GL does not have the same functionality as mricron, it does have the ability to view slices but it's kind of odd. They have very different interfaces for kind of different things."

We could definitely just use the old module if they need backward compatibility. But people were getting confused by loading the 'mricron' module and then getting 'mricron not found' when they tried to open the old one. So I think keeping the links, or naming the new modules slightly differently (MRIcroGL?) might help reduce confusion.

**Comment by josephdviviano** [comment]
Or they could learn that the software they're used to using is just old and was replaced with something else :). Whatever. Your solution is fine.
