### ISSUE TITLE
Disable shutdown + suspend for user accounts on all machines.

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#133]
Adding the following lines as `/etc/polkit-1/localauthority/50-local.d/restrict-login-powermgmt.pkla` works:

    [Disable lightdm PowerMgmt]
    Identity=unix-user:*
    Action=org.freedesktop.login1.reboot;org.freedesktop.login1.reboot-multiple-sessions org.freedesktop.login1.power-off;org.freedesktop.login1.power-off-multiple-sessions;org.freedesktop.login1.suspend;org.freedesktop.login1.suspend-multiple-sessions;org.freedesktop.login1.hibernate;org.freedesktop.login1.hibernate-multiple-sessions
    ResultAny=no
    ResultInactive=no
    ResultActive=no

**Comment by pipitone** [comment]
Can you provide a reference for this? 

There is also kiosk mode: 
http://docs.xfce.org/xfce/xfconf/start
http://docs.xfce.org/xfce/xfce4-session/advanced

**Comment by josephdviviano** [comment]
This is such a low priority I'm nuking the issue. I don't think this has ever caused a problem.
