### ISSUE TITLE
dm-qc-report should display both T2 and PD in html

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#1333]
So the old (Jan version of the html reports used to look for and run slicer on the _T2_ and _P2_ images then display both on the html...this also serves as a 
1) show that the PDT2 splitting step of the management pipeline ran correctly.
2) ensure that both PD and T2 signal is displayed for QC, This is important because the T2 (if collected) is most useful for checking for incidental findings.

This functionally appears to have been lost in recent rewrite of dm-qc-report.py. Now the _PDT2_ nifti is feed to slicer and only the first image is displayed (which could be the PD or the T2 scan..).

**Comment by josephdviviano** [comment]
@edickie shouldn't we be using the interactive viewer to review the PD/T2 scans anyhow?

**Comment by edickie** [comment]
The interactive viewer also only displays the first image..

**Comment by DESm1th** [comment]
Hey Erin,

As far as I know dm-qc-report hasn't been (meaningfully) modified since last year, so maybe something else went awry. Can you give an example of a subject that's having this problem to help with debugging?

**Comment by edickie** [comment]
And...the split images do not show up in any of the tables (because they are not in the expected tags??) so you can't get to them from the interactive viewer... So this same issue

**Comment by edickie** [comment]
Sorry, it's not a bug...it's a functionality that used to exist in the old html qc page generator (is Jan 2016) that was never incorporated into the new dashboard.

**Comment by DESm1th** [comment]
Ok. I'll look at it. Can you point me to a subject so I can have a current example to look at?

**Comment by DESm1th** [comment]
Ok. I think I've fixed this.

PD and T2 split images not showing up on QC pages has been fixed with https://github.com/TIGRLab/datman/pull/106

For the dashboard, Joe spoke to Sophia and found out there wasnt really any reason for us to visualize the PD images, so I've modified the scans page to just always show the split T2 with https://github.com/TIGRLab/dashboard/pull/3
