### ISSUE TITLE
plis halp make PNC data clean

### ISSUE THREAD

**Issue by sstojanovski** [TIGRLab/admin#1337]
The dtifit outputs in /external/PNC/data/dti/ are a bit of a mess. They include the unpreprocessed data of the new PNC participants as well as preprocessed data from the old PNC that includes holes due to problems with BET.  I cleaned everything up and was hoping to move it to one centralized place. Commands to do so ...:

1. rm the bad old scans from external : 
while read i; do rm  /external/PNC/data/dti/${i} ; done < /projects/sstojanovski/dti_preproc/originalpptwithholes_NOTsaved.txt

3. replace them with good preprocessed data: 
while read i; do mv /projects/sstojanovski/dti_preproc/preproc/${i}  /external/PNC/data/dti/ ; done <  /projects/sstojanovski/dti_preproc/originalpptwithholes_saved.txt

3. move the preprocessed contents of the new PNC into the existing external folders : 
while read i; do mv /projects/sstojanovski/dti_preproc/PNC_v02_dti_niis/${i}/*  /external/PNC/data/dti/${i}/ ; done <  /projects/sstojanovski/dti_preproc/originalpptwithholes_saved.txt

**Comment by josephdviviano** [comment]
@sstojanovski I completed the first two steps, but the last one fails because the subjects listed in `/projects/sstojanovski/dti_preproc/originalpptwithholes_saved.txt` are not found in `/projects/sstojanovski/dti_preproc/PNC_v02_dti_niis`.

**Comment by sstojanovski** [comment]
Srry tht I m dum

**Comment by josephdviviano** [comment]
ITS KEWL WHAT ARE THE RIGHT PPLZ

**Comment by sstojanovski** [comment]
Thr b a list in /projects/sstojanovski/dti_preproc/PNC_v02_dti_niis called like newpncppt_SAVED.txt that is th g00d & n;ce preprocessed new PNC

**Comment by josephdviviano** [comment]
K running now!

**Comment by josephdviviano** [comment]
@sstojanovski -- is this resolved?

**Comment by josephdviviano** [comment]
@sstojanovski reopen this if it's still an issue.
