### ISSUE TITLE
redirect http://imaging-genetics.camh.ca/cerebellum to http://imaging-genetics.camh.ca/projects/subcortical-atlases/

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#134]
There is a broken link in Matt's abstract :D

http://www.sciencedirect.com/science/article/pii/S1053811914001840

**Comment by pipitone** [comment]
https://help.github.com/articles/redirects-on-github-pages/

**Comment by pipitone** [comment]
Also, /Hippocampus from Julie's paper.

**Comment by pipitone** [comment]
Fixed in TIGRLab/tigrlab.github.io@fb37195ac95361e77f69fa565c1bccaaab15762e ... TIGRLab/tigrlab.github.io@1efcc1ba10efca6aadf3866b1da08de2e662f708
