### ISSUE TITLE
please take a look at SPN01_MRP_0118

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1343]
@edickie @josephdviviano @DESm1th 

Hey guys,

Can you take a look at SPN01_MRP_0118, and confirm that what we see here is merely a dermoid cyst?

![screenshot from 2017-10-16 13-03-05](https://user-images.githubusercontent.com/13733654/31625301-958b4fa8-b273-11e7-83a3-7ad14ad612b1.png)

The RA notes don't say anything about this, and there's no Tech Notes.

**Comment by edickie** [comment]
I don't know if any or us are qualified to determine that...has the site noticed it??

**Comment by navonacalarco** [comment]
Not as far as I can tell. I haven't asked directly, but the RA notes don't say anything about this (and there's no Tech Notes).

I guess email AV?

**Comment by navonacalarco** [comment]
Contacted site; they were aware and caring for participant.
