### ISSUE TITLE
figure out why not getting notifications for Scan Completed ... 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1352]

**Comment by navonacalarco** [comment]
Alright, it seems there's a bug with REDCap switching secondary and tertiary email addresses. So, our emails to tigrlab@camh.ca (my secondary address) are being directed to scwg@camh.ca (my tertiary address), and vice versa.

Temporarily turned off email notifications until this is fixed.

@DESm1th please let me know if you'd like me to turn your notifications back on. I wasn't sure if you have a secondary and tertiary account, and thought better safe than sorry.

**Comment by DESm1th** [comment]
As far as I know I only have the one account. I think I'd prefer the notifications if you can turn it back on without it negatively affecting you

**Comment by navonacalarco** [comment]
Done. Thanks!
