### ISSUE TITLE
look into missing data on REDCap surveys (namely Scan Completed)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1353]
@DESm1th  noticed that we have missing data on recent Scan Completed:

SURVEY # |   | SURVEY DATETIME | DATE SCAN | TIME SCAN| RA ID
-- | -- | -- | -- | -- | --
396 |   | 2017-10-24 12:18:19 | 2017-10-24 | 10:30 | 27
397 |   |   |   |   |  
398 |   |   |   |   |  
399 |   |   |   |   |  
400 |   |   |   |   |  
401 |   | 2017-10-26 16:21:42 | 2017-10-26 | 12:30 | 14
402 |   | 2017-10-30 08:54:07 | 2017-10-27 | 13:36 | 9999
403 |   |   |   |   |  
404 |   |   |   |   |  
405 |   |   |   |   |  
406 |   |   |   |   |  
407 |   |   |   |   |  
408 |   | 2017-10-31 15:03:53 | 2017-10-31 | 13:30 | 7
409 |   | 2017-10-31 16:30:18 | 2017-10-31 | 12:30 | 33
410 |   | 2017-10-31 16:39:24 | 2017-10-31 | 10:30 | 33
411 |   | 2017-11-02 13:42:37 | 2017-11-02 | 09:00 | 27
412 |   | 2017-11-02 15:16:45 | 2017-11-02 | 13:00 | 14
413 |   | 2017-11-03 15:43:59 | 2017-11-03 | 13:09 | 9999
414 |   | 2017-11-03 17:21:48 | 2017-11-03 | 02:30 | 9999
415 |   | 2017-11-06 12:08:42 | 2017-11-06 | 10:30 | 7

As far as I can tell, these missing values represent real scans, and the RAs filled out the form properly - simply, the data wasn't saved when the form was submitted.

First, checking Community site to see if issue reports.

**Comment by navonacalarco** [comment]
Alright, figured this one out, and it's a doozie.

Because of the bug mentioned in #1352, the notifications sending to my secondary email (tigrlab@camh.ca) were redirecting to my tertiary email (redcap_camh@camh.ca).

And, the admin who monitors the redcap_camh.ca account was opening the notifications, accessing the survey, and for some unknown reason, overwriting the data... will be discussing with her.

Luckily, the real data is all captured in logging, so I'll transcribe back in for the several surveys it affects.

**Comment by DESm1th** [comment]
Wow, good catch!

**Comment by navonacalarco** [comment]
@DESm1th alright, I think all the data is back in these forms. So, everything should look good tomorrow (with the exception of that real missing data from VR). Please let me know if the logs say otherwise!
