### ISSUE TITLE
Freesurfer-6 for PACTMD data

### ISSUE THREAD

**Issue by NedaRR** [TIGRLab/admin#1355]
Hi @edickie @DESm1th 

Just following on this issue, and a kindly reminder to fix the freesurfer 6 for PACT-MD data please. 

Thank you.
Neda

**Comment by DESm1th** [comment]
yup, working on it now. Have to move our slower pipelines back to the scc as per #1361

**Comment by josephdviviano** [comment]
@DESm1th sounds good -- so long as we do this by writing the existing `dm_proc_freesurfer.py` script so that it works on either the SCC or here, instead of maintaining two separate scripts.

**Comment by DESm1th** [comment]
Forgot to close this one, it's been running smoothly on the scc for about a week now.
