### ISSUE TITLE
missing boat in pic, please add

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1358]
![screenshot from 2017-11-10 14-21-08](https://user-images.githubusercontent.com/13733654/32674737-7440fd3a-c622-11e7-8f52-cae5f5bd54db.png)

**Comment by josephdviviano** [comment]
![profile-boats-635h-17-1-1024x453](https://user-images.githubusercontent.com/4142570/32680723-0383cd58-c63a-11e7-9a47-6b16340d1005.jpg)

**Comment by navonacalarco** [comment]
Thanks!
