### ISSUE TITLE
XFCE doesn't return from screenlock

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#136]
Filing this bug and solution for future reference. 

@dfelsky reports his desktop doesn't return from screen lock gracefully on `talairach`: the "session timed out" message appears, the screen blanks as if about to show the login dialog, but then stays blank with just the basic X windows "X" mouse prompt.  Switching to virtual console 1, and back to 7 (e.g. `shift-alt-1`, `shift-alt-7`) just repeats this process. 

I couldn't find a specific bug report for this behaviour (not sure how to search for it exactly), but [this post](http://xubuntu.org/news/screen-locking-in-xubuntu-14-04/) explains a bit more about how screen locking works in Xubuntu. 

The fix I've found is to `kill` the user's `light-locker` process, and then retry the console switch. I was immediately brought back to Dan's desktop session. Magic.

**Comment by josephdviviano** [comment]
I'm installing `xscreensaver` on his machine, and I'm going to make it his default. We'll see if that fixes the problem.

**Comment by josephdviviano** [comment]
I think our solution is to transition over to xscreensaver -- im going to ansibleify dis

https://bugs.launchpad.net/ubuntu/+source/xubuntu-default-settings/+bug/1303736/comments/193

**Comment by josephdviviano** [comment]
I did it :D
