### ISSUE TITLE
Moving analysis pipelines back to the scc?

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1361]
Neda noticed last week that PACTMD subjects werent being run through freesurfer. Erin and I looked into it and fixed the (small) problem, but 5 days later no outputs have been generated still. Colin also noticed NEUR jobs are not being run despite the fact that I set that up over a week ago.

Subjects run in single subject mode, and job submission works correctly. The culprit seems to be that jobs are getting backlogged in the queue. The fact that there are ~6000 freesurfer jobs pending confirms this. The queue is not completing the jobs fast enough, and every night the same subjects are being resubmitted leading to huge backlogs. I think we need to move some of the longer running code back to the scc for now.

**Comment by NedaRR** [comment]
These are the subjects we dont have Enigma DTI output. I checked if we actually have the data in archive, and except for very few, we have the rest.
PACTMD_CMH_3070014_01_01
PACTMD_CMH_0110009_01_01
PACTMD_CMH_3070014_01_02
PACTMD_CMH_3070007_01_01
PACTMD_CMH_0950026_02_01
PACTMD_CMH_0950013_02_01
PACTMD_CMH_3070006_02_01
PACTMD_CMH_3060018_02_01
PACTMD_CMH_0950030_01_01
PACTMD_CMH_0110005_02_01
PACTMD_CMH_0110004_02_01
PACTMD_CMH_3060008_02_01
PACTMD_CMH_3060001_02_01
PACTMD_CMH_3070002_02_01
PACTMD_CMH_3070019_02_01
PACTMD_CMH_3060021_02_01
PACTMD_CMH_0950020_02_01
PACTMD_CMH_3070014_02_01
PACTMD_CMH_0950027_02_01
PACTMD_CMH_0110006_02_01
PACTMD_CMH_3060029_01_01
PACTMD_CMH_0950019_02_01
PACTMD_CMH_3060017_02_01
PACTMD_CMH_0100010_02_01
PACTMD_CMH_3070015_02_01
PACTMD_CMH_0110008_02_01
PACTMD_CMH _3070007_02_01
PACTMD_CMH_3070023_01_01
PACTMD_CMH_3060029_02_01
PACTMD_CMH _3070016_02_01
PACTMD_CMH_3060028_02_01
PACTMD_CMH_0110015_02_01
PACTMD_CMH_0110014_02_01
PACTMD_CMH _3070027_01_01
PACTMD_CMH _3070028_01_01
PACTMD_CMH_0110017_02_01
PACTMD_CMH_3060034_02_01
PACTMD_CMH_3070022_02_01
PACTMD_CMH_3060030_02_01
PACTMD_CMH_0950040_01_01
PACTMD_CMH_3060047_01_01
PACTMD_CMH_3060040_02_01
PACTMD_CMH_3060043_02_01
PACTMD_CMH _3070002_03_01
PACTMD_CMH _3070040_01_01
PACTMD_CMH _3070033_01_01
PACTMD_CMH _3060046_02_01
PACTMD_CMH _3060025_02_01
PACTMD_CMH _3060051_02_01
PACTMD_CMH_0100017_02_01
PACTMD_CMH_0950035_02_01
PACTMD_CMH_0950036_02_01
PACTMD_CMH _3070031_01_01
PACTMD_CMH_0110013_02_01
PACTMD_CMH _3070028_02_01
PACTMD_CMH_3060055_01_01
PACTMD_CMH_0110020_02_01
PACTMD_CMH _3070027_02_01
PACTMD_CMH_0110021_02_01
PACTMD_CMH_0110004_03_01
PACTMD_CMH _3070016_03_01
PACTMD_CMH_0110018_02_01
PACTMD_CMH_3060047_02_01
PACTMD_CMH_0950040_02_01
PACTMD_CMH_3060049_02_01
PACTMD_CMH_3060039_02_01
PACTMD_CMH_3060042_02_01
PACTMD_CMH _3070043_01_01
PACTMD_CMH_0950037_02_01
PACTMD_CMH_0950042_02_01
PACTMD_CMH_0110026_02_01
PACTMD_CMH_0110025_02_01
PACTMD_CMH_0110028_02_01
PACTMD_CMH_0950044_02_01
PACTMD_CMH_0950039_02_01
PACTMD_CMH _3070035_02_01
PACTMD_CMH _3070033_02_01
PACTMD_CMH _3070045_01_01
PACTMD_CMH_3070031_02_01
PACTMD_CMH_3070037_02_01
PACTMD_CMH _0110036_01_01
PACTMD_CMH_3070041_02_01
PACTMD_CMH_3060063_02_01
PACTMD_CMH_3070012_03_01
PACTMD_CMH_3060032_02_01
PACTMD_CMH_3060062_02_01
PACTMD_CMH_0950045_02_01
PACTMD_CMH_3070014_03_01
PACTMD_CMH_0950049_02_01
PACTMD_CMH _3070043_02_01
PACTMD_CMH_3060060_02_01
PACTMD_CMH_3070045_02_01
PACTMD_CMH_3060065_02_01
PACTMD_CMH_3060066_02_01
PACTMD_CMH_0100031_02_01
PACTMD_CMH_0100033_02_01
PACTMD_CMH_3070048_01_01
PACTMD_CMH_0100029_02_01
PACTMD_CMH_0110036_02_01
PACTMD_CMH_0100024_02_01
PACTMD_CMH_0100032_02_01
PACTMD_CMH_3060070_02_01
PACTMD_CMH_0950046_02_01
PACTMD_CMH_3060061_02_01
PACTMD_CMH_0100027_02_01
PACTMD_CMH_3060072_02_01
PACTMD_CMH_3060078_02_01
PACTMD_CMH _3070049_01_01
PACTMD_CMH_3070048_02_01
PACTMD_CMH_3060081_02_01
PACTMD_CMH_3060075_02_01
PACTMD_CMH_3060083_02_01
PACTMD_CMH_3060079_02_01
PACTMD_CMH_0110043_02_01
PACTMD_CMH_3070046_02_01
PACTMD_CMH_0110044_02_01
PACTMD_CMH_0110038_02_01
PACTMD_CMH_0950056_02_01
PACTMD_CMH_0110033_02_01
PACTMD_CMH_3060077_02_01
PACTMD_CMH_0950048_02_01
PACTMD_CMH_0950053_02_01
PACTMD_CMH_0100038_02_01
PACTMD_CMH_0950061_02_01
PACTMD_CMH_3060084_02_01
PACTMD_CMH_0110039_02_01
PACTMD_CMH_0100046_02_01
PACTMD_CMH_0100031_03_01
PACTMD_CMH_0950058_02_01
PACTMD_CMH_3060088_02_01
PACTMD_CMH_0110030_02_01
PACTMD_CMH_0110052_02_01
PACTMD_CMH_0110046_02_01
PACTMD_CMH_3070059_02_01
PACTMD_CMH_3060086_02_01
PACTMD_CMH_0950063_02_01
PACTMD_CMH_3060089_02_01
PACTMD_CMH_0100044_02_01
PACTMD_CMH_0110048_02_01
PACTMD_CMH_3070049_02_01
PACTMD_CMH_0100051_02_01
PACTMD_CMH_3060096_02_01
PACTMD_CMH_3060097_02_01
PACTMD_CMH_3060094_02_01
PACTMD_CMH_3060030_03_01
PACTMD_CMH_3060103_02_01
PACTMD_CMH_0950066_02_01
PACTMD_CMH_3060107_02_01
PACTMD_CMH_3060099_02_01
PACTMD_CMH_0100053_02_01
PACTMD_CMH_3070060_02_01
PACMTD_CMH_0950068_02_01
PACMTD_CMH_0110058_02_01
PACTMD_CMH_3060104_02_01
PACTMD_CMH_0110053_02_01
PACTMD_CMH_0110054_02_01
PACTMD_CMH_0110062_02_01
PACTMD_CMH_3060114_01_01
PACTMD_CMH_0100056_02_01
PACTMD_CMH_0100055_02_01
PACTMD_CMH_3060111_01_01
PACTMD_CMH_3060106_02_01
PACTMD_CMH_0110060_02_01
PACTMD_CMH_3060119_01_01
PACTMD_CMH_0100059_02_01
PACTMD_CMH_0100068_01_01
PACTMD_CMH_0100054_02_01
PACTMD_CMH_3060082_02_01
PACTMD_CMH_0110069_01_01
PACTMD_CMH_3060109_01_01
PACTMD_CMH_0950075_01_01
PACTMD_CMH_0950067_02_01
PACTMD_CMH_0110066_01_01
PACTMD_CMH_0100066_01_01
PACTMD_CMH_3060108_02_01
PACTMD_CMH_0110063_02_01
PACTMD_CMH_3060113_02_01
PACTMD_CMH_3060117_02_01
PACTMD_CMH_0100065_02_01
PACTMD_CMH_0950073_01_01
PACTMD_CMH_3060129_01_01
PACTMD_CMH_3060105_02_01
PACTMD_CMH_3060125_01_01
PACTMD_CMH_3070074_01_01
PACTMD_CMH_3070038_01_01
PACTMD_CMH_3060118_02_01
PACTMD_CMH_3060119_02_01
PACTMD_CMH_3070081_01_01
PACTMD_CMH_0110067_02_01
PACTMD_CMH_0110068_02_01
PACTMD_CMH_3060126_01_01
PACTMD_CMH_0950078_01_01
PACTMD_CMH_3070053_02_01
PACTMD_CMH_0100068_02_01
PACTMD_CMH_3060114_02_01
PACTMD_CMH_0110071_01_01
PACTMD_CMH_0110024_03_01
PACTMD_CMH_0110061_02_01
PACTMD_CMH_3070085_01_01
PACTMD_CMH_3070067_02_01
PACTMD_CMH_3060008_03_01
PACTMD_CMH_0950074_01_01
PACTMD_CMH_3060120_01_01
PACTMD_CMH_0110076_01_01
PACTMD_CMH_0950070_01_01
PACTMD_CMH_3060128_01_01
PACTMD_CMH_H3060127_01_01
PACTMD_CMH_3060112_01_01
PACTMD_CMH_0110066_02_01
PACTMD_CMH_0100069_01_01
PACTMD_CMH_3070090_01_01
PACTMD_CMH_3060129_02_01
PACTMD_CMH_3070089_01_01
PACTMD_CMH_0950075_02_01
PACTMD_CMH_3060136_01_01
PACTMD_CMH_3060131_01_01
PACTMD_CMH_0110078_01_01
PACTMD_CMH_3070074_02_01
PACTMD_CMH_3070087_01_01
PACTMD_CMH_3060126_02_01
PACTMD_CMH_3070038_02_01
PACTMD_CMH_0110073_01_01
PACMTD_CMH_0110072_01_01
PACTMD_CMH_H0950080_01_01
PACTMD_CMH_3060138_01_01
PACTMD_CMH_3070085_02_01
PACTMD_CMH_3060109_02_01
PACTMD_CMH_0100063_01_01
PACTMD_CMH_3060134_01_01

**THESE ARE the 1st Sessions missing, which I need now:**
"PACTMD_CMH_3070014_01_01"
"PACTMD_CMH_0950030_01_01"
"PACTMD_CMH_3060029_01_01"
"PACTMD_CMH_3070023_01_01"
"PACTMD_CMH 3070027_01_01"
"PACTMD_CMH_0950040_01_01"
"PACTMD_CMH_3060047_01_01"
"PACTMD_CMH_3070040_01_01"
"PACTMD_CMH _3070031_01_01"
"PACTMD_CMH _3070043_01_01"
"PACTMD_CMH _3070045_01_01"
"PACTMD_CMH _0110036_01_01"
"PACTMD_CMH_3070048_01_01"
"PACTMD_CMH _3070049_01_01"
"PACTMD_CMH_3060114_01_01"
"PACTMD_CMH_3060111_01_01"
"PACTMD_CMH_0100068_01_01"
"PACTMD_CMH_0110069_01_01"
"PACTMD_CMH_0110066_01_01"
"PACTMD_CMH_3060113_02_01"
"PACTMD_CMH_3060129_01_01"
"PACTMD_CMH_3070038_01_01"
"PACTMD_CMH_3060126_01_01"
"PACTMD_CMH_0110071_01_01"
"PACTMD_CMH_3070085_01_01"
"PACTMD_CMH_0950074_01_01"
"PACTMD_CMH_0950070_01_01"
"PACTMD_CMH_0100069_01_01"
"PACTMD_CMH_3070089_01_01"
"PACTMD_CMH_0110078_01_01"
"PACTMD_CMH_0110073_01_01"
"PACTMD_CMH_3060138_01_01"
"PACTMD_CMH_3060134_01_01"
"PACTMD_CMH_0110009_01_01"
"PACTMD_CMH_3070007_01_01"
"PACTMD_CMH _3070028_01_01"
"PACTMD_CMH _3070033_01_01"
"PACTMD_CMH_3060055_01_01"
"PACTMD_CMH_3060119_01_01"
"PACTMD_CMH_3060109_01_01"
"PACTMD_CMH_0950075_01_01"
"PACTMD_CMH_0100066_01_01"
"PACTMD_CMH_0950073_01_01"
"PACTMD_CMH_3060125_01_01"
"PACTMD_CMH_3070074_01_01"
"PACTMD_CMH_3070081_01_01"
"PACTMD_CMH_0950078_01_01"
"PACTMD_CMH_3060120_01_01"
"PACTMD_CMH_0110076_01_01"
"PACTMD_CMH_3060112_01_01"
"PACTMD_CMH_H3060127_01_01"
"PACTMD_CMH_3060128_01_01"
"PACTMD_CMH_3070090_01_01”
"PACTMD_CMH_3060136_01_01”
"PACTMD_CMH_3060131_01_01"
"PACTMD_CMH_3070087_01_01"
"PACMTD_CMH_0110072_01_01"
"PACTMD_CMH_H0950080_01_01"
"PACTMD_CMH_0100063_01_01"

**Comment by NedaRR** [comment]
The enigma DTI output is missing for these subjects/sessions:

PACTMD_CMH_3070014_01_01
PACTMD_CMH_0110009_01_01
PACTMD_CMH_3070014_01_02
PACTMD_CMH_3070007_01_01
PACTMD_CMH_0950030_01_01
PACTMD_CMH_3060029_01_01
PACTMD_CMH_3070023_01_01
PACTMD_CMH_3060055_01_01
PACTMD_CMH_3070041_02_01
PACTMD_CMH_3070048_01_01
PACTMD_CMH_0110038_02_01
PACMTD_CMH_0950068_02_01
PACMTD_CMH_0110058_02_01
PACTMD_CMH_3060104_02_01
PACTMD_CMH_0110053_02_01
PACTMD_CMH_0110054_02_01
PACTMD_CMH_0110062_02_01
PACTMD_CMH_3060114_01_01
PACTMD_CMH_0100056_02_01
PACTMD_CMH_0100055_02_01
PACTMD_CMH_3060111_01_01
PACTMD_CMH_3060106_02_01
PACTMD_CMH_0110060_02_01
PACTMD_CMH_3060119_01_01
PACTMD_CMH_0100059_02_01
PACTMD_CMH_0100068_01_01
PACTMD_CMH_0100054_02_01
PACTMD_CMH_3060082_02_01
PACTMD_CMH_0110069_01_01
PACTMD_CMH_3060109_01_01
PACTMD_CMH_0950075_01_01
PACTMD_CMH_0950067_02_01
PACTMD_CMH_0110066_01_01
PACTMD_CMH_0100066_01_01
PACTMD_CMH_3060108_02_01
PACTMD_CMH_0110063_02_01
PACTMD_CMH_3060113_02_01
PACTMD_CMH_3060117_02_01
PACTMD_CMH_0100065_02_01
PACTMD_CMH_0950073_01_01
PACTMD_CMH_3060129_01_01
PACTMD_CMH_3060105_02_01
PACTMD_CMH_3060125_01_01
PACTMD_CMH_3070074_01_01
PACTMD_CMH_3070038_01_01
PACTMD_CMH_3060118_02_01
PACTMD_CMH_3060119_02_01
PACTMD_CMH_3070081_01_01
PACTMD_CMH_0110067_02_01
PACTMD_CMH_0110068_02_01
PACTMD_CMH_3060126_01_01
PACTMD_CMH_0950078_01_01
PACTMD_CMH_3070053_02_01
PACTMD_CMH_0100068_02_01
PACTMD_CMH_3060114_02_01
PACTMD_CMH_0110071_01_01
PACTMD_CMH_0110024_03_01
PACTMD_CMH_0110061_02_01
PACTMD_CMH_3070085_01_01
PACTMD_CMH_3070067_02_01
PACTMD_CMH_3060008_03_01
PACTMD_CMH_0950074_01_01
PACTMD_CMH_3060120_01_01
PACTMD_CMH_0110076_01_01
PACTMD_CMH_0950070_01_01
PACTMD_CMH_3060128_01_01
PACTMD_CMH_H3060127_01_01
PACTMD_CMH_3060112_01_01
PACTMD_CMH_0110066_02_01
PACTMD_CMH_0100069_01_01
PACTMD_CMH_3070090_01_01
PACTMD_CMH_3060129_02_01
PACTMD_CMH_3070089_01_01
PACTMD_CMH_0950075_02_01
PACTMD_CMH_3060136_01_01
PACTMD_CMH_3060131_01_01
PACTMD_CMH_0110078_01_01
PACTMD_CMH_3070074_02_01
PACTMD_CMH_3070087_01_01
PACTMD_CMH_3060126_02_01
PACTMD_CMH_3070038_02_01
PACTMD_CMH_0110073_01_01
PACMTD_CMH_0110072_01_01
PACTMD_CMH_H0950080_01_01
PACTMD_CMH_3060138_01_01
PACTMD_CMH_3070085_02_01
PACTMD_CMH_3060109_02_01
PACTMD_CMH_0100063_01_01
PACTMD_CMH_3060134_01_01

**Comment by DESm1th** [comment]
Hey Neda, almost all of those subjects should now have entries in the enigma DTI summary files. There are still about 7 or so who timed out during dtifit that I'm sorting out.

For my (and possibly others) future reference: the reason all those subjects got left out of the enigmaDTI-*-results.csv files is because the script that generates them is submitted with qbatch with the '--afterok' flag, so if any of the subjects time out or fail for any reason the summary script doesn't run. In this situation it can be fixed by running manually, or (even better) going through and fixing the subjects that are failing to run through enigmaDTI.

**Comment by navonacalarco** [comment]
Cool, thanks Dawn! I think I know what you mean when you say running manually, but what do you mean when you say run through enigmaDTI?

**Comment by DESm1th** [comment]
The very old copy of dm-proc-enigmaDTI that's on the scc runs the enigmaDTI pipeline on all subjects, submitting them as jobs to the queue, and then after the fact submits the concatresults.sh script in /archive/data/PACTMD/pipelines/enigmaDTI/bin. If any of subject jobs fail for the enigmaDTI part then the concatresults.sh doesnt run at the end. So by 'failing to run through' I mean, if a particular subject's job keeps failing for some reason (like timing out each time it's submitted).

**Comment by navonacalarco** [comment]
Aha! I understand now. Thanks, Dawn.

**Comment by NedaRR** [comment]
Thanks Dawn :)

**Comment by DESm1th** [comment]
Ok! We now have a datman/packages module on the scc that uses the copy of datman at /archive/code/datman, and it has its own conda environment that should be identical (or near enough) to the one used by packages.module. Only a small modification was needed to dm_proc_freesurfer to allow it to submit jobs on the SCC too.

Erin wants to verify that the SCC's freesurfer 6 outputs don't differ significantly from the ones generated on our queue, so for now we've turned off the freesurfer stage of our nightly pipelines (to prevent the backlog from growing) and we're re-running all of RTMSAD on the SCC. On Monday we'll check out the outputs and if it looks ok we'll move it over for all studies.

I'm also going to move dm_qc_report to the scc, since it has far more matlab licenses and currently 30,000 of the 42,000 jobs on our queue are qc_report jobs. Not sure how long that will take, but I'll update when it's running.

**Comment by josephdviviano** [comment]
@DESm1th  -- the `dm_qc_report.py` script could be modified to only submit a QC job if the outputs for a subject don't exist. Right now, that check is done by the submitted job, but it could be done before any job is submitted.

**Comment by DESm1th** [comment]
Whoops, forgot to update this. dm_proc_freesurfer.py is now successfully being run from the scc and as per Joe's suggestion I've modified dm_qc_report to only submit new subjects, and the queue backlog has disappeared. We might move more over the SCC in the future, but I'm closing this for now.

**Comment by josephdviviano** [comment]
@DESm1th THANK YOU!!
