### ISSUE TITLE
2 PACt-MD scans are mislabelled and should change:

### ISSUE THREAD

**Issue by NedaRR** [TIGRLab/admin#1364]
I received this email from Shima. Please change the name to the correct one. 
1. "We realized that the scan for 3070047 is mislabeled and should actually be: PACTMD_CMH_3070048_01".
2. "The scan for 3070026 was also mislabeled. It should actually be: PACTMD_CMH_3070023_01_01"
Thanks.

**Comment by NedaRR** [comment]
"The scan for 3070026 was also mislabeled.  It should actually be: PACTMD_CMH_3070023_01_01"

**Comment by DESm1th** [comment]
I've renamed those two subjects and deleted all their outputs. Beware that the old IDs _might_ still show up in some of the qc pages or aggregate results files. I'll check tomorrow once everything has had a chance to start regenerating with the correct ids

**Comment by NedaRR** [comment]
Thanks Dawn!
