### ISSUE TITLE
PASAD: does anyone know what's going on with RS scans?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1365]
Neda is considering analyzing PASAD data. We noticed that there's no RS data in the file system, but it seems to be contained in XNAT in the 'resources' folder, alongside the MRS. 

Does anyone know if there's a reason for this? If not, can we work on getting the RS data into our file system?

**Comment by navonacalarco** [comment]
Dawn informs us that the PASAD RS data is in archive/data/PASAD/data/RESOURCES/participant/MISC/.

New question, maybe for @edickie. Can we get the QC pages to find the RS data here, so it can be QC'd on the HTML pages?

**Comment by DESm1th** [comment]
Spoke to Erin, the sprl.nii needs to be linked, it was just left out of the run script when the study was set up. Will add that now.

**Comment by navonacalarco** [comment]
You guys are the best. Thanks so much.

**Comment by DESm1th** [comment]
Ok, this has been added. The links should show up tomorrow, but the older qc pages will need to be regenerated to get the spiral qc to be added to the page

**Comment by NedaRR** [comment]
Thank you all :)
