### ISSUE TITLE
please re-run the QC report page of RTMSAD for following subjects:

### ISSUE THREAD

**Issue by NedaRR** [TIGRLab/admin#1374]
RTMSAD_CMH_RAD018_02
RTMSAD_CMH_RAD019_01
RTMSAD_CMH_RAD016_02
RTMSAD_CMH_RAD019_02
RTMSAD_CMH_RAD012_01
RTMSAD_CMH_RAD021_01
RTMSAD_CMH_RHC008_01
RTMSAD_CMH_RHC009_01
RTMSAD_CMH_RAD012_02
RTMSAD_CMH_RHC010_01
RTMSAD_CMH_RAD025_01
RTMSAD_CMH_RHC011_01
RTMSAD_CMH_RHC012_01
RTMSAD_CMH_RAD025_02
RTMSAD_CMH_RAD029_01
RTMSAD_CMH_RAD031_01
RTMSAD_CMH_RAD029_02
RTMSAD_CMH_RAD031_02
RTMSAD_CMH_RHC015_01

**Comment by navonacalarco** [comment]
@DESm1th, Sorry to bother you - I'm getting what I think is a warning (?) when I try to rerun a batch of participants QC pages with the script we wrote: 

> ./rtmsad.txt does not match datman convention

(where `rtmsad.txt` is the text file with the list of participants to rerun).

Is this a real problem, or can this be ignored? The pages aren't regenerating properly.

![screenshot from 2017-11-22 14-24-24](https://user-images.githubusercontent.com/13733654/33146427-158d9914-cf92-11e7-974a-b4d106c4ea14.png)

**Comment by navonacalarco** [comment]
Whelp. Let's just say it was user error ... ;)

Thanks Dawn.
