### ISSUE TITLE
using yppasswd results in a segmentation fault

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#139]
Users are unable to change their password on multiple machines (i.e., has nothing to do with lightdm vs gdm).

**Comment by josephdviviano** [comment]
Restarting ypserv, ypbind, and msdti did not help.

**Comment by josephdviviano** [comment]
might be related to: https://bugs.launchpad.net/ubuntu/+source/nis/+bug/1204530 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721737

Also I notice that nissl is a ypserver, but it isn't configured correctly. This should be un-done (we should have only one NIS server: msdti).

**Comment by pipitone** [comment]
Looks like there is a known bug: 
https://bugs.launchpad.net/ubuntu/+source/nis/+bug/1204530

It was freshly fixed upstream in debian a month ago (in version 3.1.17-34), and still hasn't made it's way to Ubuntu Trusty yet: 
http://packages.ubuntu.com/trusty/nis

(ATM, 3.17-32ubuntu6 is the latest, and that's what we have.)

Fixes include: 
  1. pull in the upstream debian package,
  2. compile nis from patched source (patch is tiny)
  3. wait for change to arrive in trusty

If we wait, then a workaround for this is to help users change their passwords like so: 
 
```bash
ssh mrsdti
sudo passwd <username>
# let user update their password
cd /var/yp
sudo make     # refresh NIS database 
```

**Comment by josephdviviano** [comment]
im ok with manual

**Comment by pipitone** [comment]
By "im ok with manual" you mean that you're okay with users have to update their passwords by ssh'ing to `mrsdti` and then informing us so that we can run `make` in `/var/yp`?

**Comment by josephdviviano** [comment]
Well this is only going to happen in the rare case that a user's password expires, which I'm thinking won't be many more times before this update gets pushed to trusty (I'm guesing). What do you think?

**Comment by pipitone** [comment]
Actually, at the moment, it's impossible to use `yppasswd` for me also, and my password hasn't expired. The *only* way for people to change their passwords right now is with sysadmin intervention. Yay! 

From the bug report above, it looks like if we disable "shadow" passwords, this bug won't be triggered. So, I've added that to list of fixes above. :-)

**Comment by pipitone** [comment]
Okay, I'm marking this as `wontfix` for now but I'll update the wiki with the new instructions (in short: bother the admins to change your password, until the fix for NIS arrives): 
https://github.com/TIGRLab/documentation/wiki/Changing-Your-Password
