### ISSUE TITLE
/opt/quarantine/DTIPrep vs /opt/quarantine/slicer/DTIPrep

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#147]
@djrotenberg What is the difference between these two?   I think only `/opt/quarantine/DTIPrep` is necessary, but the DTIPrep protocol file referenced in the UKF tractography script includes references to commands in `/opt/quarantine/slicer/DTIPrep`.

**Comment by pipitone** [comment]
Just tried creating a new DTIPrep protocol file (via [this tutorial](http://www.slicer.org/slicerWiki/images/a/a6/DTIPrep_TutorialContestSummer2013.pdf)) and it looks like the paths get automatically set to the `/opt/quarantine/DTIPrep` location. So, the other paths are probably due to this sub-slicer module being loaded. 

 - Can we remove `slicer/DTIPrep` then?
 - Also, it looks like DTIPrep depends on FSL (for bet2) as well as Slicer. Perhaps add them into the DTI module as requirements?

**Comment by djrotenberg** [comment]
Hi Jon. Yes we can certainly remove the slicer/DTIPrep directory at this point. I agree that we should add bet2 and slicer to the DTI module file to make sure they are included.

**Comment by djrotenberg** [comment]
I've added FSL/5.0.7 and slicer/4.4.0 as 'prereq' entries in the DTIPrep module file.

**Comment by pipitone** [comment]
Great! Thanks.
