### ISSUE TITLE
Retiring user accounts

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#149]
How should we handle user accounts for people that are no longer part of the lab? 

- Do we just revoke authorized SSH keys, and/or disable the account, or remove the account entirely? 
- Who decides this, and when? 
- What do we do with the user's data?

**Comment by josephdviviano** [comment]
I suggest we retire user accounts with reckless abandon, unless the retired user (i.e., Tris) requires it for ongoing work and asks us for ongoing access. However, we move the data to a holding tank of sorts. The user is informed of this change quickly and access can be given to this data via FTP immediately. This will protect our resources / security, as any other solution might lead to 'forgotten' accounts that could be abused by 3rd parties. We can destroy the held data (or archive it) with a reasonable lag time, around 6 months - 1 year.

**Comment by pipitone** [comment]
I agree completely.  I suggest moving user data to /external.

**Comment by pipitone** [comment]
Done. Moved retired user data to `/projects/alumni` for now. About .5TB of stuff.
