### ISSUE TITLE
Commit recent quarantine activity

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#151]
Over the past month or two there have been a bunch of changes to the quarantine which haven't been checked into to the git repo (see below). What I suggest is committing changes for each module separately, with a log message like: 

```
Fixed queue in sge_batch in SGE-extras/1.0

sge_batch incorrectly had comp.q set as the default queue
(should be main.q).
```

Anyhow, here is the pile of outstanding changes to commit: 
```bash
$ cd /opt/quarantine
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore
	modified:   CIVET/1.1.10/module
	modified:   FSL/4.1.9/module
	modified:   FSL/4.1.9/src/README
	modified:   FSL/5.0.0/module
	modified:   FSL/5.0.0/src/README
	modified:   FSL/5.0.6/module
	modified:   FSL/5.0.6/src/README
	modified:   FSL/5.0.7/module
	modified:   FSL/5.0.7/src/README
	modified:   R-extras/3.1.1/src/README
	modified:   R/3.1.1/src/README
	modified:   SGE-extras/1.0/src/bin/sge_batch
	modified:   SPM/12/module
	modified:   SPM/8_r5236/module
	modified:   freesurfer/5.3.0/module
	deleted:    modules/matlab/R2012b
	deleted:    modules/matlab/R2013b
	modified:   modules/python/2.7.8-anaconda-2.1.0
	modified:   pyminc/0.4/module
	modified:   python-extras/2.7.8/src/README

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	AFNI/2014.09.22.1635EDT/src/
	AFNI/2014.12.16/
	ANTS/2.1.0/src/Linux_Ubuntu14.04.tar.bz2
	BRAINSTools/
	CIVET-extras/1.0/src/bin/extract_cls_volumes.py
	CIVET/1.1.10+Ubuntu_12.04/src/test/
	CIVET/1.1.12+Ubuntu_12.04/
	DTI_Preproc/
	DWIConvert/
	DiffusionKurtosisFit/
	ENIGMA-DTI/
	FIX/
	FSL/5.0.6/src/fsl_sub
	MICe-build-model/
	R-extras/3.1.1/src/.Rhistory
	UKFTractography/2015-02-05/src/ukf-build/
	UKFTractography/2015-02-05/src/ukftractography/
	bioimage/
	bpipe/
	dcm2nii/2014.10.11/src/dcm2/
	matlab/MATLAB_MANAGER/
	matlab/R2012b/src/MATLAB_Compiler418_glnxa64.zip.crdownload
	matlab/R2012b/src/activate.ini
	matlab/R2012b/src/bin/
	matlab/R2012b/src/etc/
	matlab/R2012b/src/help/
	matlab/R2012b/src/install
	matlab/R2012b/src/install_guide.pdf
	matlab/R2012b/src/installer_input.txt
	matlab/R2012b/src/java/
	matlab/R2012b/src/license.txt
	matlab/R2012b/src/readme.txt
	matlab/R2012b/src/sys/
	matlab/README
	matlab/compiler-runtime-715/
	matlab/licenses/
	matlab/matlab_concurrent_all/
	minc-tools/2014.01/
	modules/AFNI/2014.12.16
	modules/DTIPrep/
	modules/DTI_Preproc/
	modules/FIX/
	modules/bioimage/
	modules/bpipe/
	modules/matlab/R2012b_concurrent
	modules/matlab/R2013b_concurrent
	modules/matlab/R2014b_concurrent
	modules/matlab/compiler-runtime-715
	modules/python-extras/2.7.9
	modules/python/2.7.9-anaconda-2.1.0-150119
	modules/slicer/
	modules/trollolol/
	modules/whitematteranalysis/
	python-extras/2.7.9/
	python/2.7.8-anaconda-2.1.0/.gitignore
	python/2.7.9-anaconda-2.1.0-150119/
	slicer/
	whitematteranalysis/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by josephdviviano** [comment]
can I suggest we move to nightly commits? far less work...

**Comment by pipitone** [comment]
Definitely not. I don't want modules in-progress being committed, or half-committed because an auto-commit script doesn't include important files. I also want us to get in the habit of documenting what we do well enough that it's ready to be shared with, say, the cobralab. 

It's a minor pain in the ass to use version control but the benefits, I think, of us using it correctly for reproducibility/traceability/shareability/coordination amongst each other far outweight the pain.

**Comment by josephdviviano** [comment]
OK, I agree. I'm slowly working through the ones I did.

**Comment by josephdviviano** [comment]
How are we going to divvy this up? For most of these programs all I could thing of committing was 'added ${software name}'.

**Comment by pipitone** [comment]
> How are we going to divvy this up? For most of these programs all I could thing of committing was 'added ${software name}'.

That's what I've been doing. Just separating the various modules up into separate commits. I've been roughly sticking to the convention of: 

 - "Added modulename/version" when I add something
 - "Fixed modulename/version problem" when I fix something, and then putting two new lines and a longer description of the problem and the fix.

**Comment by pipitone** [comment]
Mostly done. It's still a bit of a mess in there, with packages that haven't been added (especially the MATLAB changes... I didn't want to wade into that). In any case, I've committed all of our recent modifications and the packages I was familiar with.
