### ISSUE TITLE
adobe reader blocks all forms of updates

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#152]
In a strange turn of events, it appears adobe reader is a big bag of fail.

I needed to run this to return to sanity:

    sudo dpkg --remove --force-remove-reinstreq adobereader-enu

Now, I think it might be best to abandon adobe reader, as they have abandoned linux.

    http://www.techrepublic.com/article/how-the-open-source-community-should-respond-to-adobe-pulling-linux-support/

Aside from 'evince', which is fine but basic, I'm going to experiment with https://pwmt.org/projects/zathura/

**Comment by josephdviviano** [comment]
nvm zathura is clearly for 1337 h4x0rz and okular is clunky, evince will have to do for now.

We should ansible the above command if anyone reports strangeness w.r.t. updates.

**Comment by pipitone** [comment]
> We should ansible the above command if anyone reports strangeness w.r.t. updates.

Let's just remove adobe reader. It's teh sux.

**Comment by josephdviviano** [comment]
![4252c36ac7f1a75047cde92e3d26a5c6afd1b2295b6669039254994a63e67ec0](https://cloud.githubusercontent.com/assets/4142570/6110461/d8077f6a-b04f-11e4-82ec-2494a924690b.jpg)
