### ISSUE TITLE
What do to do with SCC storage space

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#154]
We have dedicate space on the SCC (separate from our scratch space) that we can use for backups, moving data off/onsite, etc. I'm filing this issue so that we can discuss if/how/where to mount it and how to use it exactly (e.g. perhaps incorporating it into our backup schedule, etc..).

**Comment by josephdviviano** [comment]
Do we need extra backup space? I don't get the impression we do.

We could mirror external there?

**Comment by pipitone** [comment]
We're using this as cold storage for scratch overflow.
