### ISSUE TITLE
admin passwords should all be the HAL password

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#155]
because our old password is teh sux

                                                    _.--"""""--._
                                                 ,-'             `-.
                      _                        ,' --- -  ----   --- `.
                    ,'|`.                    ,'       ________________`.
                   O`.+,'O                  /        /____(_______)___\ \
          _......_   ,=.         __________;   _____  ____ _____  _____  :
        ,'   ,--.-`,,;,:,;;;;;;;///////////|   -----  ---- -----  -----  |
       ( SSt(  ==)=========================|      ,---.    ,---.    ,.   |
        `._  `--'-,``````"""""""\\\\\\\\\\\:     /`. ,'\  /_    \  /\/\  ;
           ``````                           \    :  Y  :  :-'-. :  : ): /
                                             `.  \  |  /  \=====/  \/\/'
                                               `. `-'-'    `---'    ;'
                                                 `-._           _,-'
                                                     `--.....--'   ,--.
                                                                  ().0()
                                                                   `'-'

**Comment by djrotenberg** [comment]
Completely agreed!

**Comment by josephdviviano** [comment]
I don't get this NIS thing at all. I've changed the localadmin passwd on mrsdti and sudo make in /var/yp and nothing changes anywhere.

**Comment by pipitone** [comment]
I hate to be that guy but Joe, you need to RTFM before you complain. In this case, `man nsswitch.conf` and the linux docs on NIS are good places to start. 

If you're still stuck, we can talk about it since I'm pretty sure about what's happening here.

> I don't get this NIS thing at all. I've changed the localadmin passwd on mrsdti and sudo make in /var/yp and nothing changes anywhere.

**Comment by josephdviviano** [comment]
Sorry, I didn't mean to complain. More a cry for help :). I'm looking into it now.

**Comment by josephdviviano** [comment]
OK, all the passwords have been changed. I've added the ansible command into a file called pass.yml, under the workstation tasks. It is accompanied by a .gitignore so we aren't adding them to the repo.

**Comment by pipitone** [comment]
> a file called pass.yml, under the workstation tasks. It is accompanied by a .gitignore so we aren't adding them to the repo. 

Nice. Thanks bro. Can you please add a note and usage example to the README about this if you haven't already.

**Comment by josephdviviano** [comment]
ok.
