### ISSUE TITLE
Configure email notifications for RAID/temperature alerts from the servers

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#156]
We had this configured before, but I think with the change in the PET mail server routing policies and also network set up, our servers no longer spam us with alerts, but they ought to (consider the ongoing cooling problems). 

I suggest setting up the Dell iDRAC notifications, as well as also setting up something on the OSes for good measure. I'm filing this issue so that we can investigate our options and record what actions we've taken. 

Gabe (cobralab) or Peter (PET) might be good people to check in with about options.

**Comment by josephdviviano** [comment]
I think we'll close this for now.
