### ISSUE TITLE
test Nissl's drives, RMA broken drive, make sure Nissl is otherwise properly configured.

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#159]
They shouldn't be out in the open, either.

**Comment by pipitone** [comment]
Bump. Did you ever do this?

**Comment by pipitone** [comment]
Bump.

**Comment by pipitone** [comment]
Bump.

**Comment by josephdviviano** [comment]
![feynman-bongos2](https://cloud.githubusercontent.com/assets/4142570/8862395/52d6b0be-315e-11e5-9555-1404888cf10d.jpg)

**Comment by pipitone** [comment]
![duh](https://malialitman.files.wordpress.com/2015/01/duh.jpeg)

**Comment by pipitone** [comment]
Done.
