### ISSUE TITLE
install AMICO into matlab extras

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#163]
https://github.com/daducci/AMICO/

**Comment by josephdviviano** [comment]
I installed it into its own module instead (amico) -- not sure if I did it correctly.

**Comment by pipitone** [comment]
If you aren't sure, perhaps reopen this issue and assign it to me to look over.

**Comment by josephdviviano** [comment]
Hey Jon, thanks for the offer. My hunch is we won't know if I did everything right without pushing some data through, which I think Tina might be better suited toward. I had to compile both a bunch of MEX as well as some C binaries, so the odds I did *something* wrong seems pretty high :)

**Comment by pipitone** [comment]
Ah, okay, I thought you meant you didn't know if you'd built the module
correctly or had it laid out properly, etc.. If it's just a matter of
being unsure if the code itself is working correctly, I'm okay with
closing this issue and filing future issues with specific bugs.

**Comment by tina-roostaei** [comment]
Hi, when I load matlab/R2012b_concurrent and amico/150219, and then I open matlab, I see this:

Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/amico
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/spams
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/ParforProgMonv2
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/fitting
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/models
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/niftimatlib/matlab
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/amico
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/spams
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/ParforProgMonv2
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/fitting
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi/models
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/noddi
Warning: Name is nonexistent or not a directory: /opt/quarantine/amico/150219/build/build/niftimatlib/matlab

I think there is an extra "/build" in the paths, but I'm not sure this is the reason.

**Comment by josephdviviano** [comment]
Hi Tina,

That was a typo on my part. It should be fixed now.

**Comment by tina-roostaei** [comment]
Thanks. Now I get this warning:

Warning: Directory permission denied: /opt/quarantine/amico/150219/build/noddi/ParforProgMonv2

**Comment by josephdviviano** [comment]
Oops, that is fixed as well :D

**Comment by tina-roostaei** [comment]
Thank you. The toolbox worked properly after: 

 >> addpath(genpath('/opt/quarantine/amico/150219/build/noddi'))
 >> addpath(genpath('/opt/quarantine/amico/150219/build/spams'))

:)

**Comment by josephdviviano** [comment]
OK I'll look into why that isn't happening automatically... those should be appended to the matlab path in the module file. Thanks!

**Comment by josephdviviano** [comment]
Hey Jon,

The module file looks like this:

    set           basepath         ${quarantine_path}/amico/150219/build

    # set up camino  
    prepend-path  PATH             ${basepath}/camino/bin 
    setenv        CAMINO_HEAP_SIZE 1800
 
    # set up noddi 
    prepend-path  MATLABPATH       ${basepath}/niftimatlib/matlab
    prepend-path  MATLABPATH       ${basepath}/noddi
    prepend-path  MATLABPATH       ${basepath}/noddi/models
    prepend-path  MATLABPATH       ${basepath}/noddi/fitting
    prepend-path  MATLABPATH       ${basepath}/noddi/ParforProgMonv2
 
    # set up spams
    prepend-path  MATLABPATH       ${basepath}/spams

    # set up amico
    prepend-path  MATLABPATH       ${basepath}/amico

Any idea why she needs to set these herself as well?

**Comment by josephdviviano** [comment]
Hey, nevermind, I realize I forgot some of the subdirectories that 'genpath' captured. I've added those to the module. Tina, give the module a whirl without adding those extra paths. If you continue to have issues feel free to reopen this issue.
