### ISSUE TITLE
Ansible gets stuck on one computer

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#166]
Since I changed the localadmin password, ansible is hanging while trying to authenticate with a computer.
It isn't MRSDTI, oops.

**Comment by pipitone** [comment]
You can make ansible more verbose using -vvvv, perhaps this will tell you which machine it fails on.

If you use a newer version of ansible, you can pass --step to ansible-playbook to have it wait for confirmation from you before moving on to the next play.

**Comment by josephdviviano** [comment]
It was nissl's known host entry on franklin that was causing the problem. I think changing shadow resulted in a new known hosts entry that conflicted with the older one. I havent seen this sort of error before, but manually removing the known hosts entry solved the problem.
