### ISSUE TITLE
SGE master is not running on mrsdti?

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#167]
@josephdviviano It looks like the changes to move the SGE master over to mrsdti are not quite working at the moment. The cluster was running fine this afternoon, but perhaps your ansible changes did something? 

In any case, symptoms: 

```bash
$ hostname
kandel
$ qstat
error: commlib error: got select error (Connection refused)
error: unable to send message to qmaster using port 6444 on host "mrsdti.kimel.ric": got send error
```

**Comment by josephdviviano** [comment]
uh oh, I had a hankering that something would go wrong with SGE when I was running ansible earlier today... let me look into it.

**Comment by josephdviviano** [comment]
Fixed. I journaled some of my findings in the wiki.

**Comment by pipitone** [comment]
Where?
