### ISSUE TITLE
Configure ZFS on kimsrv to use little / no RAM by turning off prefetch

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#168]
from https://wiki.freebsd.org/ZFSTuningGuide

    Loader tunables (in /boot/loader.conf): 
    # Disable ZFS prefetching 
    vfs.zfs.prefetch_disable="1"

May also be related to ARC

http://blog.zach.st/2014/08/02/control-the-size-of-the-zfs-arc-cache-dynamically.html

**Comment by pipitone** [comment]
BSD settings may be different. Check zfsonlinux.org. I recall being able to tune the max ARC size.

**Comment by josephdviviano** [comment]
Trying this: http://wiki.gentoo.org/wiki/ZFS#Adjusting_ARC_memory_usage

Adjusting ARC memory usage

The minimum and maximum memory usage of ARC is tunable via zfs_arc_min and zfs_arc_max respectively. These properties can be set any of three ways. The first is at runtime (new in 0.6.2):
    
    root #echo 536870912 >> /sys/module/zfs/parameters/zfs_arc_max

This sysfs value became writable in ZFSOnLinux 0.6.2. Changes through sysfs do not persist across boots. Also, the value in sysfs will be 0 when this value has not been manually configured. The current setting can be viewed by looking at c_max in /proc/spl/kstat/zfs/arcstats

The second is via /etc/modprobe.d/zfs.conf.

    root #echo "options zfs zfs_arc_max=536870912" >> /etc/modprobe.d/zfs.conf

If using genkernel to load ZFS, this value must be set before genkernel is run to ensure that the file is copied into the initramfs.

**Comment by josephdviviano** [comment]
I did this on KIMSRV

    sudo vi /etc/modprobe.d/zfs.conf

    # min 2 GB, max 4 GB
    options zfs zfs_arc_min=2000000000
    options zfs zfs_arc_max=4000000000


more [here](https://github.com/TIGRLab/admin/wiki/ZFS-for-n00bs)

**Comment by josephdviviano** [comment]
I believe this is done with a reboot of kimsrv.

**Comment by josephdviviano** [comment]
I've added this to ansible via the zfs role: 

    /projects/IT/ansible/ansible-playbooks/roles/zfs
