### ISSUE TITLE
tbss_2_reg doesn't submit jobs to the queue

### ISSUE THREAD

**Issue by tinabehdinan** [TIGRLab/admin#170]
Steps to reproduce: 
1. `module load FSL/5.0.7`
2. Run `tbss_2_reg` 

‎(ﾉಥ益ಥ）ﾉ ┻━┻

**Comment by josephdviviano** [comment]
I might have a handle on this -- give it a go when you get back.

**Comment by josephdviviano** [comment]
I believe this is related to the fsl_sub issue previously reported. Please reopen if you continue to have issues.
