### ISSUE TITLE
Manage data quality issues under datman issues

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#171]
[see here](https://github.com/TIGRLab/datman/issues)

**Comment by pipitone** [comment]
Are you suggesting that we file all issues for data management stuff in the tigrlab/datman repo?  If so, I'm a bit worried this might lead to fragmentation/losing track of things.. what do you think?  Perhaps just use a label instead? 

I'm oddly fine with filing issues about datman code itself under the datman repo though.. hmm.

**Comment by josephdviviano** [comment]
where should we keep track of it then?

**Comment by pipitone** [comment]
As I suggested, we could label data issues here in the admin repo for now? Are you worried it will get too cluttered? 

Alternatively, we could create a `data` repo and put tickets there, or create a repo for each study and put issues there if we really expect lots of issues and want to file them separately/having them linked to other study data assets that we can make public.

**Comment by josephdviviano** [comment]
Oh sorry I didn't catch that you wanted to label data issues here.

I think it would be good for us to log these sorts of things somewhere (anywhere really). Need not be github though the interface is nice. Could be a seperate repo (perhaps we rename admin --> system and then make a new repo called data)? If you like that idea I'll do it.

**Comment by pipitone** [comment]
We decided to use this http://github.com/TIGRLab/data for this.
