### ISSUE TITLE
rpcbind doesn't start on reboot of kimsrv 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#173]

**Comment by josephdviviano** [comment]
As per here: http://serverfault.com/questions/663425/how-to-start-rpcbind-automatically-at-boot-on-ubuntu-14-04-server I added

    service rpcbind start

to 

    /etc/rc.local

**Comment by pipitone** [comment]
Why is this the only machine that needs this? 

Worth adding to ansible if this is truly what needs doing.
