### ISSUE TITLE
matlab

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#177]
Is there are problem with the matlab license? I can load matlab but not open it. I'm getting the following error:
melissa@hebb:~$ matlab
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2013b/15

Diagnostic Information:
Feature: MATLAB 
License path: /home/melissa/.matlab/R2013b_licenses:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/lic
enses/license.dat:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/licenses/network.lic 
Licensing error: -15,570. System Error: 115

**Comment by josephdviviano** [comment]
I think that was my bad. Try again?

**Comment by mlevesque82** [comment]
That was fast! It works now thanks. :)
