### ISSUE TITLE
make kimsrv send more emails

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#180]
![2603 png](https://cloud.githubusercontent.com/assets/4142570/6364657/a75cb572-bc77-11e4-8460-3bd5ceff289f.gif)

**Comment by pipitone** [comment]
![trollolol](http://zero-k.info/Resources/Trololo.minimap.jpg)

**Comment by josephdviviano** [comment]
![maxresdefault](https://cloud.githubusercontent.com/assets/4142570/6364836/96f76e22-bc7a-11e4-8d71-7811887e58d1.jpg)

**Comment by josephdviviano** [comment]
![080312-total-recall](https://cloud.githubusercontent.com/assets/4142570/6365290/b0089bf4-bc82-11e4-8a73-a9023d63f5d3.jpg)
