### ISSUE TITLE
kimsrv need to be integrated with the queue

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#182]
right now it is in a disabled state because job are failing. i think it has to do with disk space issues.

**Comment by pipitone** [comment]
#181 closed, so perhaps check this out again.

Relatedly, did the ZFS memory fixes for #168 make it into ansible? If not, perhaps file a ticket so that we remember to do that.

**Comment by josephdviviano** [comment]
I just did that (check my work here):

    /projects/IT/ansible/ansible-playbooks/roles/zfs

I've also added kimsrv back into the queue, but I'm going to leave this ticket open until we are sure that things are set up properly.

**Comment by josephdviviano** [comment]
Correction I will have to do this when I get in (some sort of font bug over ssh...)

**Comment by josephdviviano** [comment]
I think the bugs we saw before were unrelated to kimsrv. Closing.
