### ISSUE TITLE
set up passwordless authentication with MR server / way of auto-transfering data?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#183]
Right now using the MR server is a really irritating and slow process, especially since the password is impossible to memorize.

I propose passwordless authentication for authorized machines (say kimsrv). This will give us some hope of scripting data retrieval from the server.

**Comment by pipitone** [comment]
I can authorize specific kimel lab users for specific ftp users.

**Comment by josephdviviano** [comment]
Oh ok :) I guess this is a closed case then.

**Comment by josephdviviano** [comment]
(buy

**Comment by josephdviviano** [comment]
as long as a certain someone can get access :)
