### ISSUE TITLE
buy spare switch

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#184]

**Comment by josephdviviano** [comment]
Email sent to Royston Appu [roysapp@cdw.com] asking for a fresh quote for:

+ Cisco Catalyst 3750X-48T-S - switch - 48 ports - managed - rack-mountable [Mfg. Part#: WS-C3750X-48T-S]
+ Cisco - expansion module - 4 ports [Mfg. Part#: C3KX-NM-1G=]

I've asked the total to be under our CFI budget of $9943, with an in-kind discount of 25%.

**Comment by josephdviviano** [comment]
Due to the current exchange rate, the 48 port option we were quoted for was too much. I've followed up asking for a 24 port quote.

**Comment by josephdviviano** [comment]
Quote received and is in our budget. However we are moving to the CAMH network, so we need to make sure the switch can be managed by CAMH IT. I'm going to try to figure out which management interface we're used to using, and then buy a 24 port item of that kind.

**Comment by josephdviviano** [comment]
Jon is going to take this over since we need to find more money to buy a new CAMH compatible switch. We're going to migrate off of the PET network.

**Comment by pipitone** [comment]
CAMH IT is going to send us infos on a switch to buy. 

![oh yeah](http://comps.canstockphoto.com/can-stock-photo_csp17917062.jpg)

**Comment by pipitone** [comment]
CAMH has a spare for us.
