### ISSUE TITLE
Buy SFP

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#185]

**Comment by pipitone** [comment]
We should have a spare for B67 in case of fail (which may be what is happening ATM)

**Comment by pipitone** [comment]
And a spare SM patch cable

**Comment by josephdviviano** [comment]
We need an SFP for the Dell Powerconnect 5524 for $275: http://accessories.dell.com/sna/productdetail.aspx?c=us&l=en&orig_s=corp&sku=310-7225&s=bsd

Dell Networking Transciever SFP 1000BASE-T
Manufacturer Part# : PF911 | Dell Part# : 310-7225

I'm going to try our luck with this knockoff for $21.75 from fiberstore.com: http://www.fs.com/-p-13277.html?currency=CAD&paid=google_shopping&gclid=CIvi_8vEu8oCFRCqaQod-gsFcw#all_reviews

Dell 310-7225 Compatible 1000BASE-T SFP RJ-45 100m Transceiver
FS SKU#: SKU20435M
Model#: SFP-GB-GE-T
MFG PART#: 310-7225

**Comment by josephdviviano** [comment]
Order placed, see tigrlab@camh.ca for details. Order # FS160121022576

**Comment by josephdviviano** [comment]
I ordered the wrong thing. @pipitone will take care of this.

**Comment by josephdviviano** [comment]
+ SFP downstairs is single mode (fyi: yellow cable == single mode, orange cable == multimode).

I believe we need this SFP: Dell Networking Transceiver SFP 1000BASE-LX 1310nm Wavelength 10km Reach
http://accessories.us.dell.com/sna/productdetail.aspx?c=us&l=en&s=fed&cs=16&sku=331-5309

@pipitone you might want to double check all of this ;)

Dell Part# : 331-5309 <-- suggests this alternative...: http://www.qsfps.com/331-5309

**Comment by pipitone** [comment]
SFPs received. David is working with IT to get the switch installed into RM 107.
