### ISSUE TITLE
Contact S-van about opening a DMZ port and pointing it to 107 for our XNAT server (172.25.9.79) 

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#186]
This will mean people won't have to auto-ssh from kimsrv to DTI to access our database.

**Comment by pipitone** [comment]
Posted an IMG request for a static CAMH IP. We'll see what happens.

**Comment by pipitone** [comment]
I'm closing this. If it ever happens, it'll be a miracle. No wait, fuck it, I'm going to see if David can find out anything about this for us.

**Comment by pipitone** [comment]
![You're a wizard, harry!](http://i.imgur.com/riAj774.jpg)

**Comment by josephdviviano** [comment]
![tumblr_n0tn55vxhk1rpzbo4o1_250](https://cloud.githubusercontent.com/assets/4142570/7892047/8c960f08-061f-11e5-8f59-19e0d0e06a6c.gif)

**Comment by pipitone** [comment]
![it's happening](http://i.imgur.com/Na3cZe8.gif)

**Comment by pipitone** [comment]
It finally happened, guise. We now have a CAMH public IP address mapped back to an internal IP address on the SCC vlans. 

![lols](http://memeguy.com/photos/images/mrw-my-roommate-told-me-he-lost-his-virginity-finally-43065.gif)
