### ISSUE TITLE
matlab

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#188]
permissions issue with matlab 2013

**Comment by josephdviviano** [comment]
what is the exact error?

**Comment by mlevesque82** [comment]
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2013b/15

Diagnostic Information:
Feature: MATLAB 
License path: /home/melissa/.matlab/R2013b_licenses:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/lic
enses/license.dat:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/licenses/network.lic 
Licensing error: -15,570. System Error: 115

**Comment by mlevesque82** [comment]
I did load it without issue...

**Comment by josephdviviano** [comment]
Right the license manager was down, likely because of the power outage over the weekend. try again?

**Comment by mlevesque82** [comment]
Problem solved, thanks!
