### ISSUE TITLE
problem with large number of MATLAB jobs in the queue

### ISSUE THREAD

**Issue by tina-roostaei** [TIGRLab/admin#189]
Hi, 

I have the following script submitted 27000 times to the cluster (now it is around 27000, totally it was near 45000 I think):

addpath(genpath('/projects/tina_r/softwares/niftimatlib-1.2'))
addpath(genpath('/projects/tina_r/softwares/NODDI_toolbox_v0.9'))
CreateROI('../data.nii','${mask}','NODDI_brain_${mask:5:3}.mat')
quit

and it is causing problems for the machines it is running on. But, I don't think it is a problem with the job itself, because the same script was running well for a couple of hours before the number of submitted jobs gradually became this large. This makes me think that the problem is because of the large number of jobs in the queue for each computer...

Tina

**Comment by josephdviviano** [comment]
Hey Jon, crazy idea maybe but I think this has something to do with cached ram. Even after suspending my machine, I found it to be slow. My ram was maxed but it was 95% cached ram. Running this as root cleared me up

    sync; echo 3 > /proc/sys/vm/drop_caches

I'm going to keep looking at this. I think maybe that matlab code (or something) isn't cleaning itself up properly after running.

**Comment by pipitone** [comment]
Hmmm. Interesting idea Joseph. I see there's even a reference to repeatedly running the `drop_caches` command in order to speed up MATLAB, [check it out](https://books.google.ca/books?id=tXPOBQAAQBAJ&lpg=PA107&ots=xWwZODNT3J&dq=matlab%20linux%20drop_caches&pg=PA107#v=onepage&q=matlab%20linux%20drop_caches&f=false)

Also, I just watched one MATLAB process consume 12+GB of ram... 

This issue may also be (partly) a disk I/O thing. If MATLAB is reading/writing a lot, then lots of processes doing this at once would have a noticeable impact I imagine.

**Comment by pipitone** [comment]
In any case, Tina, you probably shouldn't be submitting 45000 jobs to the queue at one time. :-) Come talk to me about submitting an array job. It's a single job that run 45000 times for each command you have. Much easier load on the queueing system. 

If you want to try this yourself: 
```sh 
$ module load SGE-extras
$ sge_submit_array commands.txt
```

**Comment by tina-roostaei** [comment]
Yes, you're right. I didn't think of the number of the jobs before
submitting them. I think it was before I talked to you. They are part of
the preprocessing and as they take just seconds to run I thought they might
not take more than a few hours, which turned out not to be the case. After
this disaster finishes I 'll try the array job for fitting NODDI. Thanks.

**Comment by josephdviviano** [comment]
I'm looking at the matlab code now... it's worth noting that this job shouldn't be taking anywhere close to 12 GB of RAM

    /projects/tina_r/softwares/NODDI_toolbox_v0.9/fitting/CreateROI.m

Looks like it:

+ loads a DTI image and a brain mask
+ figures out how many voxels are in the mask
+ loads only the DTI data  into a new matrix that only includes regions inside the mask.
+ saves an index of these locations.
+ saves these as some sort of output file.

But it does so in a crazy way: 3 nested for loops where a `find` would have worked from what I can tell. I think I could really speed this code up AND prevent this memory usage, which should never hit 1 GB let alone 12, but I would need to test some things to make sure I understand what it is really doing.

Also, maybe adding a `clear` to the code will work (7 of 12: https://www.mathworks.com/matlabcentral/newsreader/view_thread/161419).

Tina, could you post a path to some example input data from your submission? (Mask and DTI image).

**Comment by pipitone** [comment]
Good catch Joseph. vectorize -> speed up, less memory. 

Why on earth are they using for-loops??? 

You probably know this, but in case not, I think MATLAB allows you to use boolean matrices as indices (as does numpy) so it might be a matter of doing (pseudocode):

```python
image, mask = load_image(), load_mask() > 0
masked_image = zeroes(image.shape)

masked_image[mask] = image[mask] 

save(masked_image)
```

**Comment by pipitone** [comment]
I'm going to close this issue, because I think we have it sussed, but reopen if not.
