### ISSUE TITLE
1. I see no data repo & 2. COGBD-Y naming issue 

### ISSUE THREAD

**Issue by tinabehdinan** [TIGRLab/admin#192]
27B025, 27B026, 27B027, 27B028, 27B031 FA maps are named *DTI-60plus5* instead of *DTI-60+5* like the other COGBD and DTI subjects

I would post this in data repo but I seriously cannot find it

**Comment by pipitone** [comment]
Ah.. that's because the `data` repo is private, and you weren't part of the "Users" team (and only they have access to it). I've invited you. 

Sorry for the #nofriendship

**Comment by tinabehdinan** [comment]
rejected :( ... accepted :)

**Comment by josephdviviano** [comment]
Thanks Tina, I'm getting going on the COGBD data as well. This issue will be resolved among some other things I've found with the `new way`.

new way
------------


NEW WAY
========

    ooooo        ooooo
    o       o        o       o
    o       o        o       o
    ooooo        ooooo


    \---------------------/
     \                         /
       \                     /
           ~~~~~~~
