### ISSUE TITLE
Download new dbgap datasets

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#194]
Dan has sent me links to some more dbgap datasets to download. They are small enough that I think we can download them directly over the RIC network. @tina-roostaei asks that I start with the "cardia" dataset first. Filling this issue so that I don't forget. :-)

To download:
- [x] Dataset ID 43161 - CARDIA Consent Group 1
- [x] Dataset ID 43162 - CARDIA Consent Group 2
- [x] Dataset ID 43163 - GenADA LONG
- [x] Dataset ID 43164 - Alzheimer's Disease Genetics Consortium (ADGC)

**Comment by pipitone** [comment]
I've started to download the cardia datasets in `/external/dbgap/incoming`. We'll need to decrypt them before putting them into `/external/dbgap`

**Comment by pipitone** [comment]
@tina-roostaei Are you able to do the work of decrypting new datasets in the `incoming/` folder?  If so, @dfelsky has written up some instructions here: `/external/dbgap/README_decrypt`.

 Once you decrypt the files, let's move them into `/external/dbgap` using a decent naming scheme (eg `cardia_consent_group_1`). 

I'm updating the original issue text as I finish downloading the datasets.

**Comment by tina-roostaei** [comment]
Hi Jon,

Thanks for downloading. I'll try.

Tina

**Comment by josephdviviano** [comment]
Tina is just copying the files to her scratch folder to decrypt them there, as the software works in place.

**Comment by pipitone** [comment]
> Tina is just copying the files to her scratch folder to decrypt them there, as the software works in place.

Excellent. Tina, let me know when you've got them decrypted and I'll
move that stuff back to /external. Thanks for doing this!

**Comment by tina-roostaei** [comment]
Hi, the decryption seems to be finished :)
/scratch/tina_r/43161/
/scratch/tina_r/43162/

**Comment by pipitone** [comment]
Excellent. Copying those over to /external now.

**Comment by pipitone** [comment]
K, copied. @tina-roostaei you can remove `/scratch/tina_r/4316*`

**Comment by pipitone** [comment]
Done, and organized with a nice README. :-)
