### ISSUE TITLE
Accidental line in ~/.ssh/known_hosts !!!

### ISSUE THREAD

**Issue by vincent-man** [TIGRLab/admin#195]
Hey guys,

I accentually copied a line into ~/.ssh/known_hosts (on the nissl station, though I'm not sure if this document is general across stations). This line is at the end of the document and is not useful. For some reason I could copy it into known_hosts but can't delete it with pico/vi/nano. Can you remove it? 

(Also, I tried to sudo vi .ssh/known_hosts but it said I'm not a sudoer and that this will be reported, so just a heads up in case you see a red flag somewhere!) 

The line: 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDflKvNpwLR4Da//7lK0U8Te+KkDZ2iRrvwkEAcfz0f7QbXMi9aNKobFb1TYtA3IFRNGXRPXh0NcpEW/FoOEHhYsYzwMz1/jSOu8oSvmaOC3k6E0A+ZqIU92zWvWdzZsdBmOH+hFQRuoaA4EzY06PqGRsHkvWI4cNzxiuq1rhBqxhyO44tkbCq+boUf0oUUjJB4aFTvUSwmEaX8B4vp1q99nzN3VskcKHLgKK5doBW5cOQhwNMK43yJrkMdqszViyvFDZ6IVGdIemPuh5hqjPSEA8b8ASmzmMpJ+cnwpkdhnlMmazSu+CROG5uIgryzP0tvkPtJ0ZRG+eGGBXf+GSFX wc2@WC2s-iMac.local

**Comment by pipitone** [comment]
Hey Vincent, Just checked this file on nissl, and don't see the line...  Also, as your user, on nissl, I can edit the file just fine. Could it be another computer you were on?

**Comment by vincent-man** [comment]
Oh weird! Yup I was on another computer, ssh-ing into nissl. Maybe that's where the permission issue came up. Happy that the extra line isn't there any way!

**Comment by pipitone** [comment]
Could you have been on kimsrv? 
And could this file have been ~/.ssh/authorized_keys? 

This file does exist on kimsrv in your home folder there, and does have
a few keys from your mac installed, including a line that had an
improper line ending (was a dos line ending \r\n, not a unix line ending
\n). I fixed that up. 

Are you having problems connecting remotely to kimsrv?
