### ISSUE TITLE
download HCP data

### ISSUE THREAD

**Issue by tina-roostaei** [TIGRLab/admin#196]
Hi,

Just filing a reminder about downloading T1 and rest-fMRI HCP data (500 subjects).

Tina

**Comment by josephdviviano** [comment]
I think we should file a request to open UDP on the CAMH network. Daivd, can you take care of this?

**Comment by pipitone** [comment]
I've put in a request.

**Comment by pipitone** [comment]
FYI, the UDP port issue is being tracked over here: CAMH-Scientific-Computing/SCC#7

**Comment by pipitone** [comment]
And... we can finally download the HCP data if you want it. Here's how:

ssh to the scc, and from there to `mgmt1`. This is the file server. From that server you should be able to use aspera connect from the command line ('aspc').  I have it installed in my home folder, to get set up, run: 

     source ~jpipitone/software/aspera-connect-3.6.0.106805-linux-64.sourceme
