### ISSUE TITLE
Document the dbgap datasets we have

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#199]
We have a few datasets from [dgbap](http://www.ncbi.nlm.nih.gov/gap) now in `/external/dbgap` but I'd like us to have a bit of a written description of them so that newcomers know what these data are. 

@dfelsky and @tina-roostaei, can you one or both of you please reply with a short description for each of these (include the name, a short description, and perhaps a URL for more info): 
- `/external/dbgap/dataset1` (we should rename this to it's ID or something sensible, suggestions?)
- `/external/dbgap/dataset2` (ditto)
- `/external/dgbap/43161`
- `/external/dgbap/43162`

Also, the two other datasets mentioned in #194 to be downloaded yet: 
- Dataset ID 43163 - GenADA LONG
- Dataset ID 43164 - Alzheimer's Disease Genetics Consortium (ADGC)

**Comment by josephdviviano** [comment]
See https://github.com/TIGRLab/data/issues/15 for more relating to the PNC dataset.

**Comment by pipitone** [comment]
Done, see: https://github.com/TIGRLab/external-dbgap
