### ISSUE TITLE
contact Dell regarding PowerConnect switch (needs to be reconfigured for VLAN 9 with every power outage).

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#200]
:(

**Comment by pipitone** [comment]
Let's first check the Admin console for the switch and see if it reports low battery / useful diagnostics. Dell will ask us to do this anyway.

**Comment by josephdviviano** [comment]
I'm willing to live with having to reconfigure this one with the occasional power outage. Unassigned.
