### ISSUE TITLE
Give Joseph access to DTIG on the MR-FTP server

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#201]

**Comment by josephdviviano** [comment]
i needs dat passwordless access yo

**Comment by pipitone** [comment]
![password](http://image.shutterstock.com/display_pic_with_logo/635779/217297384/stock-vector-password-217297384.jpg)

**Comment by josephdviviano** [comment]
'listen to this article' http://en.wikipedia.org/wiki/Bhutanese_passport

**Comment by pipitone** [comment]
> 'listen to this article' http://en.wikipedia.org/wiki/Bhutanese_passport

best part of this is the talk page.

**Comment by pipitone** [comment]
Done. 

![good to go](http://ak.picdn.net/shutterstock/videos/1590916/preview/stock-footage-man-giving-thumbs-up-sign-isolated-on-white.jpg)
