### ISSUE TITLE
Buy an NVIDIA Dev Box

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#202]
http://info.nvidianews.com/early_access_nvidia_3_15.html

**Comment by josephdviviano** [comment]
![telfar_med](https://cloud.githubusercontent.com/assets/4142570/7862493/47ef6df0-0524-11e5-96a4-77e710b7d30d.gif)

**Comment by josephdviviano** [comment]
I have the quotes -- looking into how to buy stuff

**Comment by pipitone** [comment]
Purchase Req is in. 
![Yeaaah](http://i.imgur.com/8bHy8Xg.gif)

**Comment by josephdviviano** [comment]
![tumblr_n5ol99ue731qz8x31o1_500](https://cloud.githubusercontent.com/assets/4142570/8862378/355e7846-315e-11e5-9df8-c1e46302789c.gif)

**Comment by pipitone** [comment]
![oooooh](https://kayfil.files.wordpress.com/2015/01/rathore-mustache.gif)

**Comment by pipitone** [comment]
Well, it arrived in record time: 7 months. Yay!

**Comment by josephdviviano** [comment]
![giphy](https://cloud.githubusercontent.com/assets/4142570/10400510/2a5b4102-6e87-11e5-880d-b13e27c0d9f2.gif)
