### ISSUE TITLE
Ansible didn't sync .bashrc with kimsrv when jon ran sync_homes this morning?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#204]
Strange? Or expected?

**Comment by pipitone** [comment]
For Arash? Expected. I just ran it on the workstations group.

**Comment by pipitone** [comment]
Also, to be clear, I only sync'ed arash's .bashrc. Nothing/nobody else.

**Comment by josephdviviano** [comment]
OK sounds good. We've manually patched up kimsrv/riker.
