### ISSUE TITLE
MATLAB slow?

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#205]
@colinhawco reports MATLAB is running slowly on `talairach`, when doing PLS. Could this be a hyperthreading thing?  Colin is going to try running on `golgi`

**Comment by josephdviviano** [comment]
has to do with `matlabpool`:

if a machine isn't being kewl, try opening the pool

    matlabpool open

if this fails, try janking the switch, or rebooting the ish, or delete system32

**Comment by pipitone** [comment]
Documentation here: 
http://www.mathworks.com/help/distcomp/parpool.html

Note that `matlabpool` has, in 2015b, been deprecated in favour of using the `parpool` command (linked to above).
