### ISSUE TITLE
Configure XNAT to send email notifications when data arrives

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#209]

**Comment by pipitone** [comment]
@josephdviviano has this working. Joseph, can you please have xnat email admins@ so that we both get notifications?

**Comment by pipitone** [comment]
(or alternatively, make a new alias on kimsrv/tigrsrv for xnat@ and that way we can eventually add Erin to it).

**Comment by josephdviviano** [comment]
Sure, no problem. It is interesting that you aren't getting the emails because I added you to the list too -- maybe I only entered the first one correctly. It makes most sense for all kimel admins to get them at all times, I agree.

**Comment by pipitone** [comment]
This is done now.
