### ISSUE TITLE
XNAT backup

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#211]
According to Fan from the Stothers' lab: 

> There are two things need to be backed
> up, the postgreSQL table and the filesystem.  The database dump together
> with the filesystem that stores actual images are (tape?) backed up every
> day. We also keep a clone of the XNAT VM image.  Depending on how fast
> [our storage provider] can restore the backup for us, the disaster recovery usually takes up
> to a day.  So yes, the downtime is still considered significant but that
> seems to be the best we can do with the current resources.

So, we should look into making sure we have the following backups in place (and, of course, test them. :-): 

- [ ] Backup the VM image
- [ ] Backup the XNAT database (see the [postgres docs on the topic](http://www.postgresql.org/docs/8.1/static/backup.html))
- [ ] Backup the XNAT filesystem

**Comment by josephdviviano** [comment]
Thanks for doing this Jon. Since I put the current backup scripts in place I'll look at what we are/arent doing and report back / fix. I'll let you know if I run into any funcades.

**Comment by pipitone** [comment]
Where are you at with this?

**Comment by josephdviviano** [comment]
Summary that I just added to the wiki:

https://github.com/TIGRLab/admin/wiki/XNAT-&-XEN-Guide

backup scheme
-------------
Currently, there are 3 major things that need to be backed up:

+ backup vm image
+ backup xnat database
+ backup xnat filesystem

**vm image**

This is currently *not* being backed up. We should def be doing this, but don't have a good way of doing it as it is a 1TB file that is changing daily.

**xnat database**

Following this [postgres guide](http://www.postgresql.org/docs/8.1/static/backup.html), I wrote `/mnt/xnat/spred/pg-bkup.sh`, which dumps a daily backup of the database to `/mnt/xnat/spred/db-bkup`. They're really small at the moment, so I'm not removing old versions.

**xnat filesystem**

Finally, the contents of the xnat filesystem (`/mnt/xnat/spred`) are being backed up via `/projects/admin/bin/backup.sh`. This syncs the entire database including the postgres dumps to `tank/`.

**Comment by pipitone** [comment]
Okay, before closing this, I'd want a few changes: 
- `/mnt/xnat/spred/pg-bkup.sh` moved to `/projects/admin/bin` and documented
- A cronjob with the `MAILTO` set so that we receive email notifications when this job completes/errors out

Alternatively, incorporate these backup tasks into the `/projects/admin/bin/backup.sh` script.

**Comment by clevisboxx** [comment]
+ this must be run on the VM so I'm making an xnat repo for this scrip.
+ I added admins@kimel.ric to the crontab
