### ISSUE TITLE
FSL versions 

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#212]
TBSS seems to be running fine in FSL/5.0.6 but failing in FSL/5.0.7

**Comment by josephdviviano** [comment]
Is there any error printed to the terminal when it does?

**Comment by mlevesque82** [comment]
TBSS Step 3:
using pre-chosen target for registration
transforming all FA images into MNI152 space
ERROR:: cannot find the following warp results:
     DTI_CMH_H033_02_01_DTI60-1000_11_Ax-DTI-60+5_eddy_correct_dtifit_FA_FA_to_target_warp DTI_CMH_H155_01_01_DTI60-1000_11_Ax-DTI-60+5_eddy_correct_dtifit_FA_FA_to_target_warp DTI_CMH_H174_01_01_DTI60-1000_11_Ax-DTI-60+5_eddy_correct_dtifit_FA_FA_to_target_warp
Please wait for registration (fnirt) to finish or re-run registrations

**Comment by josephdviviano** [comment]
Can you post the contents of the script you are using to run TBSS?

**Comment by mlevesque82** [comment]
This is the step that isn't working in FSL/5.0.7: 

tbss_3_postreg -S
# output: derive mean FA and mean FA skeleton of all subjects
# all_FA, mean_FA, mean_FA_mask, mean_FA_skeleton (in stats folder)
# _FA_to_target.nii.gz (image in FA folder)

I'll send you the full script by email.

**Comment by josephdviviano** [comment]
Hey,

Is it possible that the second stage of TBSS is generating a folder? Try running stage 3 inside of that folder?

**Comment by mlevesque82** [comment]
That seems to work. Weird that I didn't have to do that with the other version of FSL...

**Comment by josephdviviano** [comment]
Yes their documentation is sometimes less than clear. After you are done perfecting your script, we can put it on the internet so the whole world can know how clever we are!! :D
