### ISSUE TITLE
freesurfer QA

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#217]
I want to run some quality control on freesurfer outputs. I found this site: https://surfer.nmr.mgh.harvard.edu/fswiki/QATools and Joe was nice enough to create a module for it. I think perhaps the dependencies were not uploaded though because some functions are not working. 

Dependencies
QA Tools requires:
ImageMagick Studio version 6.2.8 or higher when using the snapshots option. This can be downloaded here.
The GNU awk (gawk) utility. This can be downloaded here.

Can someone check this out?
Thanks!

**Comment by josephdviviano** [comment]
@pipitone can you run ansible? I put that stuff in it.

**Comment by pipitone** [comment]
> @pipitone can you run ansible? I put that stuff in it.

Done.

**Comment by josephdviviano** [comment]
Awesome, thanks. Melissa if you continue to have trouble let me know ... I **think** I did the right thing :D

**Comment by mlevesque82** [comment]
The QA seems to be running but I keep getting a 'gawk: Command not found.' error message.

**Comment by pipitone** [comment]
> The QA seems to be running but I keep getting a 'gawk: Command not found.' error message.

Okay, I'll look into it.

**Comment by pipitone** [comment]
> The QA seems to be running but I keep getting a 'gawk: Command not found.' error message.

gawk is installed on Hebb now.  I'll figure out why it's not installed
everywhere else.

**Comment by josephdviviano** [comment]
Is it running on the queue? Gawk is only installed on the workstations, so if it trys to run on kimsrv or tigrsrv, it will fail.

**Comment by mlevesque82** [comment]
No I am running it on my machine.

**Comment by pipitone** [comment]
> Is it running on the queue? Gawk is only installed on the workstations, so if it trys to run on kimsrv or tigrsrv, it will fail. 

It's not even installed on workstations (e.g. kandel, I just checked)
for some reason; I'm not sure what's up with ansible.

**Comment by josephdviviano** [comment]
- gawk is on line 60 of main.yml. Strange. K thanks.

**Comment by pipitone** [comment]
gawk should be installed on all machines now.
