### ISSUE TITLE
freesurfer outputs

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#218]
"This sounds like a personal problem..."
Hey guys, this isn't really an issue for you guys but I'm putting this on here in case someone has any insight on this problem that I don't.

If we're using freesurfer to get voxel-wise thickness/surface area/volume values to perform a macacc or network-analysis, we need .txt files with those values. CIVET outputs .txt files but freesurfer outputs .mgh files. 

.mgh files can be read into matlab using the mgh.load.m script found on 
https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/MghFormat

Values can be copied and pasted into a text file, although I'm sure someone could write a script to do the same thing automatically. The issue is that there's roughly four times more values in freesurfer outputs as in CIVET outputs. 

I'm currently trying to figure out why that is. Do we have 4 freesurfer values for every 1 CIVET value? Is the smoothing different (as far as I know I'm using files smoothed at 20mm with both programs)?

**Comment by mlevesque82** [comment]
From freesurfer QA:

Q. How can I obtain the thickness of each vertex, and how can you identify which structure each vertex belongs to?

A: You will need to use the read_curv() function to get the thickness estimates, and use the read_annotation() function to assign each index in the surface vector to a specific structure. You can then match up corresponding indices in the the thickness vector and the structure vector to determine the thickness and structure label for each vertex.

**Comment by pipitone** [comment]
> The issue is that there's roughly four times more values in freesurfer
> outputs as in CIVET outputs. 

Freesurfer uses a denser mesh (~160K vertices per hemisphere vs CIVET
which uses 80K vertices).

**Comment by pipitone** [comment]
You can use AFNI's ConvertSurface to convert from FS to MNI formats: 
http://afni.nimh.nih.gov/pub/dist/doc/program_help/ConvertSurface.html

**Comment by josephdviviano** [comment]
Note that you will need to intelligently downsample to get this to work.

I would:

+ get an atlas in register with the FS and CIVET surfaces independently.
+ take the mean thickness value within each ROI.
+ compare.

**Comment by josephdviviano** [comment]
Freesurfer and Civet use very different algorithms, and the number of output verticies is arbitrary, hence why they are different.

**Comment by pipitone** [comment]
@mlevesque82 Have you got anything working with this?

**Comment by josephdviviano** [comment]
feel free to ask me to look at the data if you still are.

**Comment by mlevesque82** [comment]
No but I haven't dedicated very much time to this.
