### ISSUE TITLE
XNAT downloads are not working any longer?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#223]
+ click 'download' images
+ click 'submit'
+ goes to front page --- should result in the downloading of a kewl zip

**Comment by pipitone** [comment]
Restarted tomcat, and no difference. 

Then went here to find out where to look for xnat logs (hint `/usr/share/tomcat6/webapps/spred/logs`): 
https://wiki.xnat.org/display/XNAT16/Troubleshooting

Looking at `xdat.log`, I see references to "No space left on device" errors, e.g: 
> ```
> 2015-06-03 11:48:56,524 [main] ERROR org.nrg.xnat.turbine.utils.ArcSpecManager - 
> org.xml.sax.SAXException: No space left on device
> java.io.IOException: No space left on device
> ```

Sure enough: 
```sh
$ df -h 
# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_centos-lv_root
                       50G   21G   26G  45% /
tmpfs                 2.9G     0  2.9G   0% /dev/shm
/dev/mapper/vg_centos-lvol0
                      788G  748G     0 100% /usr/xnat
/dev/xvda1            485M   59M  401M  13% /boot
/dev/mapper/vg_centos-lv_home
                       99G  191M   94G   1% /home
```

**Comment by pipitone** [comment]
Here are some instructions on how to clean up after XNAT: 
https://wiki.xnat.org/display/XNAT16/Tips+for+Maintaining+your+XNAT+Application

**Comment by josephdviviano** [comment]
Great.
