### ISSUE TITLE
Find a good password manager for the lab to use

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#225]
I've been asked to find a way to manage passwords amongst lab members for shared accounts to imaging databases, etc.. 

Ideally this would be web-based, and something we don't have to host ourselves (although I suppose the case could be made for hosting it ourselves too). Things I've found that might fit the bill: 

- http://commonkey.com - web-based
- http://passpack.com - web-based
- http://lastpass.com - cross-platform app/browser plugin
- http://keepass.info - cross-platform app, database file

I could use some help evaluating these. @dfelsky @josephdviviano @mlevesque82 @tina-roostaei would you be able to give these a try also?

**Comment by pipitone** [comment]
@dfelsky is trying out passpack.com

**Comment by mlevesque82** [comment]
I can give commonkey a shot.

**Comment by tina-roostaei** [comment]
Hi,

I have used passpack a bit. You can save a description, a link, the
username and the password. And I think you can save 100 user/passes for
free. It is OK I think. However, I haven't tried the others.

Best,
Tina

**Comment by tina-roostaei** [comment]
And most importantly you can share. But I haven't tried that. :))

**Comment by josephdviviano** [comment]
ill do lastpass

**Comment by dfelsky** [comment]
I report that passpack.com is easy to use - I've set up a trial Kimel
account. Login information for this account can be found at /home/dan/pass/
passpack.com

On Wed, Jun 3, 2015 at 11:54 AM, Joseph Viviano <notifications@github.com>
wrote:

> ill do lastpass
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TIGRLab/admin/issues/225#issuecomment-108495129>.
>



-- 
*Daniel Felsky BSc.*

PhD Candidate, Institute of Medical Science, University of Toronto
<http://www.ims.utoronto.ca/>
Vanier Scholar <http://www.vanier.gc.ca/eng/home-accueil.html>, Kimel
Family Translational Imaging-Genetics Research Laboratory
<http://tigrlab.github.io/>
Centre for Addiction and Mental Health <http://www.camh.ca>, *250 College
St. W, M5T 1R8
<https://maps.google.ca/maps?safe=off&q=250+college+st+west&ie=UTF-8&hq=&hnear=0x882b34c0e60f5c03:0x933d364d8cadc254,250+College+St,+Toronto,+ON+M5T+1R8&gl=ca&ei=Cx2RUrmeEYazrgHJtIHgCw&ved=0CCsQ8gEwAA>*
Toronto, Ontario, Canada
Work: *(416)-535-8501 x33951*
Cell: *(416)-822-8539*
Email:
*daniel.felsky@camh.ca <daniel.felsky@camh.ca>*

**Comment by mlevesque82** [comment]
Commonkey is ok. Setting up an account is easy. They have a tutorial, which isn't really necessary since it's basically two lines of text. You can create teams and invite users via email. I've sent you an invitation to join the group, Jon, to see what happens.

**Comment by pipitone** [comment]
Didn't get the invite, Melissa. 

Dan says passpack.com is good.

**Comment by mlevesque82** [comment]
Then I would suggest we don't go with commonkey

**Comment by josephdviviano** [comment]
lastpass is sort of annoying i don't recommend.

**Comment by pipitone** [comment]
Okay, we're going with passpack.com

**Comment by pipitone** [comment]
Thanks for your help, y'all.
