### ISSUE TITLE
cajal and tesla are having trouble with /scratch

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#227]
Check the recent sge qmaster logs: 

     mrsdti:/var/spool/gridengine/qmaster/messages

You'll see lots of error messages of jobs failing on these nodes, and I'm not sure why. 

For example: 
```
06/03/2015 17:58:32|worker|mrsdti|W|job 208911.1 failed on host tesla.kimel.ric general opening input/output file because: 06/03/2015 17:58:31 [1008:300]: error: can't open output file "/scratch/anne/Julie_CIVET/nusdast/output/NM1089/logs/NM1089.nuc_inorm_t1.log": Operation not permitted
06/03/2015 17:58:32|worker|mrsdti|W|rescheduling job 208911.1
06/03/2015 17:58:32|worker|mrsdti|W|job 208913.1 failed on host tesla.kimel.ric general opening input/output file because: 06/03/2015 17:58:31 [1008:302]: error: can't open output file "/scratch/anne/Julie_CIVET/nusdast/output/NM2103/logs/NM2103.skull_removal.log": Operation not permitted
06/03/2015 17:58:32|worker|mrsdti|W|rescheduling job 208913.1
06/03/2015 17:58:32|worker|mrsdti|W|job 208914.1 failed on host tesla.kimel.ric general opening input/output file because: 06/03/2015 17:58:31 [1008:301]: error: can't open output file "/scratch/anne/Julie_CIVET/nusdast/output/NM2104/logs/NM2104.skull_removal.log": Operation not permitted
06/03/2015 17:58:32|worker|mrsdti|W|rescheduling job 208914.1
06/03/2015 17:59:02|worker|mrsdti|W|job 208917.1 failed on host cajal.kimel.ric general opening input/output file because: 06/03/2015 17:59:01 [1008:25530]: error: can't open output file "/scratch/anne/Julie_CIVET/nusdast/output/NM2107/logs/NM2107.nuc_inorm_t1.log": Operation not permitted
06/03/2015 17:59:02|worker|mrsdti|W|rescheduling job 208917.1
06/03/2015 17:59:02|worker|mrsdti|W|job 208918.1 failed on host cajal.kimel.ric general opening input/output file because: 06/03/2015 17:59:01 [1008:25538]: error: can't open output file "/scratch/anne/Julie_CIVET/nusdast/output/NM2109/logs/NM2109.skull_removal.log": Operation not permitted
06/03/2015 17:59:02|worker|mrsdti|W|rescheduling job 208918.1
```

Looks like an ownership thing ("Operation not permitted"), but then I tried this: 
```
jp@tesla:~$ sudo -u anne touch /scratch/anne/Julie_CIVET/nusdast/output/CC8323/logs/foo                                                                               
touch: setting times of ‘/scratch/anne/Julie_CIVET/nusdast/output/CC8323/logs/foo’: No such file or directory
```

I'm not sure what the "setting times" part of the error is all about. The folder certainly exists. If I run this same command as anne on any other machine (except cajal) I have no problem creating the file.

**Comment by josephdviviano** [comment]
confirmed happens with all users including root

**Comment by josephdviviano** [comment]
problem is with 'async' flag in fstab -- no problems when replaced with 'sync'.

+ putting in ansible [ ]
+ ansiblizing the computerz [ ]
+ unmounting / remounting cajal external [ ]
+ unmounting / remounting cajal scratch [ ]
+ unmounting / remounting tesla external [ ]
+ unmounting / remounting tesla scratch [ ]

**Comment by josephdviviano** [comment]
k nvm async also works after remount:

I :

+ updated tesla's software (apt-get upgrade)
+ remounted /scratch

testing on cajal to see if updating software is required.

**Comment by josephdviviano** [comment]
All that these partitions need is a remount:

+ sudo umount -l /external
+ sudo mount -a

**Comment by josephdviviano** [comment]
I put some notes here: https://github.com/TIGRLab/admin/wiki/NFS

**Comment by pipitone** [comment]
> I put some notes here: https://github.com/TIGRLab/admin/wiki/NFS

Thanks. Can you reference the issue?

**Comment by pipitone** [comment]
Reopening, as @awheel24 still reports problems, now also with `/opt/quarantine` (I can confirm; similar behaviour as with `cajal`). Remounting doesn't help, but forcing a remount after a lazy unmount does: 

```sh
jp@tesla:~
$ ls -lh /opt/quarantine/modules/quarantine
-r--r--r-- 1 jp kimel 436 Oct  2  2014 /opt/quarantine/modules/quarantine

jp@tesla:~
$ cat /opt/quarantine/modules/quarantine
cat: /opt/quarantine/modules/quarantine: Operation not permitted

jp@tesla:~
$ sudo mount -o remount /opt/quarantine

jp@tesla:~
$ cat /opt/quarantine/modules/quarantine
cat: /opt/quarantine/modules/quarantine: Operation not permitted

jp@tesla:~
$ sudo umount /opt/quarantine
umount.nfs4: /opt/quarantine: device is busy
umount.nfs4: /opt/quarantine: device is busy

jp@tesla:~
$ sudo umount -l /opt/quarantine

jp@tesla:~
$ sudo mount /opt/quarantine

jp@tesla:~
$ cat /opt/quarantine/modules/quarantine
#%Module1.0#####################################################################
blahblah

```

**Comment by josephdviviano** [comment]
I never did the quarantine yesterday so it makes sense that this fixed it. I always was lazy unmounting and remounting.

**Comment by pipitone** [comment]
Anne still reports permissions problems (this time with opening files in `/projects` I believe). She is working around the issue by SSHing to another machine.

**Comment by josephdviviano** [comment]
From 'tesla':

    NFS - state manager: check lease failed on NFSv4 server 'tigrsrv' with ERROR 5.

This was preventing reboot.

**Comment by pipitone** [comment]
I'm closing this until we see more of this shit. I want to believe all it took was an `apt-get update` and a reboot...
