### ISSUE TITLE
Verify the amount of money we can spend from the CFI budget

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#228]
The CFI budget includes "in-kind" monies (heh, monies)... if we want to buy something that doesn't have any "deep vendor discounts" (e.g. this compute server), wat do? 

Specifically, how much money can we spend from the compute server line item on something with no discounts? Is it the entire amount? The entire amount less the in-kind amount? Or do we absolutely need to have in-kind money on the invoice of the thing we're buying? 

This ticket is an adventure. Your mission, should you choose to assign yourself, is to: 
- [ ] Discover who to ask these questions of. One person might be S Powell. If not, you could ask David, or Dielle about who they would recommend (they might also have the answers you seek).
- [ ] Present to this person the CFI budget, and the quotation for the compute server. 
- [ ] Ask the questions. 
- [ ] Get answers. 
- [ ] Report back.

**Comment by josephdviviano** [comment]
I contacted S powerll.

**Comment by pipitone** [comment]
David's figured this out. And basically it doesn't matter for the storage purchase since we're going to put all of it (whatever that figure is) over to them.
