### ISSUE TITLE
FSL GLM gui

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#229]
Hey, I'm trying to use the GLM FSL gui to do some DTI analyses on my TBSS outputs and the gui keeps freezing up on me. I prefer the command line but I'm not sure about the command so I was going to try the gui first and then look at the command line it printed.

**Comment by josephdviviano** [comment]
Can you show me what is happening?

**Comment by mlevesque82** [comment]
The problem is only on Hebb. Ran everything on Tesla with no problems.

**Comment by mlevesque82** [comment]
Yesterday it was fine, today it's freezing up again, but my computer in general is freazing out. I'm running lots of permutations in parallel so that may be the problem.

**Comment by pipitone** [comment]
Closing this. I *think* this had something to do with your Melissa's machine getting hammered on the queue. I rejigged some default job memory settings and that seems to have helped with scheduling fewer jobs there.
