### ISSUE TITLE
NFS is being a jerk

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#230]
Assorted notes:

+ on tigrsrv -- 'groups: cannot find name for group ID 1000'
+ on most machines, permissions are not working properly (e.g., can't execute scripts I own on kimsrv)
+ samba seems to be installed everywhere (why?)

Thoughts:

+ update SW on MRSDTI + RIKER
+ reboot MRSDTI + RIKER

**Comment by pipitone** [comment]
I think this is mostly solved right now, although last night's data run failed because `/opt/quarantine` isn't playing well on riker (I think). Will investigate now.

**Comment by pipitone** [comment]
Yep, `/opt/quarantine` wasn't mounting (nor was it in `/etc/fstab`.. What the... ). Fixed, and I've inserted a one-time call to run.sh in `/etc/cron.d/data` so we'll get today's run going.
