### ISSUE TITLE
MATLAB license server isn't started, and doesn't start with a machine reboot

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#231]
@colinhawco reports: 

```sh
colin@talairach:~$ matlab
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server.
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting:
http://www.mathworks.com/support/lme/R2012b/15

Diagnostic Information:
Feature: MATLAB
License path: /home/colin/.matlab/R2012b_licenses:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2012b/build
/licenses/license.dat:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2012b/build/licenses/netw
ork.lic
Licensing error: -15,570. System Error: 115
```

I think this is due to us rebooting kimsrv/tigrsrv to fix the NFS problems this weekend (#230). 

Let's:
 - [x] [restart the license server](https://github.com/TIGRLab/admin/wiki/matlab-license-server-usage)
 - [x] set it up to always restart the server on reboot (@restart in the crontab or a proper service if possible.

**Comment by josephdviviano** [comment]
OK -- root on tigrsrv now has this line in its crontab

**Comment by pipitone** [comment]
Get out of my way. I'm fixing this.

**Comment by pipitone** [comment]
Undid your tigrsrv change. Added crontab entry in ansible at TIGRLab/ansible-playbooks@e431bde

**Comment by josephdviviano** [comment]
sowwie
