### ISSUE TITLE
Update EA and IM/OB tasks scripts to work with data-2.0

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#237]
Via @josephdviviano:

`dm-proc-ea` & *dm-proc-imob* should take 4 inputs:

​- `experiment-directory` -- top level of the DATMAN project
- `scratch-directory` -- a place to store temporary files
- `script` -- a epitome pre-processing script that analyzes the fMRI data.
- `assets` -- a folder containing required .csv files

​They should be similar / the same as `dm-proc-rest`, which works. (it just does not use an assets folder).​

​The 'assets' folder in this case is always:

    /archive/data-2.0/SPINS/metadata/​design

so you don't need to worry too much about this.

The 'script' in this case should be:

    /archive/data-2.0/code/datman/assets/150409-compcor-nonlin-8fwhm.sh

I might make more of these in the future, but this one will hopefully do the trick in the short term.

The major things that will need to change are:

1. how the input files are found
2. how the behavioural data is found (it is now inside `RESOURCES`).
3. how we handle temporary directories (the only way basicially didnt, but the `dm-proc-rest` script does).

This used to be run from `/projects/spins`. Example outputs can be found in:

    /projects/spins/data/imob
    /projects/spins/data/ea

The code in datman is mostly untouched and *would* work in the old way minus a few cursory changes.

**Comment by pipitone** [comment]
@josephdviviano took this over. Done?

**Comment by josephdviviano** [comment]
I believe this is done. I'm going to reopen it if I'm proven otherwise.
