### ISSUE TITLE
printer toner

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#240]
The printer seems to be out of toner. Do we have any lying around? :)

**Comment by pipitone** [comment]
> The printer seems to be out of toner. Do we have any lying around? :)

We do!  I'll be in shortly and replace it.

Jon.

**Comment by pipitone** [comment]
I lied. We don't *black* toner. I think we replaced that a month ago, so I'm surprised it's down so quickly. I'll order more. Will take at least 24hrs.

**Comment by pipitone** [comment]
I requested two cartridges because we're badass.
