### ISSUE TITLE
CIVET preprocessing error: export: BASH_FUNC_module%%: bad variable name

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#241]
_From @sabashahab on June 17, 2015 13:23_

Hi,

I get the following error message when I'm trying to run the CIVET preprocessing pipeline:

/var/spool/gridengine/execd/cajal/job_scripts/223574: 33: export: BASH_FUNC_module%%: bad variable name

This is in the 'logs' folder of a subject. Most subjects don't have a '.log' file and the ones that do, have the error message right after the "Available SubCommands and Args" listing. 

This is where all the files are stored: /projects/saba/RTMSWM/civet/

Thanks!!

_Copied from original issue: TIGRLab/documentation#1_

**Comment by pipitone** [comment]
Does CIVET continue to run? 

I think this might be a known bug with the modules system. Something similar to this: 

https://github.com/TIGRLab/admin/issues/178#issuecomment-77392434

If it's causing problems with CIVET actually running, that's a different matter...

**Comment by pipitone** [comment]
_From @sabashahab on June 17, 2015 14:13_

The process didn't terminate on the terminal and it showed as 'Eqw' in the queue. And unlike Melissa's earlier post above, all subfolders were empty. 

Entering this on the terminal gave a better error message. It was a "can't open directory" issue: qstat -j jobid | grep error

I changed the permissions of the subject folders in the output folder and now the preprocessing is running.

PS: I was checking my CIVET preprocessing output for another data set and VBM failed (similar to Melissa's post). I don't need it but thought I should let you know about it.

**Comment by josephdviviano** [comment]
#261

**Comment by pipitone** [comment]
Well, I've looked into this `environment-modules` madness some more. For reference, check out [this](https://kb.brightcomputing.com/faq/index.php?action=artikel&cat=2&id=239&artlang=en) and [this](http://stackoverflow.com/questions/10496758/unexpected-end-of-file-and-error-importing-function-definition-error-running).

It looks like the simplest fix I can find is to: 

1. Edit `/usr/share/modules/init/bash` and comment out the line `export -f module`. This stops the `module` function from ending up being passed along by `qsub -V`
2. Set the shell for `main.q` to `/bin/bash -l` (via `qconf -mq main.q`). The `-l` makes the shell a "login"-shell, which means everything in `/etc/profile.d/` gets sourced, including '/etc/profile.d/modules.sh` and `quarantine.sh`. 

et voila...

**Comment by pipitone** [comment]
Er... not quite. Looks like SGE doesn't like `/bin/bash -l` as a login shell.  So... Either people start their scripts with `#!/bin/bash -l` or: 

    source /etc/profile.d/modules.sh
    source /etc/profile.d/quarantine.sh
