### ISSUE TITLE
permissions to copy from data-2.0

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#242]
I'm trying to copy the spins study freesurfer outputs from data-2.0 to my projects folder to analyse them but I don't think I have permission. I'm getting 'cp: omitting directory ‘/archive/data-2.0/SPINS/data/freesurfer/SPN01_CMH_0001_01’ errors.

**Comment by pipitone** [comment]
Hmmm.. Permissions look good to me: 

```sh 
$ ls -lhd /archive/data-2.0/SPINS/data/freesurfer/SPN01_CMH_0001_01/
drwxrwxr-x 12 clevis data 4.0K Apr  9 16:59 /archive/data-2.0/SPINS/data/freesurfer/SPN01_CMH_0001_01/
```

Note the global read/executable permissions on that folder. 

So, this might be related to our recent NFS permissions trouble (see #234). Which machine were you trying to do the copy on? I have a fix I can make that should help if it's #234 at work.

**Comment by mlevesque82** [comment]
Hebb
I tried sudo service nfs-kernel-server restart but I'm not on the "sudoer" file and the incident has been reported. I hope I don't get deported or something.

**Comment by pipitone** [comment]
Agents have been dispatched. You will be deported.

**Comment by mlevesque82** [comment]
Oh man, that really ruins your Monday...

**Comment by mlevesque82** [comment]
So it turns out I'm just an idiot... Closing.

**Comment by mlevesque82** [comment]
So it turns out I'm just an idiot... Closing.
