### ISSUE TITLE
Hebb too slow!

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#243]
My computer is really struggling. It's taking 1-2 minutes to load fslview images! Grrr!!!

**Comment by pipitone** [comment]
I'm sorry. This is my fault. I've tweaked some settings which I hope will make it more fair for your workstation but let me know. 

If this happens again, run: qmod -sq main.q@hebb 

This will suspend all of the jobs running on your machine. 

Jon.

**Comment by mlevesque82** [comment]
Thanks Jon!

**Comment by mlevesque82** [comment]
It's much better now. Thank you!
