### ISSUE TITLE
COGBDY needs to be added to XNAT

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#246]
A few things are up with the COGBDY project: 
- there isn't a project in XNAT, so the upload/extract script is failing. 
- there are some scans not being linked to the proper names (which suggests `scans.csv` needs to be updated): 

    jp@tigrsrv:/archive/data-2.0/COGBDY$ ls data/dicom/ | grep -v COGBDY
    COEBY_CMH_27B037_01_01.zip
    COGBY_CMH_27B034_01_02.zip

**Comment by josephdviviano** [comment]
I fixed it. New project is in COGBDYY because of LOL.

**Comment by josephdviviano** [comment]
![why-so-serious](https://cloud.githubusercontent.com/assets/4142570/8622714/e0beb9e4-26fa-11e5-9de7-17badf6dfaa0.jpg)
