### ISSUE TITLE
new kimsrv vm's 'localadmin

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#249]
+ change ownership of all $UID = 999 items to $UID = 1000

**Comment by pipitone** [comment]
To which items are you referring?

**Comment by josephdviviano** [comment]
like, a lot of them

**Comment by pipitone** [comment]
> like, a lot of them

You can do better than that. :-)

**Comment by pipitone** [comment]
Yo

**Comment by pipitone** [comment]
Can you please explain what this ticket is about?!

**Comment by josephdviviano** [comment]
A huge number of files have UID 999 (for example, a bunch of stuff in quarantine). Producing a full list would take forever. it maybe shouldn't be a ticket because it is too big a problem to resolve in one go (and the group == kimel likely gets around it).

in the dark ages, localadmin was 999 on kimsrv and 1000 everywhere else. when we remade kimsrv, localadmin was moved to 1000.

At least, I think that is what is going on :)

**Comment by pipitone** [comment]
Okay, thank you. Now at least I understand the issue. :-) 

So, historically, you're right, mallar was uid 1000 and localadmin was 999. But, we started to abandon that with the upgrade to 14.04 and mallar leaving. 

kimsrv was, perhaps, the last machine to go (to be honest, I thought we'd changed localadmin's uid on kimsrv too). 

If things are owned by uid 999, then that's quite old. Easily fixed coarsely, e.g. `chown -R localadmin /path`).

**Comment by josephdviviano** [comment]
Yes but this would have to be done basically at /, so anyhow it isnt a worry.
Sorry today has been incredibly busy.

**Comment by pipitone** [comment]
> Yes but this would have to be done basically at /, so anyhow it isnt a worry.

It's not out of the question. We have the following filesystems on
tigrsrv: 

	tigrsrv:~$ mount | grep ext4 | cut -f3 -d' '
	/
	/mnt/projects
	/mnt/archive
	/mnt/home
	/mnt/quarantine2
	/mnt/external
	/mnt/quarantine-nouveau

I *don't* think we have to worry about: home, projects, external, or
really even archive since those are unlikely to have localadmin owned
files. Unless you've seen otherwise. 

That leaves the quarantines. Very do able.

**Comment by pipitone** [comment]
> Yes but this would have to be done basically at /, so anyhow it isnt a worry.

To reset ownerships, I'm running: 

    find /mnt/quarantine-nouveau -uid 999 -exec sudo chown localadmin {} \;
