### ISSUE TITLE
MATLAB is broken because our 'machine code' is new

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#252]
from /opt/quarantine/matlab/matlab_concurrent_all/license_manager/build/etc/glnxa64/license.dat

old:

        SERVER kimsrv 782BCB4506FE 27000000

new:

        SERVER kimsrv 000c2993b765 27000000

but now matlab does not like this new 'machine code' because it conflicts with the 'license key' 
 
        15:44:23 (MLM) Invalid license key (inconsistent authentication code)
        15:44:23 (MLM)  ==>INCREMENT MATLAB MLM 32 01-feb-2016 25533 7F9BFBF2023F \
                VENDOR_STRING=vi=0:at=299:ae=1:lu=200:lo=TA1:ei=1261622:lr=1: \
                DUP_GROUP=UH asset_info=676468 ISSUED=18-Dec-2014 BORROW=720 \
                NOTICE=product=MATLAB SN=676468 SIGN="0029 2FE0 7E8E 1C42 12DE \
                8857 857E D900 EE5B A56A CDCC 22AC 8245 E17E DCD3"

I don't know where this machine code comes from, but I know the new code for our VM is the correct one.

**Comment by josephdviviano** [comment]
Machine code == MAC address minus colons.
Lic file obtained from MATLABs website.
Details in README.

Fixed.

**Comment by pipitone** [comment]
Awesome. I was just thinking that in the future if we have to create a new VM we can set the MAC address to what it is now, and perhaps this will be enough to not disturb the slumbering MATLAB demons.
