### ISSUE TITLE
install a shared zotero library for everyone to collabo on

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#255]
:D

**Comment by edickie** [comment]
making a zotero group might be a better way to do this...
https://www.zotero.org/support/groups

**Comment by pipitone** [comment]
Done: https://www.zotero.org/groups/tigrlab

**Comment by navonacalarco** [comment]
Can someone add the login info to Passpack for this?

**Comment by josephdviviano** [comment]
Hi Navona, sure. I'm looking at this now, and it seems like the owner of the project is

# Pipitone

@pipitone , I've made a zotero account for the lab (username `tigrlab`, password in passpack). Could you make this user the owner of the tigrlab group?

**Comment by pipitone** [comment]
Done.
