### ISSUE TITLE
ansible authentication error

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#257]
I:  

+ added edickie to group sudo on mrsdti
+ ran 'make' in '/var/yp'

Now:

+ edickie's group membership is NOT synchronized with the other machines.
+ I (jdv) am no longer to run ansible.

What, exactly, did I Joseph I wonder?

**Comment by pipitone** [comment]
> + added edickie to group sudo on mrsdti

This will only add edickie to the sudo group on mrsdti. NFS doesn't
propagate groups < 1000  (unless we tell it to). 

> + I (jdv) am no longer to run ansible.

I have no idea. You'll have to post the error message.

**Comment by josephdviviano** [comment]
DO you add users to the sudo group using this?

ansible -kKs -m command -a 'gpasswd -a edickie sudo' -i inventory workstations

Also with ansible I get authentication failures. But I can still SSH around.

**Comment by josephdviviano** [comment]
LOL I forgot to be localadmin.

Why do I need to be localadmin to get this to work, if I have sudo access as jdv on all machines?

PS @edickie  you now have sudo access on all machines.

**Comment by pipitone** [comment]
On 07/13, Joseph Viviano wrote:
> LOL I forgot to be localadmin.
> 
> Why do I need to be localadmin to get this to work, if I have sudo access as jdv on all machines?

You don't need to be localadmin, but you do need to be able to access
the machines without SSH prompting you for anything other than a
password. Use ansible -vvvvv to confirm.

**Comment by josephdviviano** [comment]
Ah, I see, I think it is because, in inventory, everything looks like this:

        kandel     ansible_ssh_user=localadmin

When I run ansible with -vvvvv, it shows that it is trying to log in as localadmin regardless of the user who runs the command. If I enter localadmin's password, not my own, it works OK. This makes sense.

**Comment by pipitone** [comment]
> When I run ansible with -vvvvv, it shows that it is trying to log in
> as localadmin regardless of the user who runs the command. 

Correct. If you want to connect as your user, you need to specify that
on the ansible command line.
