### ISSUE TITLE
Archive HCP processed data from tina r

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#259]
Data is in `/scratch/tina_r/HCP/`. Subfolders with NODDI data is here: `/scratch/tina_r/HCP/folder_list`

All of this data should be copied to `/external/HCP/NODDI`

**Comment by pipitone** [comment]
@tina-roostaei, can you reply with a blurb I can include in the README for this folder that explains what this data is, what your source data was, and how you produced it (i.e. the scripts/steps you used)?

**Comment by pipitone** [comment]
`/external` is almost full. I suggest we create a new filesystem (`/alumni`?) and move David/Matt and Mallar's project folders there for now.

**Comment by josephdviviano** [comment]
+1 on `/alumni'. Particularly for Mallar + Matt. Seems unlikely we have anything they really need at this point.

**Comment by pipitone** [comment]
`vg_volumen1/lv_alumni` has been created. Moved `/external/mallar`, and am in the process of moving `/external/matt`.

**Comment by pipitone** [comment]
I've now copied David's `/external/david` to `/alumni/david`. Also, I've updated the `broten-bkup.sh` script to backup `/projects/david` to `/alumni/david`.

**Comment by tina-roostaei** [comment]
Hi,

I think because external was full a while ago, my HCP folder could not be
backed up there. Do you think it could be backed up now? (I will delete
them from scc if they get copied here).
@Jon: I will provide a README for it soon.

Best,
Tina

**Comment by pipitone** [comment]
Thanks @tina-roostaei. I'm now copying the folders named in `/external/HCP/NODDI/folder_list` from the `/scratch/tina_r/HCP/`folder.

**Comment by pipitone** [comment]
@tina-roostaei Files have copied. Can you double check everything is there? And then yeah, send me the README. :-)

**Comment by tina-roostaei** [comment]
Hi Jon,

Please find attached the README.

Could you please copy the README and the following files/folders to
/external/HCP/NODDI/ :

[/projects/tina_r/softwares/NODDI_toolbox_v0.9_compile/fitting/]:
ThreeStageFittingVoxel.m, batch_fitting_single_grad.m, FSL2Protocol_grad.m

[/scratch/tina_r/HCP/]: run_batch_fitting_single_grad.sh,
batch_fitting_single_grad

[/projects/tina_r/softwares/]: niftimatlib-1.2, NODDI_toolbox_v0.9

Thanks,

Tina

**Comment by josephdviviano** [comment]
Hi Tina, I've copied the files but there is no attached readme I can see?

**Comment by tina-roostaei** [comment]
Thanks Joe. Strange! I'll send it to you directly.

**Comment by josephdviviano** [comment]
Thanks! I added the README :D
