### ISSUE TITLE
add erin to our nightly email extravaganza 

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#260]

**Comment by pipitone** [comment]
Added @edickie to the admins alias on tigrsrv, kimsrv, and backup (see tigrsrv/ansible-playbooks@8d4acf9 for login node aliases). 

@edickie, you'll need to add your preferred email address to ~/.forward on those machines if you want to forward mail to your camh.ca address.

**Comment by edickie** [comment]
p.s. my email is erin.w.dickie@gmail.com

**Comment by pipitone** [comment]
Ah. I think I added your camh email address...

**Comment by pipitone** [comment]
Perhaps another ticket, but we could setup a log aggregator to pile all system logs together and reduce the email spam, or perhaps just send emails with less frequency. If you're all finding it too much. 

Personally, I just love waking up to the servers wishing me good morning.

**Comment by edickie** [comment]
hhhmmm... I'm not getting anything in either address at the moment...

**Comment by josephdviviano** [comment]
Hey Erin,

I added a `.forward`to your home folder on `kimsrv` with your email address in it: 'erin.w.dickie@gmail.com'. Tomorrow you should get a (friendly) email blast.
