### ISSUE TITLE
CIVET and datman are not friends :(

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#261]
So my test run of CIVET is failing at nuc (which is like the second step). The message in the nuc logs is:
cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
	-H|--help		this usage info
	-V|--version		modules version & configuration options
	-f|--force		force active dependency resolution
	-t|--terse		terse    format avail and list format
	-l|--long		long     format avail and list format
	-h|--human		readable format avail and list format
	-v|--verbose		enable  verbose messages
	-s|--silent		disable verbose messages
	-c|--create		create caches for avail and apropos
	-i|--icase		case insensitive
	-u|--userlvl <lvl>	set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
	+ add|load		modulefile [modulefile ...]
	+ rm|unload		modulefile [modulefile ...]
	+ switch|swap		[modulefile1] modulefile2
	+ display|show		modulefile [modulefile ...]
	+ avail			[modulefile [modulefile ...]]
	+ use [-a|--append]	dir [dir ...]
	+ unuse			dir [dir ...]
	+ update
	+ refresh
	+ purge
	+ list
	+ clear
	+ help			[modulefile [modulefile ...]]
	+ whatis		[modulefile [modulefile ...]]
	+ apropos|keyword	string
	+ initadd		modulefile [modulefile ...]
	+ initprepend		modulefile [modulefile ...]
	+ initrm		modulefile [modulefile ...]
	+ initswitch		modulefile1 modulefile2
	+ initlist
	+ initclear

/var/spool/gridengine/execd/crick/job_scripts/254721: 56: export: BASH_FUNC_module%%: bad variable name

Any idea what is wrong or how to fix it?

**Comment by pipitone** [comment]
Can you show exactly what you are running, and how you are submitting this?

**Comment by edickie** [comment]
So the full CIVET command is this:

CIVET_Processing_Pipeline -sourcedir /projects/edickie/analysis/CIVETtesting/SPINS_T1only/input -targetdir /projects/edickie/analysis/CIVETtesting/SPINS_T1only/output -prefix SPN01 -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 -queue main.q -3Tesla -N3-distance 75 -id-file /projects/edickie/analysis/CIVETtesting/SPINS_T1only/logs/id-file-2015-07-21.txt -run

It's getting submitted using datman.utils.run(CIVETcmd) inside a python script

modules loaded (before running the python script) are:
Currently Loaded Modulefiles:
  1) quarantine                           4) datman/edickie
  2) use.own                              5) CIVET/1.1.10+Ubuntu_12.04
  3) python-extras/2.7.9                  6) python/2.7.9-anaconda-2.1.0-150119

Does that make sense?
The error message above I got from the nuc log for one participant:
cat CMH000101.nuc_t1_native.log

**Comment by pipitone** [comment]
Pssst, see #241

**Comment by edickie** [comment]
now they are friends :)

**Comment by pipitone** [comment]
What changed?

**Comment by tina-roostaei** [comment]
I get the same message when I run impute using sge_batch:

cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]
...

What do you recommend?

**Comment by pipitone** [comment]
Ignore this. It shouldn't cause any errors. 
@josephdviviano and @edickie, we could modify sge_batch to `unset module` before submitting the job so that this isn't an issue. Alternatively `source /etc/profile` when the job runs.
On Sep 2, 2015 11:01 PM, tina-roostaei <notifications@github.com> wrote:I get the same message when I run impute using sge_batch:

cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

Usage: module [ switches ] [ subcommand ] [subcommand-args ]
...

What do you recommend?

**Comment by edickie** [comment]
"source /etc/profile" is what I did. Works great. Plus you need it if you
want to load and unload modules within the code of your submitted script.

**Comment by josephdviviano** [comment]
@pipitone @edickie  I'm for unsetting module in sge_batch ... seems like it would conflict less? If I understand correctly, we would need to put `source /etc/profile` in the SUBMITTED job for us to be able to use the module system, which is more of a border case than submitting a job that has no idea what the module system is.

What do you ppls think?

**Comment by josephdviviano** [comment]
#241

**Comment by pipitone** [comment]
See #241. I think we have a fix for this (and it looks like you're using the `source /etc/profile.d/...` trick anyhow. I'm going to close this.
