### ISSUE TITLE
create module for CIVET/1.1.12+Ubuntu_12.04?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#263]
Hey, is the CIVET version 12 module supposed to be 1.1.12 or 1.1.12+Ubuntu_12.04? Right now only a module file for 1.1.12 exists and that version --is very very bad (every single subject fails QC). Is 1.1.12+Ubuntu_12.04 the better build?

**Comment by pipitone** [comment]
On 08/04, edickie wrote:
> Hey, is the CIVET version 12 module supposed to be 1.1.12 or
> 1.1.12+Ubuntu_12.04? Right now only a module file for 1.1.12 exists
> and that version --is very very bad (every single subject fails QC).
> Is 1.1.12+Ubuntu_12.04 the better build?

Hmmmmm.. 1.1.12+Ubuntu_12.04 is an old build. I just recently rebuilt
1.1.12 so I'm curious why it is sucking so badly....

**Comment by edickie** [comment]
That is sad. It suck very very badly

**Comment by pipitone** [comment]
> That is sad. It suck very very badly

Hmm... Perhaps something we can compare with the cobralab. I'll intro
you over da emails.

**Comment by pipitone** [comment]
Okay, I'm closing this specific issue, but @edickie, once you sort out the CIVET madness, perhaps you could write up a wiki page on the http://github.com/tigrlab/documentation wiki?

**Comment by edickie** [comment]
Never use CIVET 1.1.12 - unless through CBRAIN (or maybe gabe's scinet
build)...Done.
