### ISSUE TITLE
Teamviewer not connecting

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#265]
Teamviewer says "Not ready please check your connection". How am I to work? HOW????!

**Comment by pipitone** [comment]
Is this you connecting from the k-lab to QS, or QS to k-lab?

**Comment by colinhawco** [comment]
it resolved. I seem to get this perdiodically. it is from K-lab to QS, and
is not an issue from the QS end (i.e. I cannot teamview in from my laptop).
