### ISSUE TITLE
Where do issues go?

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#267]
For @josephdviviano and @edickie. It seems to me we have a confusing number of places we're filing issues: 
- `admin`: almost anything goes here
- `data`: data issues go here for any study
- `dataman`: data issues go here, plus issues about the datman software itself
- `spins-old`: I have no idea

I'd rather just have a place for general issues, and a place for data issues (not mix datman code and data issues). 

What do you think?

**Comment by pipitone** [comment]
Hmm. Okay, what about this guys: 

 - `admin`: for all issues, except project specific ones (like `datman`). 

We'll use labels to sort issues if needs be. 

What say you?

**Comment by josephdviviano** [comment]
+ I can get rid of spins old -- I'm pretty sure everything has made it into the datman 2.0 spins repo.
+ datman issues should be about the code itself.
+ data issues should maybe go in each study? get rid of the data repo altogether ? many of the data issues won't be resolved immediately, and at the very least this will be the easiest way for the scientists to figure out which subjects are the 'problem' subjects'
+ admin is for all of the systemy stuff.

**Comment by pipitone** [comment]
> + data issues should maybe go in each study? get rid of the data repo
> altogether ? many of the data issues won't be resolved immediately,
> and at the very least this will be the easiest way for the scientists
> to figure out which subjects are the 'problem' subjects'

- The data repo contains the code (master run.sh), README and other
  assets. It can't be gotten rid of atm. 

- My concern around dumping issues into project specific repos is that
  it becomes more difficult to search for issues unless you know the
  study that was involved. That said, that problem is somewhat worked
  around by the github global issue search: 
      https://github.com/search?q=%40tigrlab&type=Issues

  In any case, the "losing track of issues" problem is why I suggested
  one repo + labels. 
  
  I don't have a strong opinion about this though.

- Shouldn't the "problem subjects" be noted somewhere *in* the study
  folder. Perhaps the checklist because it's a consolidated list.
  Sifting through issues to find problem subjects sounds like a pain.

**Comment by mlevesque82** [comment]
In my opinion, the best place for a problem subjects document would be in folders for each project in /archives/data-2.0/*study*/data where people could note any issues they have with specific subjects. Something clearly labelled, like "README.probsubjs" would be appropriate.

**Comment by josephdviviano** [comment]
Melissa's suggestion is a good one in my opinion ... my concern is this stuff ending up in a place the scientists won't see them.

**Comment by pipitone** [comment]
Does anyone have strong opinions on whether issues for data 2.0 studies go into their own separate repositories per study or whether they are kept in one repo (i.e. admin or data)?

**Comment by pipitone** [comment]
Apparently not. 

Let's put all data issues into the admin repo along with our other issues, and label them. 

Issues specifically belonging to a project (e.g. datman, epitome) should live in their respective repos.
