### ISSUE TITLE
SPINS enigma outputs 

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#268]
Tina had helped me run the SPINS study participants through enigma, and I just noticed that two subjects have issues in their FA-to-target images (they have big chunks missing).

The subjects are MRC0004 (around coordinates 118 70 52) and MRC0006 (120 64 50).

I don't know enough about DTI and enigma to fix this. Any ideas?

**Comment by edickie** [comment]
Looks like an epic fail of the betting (brain extraction tool) step during
dtifit...

If you look through the engimaDTI QC folder  - it might be in more that
this subject...

maybe we need a bet qc page for the dtifit pipeline? or we need to adjust
the BET parameters for this project??

What do you guys think?

**Comment by pipitone** [comment]
Yeah I think a QC is in order. 
On Aug 25, 2015 1:27 PM, edickie <notifications@github.com> wrote:Looks like an epic fail of the betting (brain extraction tool) step during
dtifit...

If you look through the engimaDTI QC folder  - it might be in more that
this subject...

maybe we need a bet qc page for the dtifit pipeline? or we need to adjust
the BET parameters for this project??

What do you guys think?

**Comment by pipitone** [comment]
@edickie What came of this? Is there a workaround for the nasty BETing? If not, shall we blacklist these guys?

**Comment by edickie** [comment]
Nothing officially yet - don't blacklist though, it's fixable.

The official solution will be to modify the dtifit pipeline to change the
betting parameters for the MRC site in SPINS ...which will take a bit of
troubleshooting to perfect...

**Comment by edickie** [comment]
Modified the dm-proc-dtifit.py to allow for different options for each site. To activate (once the new datman is pulled) Need to update the dtifit call in teh run script to:

dm-proc-dtifit.py --tag "MRC" --fa_thresh "0.15" --datadir ${PROJECTDIR}/data/ --outputdir ${PROJECTDIR}/data/dtifitdm-proc-dtifit.py --tag "ZHH" --datadir ${PROJECTDIR}/data/ --outputdir ${PROJECTDIR}/data/dtifit
dm-proc-dtifit.py --tag "CMH" --datadir ${PROJECTDIR}/data/ --outputdir ${PROJECTDIR}/data/dtifit

Note: In the meantime, I've been running dtifit with these settings (outputing /projects/edickie/analysis/dtifit_testing/SPINS/). All the QC look qc looks good with these settings!
