### ISSUE TITLE
Clean up old user accounts

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#269]
- [x] Accounts: Matt, Tina, Mikko, Anne(?), Erin's duplicate account :D, Lauren, Ron?
- [x] Move data to /alumni where appropriate

**Comment by MikkoMason** [comment]
I think I'm also on a bunch of mailing lists that you guys can remove me
from...




On Wednesday, 26 August 2015, Jon Pipitone <notifications@github.com> wrote:
> Accounts: Matt, Tina, Mikko, Anne(?), Erin's duplicate account :D,
Lauren, Ron?
> Move data to /alumni where appropriate
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/2xfxAGhPRU7XOdgJTXuDX1vHxb3v0uzIuaqLMSITsl3NVsPkglapJR3MAm82l93s5xPt4rZVceuEQ29dEgsTAognmshlB9zh3nzatJ0vtQuiUDqRbwfteS1yWZBa1jpfvfHRefrOzHVNKVH5tlqr1u3rUkip4g=s0-d-e1-ft#https://github.com/notifications/beacon/AJWe1KJQlMHjQOT2ayxD6Y7BZjHdflijks5orcvWgaJpZM4FynII.gif
>

**Comment by pipitone** [comment]
Removed some of those accounts, nothing to move to `/alumni` just yet. 

Mikko, your aren't on the mailing list, so I suspect you're receiving mail from github only (which only you can change the settings for).
