### ISSUE TITLE
deal with weird run.sh error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#271]
Error 1 while executing: dcm2nii -x n -g y  -o /tmp/tmprvaDD9 /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_260003_01_01/SCANS/0/DICOM
stdout:
>    Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
>    Data will be exported to /tmp/tmprvaDD9/
>    Validating 22 potential DICOM images.
>    Unable to find any DICOM files in the path /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_260003_01_01/SCANS/0/DICOM/STOPPD_MAS_260003_01_01.PR.STOPPD02.0.1.20150424.130339.nf3pam.dcm

**Comment by pipitone** [comment]
I tried `dcm2mnc` and `DWIConvert` and both have no love for us. 

Looking at the headers is just... strange: 
```sh 
$ dcmdump /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_260003_01_01/SCANS/0/DICOM/*.dcm | grep -i descr | sort | uniq
(0008,1030) LO [STOPPD02]                               #   8, 1 StudyDescription
(0008,103e) LO [dReg - WIP DTI_60dir SENSE]             #  26, 1 SeriesDescription
(0008,103e) LO [DTI_60dir]                              #  10, 1 SeriesDescription
(0008,103e) LO [DUAL_TSE]                               #   8, 1 SeriesDescription
(0008,103e) LO [facReg - WIP DTI_60dir SENSE]           #  28, 1 SeriesDescription
(0008,103e) LO [FLAIR_LongTR]                           #  12, 1 SeriesDescription
(0008,103e) LO [MPRAGE]                                 #   6, 1 SeriesDescription
(0008,103e) LO [Patient Aligned MPR AWPLAN_SMARTPLAN_TYPE_BRAIN] #  48, 1 SeriesDescription
(0008,103e) LO [SmartBrain]                             #  10, 1 SeriesDescription
(0008,103e) LO [VWIP MPRAGE SENSE]                      #  18, 1 SeriesDescription
(0008,1080) LO (no value available)                     #   0, 0 AdmittingDiagnosesDescription
(0070,0081) LO (no value available)                     #   0, 0 ContentDescription
```

Not sure what it means to have multiple series descriptions across dicoms in a single series. 

What about, in XNAT, moving this series out of this subject and into a backup?

**Comment by josephdviviano** [comment]
OK I removed those 'images' from the session in XNAT -- should export properly now.
