### ISSUE TITLE
Set up the CAMH FTP server

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#274]

**Comment by djrotenberg** [comment]
Hi Jon. Thanks for noting this. An FTP server is an ongoing and (for many users) very critical requirement and for that reason it's been a major topic of discussion. 

We are planning to configure the storage solution to include this capability, and thereby also solve collaboration issues. 

Let's add/link this to the Scientific Computing github page so we can push it along with the whole team, to make sure this is solved.

**Comment by pipitone** [comment]
Thanks David. I filed this issue to specifically remind me to set up our FTP server on `kimel-web-01`.

**Comment by pipitone** [comment]
Done. `ftptransfer` user can access kimel-web-01 externally. Contact me for IP/port deets.
