### ISSUE TITLE
Integrate Gabe's MAGeTbrain + ANTS rewrite into datman

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#277]
Gabe has put together a working version of MAGeT brain that only requires ANTS, so it should work on both minc and nifti images. It's a bit rough around the edges, but we should give it a try and perhaps send any PRs if we find something to fix up. 

https://github.com/CobraLab/antsRegistration-MAGeT

**Comment by josephdviviano** [comment]
@pipitone is this software ready for us yet, or is it still a buggy bug?

**Comment by josephdviviano** [comment]
I'm closing this until there's an official release of maget.
