### ISSUE TITLE
/archive/data/PNC should be in /external, and needs to be organized

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#293]
_From @josephdviviano on March 16, 2015 17:23_

@dfelsky @awheel24 

To manage our resources, Jon and I would only like to keep pre-processed external data in /archive/data/PNC (which we should maybe move to data-2.0).

I've moving the raw PNC data over to /external/dbgap/pnc_originals/38504 (ugly, I know, we can restructure later when we come up with a unified dbgap naming scheme).

The NIFTI files inside of this raw folder will likely need to be deleted or moved to their own seperate folder.

In general this relates to the issue raised here #3 and here https://github.com/TIGRLab/admin/issues/199. We need to make the dbgap folder in /external well-documented, and only store the processed outputs of pipelines in /archive/data-2.0.

_Copied from original issue: TIGRLab/data#15_

**Comment by pipitone** [comment]
_From @awheel24 on March 16, 2015 21:13_

I have attached an info file that can be included with the PNC data that describes broadly what it consists of and points to some websites and references for more info. 
Perhaps we should move the processed scans that are currently in the raw directory to data-2.0 along with the /processed/CIVET that is still in archive/data/PNC.
Anne

Date: Mon, 16 Mar 2015 10:23:30 -0700

**Comment by pipitone** [comment]
_From @josephdviviano on March 18, 2015 18:56_

Hi Anne,

I've moved dbgab_original into /external.

Will move processed/CIVET into data-2.0.

**Comment by pipitone** [comment]
CIVET data for PNC is currently located in `/archive/data-2.0/PNC/data/CIVET-1.1.0`

@awheel24 Can you please put the write up you have about the PNC data (and any other documentation) into `/archive/data-2.0/PNC/metadata/`? Thanks.

**Comment by pipitone** [comment]
I'm currently rsync'ing `/archive/data-2.0/PNC` `/external`

**Comment by josephdviviano** [comment]
@pipitone:

`/external/PNC/data/rsfc-awheel`contains a lot of intermediate data. I'm going to clear some of it out.

**Comment by josephdviviano** [comment]
OK, I removed all of the intermediate functional files (the only files used for analysis were the `func_volsmooth* data).

**Comment by josephdviviano** [comment]
I've removed the PNC folder from data-2.0.

I've also added some notes to the RSFC component of the PNC data.
