### ISSUE TITLE
STOPPD: Missing Data

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#294]
_From @josephdviviano on March 8, 2015 4:48_

@djrotenberg 

    STOPPD_NKI_120012_02_01		120012_2	2014-09-05	case 
    STOPPD_NKI_120017_01_01		120017	21-04-2014	case
    STOPPD_MAS_220006_02_01		220006	2014-06-13
    STOPPD_MAS_210027_01_01		210027	2014-06-26 
    STOPPD_CMH_410031_02_01		24S024	410031	Case	2015-01-22

_Copied from original issue: TIGRLab/data#12_

**Comment by pipitone** [comment]
_From @djrotenberg on March 9, 2015 17:41_

Hi Joseph,

The scans are located as follows:

STOPPD_NKI_120017_01_01     120017  21-04-2014  case /projects/david/archive/SCANS/STOP_PD_II/New_York/120017_1

STOPPD_NKI_120012_02_01     120012_2    2014-09-05  case /projects/david/archive/SCANS/STOP_PD_II/New_York/120012_2

STOPPD_CMH_410031_02_01     24S024  410031  Case    2015-01-22 /projects/david/archive/SCANS/STOP_PD_II/TO/2015_0122_VH046.zip

STOPPD_MAS_210027_01_01     210027  2014-06-26: In our records this scan was not completed:

Hi All:

     Subject #210027 withdrew consent approximately five minutes into the scan. The scan could not be completed due to the subject’s claustrophobia. I have updated the spread sheet, and uploaded it to the FTP site.

Please let me know if there were any issues with the uploading.

Thanks,
Jessica
Jessica Penny, BS
Clinical Research Assistant
Psychiatry; Center for Psychopharmacologic Research and Treatment
University of Massachusetts Medical School

STOPPD_MAS_220006_02_01     220006  2014-06-13: This scan had an issue with the FLAIR and I recall that I had dealt  with it somewhat differently for QC. I will track this down for us. 

Best,

David

**Comment by pipitone** [comment]
_From @josephdviviano on March 9, 2015 17:56_

Hi David:

RE: `STOPPD_NKI_120017_01_01 120017`, `STOPPD_NKI_120012_02_01`, `STOPPD_MAS_210027_01_01 210027`, great, thanks. Avaiting response on `STOPPD_MAS_220006_02_01`.

I don't think `2015_0122_VH046.zip` is `STOPPD_CMH_410031_02_01`. From our logs (see `/archive/data-2.0/STOPPD/metadata/cmh-stoppd-log.csv`):

    STOPPD_CMH_420029_02_01,2015_0122_VH046.zip,24S022,420029,Case,VH,2015-01-22,X

**Comment by pipitone** [comment]
_From @djrotenberg on March 11, 2015 22:17_

Hi Joseph,

A zipped copy of STOPPD_MAS_220006_02_01 220006 2014-06-13 has bee placed into /projects/david/archive/SCANS/STOP_PD_II/UMass/Rothschild_S220006S02_061322014.zip

**Comment by pipitone** [comment]
To summarize where we're at with this: 

- `STOPPD_NKI_120012_02_01`: Scan data in `/archive/data-2.0`
- `STOPPD_NKI_120017_01_01`: Scan data in `/archive/data-2.0`
- `STOPPD_MAS_220006_02_01`: No data in `/archive/data-2.0`, but we do have `_01_01` and `_03_01`
- `STOPPD_MAS_210027_01_01`: No data in `/archive/data-2.0` 
- `STOPPD_CMH_410031_02_01`: This scan never existed. The data we have is now correctly assigned to `STOPPD_CMH_420029_02_01`

So, from what I can see `STOPPD_MAS_220006_02_01` and `STOPPD_MAS_210027_01_01` are still missing.

**Comment by josephdviviano** [comment]
+ STOPPD_MAS_220006_02_01: 220006  2014-06-13 /projects/david/archive/SCANS/STOP_PD_II/UMass/Rothschild_S220006S02_061322014.zip
+ STOPPD_MAS_210027_01_01: 210027  2014-06-26 -- withdrew from the study. No data to find.

**Comment by josephdviviano** [comment]
STOPPD_MAS_220006_02_01 is in XNAT, so we're done.
