### ISSUE TITLE
MISSING: STOPPD_CMH

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#297]
_From @josephdviviano on March 3, 2015 19:35_

    mriid       subjid                    date
    24S024	410031	Case		2015-01-22 
    24S018	410020	Case		2013-10-09
    24S014	420020	Case		2013-06-03
    460002	N/A	        Ctrl   	2015-02-27

_Copied from original issue: TIGRLab/data#7_

**Comment by pipitone** [comment]
This issue was moved to TIGRLab/admin#296

**Comment by pipitone** [comment]
We have subject `410031` and `420020`, but we are missing `410020`.

**Comment by pipitone** [comment]
I'm going to have unassign myself from this. I'm not sure how big of a deal it is.

**Comment by josephdviviano** [comment]
I just need to find this subject:

```
24S018  410020  Case        2013-10-09
```

**Comment by josephdviviano** [comment]
According to 

`/archive/data-2.0/STOPPD/metadata/scanid_reckoning/raw/cmh-stoppd-log-II.xls`

this subject refused to do the MRI scan due to anxiety. The data was never collected.
