### ISSUE TITLE
Signed XNAT download applet certificate has expired... 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#299]
See: https://wiki.xnat.org/display/WaterCooler/2015/07/16/Dealing+with+expired+signing+certificate+in+the+XNAT+applets

This causes browsers to complain unless you authorize an exception (highly annoying process, especially for non-nerds). The above site has a fix: freshly signed applets for several versions of XNAT including our current version.

**Comment by pipitone** [comment]
Is fix. 

But, we just found [this discussion](https://groups.google.com/forum/#!searchin/xnat_discussion/download$20zip/xnat_discussion/cmzh9Pqc-g8/m-rNWz8XY1IJ) which contains a fix to turn off the Java applet for downloads, and instead just send a zip for download: 
> You can change this configuration from Administer/Data Types.  Choose `xnat:mrSessionData`, then "Edit".  For the `Download Images` action, change the "Name" (first column) to `download` and "Popup" to `always`.  You can also look at `xnat:ctSessionData` for an example.

**Comment by josephdviviano** [comment]
DowNLOADED HERE https://wiki.xnat.org/display/WaterCooler/2015/07/16/Dealing+with+expired+signing+certificate+in+the+XNAT+applets

**Comment by pipitone** [comment]
We did both. Fix applet, remove applet.

**Comment by josephdviviano** [comment]
![here-to-help](https://cloud.githubusercontent.com/assets/4142570/9590383/2d500a4e-5002-11e5-84d7-d8bf285d4cde.jpg)

**Comment by pipitone** [comment]
![oh-thanks-its-very-helpful](https://cloud.githubusercontent.com/assets/509382/9590404/606171b6-5002-11e5-9469-273b6aa7ab18.jpg)
