### ISSUE TITLE
Quarantine FSL FIX

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#3]
Request from Vincent to quarantine [FSL FIX](http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FIX), and he says: 

> I have it downloaded and unzipped the fix package in /projects/vincent/COGBD-project/Software/ (it's the fix1.06 folder). 
> The instructions for installing it are within that folder, in fix1.06/README.txt 

Apparently FIX depends on the MATLAB compiler, which Vincent says: 
>to set up the MATLAB compiler:  (this is also in /fix1.06/README)                          
```
cd compiled/Linux/x86_64                                                                    
cp MCRInstaller.zip /tmp                                                               
cd /tmp; unzip MCRInstaller.zip && ./install                                               
```             
> This will open the MATLAB compiler installer. One thing to make a note of is the installation path for the compiler. Then `open /fix1.06/settings.sh`. Change the variables to match where MATLAB is installed and where the compiler is installed:
```  
FSL_FIX_MATLAB_ROOT= (where the Matlab app is installed)                                      
FSL_FIX_MCRROOT= (where the compiler is installed)                                             
```
> Finally, run `fix1.06/build_MATLAB`

**Comment by pipitone** [comment]
@josephdviviano and I talked, and figure unless we really really need FIX 1.06, let's ditch it and just keep the one joe already set up. @djrotenberg if you're okay with this, go ahead and close this issue.

**Comment by djrotenberg** [comment]
@pipitone and @josephdviviano Sounds good to me!

**Comment by josephdviviano** [comment]
i did it.
