### ISSUE TITLE
Fontconfig error with ImageMagick??

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#300]
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 14: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 23: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 32: out of memory

I'm getting the above error for every QC pic I'm trying to generate (using the montage command from ImageMagick). I think it's only a problem when I use sudo on tigrsrv? Never got it when I was running it on Franklin...

seems like a basic bug...but I thought you guys might know better what to do..
http://askubuntu.com/questions/421891/fontconfig-error-out-of-memory

**Comment by josephdviviano** [comment]
I just removed the offending fonts with 

```
apt-get purge  fonts-khmeros-core
```

Did that help?

**Comment by pipitone** [comment]
If true, let's add to ansible.

**Comment by josephdviviano** [comment]
+1

**Comment by pipitone** [comment]
@edickie Can you suggest a short command to reproduce this error?

**Comment by edickie** [comment]
I'm running the QC scriptts now - no errors!!

**Comment by josephdviviano** [comment]
OK Erin, are you familiar with Anisble? This might be a good opportunity for you to learn how we've got it configured. I can help you if you get stuck! What we want is `apt-get purge  fonts-khmeros-core` to be run on all of our workstations and compute nodes.

**Comment by edickie** [comment]
updated  ansible-playbooks/roles/common/tasks/main.yml to add:

- name: bad software purged  
  apt:  pkg={{ item }} state=absent update_cache=yes
  with_items:
    - fonts-khmeros-core

**Comment by josephdviviano** [comment]
:D
