### ISSUE TITLE
blacklist many fieldmaps

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#301]
+ need to blacklist all scans before 3rd july 2015
+ write check: minimum value is -ve for fieldmaps?

**Comment by pipitone** [comment]
> + need to blacklist all scans before 3rd july 2015

All of which scans? 

> + write check: minimum value is -ve for fieldmaps?

wat.

**Comment by pipitone** [comment]
@josephdviviano Is it all fieldmaps before 3rd July 2015 across all studies at CAMH that need to be blacklisted? 

Can you also be more specific about what the check for a valid fieldmap should be?

**Comment by josephdviviano** [comment]
Sorry, I'll elaborate:

All studies prior to 3rd July 2015 were using a 'faulty' fieldmap sequence. So all of the fieldmaps collected here prior to that date won't give us anything meaningful.

Specifically, either the real or imaginary volume (3rd or 4th, I forget) are all roughly positive. this shouldn't be the case (see here: http://www.allaboutcircuits.com/textbook/alternating-current/chpt-2/polar-rectangular-notation/). So as a rough check, you could see what the minimum value is for the real and imaginary volumes to ensure we have a healthy number of negative values.

**Comment by josephdviviano** [comment]
OK, my solution:

# step 1: find all the fieldmaps and their scan dates

```
#!/bin/bash

cd /archive/data-2.0

# find all fieldmaps
files=$(find -name '*_CMH_*FMAP*.dcm')

# init output file
echo 'filename imagedate' > ~/fieldmaplist.csv

for file in ${files}; do

    # grabs the imageactualdate from header
    imgdate=$(dcmdump ${file} | grep 0009,1027 | cut -d ' ' -f 3 | xargs)

    # convert into something more friendly
    imgdate=$(python -c 'import datetime; print(datetime.datetime.fromtimestamp(float('${imgdate}')).strftime("%Y-%m-%d"))')

    # write this to a file
    echo ${file} ${imgdate} >> ~/fieldmaplist.csv

done
```

**Comment by josephdviviano** [comment]
I'll need to re-do ASDD tomorrow, because we neglected to export the `dcm` files from XNAT for this study. All the rest of the projects are good.

**Comment by josephdviviano** [comment]
OK, I just forced the ASDD project. We should be good.
