### ISSUE TITLE
some dtifit outputs have different voxel size..

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#302]
Hey guys,

I was looking into why some of my dtifit QC pages look weird for some participants and it looks like the voxel size is different for a small subset of the scans. Any reason why this might be?? Do we need to do anything about this?

edickie@franklin:/archive/data-2.0/DTI/CMH/data/dtifit/DTI_CMH_H161_01$ fslinfo DTI_CMH_H161_01_01_DTI60-1000_11_Ax-DTI-60+5_eddy_correct_b0_bet.nii.gz 
data_type      FLOAT32
dim1           128
dim2           128
dim3           74
dim4           1
datatype       16
pixdim1        2.000000
pixdim2        2.000000
pixdim3        2.000000
pixdim4        1.000000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+
edickie@franklin:/archive/data-2.0/DTI/CMH/data/dtifit/DTI_CMH_H161_01$ cd ../
edickie@franklin:/archive/data-2.0/DTI/CMH/data/dtifit$ fslinfo DTI_CMH_H082_02/DTI_CMH_H082_02_01_DTI60-1000_11_Ax-DTI-60+5_eddy_correct_b0_bet.nii.gz 
data_type      FLOAT32
dim1           256
dim2           256
dim3           74
dim4           1
datatype       16
pixdim1        1.000000
pixdim2        1.000000
pixdim3        2.000000
pixdim4        1.000000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

**Comment by josephdviviano** [comment]
OK looking into it -- seems like DCM2NII is causing this as the raw DICOMs have the right dimensions (which is why our header checkers aren't catching the error) ... I'll get back to you with more info soon.

**Comment by josephdviviano** [comment]
Looks like I was wrong, this is an issue with the data itself. Jon found and fixed an error in check-headers. We're going to run it on the data and see what happens tomorrow (I imagine a bunch of errors will be thrown in run.sh...)

**Comment by pipitone** [comment]
Here is a list of headers from DTI/CMH that fail to compare against the gold standard. Which ones should be safely ignored: 
```
AcquisitionMatrix
AcquisitionNumber
Columns
EchoNumbers
EchoTime
FlipAngle
HeartRate
ImageOrientationPatient
ImagesInAcquisition
InPlanePhaseEncodingDirection
PatientAge
PatientBirthDate
PatientSex
PercentPhaseFieldOfView
PerformedProcedureStepDescription
PixelBandwidth
PixelSpacing
ProtocolName
ReconstructionDiameter
RepetitionTime
Rows
ScanningSequence
ScanOptions
SequenceVariant
SeriesDescription
SmallestImagePixelValue
TemporalPositionIdentifier
TriggerTime
```

**Comment by pipitone** [comment]
Examples: 
```
header AcquisitionMatrix, expected = [0, 256, 256, 0], actual = [0, 256, 230, 0]
header AcquisitionNumber, expected = 1, actual = 2
header Columns, expected = 128, actual = 256
header EchoNumbers, expected = 2, actual = 1
header EchoTime, expected = 2.996, actual = 2.988
header FlipAngle, expected = 90, actual = 77
header HeartRate, expected = 301, actual = 373
header ImageOrientationPatient, expected = ['0.998378', '-0', '0.0569396', '0.00506838', '0.996031', '-0.0888682'], actual = ['0.999837', '-0.0180668', '0', '0.018067', '0.999451', '-0.0277718']
header ImagesInAcquisition, expected = 200, actual = 170
headers in standard, not in series: InversionTime
header InPlanePhaseEncodingDirection, expected = COL, actual = ROW
header PatientAge, expected = 000Y, actual = 044Y
header PatientBirthDate, expected = , actual = 19780527
header PatientSex, expected = , actual = M
header PercentPhaseFieldOfView, expected = 100, actual = 90
header PerformedProcedureStepDescription, expected = DTIG1MR, actual = DTIG3MR
header PixelBandwidth, expected = 3906.25, actual = 1953.12
header PixelSpacing, expected = ['2', '2'], actual = ['1', '1']
header ProtocolName, expected = 30.DTIG1MR_2013Oct31, actual = 30.DTIG1MR_2012Jun12
header ReconstructionDiameter, expected = 200, actual = 220
header RepetitionTime, expected = 6.736, actual = 6.708
header Rows, expected = 128, actual = 256
header ScanningSequence, expected = ['EP', 'RM'], actual = ['EP', 'GR']
header ScanOptions, expected = FAST_GEMS, actual = ['FAST_GEMS', 'PFF']
header SequenceVariant, expected = NONE, actual = SS
header SeriesDescription, expected = Ax EPI RestingState, actual = Obl Ax Resting State
header SmallestImagePixelValue, expected = 0, actual = 113
header TemporalPositionIdentifier, expected = 107, actual = 13
header TriggerTime, expected = 99540, actual = 100961
```

**Comment by josephdviviano** [comment]
to keep

header Columns, expected = 128, actual = 256

**Comment by edickie** [comment]
also to keep

header Rows
header Pixel Spacing

**Comment by pipitone** [comment]
keep Erin, Joe, Francisco. Ignore Dan, Colin, Julie.

**Comment by josephdviviano** [comment]
![tumblr_m7brwukwoj1r23csa](https://cloud.githubusercontent.com/assets/4142570/9613338/b9d900cc-50b8-11e5-8caf-eec24e3da32e.png)

**Comment by edickie** [comment]
PerformedProcedureStepDescription might be a keeper

**Comment by josephdviviano** [comment]
ok i keep

**Comment by josephdviviano** [comment]
prelim outputs in /projects/clevis/DTI-headers.md

**Comment by pipitone** [comment]
What was decided about these scans? Are we keeping them but noting in the study README, or blacklisting, or... ?

**Comment by edickie** [comment]
This still apears to be an issue in PACTMD (newest is PACTMD_CMH_0950030_01) 
Should we write something that automatically resamples to the correct size in dtifit??

**Comment by josephdviviano** [comment]
I don't think downsampling the data and treating it the same is a good idea, the SNR of that scan is the square root of what it should be. We should notify Sofia and Nancy if we haven't though

**Comment by pipitone** [comment]
@edickie Will you write to Sofia/Nancy about this?

**Comment by josephdviviano** [comment]
OK -- this thread died but I know for a fact from the folks downstairs that these double-sized images are collected at the **correct** resolution during scanning, they are simply **reconstructed** to the wrong size. They also tell me that this is bound to happen intermittently, for a reason I don't fully understand.

But the key is, the SNR of the data isn't compromised, so we can just reslice this data to the correct resolution OR leave it as is without any real compromise. In some cases (e.g., TBSS) the higher voxel count will hurt the stats of a careless scientist, but in most cases (enigma DTI, UKF, etc) it shouldn't make any real difference at all.

We we have two options:
1) Auto-reslice data that is artificially 8X the resolution
2) Leave it as is, let the scientists deal with it on an analysis-wise basis.

I vote 1. Everyone else?

**Comment by pipitone** [comment]
> 1) Auto-reslice data that is artificially 8X the resolution

+1

**Comment by edickie** [comment]
Auto reslice

**Comment by josephdviviano** [comment]
OK, I'll come up with a little `bro` that will auto-reslice the data. It will:

+ Change the name of the 'super resolution' version to ${FILENAME}_WRONG-RESOLUTION.nii.gz
+ Used AFNI's `3dResample` program to set the grid to the 'correct' size (as determined by a gold standard)
+ Place the resampled file in the `nii` folder with the original filename.

That way, all of our downstream scripts will use this resampled version, but we still have the super-resolution version if we need it for something. Let me know if you have objections!

**Comment by pipitone** [comment]
+1 thanks broseph!

**Comment by josephdviviano** [comment]
@pipitone @edickie behold dm-reslice.py : https://github.com/TIGRLab/datman/commit/36f7b9141abf266445a5c04dedcb7e7391b3cbd6

Example usage here: `/archive/data-2.0/DTI/CMH/bin/run.sh`

I've fixed this in DTI/CMH and PACTMD. We should add this to any other run script that needs it going forward (might also want to re-run enigma  etc for these experiments).
