### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by tina-roostaei** [TIGRLab/admin#303]
Hi, 
I get this error when I submit my job using sge_batch:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
And I think that I specify more than enough RAM for the command using -l mem_free.
I don't get the error when I don't submit and I run the command directly in the terminal.
I would really appreciate if you have any ideas what I should do.

**Comment by josephdviviano** [comment]
Hi Tina, does this happen for all of your jobs, or just for some? I'm pretty sure this is a RAM allocation error, and would want to rule out that it is just some nodes that are the problem.

**Comment by tina-roostaei** [comment]
I'm not sure, but I have seen them failing on talairach, compute01,
davinici... so I think it happens on all of them

**Comment by josephdviviano** [comment]
OK so it looks like the trick was to set `mem_free`,`h_vmem`, and `virtual_free` to all `=20G` in the sge_batch command. This overcomes the thresholds set in the QMON 'complex configuration' page.

Two open questions:

+ Why does it work without these flags with vanilla qsub?
+ Do we really need hard limits on mem_free, h_vmem, and virtual_free? From what little I can gather, it looks like h_vmem OR mem_free would be enough to protect our machines from getting overloaded.

**Comment by pipitone** [comment]
Wait, did you come up with any answers to your questions, or make any changes to the Queue configuration?

**Comment by josephdviviano** [comment]
nope
