### ISSUE TITLE
Hebb very slow

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#305]
Hey guys,
Hebb is very slow, and I don't want to restart it right now because I'm running a job on it. Is there anything else I can do to speed things up? It's taking over a minute to open the file manager. I'm thinking that's not normal...

Thanks for your help!
Melissa

**Comment by mlevesque82** [comment]
Hebb is now making a liar out of me and has sped up considerably. Never mind!

**Comment by tinabehdinan** [comment]
Getting sick and tired of all your lies Melissa...

**Comment by pipitone** [comment]
Blame colin.
