### ISSUE TITLE
add extra ethernet connection between tigrsrv and storage (dedicated to xnat).

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#307]

**Comment by josephdviviano** [comment]
@pipitone could use your advice on this ... looks like the best way to do this would be via a second SAS card + cables for tigrsrv... would need to buy a second part?

**Comment by josephdviviano** [comment]
NVM -- just need a long cable and new IP going from the switch to TIGRSRV, then mount HAL over that new IP address. `Like a BRO`.

**Comment by pipitone** [comment]
Just a heads up, that I've added connections on `eth1` and `eth2`, but haven't configured any machine to mount over them. We could still look into getting a second SAS bro.

**Comment by pipitone** [comment]
I'm going to close this. It doesn't seem like it's urgent or anything.
