### ISSUE TITLE
Upgrade LibreOffice to 5.0

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#310]
For bugfixes and new features. Instructions ([via](http://askubuntu.com/questions/656794/how-to-install-libreoffice-5-0-in-ubuntu)): 

```sh 
sudo apt-add-repository ppa:libreoffice/libreoffice-5-0
sudo apt-get update
sudo apt-get upgrade
```

Resolving this issue means adding the above to the workstation role in ansible-playbooks.

**Comment by josephdviviano** [comment]
This should all be done -- I've manually run 'apt-get upgrade' on all of the machines, and added the appropriate PPA  + cache updating to Ansible.
