### ISSUE TITLE
MISSING: SPINS scans.

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#312]
Hi guys,

So there are 9 subjects listed in the list.csv file for SPINS Yr1 analysis for whom I can't even find dicoms...:-( 6 or these scans were done at CAMH but I can't even find a zips with a header that could be theres in the zips...Any ideas what might have happened??

They are: 
"SPN01_CMH_0006_01" 
"SPN01_CMH_0010_01" 
"SPN01_CMH_0018_01" 
"SPN01_CMH_0019_01" 
"SPN01_CMH_0022_01" 
"SPN01_CMH_0028_01"
"SPN01_MRC_0003_01" 
"SPN01_MRC_0010_01" 
"SPN01_MRC_0018_01"

**Comment by josephdviviano** [comment]
Hi Erin,

The RAs sent us the names of participants who have consented but not been scanned, which led to this confusion.

Are you getting the scans completed emails / scans uploaded emails from xnat? Those make it easy to see which scans were actually submitted to the database.

If you aren't, you should be able to add yourself to the 'email-notifications' field (once for each project in XNAT, unfortunately). Additionally, you will need to add your email to the `~/.forward` file on the xnat server. Let me know if you need help with any of this :).
