### ISSUE TITLE
ANDT  bin/logs file being written to by mistake?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#314]
There's a file called "logs" in the ANDT bin that is making git a bit angry...Is it being written to (by dtifit?) by mistake?

**Comment by pipitone** [comment]
It looks like dtifit output. I suspect this is `dm-proc-dtifit.py`. It has a `--logdir` option that defaults to `logs`, and I'll bet it isn't treating that as a directory but as the log file itself.

**Comment by pipitone** [comment]
This seems fixed.
