### ISSUE TITLE
bvec-compare not writing errors to logs?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#315]
So last night the "correct" arguments were feed to the modified bvec-compare and the errors that we were seeing in the run script have disapeared...completly?? Nothing in the run.sh output - no files in logs/bvec-compare...

Where have the errors gone?

**Comment by josephdviviano** [comment]
I think this is because of what we found today in the checklist.yaml file, where wildcards are being put in the file itself.

**Comment by josephdviviano** [comment]
Is this still a thing?

**Comment by edickie** [comment]
This was resolved with Jon's edits to bvec compare.
