### ISSUE TITLE
weird characters in COGBDY SPRL scannames

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#319]
ln: failed to create symbolic link â€˜/archive/data-2.0/COGBDY/data/nii/COEBY_CMH_27B037_01/COEBY_CMH_27B037_01_01_SPRL_00_20150708-161259-2015-0428-AC027-Restingstate-sprl.niiâ€™: No such file or directory
ln: failed to create symbolic link â€˜/archive/data-2.0/COGBDY/data/nii/COGBY_CMH_27B038_01/COGBY_CMH_27B038_01_01_SPRL_00_20150709-100059-2015-0707-PR031-Restingstate-sprl.niiâ€™: No such file or directory

**Comment by josephdviviano** [comment]
I'm not sure if this is still an issue. We have the following scans linked properly:

    /archive/data-2.0/COGBDY/data/nii/COGBDY_CMH_27B037_01/COGBDY_CMH_27B037_01_01_SPRL_00_20150709-093855-2015-0428-AC027-Restingstate-sprl.nii
    /archive/data-2.0/COGBDY/data/nii/COGBDY_CMH_27B038_01/COGBDY_CMH_27B038_01_01_SPRL_00_20150710-170738-2015-0707-PR031-Restingstate-sprl.nii

I'm going to go ahead and close this.
