### ISSUE TITLE
acessing cluster

### ISSUE THREAD

**Issue by shameis** [TIGRLab/admin#324]
Hi Jon, All worked for accessing cluster as long as I am in projects/stephanie/home
but not if just in projects/stephanie...no ongoing issue, just have to be there I guess. Thanks, S

**Comment by pipitone** [comment]
> Hi Jon, All worked for accessing cluster as long as I am in projects/stephanie/home
> but not if just in projects/stephanie...no ongoing issue, just have to be there I guess. Thanks, S

Hmm.. Okay, tell me more about what you are seeing exactly. You run
tbss_2_reg and ... it exits but nothing shows up when you run qstat? it
exits with an error?

**Comment by pipitone** [comment]
Hi Steph, I'm closing this issue since I don't think it's a problem any longer (given that your `tbss` jobs were running fine yesterday).  Feel free to reopen this if it's still a problem.
