### ISSUE TITLE
GOLGI NIS service `rcpbind` needs to be restarted after full system reboot

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#325]
+ not sure if it is because kimsrv went down, or because we rebooted golgi.
+ resulted in permissions issues and login trouble.
+ `sudo service rcpbind restart`, logging out, logging back in, resolved issue.

**Comment by pipitone** [comment]
I explained this in my email to you -- it isn't specific to Golgi but happened for all machines. Maybe something to do with nscd?

**Comment by josephdviviano** [comment]
I just found your email, i thrw the info in slack.

**Comment by pipitone** [comment]
Based on [this bug report comment](https://bugzilla.redhat.com/show_bug.cgi?id=846767#c27), I tried replacing the nis server name in `/etc/yp.conf` with the server's IP address on `cajal`. I rebooted and nis came up successfully. 

So... I'm not sure why this is a problem now, but this looks to be a fix we can easily add to ansible.

**Comment by josephdviviano** [comment]
I've changed the file `/projects/admin/ansible/ansible-playbooks/files/yp.conf` to contain the IP address instead of the name 'srv-nis'.
