### ISSUE TITLE
Installing Amazon Web Services

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#326]
Hi Guys,

I'd appreciate if you install AWS Command line tools as per the website's instruction: https://aws.amazon.com/cli/

pip install awscli

**Comment by pipitone** [comment]
Actually, you can do this yourself: 
```sh
$ pip install awscli --user
$ ~/.local/bin/aws
```

If you need this with other packages, or want this to be portable across machines, try using [virtualenv](https://virtualenv.pypa.io/en/latest/) to create a python environment in a shared location (e.g. `/projects/arash`):

```sh
$ module load python python-extras
$ virtualenv aws                   # Call the virtual environment whatever you like
$ source aws/bin/activate          # From now on, this activates your 'aws' environment
$ pip install awscli               # Install any packages
$ aws ...                          # do work
$ deactivate                       # jump out of the 'aws' environment

**Comment by arash-n** [comment]
Thanks Jon! 

This is awesome.
