### ISSUE TITLE
Patch VMware vCenter 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#327]
http://www.theregister.co.uk/2015/10/01/vmware_patches/

**Comment by pipitone** [comment]
HOWTO: http://www.vladan.fr/how-to-patch-esxi-5-without-vcenter-and-update-manager/

Patch in: `/projects/admin/esxi/`

**Comment by josephdviviano** [comment]
I'm closing this.

New plan is to:

+ Move everyone off of tigrsrv (get everything on CAMH storage).
+ Virtualize TIGRSRV.
+ Move all services up onto tigrsrv (including XNAT ... need web-facing IP).
+ Convert kimsrv into a compute node install on rack in 107 (no need for virtualization).
