### ISSUE TITLE
HCP 3T Diffusion Preproc

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#328]
Hi guys,

I was going to ask if you could move the HCP diffusion folder that I downloaded on SCC to KIMEL. But I just found that the /external/HCP/3T_Diffusion_preproc is no longer empty. I was wondering if you could grant us read access to all of the subdirectories.

Cheers,
Arash

**Comment by pipitone** [comment]
I've made that folder readable. How is the data there different from the
stuff you've downloaded on the SCC?

**Comment by arash-n** [comment]
It is exactly the same. There are just some empty folders in the ones that I downloaded from SCC.

**Comment by josephdviviano** [comment]
Is this finished?

**Comment by arash-n** [comment]
It turned out that I downloaded it for no reason. For some reason I couldn't see inside of the HCP folder for diffusion data. But, if you want to download anything from HCP let me know. I downloaded the diffusion data in 4-5h with SCC's ftp (~500GB).

**Comment by josephdviviano** [comment]
Awesome! We should look into some of the task data if we can generate a good hypothesis. I'm going to close this issue.
