### ISSUE TITLE
Eigen 3 library

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#329]
Hi again,

I was wondering if you can install eigen 3 library on all machines. I already have this on Golgi and used it to install some of the new functions of MRTrix for multi-shell DWI analysis (https://github.com/MRtrix3/mrtrix3/tree/updated_syntax). 

sudo apt-get install libeigen3-dev

Cheers,
Arash

**Comment by pipitone** [comment]
Hi Arash, 

If MRTrix is something you'll be making good use of, I could make a
quarantine module for it. Do you have build instructions? 

Jon.

**Comment by pipitone** [comment]
In any case, we can install libeigen3-dev on the machines also.

**Comment by arash-n** [comment]
We already have the older version which is pretty much uptodate. The newer version is an alpha version and I don't think it is worthy of installing on all machines at current stage as it is being updated every week. But it would great if you could install libeigen3. Once the new version is finally released I'll let you know. I think that would be a great addition.

Cheers,
Arash

**Comment by josephdviviano** [comment]
I'm closing this because I'm pretty sure it has been installed everywhere.
