### ISSUE TITLE
XNAT emails are not being sent :(

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#330]
Even though we have email users defined for each project.

**Comment by pipitone** [comment]
Which emails specifically?

I think I just fixed the pipeline emails over in #337. Remember to use `kimsrv` as the smtp host, and `admins@kimsrv.kimel.ric` for the admin email.

**Comment by pipitone** [comment]
Looks like we're getting emails now from the pipeline via #337.
