### ISSUE TITLE
MATLAB cluster

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#333]
Hi Guys,

Although it has been a while that we have had MATLAB parallel toolbox. We have never actually set it up so that we can submit jobs within MATLAB to the cluster. This would be a great help for NODDI and Yogesh's RBF scripts.

Cheers,
Arash

**Comment by pipitone** [comment]
I agree it would be a good thing to have. Setting this up is complicated by the fact that the MATLAB cluster has to play well with the compute cluster scheduling. I can imagine a scenario where you first submit jobs that reserve machines to be used by MATLAB and then fire up MATLAB servers on those machines. Or we could go lo-fi and just have you remove workstations from the queue and run MATLAB yourself. As long as you let everyone know beforehand this could work. 

We also need to think about licenses: we only have three I believe. 

Actually my preference would be not to implement anything like this and instead have you use the SCC for things like this. It's bigger and doesn't directly impact lab members when things go awry. 

Perhaps shoot an email over to David asking about setting this up on the SCC?

**Comment by djrotenberg** [comment]
Hi Arash,

We do have 25 concurrent Matlab licenses on the SCC, each with a parallel toolbox. The typical strategy is to call Matlab from the submission script, and use the parallel toolbox to use the available processors on each compute node. 

We are about to order additional toolboxes for both our CAMH and SCC Matlab licenses in case you might need them. So let us know if there is a particular toolbox you need and we can include it in our order.

David

**Comment by arash-n** [comment]
Hi David,

I just noticed that there is no Optimization toolbox on the SCC MATLAB. Is
it possible that we can get the toolboxes some time very soon?

Cheers,
Arash

**Comment by djrotenberg** [comment]
Hi Arash,

Yes.The Optimization toolbox is to be included with the toolbox order. I should be able to provide you with a definite time when this will be procured by the end of this week. 

David

**Comment by arash-n** [comment]
Most of my jobs are done. I enabled the following hosts:

qmod -e main.q@mansfield (cajal, franklin, talairach, milner, compute01)

Cheers,
Arash

**Comment by pipitone** [comment]
I'm going to close this. We've been able to run MATLAB on the tigrlab cluster, and the SCC will get upgraded licenses soon enough.
