### ISSUE TITLE
Some multishell DTI images are being blacklisted, but are actually okay

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#334]
@arash-n tells us that some of the subjects' multishell scans we've blacklisted are actually okay to use, or at least to have exported but flagged as "different". Specifically, the scans which have directions that span the entire sphere are okay to use (at least with NODDI) so we should export them, but perhaps give them a different tag. 

Arash will reply with a few example subjects that we've blacklisted but are okay to use.

**Comment by arash-n** [comment]
These participants have different bvecs and are fine:
H023
H030
H033
H044
H053
H055
H069
H085
H089
H102
H103
H160
H161
H162
H163
S026
S029
S032
S034
S035
S037
S045
S152
S153
S156
COGBDO:
208709
208975
209455
209647
214790
215103
215501
215532
215551
216844
216866
216921
216948
COGBDY:
27B001
27B003
27B004
27B005
27B006
27B009

**Comment by josephdviviano** [comment]
OK, I de-blacklisted these scans. I've copied the names of them into the README for each project, so if people are trying to use Yogesh's compressed sensing techniques, they will know to avoid these participants, but the pre-processed data should be available next week for analysis.
