### ISSUE TITLE
nvidia-smi hangs on hopper

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#335]
+ will test if reboot fixes
+ if so, might want to rebuild driver (https://devtalk.nvidia.com/default/topic/821372/nvidia-smi-hangs-when-run-during-bootup-to-create-dev-nvidia-files-with-346-46-and-fermi-tesla-gpu/)

**Comment by josephdviviano** [comment]
I'm guessing, @nikhil153, that a reboot fixed this?

**Comment by josephdviviano** [comment]
Did you get to the bottom of the problem? I.e., do I need to bother rebuilding the kernel?

**Comment by nikhil153** [comment]
I had reinstall cuda but looks okay for now. Thanks!
