### ISSUE TITLE
XNAT pipelines still aren't working (forever queued state)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#337]
I'm not really sure what's going on. What I do know:

+ Pipeline Installation Location in 'configuration' of the xnat GUI is set to `/data/xnat/pipeline/`.
+ `PIPELINE_CATALOG_ROOT_PATH = /data/xnat/pipeline/catalog/` is set in `/data/xnat/pipeline/pipeline.config`
+ The paths of the pipelines in Administer -> Pipelines of the XNAT GUI are correct.
+ The permissions of the `.jars` in  `/data/xnat/pipeline/lib` are all (roughly) correct.
+ The `xdat.pipeline.modules.locations=/data/xnat/modules/pipeline` defined in `/data/xnat/src/xnat-1.6.5/build.properties` does not exist. I don't know what these modules are for.
+ There are no users defined in `/etc/tomcat7/tomcat-users.xml`, but the tomcat user should be `xnat`.

**Comment by josephdviviano** [comment]
**halp plz**

**Comment by pipitone** [comment]
> Assigned #337 to @pipitone.

Will do. Anything I should know about how these things are setup, or
changes you've made to XNAT since the install?

**Comment by josephdviviano** [comment]
Everything I know is in the original post. I've changed stuff, as indicated above (but I haven't re run the install scripts or anything). I may have also corrected some permissions here or there.

**Comment by pipitone** [comment]
Thanks. I'm working on it now... 

![Get ready for a suprise](http://4.bp.blogspot.com/-Q4bn7stgH7I/VWyYjrCEL1I/AAAAAAACutg/n_xeYoODnws/s1600/total%2Brecall%2Bhead%2B2.gif)

**Comment by pipitone** [comment]
Okay. I think this was just a matter of fixing the settings in `/data/xnat/pipeline/pipeline.config`. Namely, the admin email addresses and smtp host weren't set correctly.

Having changed those, I can now run `XnatPipelineLauncher` from the command line (as the `xnat` user). See `/var/lib/tomcat7/webappgs/xnat/logs/pipeline.log.*` for more info.

**Comment by pipitone** [comment]
I'm going to see about re-running all of the autorun pipelines that have failed. 

Also, it looks like xnat is attempting to use a rotman mailhost in autorun (`grep rotman /var/lib/tomcat7/webapps/xnat/logs/pipeline*`). ;-)

**Comment by pipitone** [comment]
@josephdviviano If there is a way to force the autorun pipeline to re-run, you may want to do that. 

Failing that, you can run: 

```bash
cd /var/lib/tomcat7/webapps/xnat/logs
grep -o XnatPipelineLauncher.* | sed 's#^#/data/xnat/pipeline/bin/#g' | sudo -u xnat parallel -j1
```

**Comment by pipitone** [comment]
Looking good. Closing.
