### ISSUE TITLE
Clean up and archive recent alumni data :-(

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#340]
Specifically: 
- [ ] `/projects/anne`
- [x] `/projects/julie`
- [x] `/projects/tinab`

I suggest we sort through what is there, document the important stuff, and move it to `tigrsrv:/mnt/alumni`

**Comment by pipitone** [comment]
Updation: I'm not sure about moving anne's stuff just yet, but I've moved `julie` and `tinab`'s data.

**Comment by josephdviviano** [comment]
@pipitone where are we at with this? Looks like we have a lot of stuff in `/alumni`.

**Comment by josephdviviano** [comment]
Alumni partition is full, waiting for Anne and Julie to finish working so we can finally remove their projects folders. This will need to wait until we have the storage solution in place with CAMH, since we're low on space.

**Comment by josephdviviano** [comment]
@pipitone  update?

**Comment by pipitone** [comment]
@jdv same. Syncing /alumni to camh storage, #475, and then we can fold in julie's stuff and anne is going to do a final clean up of her stuff.

**Comment by pipitone** [comment]
Okay, I'm syncing anne's projects folder to alumni/ on tigrsrv. It's running in tmux session on tigrsrv as admin. 

    sudo rsync --delete --info=progress2 -a /projects/anne/ /mnt/alumni/anne

Next steps: 
- [ ] Sync /mnt/alumni/ to /mnt/tigrlab/alumni
- [ ] Remove /projects/anne
- [ ] Remove backup:tank/projects/anne

**Comment by pipitone** [comment]
Done.
