### ISSUE TITLE
Hopper is down / not reachable via ssh

### ISSUE THREAD

**Issue by nikhil153** [TIGRLab/admin#343]
Noticed this since last night (29th Nov). 

```
Last login: Mon Nov 30 01:18:42 2015 from cpe50395563c412-cm50395563c40f.cpe.net.cable.rogers.com
nikhil@kimsrv:~$ ping hopper
PING hopper.kimel.ric (172.25.9.110) 56(84) bytes of data.
From kimsrv.kimel.ric (172.25.9.60) icmp_seq=1 Destination Host Unreachable
From kimsrv.kimel.ric (172.25.9.60) icmp_seq=2 Destination Host Unreachable
From kimsrv.kimel.ric (172.25.9.60) icmp_seq=3 Destination Host Unreachable
^C
--- hopper.kimel.ric ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4024ms
```

**Comment by pipitone** [comment]
Confirmed. The machine is running happily, and the network looks to be up. Can I reboot?

**Comment by nikhil153** [comment]
Yup go for it!

**Comment by pipitone** [comment]
Restarted. @nikhil153 can you check the system logs to see what happened?

**Comment by nikhil153** [comment]
Couldn't find anything specific in the syslogs. Also now we are having problem with nvidia / cuda as the terminal hangs every time you query with nvidia-smi.. This has happened before - which I thought was fixed with cuda update + reboot. Doesn't seem like that quite worked.

**Comment by josephdviviano** [comment]
Looks like it was getting stuck at the GRUB screen for some reason, it was waiting there for manual input. I edited `/etc/defaults/grub` to auto-select Ubuntu and then ran `sudo update-grub`.

It now reboots cleanly. We've left the monitor and keyboard plugged in so the next time hopper acts up we can have a look at what the computer is doing.

**Comment by nikhil153** [comment]
So far things are working well. Closing the issue. Thanks!
