### ISSUE TITLE
functional steps in data-2.0 run.sh scripts should not block

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#344]
Via @edickie. Currently the `dm-proc-imob.py` (and maybe also the `ea` and `rest` steps) will submit some jobs and wait until those jobs are completed before letting the `run.sh` script complete. This is especially a problem when, as has been happening recently, the submitted jobs error out, but the `run.sh` still blocks.

**Comment by josephdviviano** [comment]
Yes this is very bad. I'll sync with you now but put it on my todo (I have to do some other things first).

**Comment by pipitone** [comment]
Keeping notes here. Looks like these scripts all call `datman.utils.run_dummy_q` which calls `echo sleep 30 | qsub -sync y -hold_jid <list of job names>` which holds until *all* the jobs in the list *complete*. 

What does "complete" mean? From the `qsub` man page for `-hold_jid`: 
> The submitted job is not eligible for execution unless all jobs referenced in the comma-separated job id and/or job name list have completed. If any of the referenced jobs exits with exit code 100 [failed to start], the submitted job will remain ineligible for execution.

So: only jobs that fail to start should cause a dependent job to block.

**Comment by pipitone** [comment]
[Here](http://comments.gmane.org/gmane.comp.clustering.gridengine.users/18327) is a discussion on ways of dealing with jobs that depend on jobs that are in an error state. 

I think in the case of the `dm-proc-*` scripts, if the jobs being waited on go into an error state, the script should bail at that point. To make that happen we'll probably need to rewrite `run_dummy_q` to do some busy waiting: check the state of the jobs every `n` seconds and exit with a success/fail depending on whether all jobs completed successfully or not?

In any case, the quick fix I'm going to suggest is that in the `run.sh` script we stick `sge_batch` in front of all the `dm-proc-{imob,ea,rest}.py` scripts to force them to be submitted to the queue. That way they won't hold up the `run.sh` script. 

The better fix is to re-engineer the proc scripts to submit a bunch of dependent jobs and then immediately exit -- no using `run_dummy_q` themselves.

**Comment by pipitone** [comment]
(Not to mention, figuring out why the preprocessing stages are erroring out.) :8ball:

**Comment by pipitone** [comment]
Debugging this is taking some time. In the interim I've disabled functional pipelines in all of the `run.sh` that have them. I'm also triggering a full run now, so we should get an update email by morning. :-)

**Comment by pipitone** [comment]
I've fixed the `qsub` use in `dm-proc-{imob,ea,rest}.py` scripts, and I'm working to enable the functional steps in all of the `run.sh` scripts now.
