### ISSUE TITLE
Install freesurfer 5.3.0-HCP

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#346]
What @arash-n wants, @arash-n gets. And @arash-n wants this: 
http://ftp.nmr.mgh.harvard.edu/pub/dist/freesurfer/5.3.0-HCP/

The trick is that it depends on netcdf v6 so we'll need to find the ubuntu builds somewhere and unpack them into the quarantine (or build from scratch).

**Comment by arash-n** [comment]
:dancer: 
Thanks!!!

**Comment by pipitone** [comment]
Done. According to the README that comes with the HCP freesurfer, only `mris_make_surfaces` has changed. Therefore, what I've done is made the `freesurfer/5.3.0-HCP` module only contain this file and the `netcdf-4.1.1` library and it *depends* on `freesurfer/5.3.0` being loaded for all of the other freesurfer goodness. 

Actually if you load `freesurfer/5.3.0-HCP` it automatically loads `freesurfer/5.3.0` for you. 

Please let me know if this works.

**Comment by arash-n** [comment]
:dancers: 

Awesome!!!
