### ISSUE TITLE
Have xnat send mail via a proper mail server :)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#347]
B/C right now we're basically spamming the internets.

**Comment by pipitone** [comment]
Also, generally our outbound mail has been shutdown by the RIC. I'm working to get us accounts on the RIC network we can use to send mail from. 

In the meantime, check `tigrsrv:/tmp/data-2.0-run.log` for the nightly run.sh logs.

**Comment by pipitone** [comment]
I've moved the logs to `/archive/data-2.0/logs/` to make them easier to get access to.

**Comment by pipitone** [comment]
Update on email via the RIC server. I've updated the email configuration so far on the [XNAT wiki page](https://github.com/TIGRLab/admin/wiki/XNAT#mailserver-settings). 

I've sorted out settings that let XNAT connect and authenticate with the server. I *think* things may be set up reasonably correctly, except I'm getting the following error in `xdat.log` when sending is attempted: 

    com.sun.mail.smtp.SMTPAddressFailedException: 553 5.7.1 <redacted@redacted>: Sender address rejected: not owned by user xtigrlab

(where `redacted` is usually @josephdviviano email's address, unless I try to send something through email interface, in which case it's my address).

I suspect what's happening is that XNAT has been configured to use joe's email address as the sender's address, and the RIC mail server doesn't like that. I've changed the senders address in `services.properties` to what it should be -- and I thought this was supposed to change the sender's address -- but I can see it was originally set in `build.properties` as Joe's email address so I imagine it's recorded in the database some place.

**Comment by pipitone** [comment]
Fixed. All it took was setting the administrator email address in the Configuration panel. I also changed the administrator email in `InstanceSettings.xml` as well. 

Note, I suspect that most of this will be preserved if/when xnat is rebuilt, because I've updated `build.properties` with the appropriate settings.
