### ISSUE TITLE
_nrrdEncodingRaw_read error

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#349]
The error I am getting in MATLAB is:

_nrrdEncodingRaw_read: WARNING: finished reading raw data, but file not at EOF

I am trying to open new.nhdr files in /projects/arash/RBF/diff/bvec2/ subfolders. Except for the first folder (214790), others that I have tried give me this warning when I am running the submit_script.sh (which in turn calls submission.m command) inside folders.

Cheers,
Arash

**Comment by pipitone** [comment]
I don't recognize the error. EOF stands for end of file, so it like the warning is that the file is longer than expected. Could be a problem with a header with an incorrect file length. Might be something to talk with the Boston folk about.

**Comment by arash-n** [comment]
Oh that makes sense. I'll take a look. 
#WordsOfWisdom

Thanks,
Arash

**Comment by pipitone** [comment]
What was the resolution?

**Comment by arash-n** [comment]
There was an error in making the new nhdr files. It basically has two parts the upper part has image dimensions and other header information and could change slightly between subjects. The lower part is DWMRI_gradients that should be the same. I was using wrong upper parts of the nhdr.
