### ISSUE TITLE
RIC connectivity issue

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#350]
Interestingly, I can ssh **in** to kimsrv from MARS...

**Comment by pipitone** [comment]
U of T has blocked outgoing traffic due to suspicious activity (a windows Trojan virus). This may take some time to resolve. :-)

**Comment by josephdviviano** [comment]
For all of U of T! Wow

**Comment by pipitone** [comment]
No just the pet centre. Yay!
