### ISSUE TITLE
XIO:  fatal IO error 11 (Resource temporarily unavailable) 

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#351]
Hi,

I am running wm_cluster_atlas.py from the whitematteranalysis module and this error message showed up:

XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 59 requests (59 known processed) with 5 events remaining.

I'm not sure how to fix this. Can I get some help?

**Comment by josephdviviano** [comment]
Hi Saba,

Are you shelled into another machine, or are you doing this on your local machine?

**Comment by josephdviviano** [comment]
(by that I mean, are you running SSH).

**Comment by sabashahab** [comment]
I'm not running SSH. I'm using Cajal at the lab.

**Comment by pipitone** [comment]
Check wm_cluster_atlas.py --help. You probably want to run
wm_cluster_atlas.py with the -norender option if you're using it in jobs
you are submitting, or if you are using over a X forwarded ssh
connection.  Without it, wm_cluster_atlas.py attempts to pop-up display
windows as it works.

**Comment by sabashahab** [comment]
Thanks Jon and Joe. I ran the same code again and it ran to completion. I was just running it on my machine, not submitting jobs so I suppose the pop-up displays weren't a problem this time. I'll keep the -norender option in mind in case I run the job on SCC or remote access next time.
