### ISSUE TITLE
Recent upload to SPINS was the MRS data from STOPPD_CMH_460004_01_01

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#352]
Have a look:

http://da55.pet.utoronto.ca:5004/app/action/DisplayItemAction/search_element/xnat%3AmrSessionData/search_field/xnat%3AmrSessionData.ID/search_value/TIGRlab_E00135/popup/false/project/SPINS

I'm guessing the wrong file was placed into the SPINS folder downstairs somehow. I'm mostly posting this to confirm it isn't a problem with @pipitone 's scripts running downstairs, otherwise we can just move the data and treat it as a fluke.

**Comment by pipitone** [comment]
> I'm guessing the wrong file was placed into the SPINS folder downstairs somehow. 

Looks like it to me. Worth an email to Nancy I think.

**Comment by pipitone** [comment]
Actually, just looking at the nightly logs and *lots* of bogus looking zip files were downloaded. Go to `tigrsrv` and run `grep MRSROI /tmp/data-2.0-run.log`.

**Comment by josephdviviano** [comment]
I don't think these files are bogus per se, but I'm not sure how to handle these files gracefully as they are DICOM data from the same session... I guess we could manually enter them all into `scans.csv` as a second (or third) repeat scan for the associated MRI data, but that seems both tedious, time consuming, and non-urgent.

I've sent an email to Nancy to see what these files are. We could ask for them to be removed downstairs, or merged into the zips containing the MRI data. That way, we could re-upload all of the STOPPD and SPINS files with the MRS data intact, similar to what I've just done for RTMSWM.

**Comment by pipitone** [comment]
Ah, sorry. I actually asked Nancy this but forgot to update this ticket. IIRC these are preproccessed MRS data (which if we use we are supposed to cite someone else's work). I'll dig up the email from Nancy but in the future these additional series will be included in the scan zips.

**Comment by pipitone** [comment]
Actually Nancy cc'd you both, Joe and Erin, on the reply about the MRS zips. Check it for more info.

**Comment by josephdviviano** [comment]
Nancy's reply:

See #1 below

> They will be in the study folder -  Naming convention is as outlined in the pdf for future acquisitions.
>cheers
>nancy

> On 12/14/2015 1:56 PM, Jon Pipitone wrote:
> A follow up question: will future exams have these masks included in the exam
> zip, or will they continue to appear as a second MRSROI.zip file?
>
> Jon.
>
> From: Nancy J. Lobaugh, PhD
> [nancy.lobaugh@camhpet.ca] Sent: December 14, 2015 1:26 PM To: Jon Pipitone
> Cc: Joseph Viviano; Erin Dickie Subject: Re: *_MRSROI.zip in STOP1MR ftp
> folder
>
> All PIs were notified last week.. two items may impact on your data
> analyses, hopefully Aristotle has forwarded the info to you, but in case
> not:
>
>> 1) Spectroscopy.  We now will be including masks of your MRS voxels with
>> your processed data. This is possible thanks to the generosity of one of
>> Dr. Sailasuta's colleagues. All MRS data from 2011 have been processed,
>> and should be available for download after tonight's zip and push to the
>> sFTP server. Information about how the data are organized is attached
>> (MRS_ROImasks.pdf).
>
>> 2) "Scheduler".  We have contracted with Calpendo/Exprodo to build an
>> interface for us that will serve as an upload site for new projects and as
>> a scheduler. Our preliminary tests with the software platform last month
>> indicate that it is a flexible, reliable system that will meet the needs
>> of CAMH.  It will be initially rolled out for MRI, but will be expanded to
>> other units during the spring.  There will be two training sessions
>> scheduled for late January 2016. The first will be directed to PIs and Lab
>> Managers and will focus on uploading documents for new studies.  The second
>> will be directed to Lab Managers and RAs and will focus on how to book and
>> cancel studies (PIs are also welcome to attend).  I will send announcements
>> once the new system is fully tested.
>>
>> 3) spiralIO fMRI studies. We have recently noticed a high spatial
>> frequency artifact that has no specific temporal frequency (i.e., there is
>> no regular temporal pattern to the artifact). This artifact only appears in
>> brain, not our phantom QA, possibly in only ~10% of studies and can be very
>> subtle. The artifact has been present since the upgrade to DV24 in November
>> 2014. A short animated visualization of the artifact is attached as
>> SpiralNoise.gif.  We are in contact with Dr. Glover at Stanford and other
>> sites using his pulse sequence. To date, no one we have talked to has
>> reported any effect on data analysis. To help us troubleshoot the artifact
>> with Dr. Glover, and determine its significance, please let us know if you
>> have seen any impact of this noise pattern on your data analyses.
>
>
> On 12/14/2015 12:24 PM, Jon Pipitone wrote:
>> Hi Nancy,
>>
>> How are you doing?
>>
>> So, it looks like on Dec 4, last week, a bunch of new zip files appeared
>> in the STOP1MR folder for both new and old scans. These have MRSROI in the
>> filename rather than the patient name, and contain dicoms for the MRS
>> acquisitions. I'm trying to figure out what these are exactly.
>>
>> Should we be replacing our old acquisitions with these or were these zip
>> files mistakenly uploaded? Sorry if I'm out of the loop and you've already
>> notified our group about them.
>>
>> Thanks! Jon.
>>
>
> -- Nancy J. Lobaugh, PhD

**Comment by josephdviviano** [comment]
Turns out @pipitone fixed this ages ago for STOPPD. We shouldn't get any more scans that look like this, so we won't need to continually map these to repeat 00, and all of the 35 scans found were linked correctly.
