### ISSUE TITLE
STOPPD MAS scans haven't been exporting from XNAT

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#354]
We haven't downloaded a STOPPD MAS scan to our system since Oct 1...(when we upgraded XNAT??)

There are 7 subjects in XNAT who are not in data-2.0...Any idea what could be causing this?

**Comment by josephdviviano** [comment]
Are their exports defined in run.sh and are they named correctly in xnat at
both the subject and session level?

**Comment by edickie** [comment]
The file naming looks right to me...

**Comment by josephdviviano** [comment]
Are they explicitly being exported in run.sh? Can you run it at clevis and
see what it says?

**Comment by pipitone** [comment]
I'm looking at `/tmp/data-2.0-run.log` and there's an exception being thrown during export. That would do it. ;-)

```sh 
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 401, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 184, in main
    extract_archive(exportinfo, archivepath, datadir, blacklist)
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 230, in extract_archive
    exportdir, blacklist)
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 241, in export_series
    mangled_descr = dm.utils.mangle(description)
  File "/archive/data-2.0/code/datman/datman/utils.py", line 79, in mangle
    return re.sub(r"[^a-zA-Z0-9.+]+","-",string)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

Looks like there may be some wackiness in one of the subject's DICOM description field. I'll check it out.

**Comment by pipitone** [comment]
Can reproduce with `xnat-extract.py -nv /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_210036_01_01/`.

**Comment by pipitone** [comment]
Turns out it's series 0 causing the problems. Folder: `/mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_210036_01_01/SCANS/0/DICOM/`

The issue is that the dicom file picked to get headers representing this series, doesn't have a `SeriesDescription` field, which is causing the mangle code to b0rk.

**Comment by pipitone** [comment]
I've made a fix to `utils.mangle()` to handle this case. Generally our code doesn't do a great job of checking the fields coming from the dicom headers to make sure they are sensible (or even, as in this case, strings). I've filed tigrlab/datman#44 to go back over the code and this sort of stuff up.

**Comment by pipitone** [comment]
I've updated the datman code in `/archive` and I've verified that `xnat-extract.py` runs cleanly (with the `--dry-run` option on), so things should be good to go for tomorrow morning's run.

**Comment by josephdviviano** [comment]
jon thanks so much for looking into this and fixing it! :-D
