### ISSUE TITLE
STOPPD and SPINS external site header mismatched

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#355]
Looking over the mismatches in a more systematic way..the only one's that look a little scary is actually ZHH and MRC from SPINS...

made little csv summaries of all scanner mismatched (excluding for the PDT2 scans) for all sites in my scratch...
/scratch/edickie/checkheaders_test/STOPPD/headermismatches_CMH.csv
/scratch/edickie/checkheaders_test/STOPPD/headermismatches_MAS.csv
/scratch/edickie/checkheaders_test/STOPPD/headermismatches_NKI.csv
/scratch/edickie/checkheaders_test/STOPPD/headermismatches_PMC.csv
/scratch/edickie/checkheaders_test/SPINS/CMH/headermismatched_CMH.csv
/scratch/edickie/checkheaders_test/SPINS/MRC/headermismatches_MRC.csv
/scratch/edickie/checkheaders_test/SPINS/ZHH/headermismatches_ZHH.csv

**Comment by josephdviviano** [comment]
I'll send emails now.

**Comment by josephdviviano** [comment]
Hi @edickie ;

OK, you likely saw the emails, but for the gitrecord, I've reviewed the files and agree that the SPINS mismatches are the scariest.

I've sent emails for these logs:

    /scratch/edickie/checkheaders_test/SPINS/MRC/headermismatches_MRC.csv
    /scratch/edickie/checkheaders_test/SPINS/ZHH/headermismatches_ZHH.csv

And I'm not sure whether it is worth worrying about these logs:

    /scratch/edickie/checkheaders_test/STOPPD/headermismatches_CMH.csv
    /scratch/edickie/checkheaders_test/STOPPD/headermismatches_MAS.csv 
    /scratch/edickie/checkheaders_test/STOPPD/headermismatches_NKI.csv
    /scratch/edickie/checkheaders_test/STOPPD/headermismatches_PMC.csv
    /scratch/edickie/checkheaders_test/SPINS/CMH/headermismatched_CMH.csv
    /scratch/edickie/checkheaders_test/SPINS/MRC/headermismatches_MRC.csv
    /scratch/edickie/checkheaders_test/SPINS/ZHH/headermismatches_ZHH.csv

**Comment by josephdviviano** [comment]
Looks like MRC does not think their mismatches are an issue. I'm waiting for confirmation from them.

This is what I got back from ZHH:

RE: fieldmaps (I think no issue)

>Most of these seem to be due to the fact that beginning with the -0033 subject on 2015-09-30, we changed the Field Map matrix from 64 to 256.  This also would change the PixelSpacing, PixelBandwidth, Rows, and columns by a factor of 4.  I expect to continue this until we shut down ~mid Feb 2016 to replace our 3T.
>I remember that Sofia said that the way were acquiring FMs before that, they were not usable.  My notes indicate that we turned on ASSET (parallel imaging) to the minimum possible value (1.25?), and I think we also had to let it zero-fill from 64 to 256 to let this happen.  Sofia may remember more of the details.

RE: EPI

Looks like we need to blacklist:

>​A few seem to be EPI cases (fMRI and DTI) where the Phase Encode direction was ROW instead of COL.  These should have been stopped very early, and would not need to be uploaded, though we do not have a communication system in place to let John Cholewa know that.  I have added some comments in the revised attached spread sheet (Excel format), with some comments copied below.
>0031: Series 5 should be ignored, only 252 images, stopped because of ROW/COL swap.  EA task in series 6-8.
> 0034: I was away for this, so someone else ran the MRI scanner, and did not realize that he needed to check the ROW/COL problem carefully.  Series 7 (all 8480 images) and 16 (4572 images) had this problem.  This subject had a repeat scan a week later, with a full 8480-image Resting State scan with the problem resolved.
>​0036: My notes do not indicate a problem, so this one must have slipped by me.

RE: FLAIR (nothing needs to be done)

>Two cases where the FLAIR TE was higher than expected.  We cannot control this, and it should not affect interpretation.

**Comment by josephdviviano** [comment]
OK, I've blacklisted the above files and deleted any downstream outputs from them.
