### ISSUE TITLE
Make reoriented SPIRAL data available in data-2.0

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#356]
from colin hawco:

>We surmised it may be better to replace the files in data2.0 with the reoriented images, such that anyone who pulls the data gets to reoriented files.
>Joseph wisely surmised it is important to make it transparent that these images are reoriented and easy to find the originals.
>I would suggest that that it not to be too easy for people to accidently grab the wrong files to avoid future confusion and lost time. I.E I thionk think we should keep the original sprl.nii files in the directory and just add a sprl_renorient.nii file, but instead have the sprl.nii as the reoriented file and a second file as sprl_original.nii, or have the original in a different but transparent location. Or whatever you guys decide is best.

**Comment by colinhawco** [comment]
Here is the code for reorienting spriral images. Tested on several cases where we could determine L/R laterality ked placement in MRI, asymetic brains), using the T1 as a guide for L/R. 

fslorient -deleteorient sprl.nii
fslswapdim sprl.nii -x -y  z sprl_swap.nii
fslorient -setqformcode 1 sprl_swap.nii.gz

**Comment by josephdviviano** [comment]
@colinhawco thanks, could you also point us towards the already-reoriented files you mentioned during lab meeting?

**Comment by colinhawco** [comment]
Sorry hit enter to soon!

/projects/colin/archive/resting/

Files are labeled sprl_reorient.nii.gz, within the study and subject folders. 

There is a file in that folder called **Resting_state_batabase.xls** which includes a column indicating which files need reorinting. As this file was created after the reorientation issue was resolved, it should include reference to all cases where this was an issue.

**Comment by arash-n** [comment]
Just make sure that you make a copy of the raw files before running it on the files as the first command delete orientation of the very file it is given without creating a new output.

**Comment by josephdviviano** [comment]
Moar deets:

From `Vincent Man`:

>Yup, there should be fixed sprl.nii files in my projects folder. I haven't yet moved them out yet, but if you want to copy the raw sprl.nii files out of there, here are some paths:

    /projects/vincent/COGBD-project/Resting_state_database.xls

>This is the excel file logging which datasets have weird orientations. It's quite old (might not have all the most recent COGBD additions) and I got it from Colin, so might be the same as what he has

    /projects/vincent/COGBD-project/Data/HC/H010_02/Raw

>The corrected spiral images are in each subject's folder. So the organization is as follows - under /projects/vincent/COGBD-project/Data - there are separate folders for HC, BD, and SCZ. HC and SCZ are from DTI, BD are just COGBDY. Each subject ID has their own folder, and the spiral images are in <subID>/Raw/

> I believe the sprl.nii files are already re-oriented, using /projects/vincent/COGBD-project/Data/Scripts/reorient.sh (take a look). There are some files called sprl_shft_al.nii.gz, which are reoriented, origin set to the AC manually using SPM, and then aligned with the T1s. The script that does that is /projects/vincent/COGBD-project/Data/Scripts/alignment.sh

**Comment by josephdviviano** [comment]
Aside from the one strange subject referenced in issue (#451), everything should be done.

The original spiral scans now have the extension `.orig`, so our pipelines won't run on them, and the reoriented files have the normal `.nii` extension.
