### ISSUE TITLE
Old folder: Moving to Archive

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#359]
Hi guys, 
I was wondering if you can move this to an archive folder that we keep a record of this and also free some space of the projects folder. 
/projects/arash/current/SWM

**Comment by arash-n** [comment]
Hey guys,

I was wondering if my SWM folder is archived so that I can delete it from my projects folder?

Cheers,
Arash

**Comment by pipitone** [comment]
> I was wondering if my SWM folder is archived so that I can delete it from my projects folder?

I haven't yet archived it. I'll try to get to this tomorrow.

**Comment by josephdviviano** [comment]
@pipitone I have some time now, moving the files. I'll close this issue after I've|

+ rsynced data to `/archive/data-2.0/SWM`.
+ removed data from Arash's projects.
+ removed old Arash's ZFS snapshots (henceforth called Aarshots).

**Comment by josephdviviano** [comment]
Hi Arash,

The data is now in /archive/data-2.0/SWM

Could you add a README in there explaining, as best as possible, what this data is, for people who want to use it in the future?

**Comment by josephdviviano** [comment]
Everything except the README is done.
