### ISSUE TITLE
Bogus series 0 in several STOPPD scans

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#360]
There are several scans from `MAS` that have a series 0 that contains a handful of dicoms with a `SeriesDescription` of `MPRAGE`, so it looks like a T1 but `dcm2nii` fails on it. I'm not exactly sure what series 0 is, but it ain't an image. 

I suggest we delete this series from XNAT. If that's not acceptable, then I propose we add a hack to deal with this in `xnat-extract.py` via an extract command line option `--ignore-series-0` or some such. 

Opinions?

**Comment by pipitone** [comment]
For reference, here are the wonky exams: 
- STOPPD_MAS_210033_03_01
- STOPPD_MAS_260002_01_01
- STOPPD_MAS_260004_01_01
- STOPPD_MAS_260006_01_01
- STOPPD_MAS_260007_01_01
- STOPPD_MAS_260011_01_01
- STOPPD_MAS_260012_01_01
- STOPPD_MAS_260013_01_01

**Comment by josephdviviano** [comment]
I like deleting them from XNAT -- no point in them polluting our database. Removing them now.

**Comment by josephdviviano** [comment]
OK -- they should be removed!
