### ISSUE TITLE
MRSROI.zip files from the CAMH MR unit

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#361]
As of Dec 4, old scans with MRS volumes have had masks applied and the data uploaded to the MR FTP server with zip file names ending with `_MRSROI.zip`. We'll need to deal with these, and I suggest we add them as session `00` for whatever time point they apply to.

**Comment by pipitone** [comment]
I've updated STOPPD's `metadata/scans.csv` to map the MRSROI zip files to session `00`. Y'all good with this?

**Comment by edickie** [comment]
This works as a first step...but eventually I think we need to put them
beside their corresponding MRS scans in the appropriate data-2.0 folder...

**Comment by pipitone** [comment]
What do you mean by "beside"? These scans can now be exported with an appropriate tag. Will that do?

**Comment by josephdviviano** [comment]
Hi Jon, that approach looks fine to me. (Thanks for doing that by the by).
