### ISSUE TITLE
Issues with the concatenated files for the DTI 1.5T data 

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#363]
Hi,

The concatenated files in /archive/data-2.0/DTI/TGH/data/nrrd/ have less than 75 directions - I have created new concatenated files and have checked that they all have 75 directions. I also averaged the concatenated files and all of the averaged files have 24 directions, as expected. The exceptions are noted below.

Can one of the sudoers please transfer the concatenated files from /scratch/saba/new_DTI1/concatenated_files to archive/data-2.0/?

Thanks,
Saba.

<b>Exceptions</b>:
<ul><li>H004_01: I cannot concatenate the 3 DTI series because: Origins differ [-151.846, -191.742, -70.9855] [-151.857, -191.414, -73.5647] (gtractConcatDwi). So I concatenated the series 05 and 07, as the origin of 06 doesn't match the origin of the other two. This concatenated file contains only 50 directions, not 75. gtractAverageBvalues gave an error when creating the averaged image. Error: *** Error in `gtractAverageBvalues': free(): invalid next size (fast): 0x0000000002ca8650 *** Aborted.</li>
<li>H007: Has 4 series. The concatenated file has 100 directions, not 75.</li>
<li>H009 has no DTI files. The only file in the data/nrrd folder is the T1 scan.</li>
<li>H011 has H011_01_01 and H011_01_02. The concatenated file is created using H011_01_01. I first used H011_01_02 to create the concatenated file but when I averaged the 75 gradients using gtractAverageBvalues, I was left with only 1 gradient.</li>
<li>H027: Has 2 series. The concatenated file has 50 directions, not 75.</li>
<li>H063_01: I cannot concatenate the 3 DTI series because: Origins differ [-123.962, -197.758, -56.7639] [-141.359, -184.258, -55.0253] (gtractConcatDwi). So I concatenated the series 06 and 07, as the origin of 05 doesn't match the origin of the other two. This concatenated file contains only 50 directions, not 75. gtractAverageBvalues gave an error when creating the averaged image. Error: *** Error in `gtractAverageBvalues': free(): invalid next size (fast): 0x0000000001daf1a0 *** Aborted.</li>
<li>H090_01 had 4 series: 05, 08, 09, 10. The origin of 05 is different from the other three so I only used 08, 09, and 10 to create the concatenated file.</li>
<li>H159_01 has no DTI files. The only file in the data/nrrd folder is the T1 scan.</li>
<li>H162_01: Has 4 series. The concatenated file has 100 directions, not 75.</li>
<li>S003 has S003_01_01 and S003_01_02. The concatenated file is created using S003_01_01. I first used S003_01_02 to create the concatenated file but when I averaged the 75 gradients using gtractAverageBvalues, I was left with only 1 gradient. S003_01_01 has 4 series but the origins differ and I could only create a concatenated file using series 07 and 08. The concatenated file has 50 directions, not 75. The series 06,07,08 are very large - all three are 190.1 MB.</li>
<li>S005 has no DTI files. The only file in the data/nrrd folder is the T1 scan.</li>
<li>S040: I cannot concatenate the 3 DTI series because: Origins differ [-181.291, -153.746, -96.7584] [-173.682, -164.883, -95.9541] (gtractConcatDwi). So I concatenated the series 06 and 07, as the origin of 05 doesn't match the origin of the other two. This concatenated file contains only 50 directions, not 75.  gtractAverageBvalues gave an error when creating the averaged image. Error: *** Error in `gtractAverageBvalues': free(): invalid next size (fast): 0x0000000001b6e650 *** Aborted.</li>
<li>S097: There are only 2 series and I cannot concatenate them as their origins differ: [-145.921, -211.533, -29.8874] [-144.523, -212.632, -30.0872].</li>
<li>S107: Origins of all three DTI images are different - cannot create concatenated image.</li> 
<li>S119: has no DTI files. The only file in the data/nrrd folder is the T1 scan.</li>
<li>S139: Has 4 series. The concatenated file has 100 directions, not 75.</li>
<li>S144: has no DTI files. The only file in the data/nrrd folder is the T1 scan.</li>
<li>S162 has S162_01_01 and S162_01_02. The concatenated file is created using S162_01_02.</li>
</ul>

<b> Summary </b>

<b> The following subjects have a subject folder in the data/nrrd folder but don't have DTI scans: </b>
<ul>
<li>H009</li>
<li>H159</li>
<li>S119</li>
<li>S144</li>
</ul> 

<b> The following subjects don't have a concatenated file: </b>
<ul>
<li>H009_01</li>
<li>H159_01</li>
<li>S005_01</li>
<li>S097_01</li>
<li>S107_01</li>
<li>S119_01</li>
<li>S144_01</li>
</ul> 

<b> The following subjects have a concatenated file but give an error when I try to average the DTI series using that concatenated file: </b>
<ul>
<li>H004</li>
<li>H063</li>
<li>S040</li>
</ul>

**Comment by pipitone** [comment]
Thanks Saba, this is great and a really well written up issue.  Do you have the script you used to concatenation the files also?

**Comment by sabashahab** [comment]
After copying and pasting all the files that were larger than 40 MB into another folder, I ran this code:

for directory in ./*; do COMMAND=gtractConcatDwi; for file in $directory/*; do COMMAND+=" --inputVolume $file"; done; echo `$COMMAND --outputVolume "$directory/concatenated.nrrd"`; done

**Comment by pipitone** [comment]
I've added these files to `/archive/data-2.0/DTI/CMH/data/nrrd` and updated the `README` with your notes. 

Thanks!

**Comment by pipitone** [comment]
Oh, one more thing @sabashahab: what command did you use to create the averages?

**Comment by sabashahab** [comment]
Thanks Jon. This is how I created the averages:

<pre><code>for directory in ./*; do gtractAverageBvalues --inputVolume $directory/*concatenated.nrrd --outputVolume $directory/averaged.nrrd; done > /projects/saba/SCZsubtype_classification_project/file13</code></pre>

**Comment by pipitone** [comment]
Kewl. Thanks.
