### ISSUE TITLE
ENIGMA ROI labels are incorrect for the IFO and UNC tracts

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#364]
via http://enigma.ini.usc.edu/protocols/dti-protocols/: 

> **** An important note **** in the analysis is that the ROI labeled “IFO” is actually different that the same ROI under the most current FSL JHU Atlas label. This was different in the older JHU atlas used to create the template and make the protocols. Please note this will not play a role in ENIGMA-DTI GWAS as we will not be using this ROI for GWAS (it is very small) but it may be considered for disorder studies.
If groups choose to use these measures for their own analysis, please be advised that this should be uncinate according to the current atlas. To avoid confusion, we will NOT switch the labels back, but we will keep this warning so you can carefully examine your data. 

This shows up in the file `ENIGMA_look_up_table.txt` as: 
```
45      IFO-R           Inferior fronto-occipital fasciculus right
46      IFO-L           Inferior fronto-occipital fasciculus left
47      UNC-R           Uncinate fasciculus right
48      UNC-L           Uncinate fasciculus left
```

whereas in the FSL `JHU-labels.xml` we have: 
```xml
<label index="45" x="55" y="127" z="54">Uncinate fasciculus R</label>
<label index="46" x="123" y="125" z="58">Uncinate fasciculus L</label>
<label index="47" x="60" y="78" z="86">Tapetum R</label>
<label index="48" x="117" y="76" z="87">Tapetum L</label>
```

This means our enigma values as already computed are mislabeled. :-D

**Comment by josephdviviano** [comment]
@edickie, could you make sure the new labels are correct in ENIGMA going forward, and if required, delete all old enigma runs so that they will be re-computed correctly?

**Comment by edickie** [comment]
Truthfully, I don't want to change any labels by default so that the results we submit to the ENIGMA DTI group are as they expect them to be (and therefore work with ENIGMA Rscripts as expected..). I think it's better to just make sure this issue is saved somewhere were we can find it...

I've added a page to the lab wiki regarding this.

**Comment by josephdviviano** [comment]
+1 @edickie  -- this could cause some massive headaches for the enigma people down the road. good thinking.
