### ISSUE TITLE
Add new email settings to ansible

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#365]
As of #347, we now ought to use the RIC mail server to route mail out to the internet. We should create a ansible role to configure postfix. This would involve: 

1. installing postfix
2. Configuring `/etc/postfix/main.cf` with: 

        myhostname = <machine hostname>
        mydestination = <machine hostname>, localhost
        relayhost = [<mail server>]:587
        mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
        smtp_sasl_auth_enable = yes
        smtp_sasl_security_options = noanonymous
        smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
        smtp_use_tls = yes
        smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
        smtp_generic_maps = hash:/etc/postfix/generic

3. Configure `/etc/postfix/sasl_passwd` with the mailserver username and password, and run `postmap` on it, and set up the proper permissions.
4. Configure `/etc/postfix/generic` to map local user addresses to the mail account address, and run `postmap` on this file. 
5. Configure the various users sending mail (e.g. `root`, and maybe `logcheck`) to have real names that indicate the server, e.g. `logcheck@backup.kimel.ric`.

**Comment by josephdviviano** [comment]
I TOOK IT

**Comment by josephdviviano** [comment]
+ Followed the above and this guide to get mail sending through `servers.tigrlab@camhpet.ca`:

https://www.linode.com/docs/email/postfix/postfix-smtp-debian7

+ Set up mail forwarding for `hal` using this guide:

http://www.binarytides.com/postfix-mail-forwarding-debian/

**Comment by josephdviviano** [comment]
This issue isn't actually done because we haven't added this configuration to ansible. Oops.

**Comment by josephdviviano** [comment]
This looks like a useful starting point: https://github.com/petemcw/ansible-role-postfix

**Comment by pipitone** [comment]
I'm going to wait on this because in ~month we'll have to revisit email again since we'll be under the CAMH network...

**Comment by josephdviviano** [comment]
I've asked Qing for the CAMH mailserver info.
