### ISSUE TITLE
run script error for STOPPD

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#369]
Many of the scans for one subject (STOPPD_CMH_420039_02) never got converted to nitfy (even though the dicoms are there) 

When I look at the run script we see: 
[xnat-upload.py] ERROR: ERROR uploading file 20160105_Ex04815_STOP1MR_STSK065/Ex04815_Se00006_MRS-sgACC-Bilat/LCModelExam#4815-6.txt
[xnat-upload.py] ERROR: Error communicating with XNAT
Traceback (most recent call last):
  File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 150, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 134, in main
    raise e
HTTPError: 400 Client Error: Bad Request

**Comment by josephdviviano** [comment]
Hey Erin,

Not sure what this was about. I deleted the nifti folder for this participant and re-ran, and the data exported OK.

However this run.sh script was in pretty bad shape! I'm not sure why. At a certain point, when some modules were unloaded, so was datman, which means that the majority of the run script was never run.

I converted all of the module loads/unloads into loads that happen in a subshell, and it appears to be working OK. Something to keep an eye on going forward.
