### ISSUE TITLE
MATLAB shared object missing for matlab_concurrent_all/MATLAB_R2013b

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#372]
code in:

/scratch/colin/epitome/tmsfmri_study1/

e.g.
bash /scratch/colin/epitome/tmsfmri_study1/P102/cmd_160115_124421_tms_part1.sh
(rubn on tesla after epi-setup)
Error:

colin@tesla:/scratch/colin/epitome/tmsfmri_study1$ bash /scratch/colin/epitome/tmsfmri_study1/P102/cmd_160115_124421_tms_part1.sh
*** MODULE: init_basic. Reorients, phys regression, removes init TRs. ***
++ 3dcalc: AFNI version=AFNI_2011_12_21_1014 (Dec 10 2014) [64-bit]
++ Authored by: A cast of thousands
** ERROR: output dataset name 'anat_EPI_tmp_initTR.nii.gz' conflicts with existing file
** ERROR: dataset NOT written to disk!
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/runtime/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/bin/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/os/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/server:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/client:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64
/home/colin/epitome/tms_part1/bin/McRetroTS: error while loading shared libraries: libmwmclmcrrt.so.7.15: cannot open shared object file: No such file or directory
colin@tesla:/scratch/colin/epitome/tmsfmri_study1$

**Comment by josephdviviano** [comment]
Just to clarify, this bug isn't `epitome` specific but relates to the `libmwmclmcrrt.so.7.15` shared object... I think it is a known MATLAB + JAVA library thing ...

http://ubuntuforums.org/showthread.php?t=1515334

**Comment by josephdviviano** [comment]
According to the above link, the MATLAB module needs an extra line:

On tigrsrv, I added the line `prepend-path  LD_LIBRARY_PATH  ${basepath}/runtime/glnxa64`

to `/export/quarantine-nouveau/matlab/matlab_concurrent_all/MATLAB_R2013b/module`:

**Comment by josephdviviano** [comment]
I've also linked the requested older library to to new one...

sudo ln -s libmwmclmcrrt.so.8.2 libmwmclmcrrt.so.7.15

**Comment by josephdviviano** [comment]
Hi Colin.

I've got it working. Looks like the AFNI code I'm using needs to use the matlab compiler runtime instead of the matlabs in our quarantine.

Because of this I had to remove any reference to MATLAB_2013B in your bashrc or epi-setup script. They now point to an install of matlab compiler runtime in `/scratch/colin/MCR`.

Please don't load any matlab modules when you are trying to use epitome :).
