### ISSUE TITLE
RST data not showing up in QC docs for PRELASPE IWA

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#373]
The files are present in data/nii..but nothing in the QC doc..

**Comment by josephdviviano** [comment]
Hi Erin, good eye.

Can you:

+ Ensure the resting-state data is of sensible dimensions.
+ Ensure the things tagged RST are actually resting-state data.
+ Ensure the tags are right (`qc.py` only works on RST and SPRL at the moment).

**Comment by edickie** [comment]
Hey Joe,

1) Dimensions are 2.5x2.5x3 with TR-2.0
2) It is tagged with RST
3) If is resting state data (looks fine in fslview)

**Comment by josephdviviano** [comment]
OK, I'd delete one of the IWA QC docs and re-run `qc.py` to see if the RST page is omitted again. It might have been generated during a nearlier export that did not have resting-state data available.

**Comment by josephdviviano** [comment]
@edickie, I'm not sure if you did anything because you didn't post here, but I can see that the QC docs now have resting state pages, so I'm considering this closed (I assume my last post worked).
