### ISSUE TITLE
PRELASPE MAS T2 images not being exported

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#374]
exportinfo.csv looks fine...but no T2 files in data-2.0...

I'm stumped

**Comment by josephdviviano** [comment]
Hi @edickie ,

Will need your help with this one. Can you get any clue of what is happening with these files from the logs?

**Comment by josephdviviano** [comment]
In `exportinfo.csv`, the REGEX for the T2 images were `3D_T2`. I've changed this to `3D.T2`, which matches any character between `3D` and `T2`, and now it works.
