### ISSUE TITLE
Organize the T drive

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#375]
**deep breath**

I think something needs to be done about the `T:` drive. I know this is going to be not good (very bad), but something needs to be done to get it under control. If the unexpected happens to DL during her next vacation in the jungle, all will be lost.

I propose doing the following in order:
- [ ] Collect intel on where useful things are here: https://github.com/TIGRLab/admin/wiki/T-Drive-Guide
- [ ] Create a full reorganization that puts different access levels at the top of the file hierarchy (therefore, people will be able to click through the folder structure without any permissions issues, and won't have to type paths in).
- [ ] Find and eliminate all duplication in the folder structure.
- [ ] Resolve the issue of allowing multiple people to edit the same file simultaneously.

**Comment by pipitone** [comment]
You're a bold and brave man, Sir Viviano. An explorer, an adventurer.

Should you choose to continue this foray into the heart of darkness, I'd suggest you a) get clear on what the scope of the reorg is (is it just kimel lab stuff, k-lab plus related studies, or are you talking about the entire slaight centre T drive), and b) get some buy-in/let people know (like DL and Aneet) about what you'd like to do and how to work with the relevant people to get'r'done.

January 21 2016 4:12 PM, "Joseph Viviano"  wrote:

	deep breath

	I think something needs to be done about the T: drive. I know this is going to be not good (very bad), but something needs to be done to get it under control. If the unexpected happens to DL during her next vacation in the jungle, all will be lost.

	I propose doing the following in order:

	[ ] Collect intel on where useful things are here: https://github.com/TIGRLab/admin/wiki/T-Drive-Guide (https://github.com/TIGRLab/admin/wiki/T-Drive-Guide)
[ ] Create a full reorganization that puts different access levels at the top of the file hierarchy (therefore, people will be able to click through the folder structure without any permissions issues, and won't have to type paths in).
[ ] Find and eliminate all duplication in the folder structure.
[ ] Resolve the issue of allowing multiple people to edit the same file simultaneously.

**Comment by josephdviviano** [comment]
Note to self: go to 7th floor to learn about our `shared` folder on the `tdrive`.

**Comment by josephdviviano** [comment]
```
T:\Kimel [Jessica D’Arcey, Marzena Boczulak, Judy Kwan, Navona Calarco, Aristotle Voineskos, Aneet Ghotra, Lianne Thai, Laura Stefanik, Rajiv Kareer]
   - Lab Shared [Jon Pipitone,Joseph Viviano, David Rotenberg,Erin Dickie,Melissa Levesque,Arash Nazeri,Tina Roostaei,Tina Behdinan]
   - Study [Kyrsten Grimes]
   - Slaight Centre Project [Aneet Ghotra, Marzena Boczulak, Aristotle Voineskos]
      - SFCYT Core team [Jessica D’Arcey, Rajiv Kareer, Lianne Thai, Marissa Williams, Kyrsten Grimes, Judy Kwan, Aneet Ghotra, Marzena Boczulak]
      - SFCYT team [Jessica D’Arcey, Judy Kwan, Rajiv Kareer, Lianne Thai, Marissa Williams]
   - Slaight business [Jessica D’Arcey, Judy Kwan, Rajiv Kareer, Lianne Thai, Marissa Williams]
```

**Comment by navonacalarco** [comment]
This was done this week. :dancer:
