### ISSUE TITLE
New email policy: let's use tigrlab@camh.ca

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#376]
When I set up the postfix server for `HAL` to contact us about hardrive troubles, I thought it would be best if it all ended up in a centralized email address that Navona set up: `tigrlab@camh.ca`.

This email is currently configured to forward all incoming mail to @pipitone @edickie Navona and `JDV` at the @camh address. It will also make is easier to transition with personnel changes.

I'd like to see **all** system emails, scan completed emails, xnat inquiries, etc, going to this address. Here's a partial list, please add to it if you can think of things I've left out.

- [X] HAL emails
- [x] Scan completed emails
- [x] SPINS, STOPPD, PRELAPSE mailing lists
- [x] XNAT alerts / emails

- [x] IDRAC emails from `kimsrv` and `tigrsrv`
- [x] general inquires
- [x] logcheck / backup emails.

**Comment by camh** [comment]
Sounds good to me.

**Comment by josephdviviano** [comment]
:D

**Comment by pipitone** [comment]
I :heart: @camh

**Comment by josephdviviano** [comment]
Scan completed emails are now administered via tigrlab@camh.ca. I've added the login info to passpack.

**Comment by josephdviviano** [comment]
tigrlab@camh.ca is also on all of the google groups mailing lists. however because it isn't a Google account, it cannot manage the group. Joseph and Erin's emails are now owners of all groups.

**Comment by josephdviviano** [comment]
I'm forwarding all 1657 'scan completed' or xnat related emails to tigrlab.ca so we have a shared copy of these files somewhere.

**Comment by josephdviviano** [comment]
I've made a tigrlab@camh.ca account for xnat -- all emails will now only be sent to this address.
