### ISSUE TITLE
Alumni isn't mounted anywhere

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#377]
@pipitone:

Julie (and I imagine others) may need access to `alumni`.

I need you to: 

+ Add `/mnt/alumni /export/alumni none bind 0 0` to `fstab` on `tigrsrv`
+ Add `/export/alumni` to the `/etc/exports` on tigrsrv
+ make a directory `/alumni` on all machines.
+ Add `tigrsrv:/export/alumni /alumni nfs rw,bg,auto  0  0` (or similar) to all machines.

Thanks,

**Comment by pipitone** [comment]
Yeah, I'm going to remove the mount under /archive, since that will get pulled into our nightly backups.

**Comment by josephdviviano** [comment]
Sure, can you also make sure it is available on all machines for the users though?

**Comment by josephdviviano** [comment]
I'm taking over. ʕ•ᴥ•ʔ

**Comment by josephdviviano** [comment]
This is done (new mounts etc added to ansible).
