### ISSUE TITLE
Backup alumni, external data

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#379]
ATM, we don't enough space on our backup server to store our alumni or external datasets, and CAMH storage isn't yet available.

Some options: 

1. Backup to the SCC. I've asked David about this, and he's working to make space for us, but it sounds like it will take a while.
2. Backup to the USB drives. We likely have enough space to make a shitty backup on these guys. It's better than nothing. 
3. Backup to tape. The SCC has tape backup. I've asked David if we could do this. 

I'll also speak to Peter, as the PET centre may have gobs of space for us to use temporarily.

**Comment by josephdviviano** [comment]
@pipitone I know you were investigating a few options. Come up with anything?

**Comment by pipitone** [comment]
We should have CAMH storage available by next week....

**Comment by pipitone** [comment]
Okay, access to the CAMH storage is partially working -- user IDs are still a little wacky. I've got mount information in a separate playbook `camh-storage.yml`, and I've added a few of the relevant hosts into `roles/common/templates/hosts.j2`, but none of this is committed yet.

**Comment by pipitone** [comment]
Despite user id's not being handled correctly, I am going ahead with syncing `/alumni` to `tigrsrv:/mnt/tigrlab` (which is our 100T CAMH storage blob). After that's done, I'll sync `/external`.

**Comment by pipitone** [comment]
I'm closing this issue for now as I've been able to backup `/alumni` `/archive` and `/external` to CAMH storage. Effectively: 

```sh 
mount -t nfs rprshnas01.camh.ca:/tigrlab/tigrlab /mnt/tigrlab
rsync --delete -a /mnt/alumni /archive /external /mnt/tigrlab/
```
