### ISSUE TITLE
"How to Kimel" Binder

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#380]
@pipitone suggested we compile a small 'how to kimel' binder. Crucially, it would contain all of the stuff we can't put online, as well as other things like purchases etc in hard-copy (bureaucracy hates trees).

This would also involve organising stuff that currently sits in `/projects/admin` and on the [admin wiki](https://github.com/tigrlab/admin/wiki)

Topics:
- [x] ESXi configuration and brief howto
- [x] username/password/ip addresses of all of our devices and admin interfaces (passwords via passpack)
- [ ] Updated [Network overview](https://github.com/TIGRLab/admin/wiki/Network-Overview) including RIC, CAMH, and SCC config
- [x] Updated [Ansible](https://github.com/TIGRLab/admin/wiki/Ansible) how-to and overview of roles
- [x] Updated [Storage & backup](https://github.com/TIGRLab/admin/wiki/Storage-and-Backup) description
- [x] [Quarantine](https://github.com/TIGRLab/admin/wiki/Quarantine-Management) and MATLAB license server
- [x] IPA configuration (with reference to ansible config)
- [x] SGE config 
- [ ] Startup/shutdown procedures for servers/equipment
- [ ] Email and mailing lists (including tigrlab@camh.ca, kimel-lab mailing list, and server email setup)
- [ ] Update [new lab member orientation](https://github.com/TIGRLab/documentation/wiki)
- [ ] Github and Gitlab 
- [x] Purchasing contact infos
- [x] CAMH IT/Research IT/Admin contact infos and procedures 
- [ ] Where to find/request behavioural/clinical data

Before closing this issue, I think we should have Qing and/or Andy read through this and confirm it is thorough enough for them.

**Comment by Navona-Calarco** [comment]
great idea! i have same stuff we can add.

**Comment by josephdviviano** [comment]
Hi @Navona-Calarco , great.

I've started a document at `/projects/admin/manuals/how-to-kimel.doc` that we can add to as we learn things.

**Comment by colinhawco** [comment]
Can you grant me write access to the admin folder?

**Comment by Navona-Calarco** [comment]
Sorry, was on Colin's computer and commented via his account. Can you please grant me write access to the admin folder?

**Comment by josephdviviano** [comment]
Hey, can you try now?

**Comment by Navona-Calarco** [comment]
Works. Thanks!

**Comment by pipitone** [comment]
I have a suggestion. Perhaps for information that's mostly okay to be shared publicly, we can continue to use the `admin` repo's wiki. There are several ways we could then go about converting the markdown to html/PDF for printing if needs be. We can use the T drive documents for stuff that absolutely can't be made public. I think this distinction might help us keep track of where our info is as we start to organise ourselves. 

(note: for the wiki, if there are bits of info that should be kept secret, perhaps we can agree to leave a blank space which fill in with pen and paper on the printed copy, or if we want to be fancy use [liquid](https://jekyllrb.com/docs/templates/) style template variables (e.g. `{{ localadmin.password }}`) in our wiki which we replace programmatically before printing or just use as indicators to ourselves to lookup these things in some other file.)

Lastly, if we are now going to use the T drive for our private info, we will have to move the existing documentation from `/projects/admin` to there. I've updated the issue description to note this.

**Comment by josephdviviano** [comment]
@pipitone , why would we want to move to the tdrive?

**Comment by pipitone** [comment]
@josephdviviano Right, I didn't explain that bit. In fact, I'm not strongly opinionated on where we put our private documentation, but I do think we it would help us to stay organized if we pick one place. I was using T drive in my last comment because I had meant to talk also about the documentation we already have there, and that perhaps the advantage to using the T drive is that others on the admin side (DL, AG, etc..) can more easily access it at the moment.

**Comment by josephdviviano** [comment]
@pipitone gotcha. I could use a tour of that private stuff we have no the tdrive since I've never actually ventured there. I'd like to record all of that as part of #375.

**Comment by pipitone** [comment]
> I could use a tour of that private stuff we have no the t-drive since
> I've never actually ventured there.

You and me both. Since the Slaight centre start up, I haven't been able
to access our lab's so-called "shared" folder. And even before that, I
only used it to access the expense log.

**Comment by josephdviviano** [comment]
OK I can do some fact finding on the

# 7th floor

┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻

**Comment by pipitone** [comment]
____  _   _ _   _     ____  _   _ _   _
    |  _ \| | | | \ | |   |  _ \| | | | \ | |
    | | | | | | |  \| |   | | | | | | |  \| |
    | |_| | |_| | |\  |   | |_| | |_| | |\  |
    |____/ \___/|_| \_|   |____/ \___/|_| \_|

**Comment by Navona-Calarco** [comment]
I have access to the 'Kimel lab shared folders' folder. There's a number of MRI-related logs and tracking sheets for AV's studies (this data should also exist in a database somewhere), as well as old copies of the presceening database for Slaight that Jon and I worked on. There's also a 'Kimel Study folders' folder that is nearly empty. It seems like the expense log may have moved to 'Slaight-Kimel Admin', which is pretty much just admin stuff (e.g., a key log and directions to camh).

**Comment by josephdviviano** [comment]
Hey @navonacalarco , can you help out with this?

**Comment by navonacalarco** [comment]
Sure thing. I'll look at what's there tomorrow.

**Comment by pipitone** [comment]
Okay, I'm going to update the issue to create a to do list of topics to cover. Please add to it.

**Comment by navonacalarco** [comment]
I think all of this is increasingly covered in our Wiki documentation. Going to close; reopen if you like!
