### ISSUE TITLE
Rebuild laplace, milner, and mrsdti

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#382]
Currently we have three machines out of commission that need ubuntu installed and configured on them: 

- [ ] `milner` had a drive failure so needs to have diagnostics on its drives to find the failure, RMA, and replacement first. 
- [x] `laplace` has ubuntu reinstalled (attempted this distractedly on Friday) but won't boot.
- [x] `mrsdti` only needs a reinstall

**Comment by josephdviviano** [comment]
I finished what @pipitone started and `laplace` is good to go.

**Comment by josephdviviano** [comment]
OK today I:

+ Reinstalled and (mostly) set up `mrsdti`. She sits in 108. Might need to reconfigure `sge` and `nis`, will investigate Monday.
+ Set up `milner` in 102.
+ Purchased mice for these machines, sourced monitors (stolen from other machines).

**Comment by josephdviviano** [comment]
I've finished setting up `mrsdti`.

**Comment by josephdviviano** [comment]
Is done!
