### ISSUE TITLE
Investigate high frequency spiral artifacts in STOPPD and RTMSWM

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#383]
Nancy mentioned the possible presence of a high spatial-frequency artifact in our spiral data in one quadrant of the brain. I've never seen it in our own data, but it would be good to keep an eye out.

Aside from remaining vigilant, I'll ask the members of the lab to look through their own data and report back (on this issue) if they find anything.

**Comment by josephdviviano** [comment]
It has been a week and all is quiet. I'm closing this issue for now.

**Comment by navonacalarco** [comment]
@josephdviviano @pipitone @edickie 

Nancy stopped by the ViPR scan and noticed that the spiral artifact is present, especially in inferior parietal areas. This is likely also the case for the former (i.e., first) ViPR scan.

**Comment by josephdviviano** [comment]
Thanks @navonacalarco

**Comment by josephdviviano** [comment]
This issue (#403) is how I plan to evaluate if this artefact is meaningful or not. I haven't seen any evidence yet that it actually effects the data after pre-processing. In fact, no one has (according to Nancy). I don't think trying to visually identify 'bad scans' by eye with the raw data is very useful until we can determine that it effects the pre-processed data.

**Comment by navonacalarco** [comment]
Thanks @josephdviviano

**Comment by josephdviviano** [comment]
I'm going to deal with this via #403
