### ISSUE TITLE
MRS scan order change (right after T1, before any fMRI)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#384]
-------- Forwarded Message --------
Subject: 	Reorder your MRS scan
Date: 	Sat, 23 Jan 2016 14:06:23 -0500

Colleagues,

Reviewing the metabolite editing results, we noticed there are number of scans with incomplete subtraction (artifacts) more so for software version DV24 than the previous DV23 which was upgraded late last year. Complete subtraction is the absolute requirement for GSH, GABA semi quantification. We observed large frequency drift during the 13  min for both GABA and GSH scans between 10- 13Hz. This is not desirable.

We conducted test scan on 3 volunteers to asset the impact of metabolite quantifications on our GE scanner. The three scanning protocols were tested:
1) FAAH1: localizer, 3D T1 weight, GSH
2) FAAH3: localizer, 3D T1 wt, rs FMRI, FMRI-task, FMRI task, GSH.
3) FAAH1 localizer, 3D T1 wt, rsFMRI, FMRI-task, FMRI-task, scanner 
     idle for 15 min, GSH.

GSH/H2O ratio reduced by 45%, 13% and 24% for the three healthy volunteers between scan 1 and scan 2. For scan 3, we found scanner idled for 15 min helps bringing the ratio back to within error of scan 1.

The effect of frequency drift is known in metabolite editing and documented in GABA measurements (Harris et al, 2015), however we found GSH measurements is also effected. We can correct for the frequency drift post-processing (and have been doing so in our processing pipeline) but there are other effects that can not be corrected such as editing efficiency. The editing frequency for each metabolite editing scan is fixed to a value relative to the main magnet proton frequency, so if the frequency is drifting during the 13  min scan then the fixed editing frequency is no longer give consistent inversion of the coupled metabolite (1.9ppm for GABA and 4.5ppm for GSH). This results in under estimate metabolite ratio.

The root cause for this drift is believed to come from high gradients duty cycle required for FMRI scans. The resulted gradient instability remains even after the scan is completed, thus effect the subsequent GSH scanning. From our limited test scans, it seems that instability normalized after 15 min of scanner complete idle time.

We chose to perform the test on the protocol that impose the highest demand on the gradients duty cycle (3 FMRI series back to back right before GSH MRS). However, we observed similar frequency drift for other protocol as well for eg. 3-5Hz drift for GLSZ1MR protocol which FMRI at the beginning follows be several other imaging series and GSH scan at the very last. 

Therefore, I would like to suggest changing the order of GSH and GABA scans to be after the 3D T1 weight sequence on every protocol contains GABA and/or GSH scan. I am hoping that this should improve scan variability.

If you are ok with this suggestion, there  is not need to talk to me. Anusha is aware of this issue and can help you with the change. However, if you want to speak to me in person, I am around this Monday and Tuesday only or just send me email with your questions.

We are working on a complete report on this and will circulate when ready.

**Comment by pipitone** [comment]
Redacted email to remove email addresses and names.

**Comment by josephdviviano** [comment]
We've decided to do nothing. :D
