### ISSUE TITLE
STOPPD_CMH_410040_02 is missing scans in /archive-2.0

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#386]
The T2/PD and SPRL scans are missing from the /archive/data-2.0 folder for subject STOPPD_CMH_410040_02. The tech notes claim they were aquired fine.

The T2/PD scan is in xnat for this subject - so I don't know what that was.
The SPRL i can't tell... (Is there a way to verify that the SPRL scan is there in the xnat web interface?)

**Comment by josephdviviano** [comment]
Hi Erin,

The T2/PD regex is likely not matching. Can you check the exportinfo file?

The SPIRAL scans are going to be in the resources folder. I can show you where those are.

**Comment by edickie** [comment]
So yesterday we deleted the folder from xnat to try to get the spiral scan to re-upload... 
This morning...still no sprial scan :-(
The run script gave this error

[xnat-upload.py] ERROR: ERROR uploading file 20160121_Ex04896_STOP1MR_STMA067/Ex04896_Se00006_MRS-sgACC-Bilat/LCModelExam#4896-6.pdf
[xnat-upload.py] ERROR: Error communicating with XNAT
Traceback (most recent call last):
  File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 150, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 134, in main
    raise e
HTTPError: 400 Client Error: Bad Request

Note: we got the same error (HTTPError: 400 Client Error: Bad Request) for the RTMSWM project as well...

**Comment by josephdviviano** [comment]
Hi Erin great detective work. I'll try to figure out what's causing the client errors. My bet is XNAT does not like a character in one of the file names.

**Comment by josephdviviano** [comment]
According to this: http://stackoverflow.com/questions/19671317/400-bad-request-http-error-code-meaning a 400 error means the REST command at upload is somehow malformed. I think a special character might be interfering with this upload command.

**Comment by josephdviviano** [comment]
I've fixed this bug (it was a url formatting issue ... didn't like the `#` sign) in this commit:

    https://github.com/TIGRLab/datman/commit/84665ff38ab29e70fba844084fd7f86d0374f21e
