### ISSUE TITLE
Upgrade ansible-playbooks to Ansible 2.0 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#389]
Because why not.

**Comment by josephdviviano** [comment]
:D

**Comment by pipitone** [comment]
Because future proof. Incidentally, that's my DJ name.

**Comment by josephdviviano** [comment]
Well That was easy. Everything just works.

I think the only thing I should do is create a virtual environment containing the currently installed version of ansible on `tigrsrv` in the ansible-playbooks folder so we can avoid future version-related trouble with ansible.

**Comment by josephdviviano** [comment]
I'm building a virutal environment using `python/2.7.9-anaconda-2.1.0-150119` and `conda`.

**Comment by josephdviviano** [comment]
OK, to use `ansible`, one should
```
# load the python environment containing ansible
source /projects/admin/ansible-playbooks/env/bin/activate

# run as normal (here, update all workstations)
cd /projects/admin/ansible-playbooks
ansible-playbook -Kk -i inventory -l workstations site.yml
```

I've updated the README.md and wiki here (https://github.com/TIGRLab/admin/wiki/Ansible).
