### ISSUE TITLE
PRELAPSE TXS DTI scans for 08 and 09 are not converting to NIFTI, MNC, or NRRD

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#391]
The converters complain that 'multiple dicom files have the same index'. We've recieved the correct number of DICOMs for all scans (4026), but since some of these are alleged duplicates (they aren't actually, the 'duplicates' clearly represent different parts of the brain), the converter isn't using all of the data and we end up with a malformed NIFTI.

@edickie will contact Vips at the TXS site to see what they use to convert these data. We also want to make sure this isn't corrupted data.

Things to try:

+ Put these dicom data through some sort of filter that will clean up the headers a little, e.g., http://www.dicomworks.com/fr/donation.htm
+ Find a new converter (what do they use at TXS?)
+ Try this Phillips data validation tool: http://sourceforge.net/projects/dvt/?source=typ_redirect

**Comment by josephdviviano** [comment]
There might also be some clues here: http://nipy.org/nibabel/dicom/dcm2nii_algorithms.html

**Comment by josephdviviano** [comment]
From Vips RE: conversion software:

> I spoke with one of the researcher and he said they use AFNI or DTI Query both are free software
> http://www.mccauslandcenter.sc.edu/mricro/mricron/

**Comment by edickie** [comment]
Hey, I know VIPS sent the write files...but the one's in data-2.0 still aren't don't look right...

**Comment by josephdviviano** [comment]
Hey @edickie , can you take care off this? I've uploaded the new data as repeat sessions for those subject. Can you have a look?

**Comment by josephdviviano** [comment]
If you need them: the files Vips sent are here --

`/projects/jdv/downloads/prelapse-data-txs.zip`

**Comment by edickie** [comment]
So looking at the data Vips sent (/projects/jdv/downloads/prelapse-data-txs.zip) it looks like each DICOM folder is a mix of both the good dicom (that do convert) and the bad dicoms. I think the bad dicoms as still screwing with the extraction from xnat. Separating them looks like not too much fun. I vote to:

1) Manually convert to nifty and nrrd and move them into data-2.0.
2) Add something to the readme to this effect
3) move on with our lives??

What do you think?
@josephdviviano can you confirm that the combo (good and bad) dicom folders were the one's uploaded to data-2.0 as session 02?

**Comment by josephdviviano** [comment]
Hi Erin, can you check how many DTIs are in the 02 sessions already uploaded? I uploaded these replacement DTI files already. If you can see them there, you should be able to remove the bad DTI images right in XNAT.

**Comment by josephdviviano** [comment]
Hi @edickie , as per our discussion, I've placed the data here 

`/archive/data-2.0/PRELAPSE/data/bkup/PRE01_TXS_30005-08-09_DTI.zip` 

and some notes in the associated `README.md`.

If you could manually place the `nii`, bvec, bval files for these three DTI sequences in DATA-2.0, that would be great, then we can close this issue.

Thanks!

**Comment by edickie** [comment]
The nii bvec an bval files are now in data-2.0.
