### ISSUE TITLE
Naming convention in the STOPPD folder doesn't look quite right....

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#394]
There are no STOPPD_CMH_*_00_?? scans in the STOPPD folder, 
There are 6 STOPPD_*_*_03 scans... 
There is one STOPPD_MAS_*_00_?? scan... 
( I don't think I remember the other sites saying they had one...right?

**Comment by josephdviviano** [comment]
Hi Erin,

This would make sense... we don't seem to have enough acute phase scans according to the naming convention alone. We might have to clean up after them.

The good news is an acute scan is very easy to identify, as it is only a resting-state scan and T1 (if I remember correctly). I can look at this when I get in.

**Comment by josephdviviano** [comment]
Actually Erin can you take care of this?

**Comment by edickie** [comment]
Talked to Judy. She says that _03 is for people who relaspe before they complete the study.
