### ISSUE TITLE
Look into storing user/pass for the MR ftp server in a file, rather than ssh passwordless access

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#397]
See [this comment](https://github.com/TIGRLab/admin/issues/396#issuecomment-177267929) on #396: 

> I'll need to install clevis's ssh key on the MR FTP server.
>
> Actually, this is something we should discuss further at some point, since it's not absolutely necessary and cumbersome since it relies on me having admin access to the server (or getting Nancy et al. to do it for us). We could just store the user/pass in a file, like we do with the XNAT credentials.

**Comment by pipitone** [comment]
I really hate saying we shouldn't use passwordless access. :-)  But, here'r a few ways to do it: 

    sshpass -f /path/to/password/file.txt scp -r username@remote:/files /here/
    rsync --password-file /path/to/password/file.txt username@remote:/files/ /here/

**Comment by pipitone** [comment]
I've updated our [wiki page on creating a data-2.0 project]https://github.com/TIGRLab/admin/wiki/Creating-a-project-in-data-2.0) with the password file option described above. I've also included a way of using `sftp` directly without using `dm-sftp-sync.sh`. :-)

**Comment by edickie** [comment]
Reopening - this is working when I copy the commands into a terminal but not when I bash run.sh :(

Therefore - nightly downloads from VIPR aren't working yet...but I can do them manually from time to time...

**Comment by navonacalarco** [comment]
Until this is working, I can can cc you on the scan completed email (which I think you already see via tigrlab@camh.ca?). There will only be 2 MRIs per month.

:)

**Comment by pipitone** [comment]
I've just tested this by deleting a sha1 file in `data/zips` for VIPR, and then rerunning the run.sh script. It works fine. @edickie I'm going to close this, but feel free to reopen and include a paste from your terminal so that I can help debug.
