### ISSUE TITLE
Explore using XNAT to do header comparisons and other QC

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#398]
@edickie and I spoke briefly about how much stuff there is in XNAT to do quality control and analysis that we don't use. We have avoided binding ourselves too much to XNAT because of how gross it is, but at the same time, there may be some benefit of using some well-baked pipelines in XNAT because a) we don't have to maintain that stuff ourselves, and b) it makes it easy to share the results of the QC with remote sites and so take some of the burden off of us. 

Specifically, I just found this paragraph in [Satterthwaite et al., 2014](http://www.ncbi.nlm.nih.gov/pubmed/23921101) which is somewhat relevant: 
> #### Custom XNAT Instance with Protocol Matching
>
> The dicom image data was imported into a customized instance of the XNAT imaging informatics platform (Marcus et al., 2007). This included a customized front-end that checked the incoming dicom files for adherence to a template MRI protocol. This front-end (called QLUX) was written in the java programming language, and compared key imaging parameters (e.g. TR, TE, resolution, flip angle, etc.) of the incoming data to a pre-defined template in order to identify any errors or deviations from the scanning procedure. Scanning sessions that successfully matched the template were then automatically imported into the XNAT database. Data sets that contained errors in the protocol were flagged for manual review. Image quality metrics (motion, tSNR) were calculated automatically. The QLUX interface also associated subject responses in the fMRI tasks to the imaging data within the XNAT database. Log files from fMRI tasks were scored by a custom, hand-validated Java-based application that uses an XML description of the task stimuli, possible responses, and the classification of responses to calculate and store the scores within XNAT. Basic image processing utilized tools that are part of FSL (Jenkinson et al., 2012) and AFNI (Cox, 1996), and was completed within the XNAT framework using NiPype (Gorgolewski et al., 2011) and PyXNAT (Schwartz et al., 2012). Highly accurate registration of T1-weighted structural images to template space was achieved using DRAMMS (Ou et al., 2011). Additional processing will be tailored to the specific goals of a given analysis and be discussed in detail elsewhere.

**Comment by edickie** [comment]
So we turned on the QC pipeline for some test cases but I don't see any outputs anywhere...lolz

**Comment by josephdviviano** [comment]
I'm closing this. We shouldn't waste our time. 

If you want to speak to someone who has abandoned using xnat for any/all pipieline stuff, talk to the xnat people at baycrest (the ones who gave us xnat in the first place).
