### ISSUE TITLE
Fix internet on 3660-MJ17YEM

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#400]
Filing this so we don't forget to follow up with IMG.

**Comment by pipitone** [comment]
Thanks. I spoke to someone from IMG in person on Friday. They had no real ideas as to what is up so I'll follow up with a ticket. Navona, it's a long shot but you could try using the second IP address in the email I forwarded to you.

**Comment by pipitone** [comment]
It is done. I've also labeled the drops with the IP and GW/SM settings.
