### ISSUE TITLE
Tickety ticket

### ISSUE THREAD

**Issue by 7jw9** [TIGRLab/admin#401]
@josephdviviano  Good luck closing this ticket. 

![screen shot 2016-02-01 at 3 12 04 pm](https://cloud.githubusercontent.com/assets/8701034/12729774/56fc6654-c8f6-11e5-824e-41fe5b7a5a40.png)

**Comment by josephdviviano** [comment]
![56fc6654-c8f6-11e5-824e-41fe5b7a5a40wwww](https://cloud.githubusercontent.com/assets/4142570/12733243/b64bbb8a-c907-11e5-874a-343a963a2ce8.png)

**Comment by pipitone** [comment]
![b64bbb8a-c907-11e5-874a-343a963a2ce8](https://cloud.githubusercontent.com/assets/509382/12733852/21c141c0-c90b-11e5-8b6f-f574e0823774.png)

**Comment by Navona-Calarco** [comment]
![default](https://cloud.githubusercontent.com/assets/13733654/12735138/57122eb8-c913-11e5-8326-80f4883ddaa8.png)

**Comment by pipitone** [comment]
Well would you look at that. Just look at it. 

        o
       /|\
       \|/
        |
       / \
