### ISSUE TITLE
add module commands to /etc/bash.bashrc in ansible

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#404]
The following lines need to be added to `/etc/bash.bashrc` in `ansible` for all work stations and compute nodes:

    source /etc/profile.d/modules.sh
    source /etc/profile.d/quarantine.sh

**Comment by pipitone** [comment]
They shouldn't need to be. They get loaded in /etc/profile

**Comment by josephdviviano** [comment]
You're right... but strangely they weren't getting loaded before on `mrsdti`. However, now they are (I've commented out my additions to `/etc/bash.bashrc`. Strange. I'm going to chalk this up to Joseph brain.
