### ISSUE TITLE
http://imaging-genetics.camh.ca/ is dead jim

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#408]
I cannot get there from my machine..

**Comment by pipitone** [comment]
I've just written to Alan about this issue.

**Comment by josephdviviano** [comment]
#（╯°□°）╯︵(\ .o.)\

**Comment by josephdviviano** [comment]
We've fixed access within the RIC network. Jon has sent out a missive to Alan Tang RE: the infinite redirect when attempting to access the site from within CAMH's network.

Since this redirect problem is a long-standing issue, I'm going to close this ticket. It might be unresolvable.
