### ISSUE TITLE
Matlab license not loading...

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#409]
We get there errors in the run script logs...

License checkout failed.
License Manager Error -18

**Comment by josephdviviano** [comment]
Hi Erin,

Which version of MATLAB? Can you module load this version manually?

**Comment by edickie** [comment]
I tried this manually

We get a licensing error for all of our versions of matlab

**Comment by josephdviviano** [comment]
Hi Erin, can you ensure the license server is active? I believe it runs on Kimsrv though I would have to check for myself.

**Comment by edickie** [comment]
Sooo...Do you think all of Colin's Matlab jobs are just exhausting the license???

**Comment by josephdviviano** [comment]
It could be. Is the license server active?

**Comment by josephdviviano** [comment]
Hi @edickie, @pipitone, looks like this problem is larger than I originally thought.

What I know:

+ on `kimsrv`, the `/etc/rc2.d/S98lmgrd`file AND folder don't exist.
+ on `kimsrv`, we get the following error when attempting to start the license server:

```
17:34:55 (lmgrd) lmdown requests disabled
17:34:55 (lmgrd) license manager: can't initialize:Cannot find license file.
17:34:55 (lmgrd) The license files (or license server system network addresses) attempted are
17:34:55 (lmgrd) listed below.  Use LM_LICENSE_FILE to use a different license file,
17:34:55 (lmgrd) or contact your software provider for a license file.
17:34:55 (lmgrd) Filename: "/usr/local/flexlm/licenses/license.dat"
17:34:55 (lmgrd) License Path: "/usr/local/flexlm/licenses/license.dat"
17:34:55 (lmgrd) FlexNet Licensing error:-1,359
17:34:55 (lmgrd) System Error:2 No such file or directory
17:34:55 (lmgrd) For further information, refer to the FlexNet Licensing documentation,available at "www.flexerasoftware.com".
17:34:55 (lmgrd) Using license file "/usr/local/flexlm/licenses/license.dat"
```

+ Note that this is very strange because the file specified by the license server start script, `/opt/quarantine/matlab/matlab_concurrent_all/license_manager/build/etc/LICENSE_MANAGER.sh`, is pointing to the correct license file, `/opt/quarantine/matlab/matlab_concurrent_all/license_manager/build/etc/license.dat`, but the license manager decided to stop looking for it.

I need some help trying to figure out what has gone wrong. Have either of you shut down or restarted `kimsrv` recently?

The whole MATLAB install situation is such a mess I might tear-down and re-install everything tomorrow from scratch instead of trying to wade through this mess, but first I'd like to know what changed recently.

PS -- I've verified our licenses haven't expired yet, so we're good on that front.

**Comment by pipitone** [comment]
I haven't touched kimsrv in a while, but let me know if you'd like a second set of eyes on any of this. I'm not that familiar with MATLAB license servers -- and certainly not with the mess in quarantine. I have only done this once before.

**Comment by josephdviviano** [comment]
HI @pipitone , thanks for the offer. 
![wanted-someone-to-go-back-in-time-with-me-this-is-not-a-joke-youll-get-paid-after-we-get-back-must-bring-your-own-weapons-i-have-only-done-this-once-before-safety-not-guaranteed-a1](https://cloud.githubusercontent.com/assets/4142570/12849567/4b96117a-cbee-11e5-85b2-d8db02ba9e99.png)

I wouldn't mind a full rebuild of matlab so we A) actually know wtf is going on in there, and B) if we have problems in the future, they will be more transparent. C) I'm not sure we should have the license server running on kimsrv any longer anyhow (perhaps tigrsrv would be better)?

**Comment by edickie** [comment]
Hi guys. Is Colin's bazinga still running? If so we might want to hold off
on this issue until it finishes...

**Comment by josephdviviano** [comment]
@edickie  I'll look into it, but I'm pretty sure he's running PLS on the SCC.

**Comment by pipitone** [comment]
@josephdviviano what's funny is that appended that same image to my message, but apparently github doesn't transfer images over email to issue comments. 

Another thought, if you want to go down this route, is to find out from David/Andy about how to have matlab authenticate with the SCC license server...

**Comment by josephdviviano** [comment]
I've contacted Mathworks for instructions... here they are:

Hello Aristotle,

From your license file it appears that you have already configured a network license server.  Is that correct?  If so I should mention that this is our normal configuration and the only one for which we have instructions.  If you're looking for a way to have MATLAB available without actually installing it locally on each machine, unfortunately we have no such instructions.  I can say that it should be possible to simply have MATLAB installed in a central location, using a network client configuration, and then provide access to that installation.

In case you don't have them already, I am including the normal instructions for a network configuration.  First, you must install the FlexNet License Manager.  To do so you will first have to contact the administrator of your TAH license, Chris Finley (chris.finley@utoronto.ca).

Provide Chris the MAC address and the operating system of the machine that will act as your license manager server.  With that information he can provide your a new license file that you can then use to install the FlexNet license manager, as follows:

How do I install or update the License Manager for a network license?
http://www.mathworks.com/matlabcentral/answers/105860

Once you have the license manager, you can then install the MATLAB clients, as follows:

How do I install a MATLAB client for a network license?
http://www.mathworks.com/matlabcentral/answers/106003

Finally, if you have any existing MATLAB installations that you would like to convert to using this new network configuration, you can do so by following the instructions on the following page:

How do I convert my installation from network to standalone or from standalone to network?
http://www.mathworks.com/matlabcentral/answers/95190



If you have any further questions, please do not hesitate to email me back. 
Please be sure to keep the REF ID included at the bottom of this email intact when replying to this message.  

Your Case Number is 01761981.

If you have a new technical support question, please submit a new request here:

http://www.mathworks.com/contact_TS.html

Regards,

Alex Cano
MathWorks Installation Support 

ref:_00Di0Ha1u._50031YOx53:ref

**Comment by josephdviviano** [comment]
todo: 

- [ ] Contact Chris Finley with MAC address of `tigrsrv` to get license file.
- [ ] Install FLEXNET on `tigrsrv`.
- [ ] Convert MATLAB licenses over to new configuration using [this guide](http://www.mathworks.com/matlabcentral/answers/95190) / Install MATLAB over network with [this guide](http://www.mathworks.com/matlabcentral/answers/106003)

**Comment by josephdviviano** [comment]
I just renewed the 3 concurrent licenses with Chris Finley (he can be found in Robarts Library, ground floor). These 3 concurrent licenses work with the TAH licenses.

**Comment by josephdviviano** [comment]
OK -- I've got it all working.

License server now live on `tigrsrv`. It can be launched on `tigrsrv` using the command:

    /opt/quarantine/matlab/license-manager/matlab-license-manager start 

Hopefully I've left enough `README.md`s around that if we ever need to do this again in the future, the process will be straightforward.
