### ISSUE TITLE
New tag for VIPR fMRI task??

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#413]
Hi guys,

The VIPR study has 6-runs for a virtual navigation task that are being collected using spiral BOLD imaging. Should we leave these are a SPRL tag or change things up to give them a new tag?? I'm acutally in favor of the later so that they are not confused with spiral rest, but maybe with something in the tag to remind us that they are spirals??

VN-SPRL?

**Comment by josephdviviano** [comment]
@edickie do they also have resting-state scans?

**Comment by edickie** [comment]
No, I'm more concerned with down the line (i.e. if someone wants to pool SPRL scans across multiple studies) that they are not confused with the resting SPRL scans in the system..

**Comment by josephdviviano** [comment]
@edickie that's a good point. the tag could even be something as generic as 'TASK'. To be fair, I don't think that 'SPRL' should ever imply resting state either, but that does not mean we need to rename all of those files across all of the studies. 

@pipitone , thoughts?

**Comment by pipitone** [comment]
> VN-SPRL?

+1

**Comment by navonacalarco** [comment]
> VN-SPRL?

+2

**Comment by josephdviviano** [comment]
doooooooo it

**Comment by edickie** [comment]
Done - as a hack I created dm-link-vm-sprl.sh which links with a new tag... Looks like it is working fine.
