### ISSUE TITLE
Blacklist and remove all data for PACTMD_CMH_3060030_01_01 from data-2.0

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#415]
All data compromised by incidental finding.

**Comment by edickie** [comment]
Just to check...were we explicitly told to blacklist this subject?? The email chain about the IF still looks inconclusive..

**Comment by josephdviviano** [comment]
I'm not sure. Sounds like they suggested fMRI signal dropout and FA dropout in that quadrant of the brain, which means ppl wouldn't want to use this participant in their analysis, but maybe it makes sense to hold off. What do you think?

**Comment by josephdviviano** [comment]
OK, we'll leave this subject in the pool for now.
