### ISSUE TITLE
Install minc-toolkit (?)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#416]
If there is a need, or @pipitone wants.

>I made a new release of minc-toolkit, standard branch - version 1.0.08 and v2 branch - version 1.9.11.  It includes all the latest versions of minc tools (as of 2nd of February 2016). V2 branch includes ITK 4.9 library and latest versions of ANTs and Elastix. V2 branch now also includes tools for patch-based segmentations ( see https://github.com/vfonov/patch_morphology ).

>MacOSX version was updated to work properly on 10.11 ( El Capitan). Unfortunately I was not able to build v2 branch for older (10.7) version, so only the standard branch is available to folks who are stuck with old version of MacOS X.

>All the binary packages are downloadable from http://www.bic.mni.mcgill.ca/ServicesSoftware/ServicesSoftwareMincToolKit

>Note that web page http://www.mcgill.ca/bic/software/minc/minctoolkit is out of date!

**Comment by pipitone** [comment]
I'm closing this. If it turns out we need it sometime, we can install it then.
