### ISSUE TITLE
weird spiral SNR dropout for PACTMD_CMH_3060034_01

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#417]
There's a diagonal line of lower SNR going through the spirals...only for this participant as far as I can tell...

P.S. check out the results on my kewl new beta qc pages
firefox /scratch/edickie/qc_pactmd/PACTMD_CMH_3060034_01/qc_PACTMD_CMH_3060034_01.html

**Comment by josephdviviano** [comment]
Hey @edickie : this new QC interface is really awesome!

Good catch. This SNR plot can really be useful. The SNR dropout is totally invisible in the raw data. I'd email Nancy about this one and attach the image.

PS -- can we look into changing the .jpeg encoding of the images to be higher quality? The images look pretty grainy.

**Comment by edickie** [comment]
@josephdviviano the images are .png by default...the grainyness might be either bad scan quality...or maybe matplotlib is doing something funny??

**Comment by josephdviviano** [comment]
@edickie it really looks like a compression artifact to me ... Ill take a look at it! Feel free to close this ticket after emailing Nancy.

**Comment by edickie** [comment]
Crap....

So, I realized, as I was testing qc-html.py that their was a bug in the run script that meant that the SPRL QC was never added to the qc pdf (because spirals were being linked the day after the qc.pdf was generated...). 

Anyway...this is quite bad... because now that I am looking at the SPRL qc for all of PACTMD and the SNR dropout artifact is present in the majority of these scans... :(

I'm going to generate the qc htmls for the other projects with spirals now.....

**Comment by josephdviviano** [comment]
Nancy's on this one, our work is done here. Thanks Erin.
