### ISSUE TITLE
Look into .png compression for the qc.py datman module (matplotlib)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#418]
qc.py is producing some funny compression artifacts in Erin's QC webpages. Likely due to a rendering stage (I suspect there are multiple stages, any of which could produce the artifact).

**Comment by edickie** [comment]
actually the .png are created by  qc-html.py (I created a new file so that it wouldn't mess with qc.py functionality while I built stuff up..)

**Comment by josephdviviano** [comment]
I think this is because, when moving `fig.savefig()` from filetype `pdf` to `png`, the program is automatically setting a particular resolution of the image, which introduces aliasing. To overcome this, I've explicitly set the image DPI to 144, which should be fairly large. 

See commits https://github.com/TIGRLab/datman/commit/28d5346ef3d81657002b9e025e339f1fd9887900
and https://github.com/TIGRLab/datman/commit/4d480fb0375579f62a8207c9cf89e810ebe5b1a9

We might want to follow this up in the future, but I'll consider this issue resolved.
