### ISSUE TITLE
condense / eliminate old quarantines

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#420]
Right now, we have 3 quarantines on `tigrsrv`:

+ `/export/quarantine`
+ `/export/quarantine2`
+ `/export/quaranine-nouveau`

@pipitone , can you merge anything we need from `quarantine` and `quarantine2` into `quarantine-nouveau` so we can remove these old quarantines (and maybe rename `quarantine-nouveau` to be just `quarantine`.)

Thanks :D

**Comment by pipitone** [comment]
Nouveau is all we need. :-)

**Comment by josephdviviano** [comment]
Can i delete `quarantine` and `quarantine2`?

**Comment by pipitone** [comment]
Yup.

**Comment by josephdviviano** [comment]
Just wondering why they were kept around? Not sure if you're being cryptic.

**Comment by pipitone** [comment]
No not being cryptic; there isn't a good reason we have kept the old quarantine around this long. Originally we kept it just in case we needed something from it after the upgrade.

**Comment by josephdviviano** [comment]
Hey @pipitone , thanks, just wanted to double check before I did something stupid :)

**Comment by josephdviviano** [comment]
OK, I'm going through quarantine2 module by module and moving anything we don't have in quarantine over. The rest is getting deleted.

I've also linked /export/quarantine to /export/quarantine-nouveau. It would make sense to change the paths in the module files to use /opt/quarantine instead of quarantine-nouveau.

**Comment by pipitone** [comment]
Great. Though, We likely don't need anything in quarantine2 I'm pretty sure. We haven't used it in a year and a half. 

> I've also linked /export/quarantine to /export/quarantine-nouveau. It would make sense to change the paths in the module files to use /opt/quarantine instead of quarantine-nouveau
> 
 all modules point to /opt/quarantine already.
