### ISSUE TITLE
Update whitematteranalysis

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#423]
Hi sudoers,

Can one of you please update whitematteranalysis/latest? Lauren has added a new function that I think would be useful for my analyses. This is where the code is stored: https://github.com/ljod/whitematteranalysis

Thanks!

**Comment by josephdviviano** [comment]
Hi @sabashahab , OK, I'll look at this soon.

**Comment by sabashahab** [comment]
Thank you Joey D! :)

**Comment by josephdviviano** [comment]
Updated into latest, I've also clarified the installer README.

**Comment by josephdviviano** [comment]
There's another update from Lauren that needs to be pulled (waiting to hear from @sabashahab  on when the changes are pushed to github).

**Comment by sabashahab** [comment]
Update: Changes have been pushed to github.

**Comment by josephdviviano** [comment]
@sabashahab we good to do this?

**Comment by josephdviviano** [comment]
Ah, I see, missed your comment (would be good to put @josephdviviano in your reply) -- I've pulled the changes.

**Comment by sabashahab** [comment]
Please update whitematteranalysis again - new code has been added. @josephdviviano

**Comment by pipitone** [comment]
I'll take care of this right now.

**Comment by pipitone** [comment]
Actually, here's how you can make your own build of whitematteranalysis: 

    cd /to/a/folder/with/your/project/files
    module load python
    conda create -p ./env vtk numpy scipy cython joblib matplotlib xlrd
    source activate ./env 
    git clone https://github.com/ljod/whitematteranalysis
    cd whitematteranalysis
    python setup.py install 
    cd .. 

This uses your own private python environment that you can install
packages into (that's what ./env is; it's a conda environment). 

Now, whenever you want to use this whitematteranalysis install, you do the
following: 

    cd /to/a/folder/with/your/project/files
    module load python
    source activate ./env 

If you want to update whitematteranalysis to the latest version: 

    cd /to/a/folder/with/your/project/files
    module load python
    source activate ./env 
    cd whitematteranalysis
    git pull
    python setup.py install

**Comment by pipitone** [comment]
In any case, the whitematteranalysis module is updated now.

**Comment by sabashahab** [comment]
Thank you, Jon. I'll try the above next time!

**Comment by josephdviviano** [comment]
@pipitone thanks!

@sabashahab if you need help trying the above next time, come find me!

**Comment by sabashahab** [comment]
@josephdviviano thank you! - I just tried it and it seems to work for now. Will let you know if I encounter any problems.
