### ISSUE TITLE
Colin needs a new epitome module for his analysis

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#424]
reference: https://github.com/josephdviviano/epitome/issues/41

**Comment by edickie** [comment]
You can just link to the MNI space freesurfer masks in the HCP outputs...

**Comment by josephdviviano** [comment]
Could you elaborate? Why is HCP also creating tissue masks? I though that was the freesurfer stage.

**Comment by edickie** [comment]
The hcp pipeline exports freesurfer masks and transforms them to MNI space.
It uses them to define the subcortical structures for cifti space.

**Comment by josephdviviano** [comment]
Ah, but this would happen after we might want them. For example, if we want to use them for tissue-based noise regression.

Maybe it would be good for me to build this module (it's extremely simple) and then your HCP module can depend on it?

**Comment by edickie** [comment]
Technically, (in my current hcp version) the T1 registration to MNI space
(and resampling of freesurfer masks) is run prior to init_epi.

**Comment by josephdviviano** [comment]
Hi Erin, OK, that doesn’t sound very modular, so I'll have to tackle that when I try to merge this stuff.

**Comment by josephdviviano** [comment]
Done. See `fs2mni` scripts.
