### ISSUE TITLE
Trouble removing quarantine2 logical volume

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#425]
I've recently removed the old quarantine here (#420) and moved some data into our new quarantine, for review. To finish the job, I've attempted to remove the logical volume that contained quarantine2 using the following commands:

    # deactivate LV
    lvchange -an /dev/vg_volumen0/lv_quarantine2
    # remove LV
   lvremove /dev/vg_volumen0/lv_quarantine2

But I got some errors I'm uncomfortable with:

    jdv@tigrsrv:/mnt$ sudo umount /dev/vg_volumen0/lv_quarantine2 
    umount: /dev/vg_volumen0/lv_quarantine2: not mounted
    jdv@tigrsrv:/mnt$ sudo lvchange -an /dev/vg_volumen0/lv_quarantine2
      Found duplicate PV kN6vBK9ez6h91XDIQYQqYYozaS3UXzLk: using /dev/sdo not /dev/sdm
      Found duplicate PV mDG9YcvVd5gBAcdVavuQLQ5yvz002cmm: using /dev/sdp not /dev/sdn
      Logical volume vg_volumen0/lv_quarantine2 contains a filesystem in use.

Leaving this here for now... when I have more time I'll investigate what exactly is going on here.

**Comment by josephdviviano** [comment]
According to this: http://serverfault.com/questions/266697/cant-remove-open-logical-volume

We can use `dmsetup info -c` to see all logical volumes:

```
vg_volumen1-vl_external            252   0 L--w    1    1      0 LVM-Mv9PDG4mg01sssx8uASu77CBsqMW8OcWh4CsbY1qrJUfXygQunvOHjTxYgLWmUN1
vg_volumen0-lv_projects            252   3 L--w    1    1      0 LVM-SoCIVXDQ8tE5kFyx3v7kzl72t9LgO3nGO7Hhqwt3WqFjNsEOknZLaEzE2ksCJJUz
vg_volumen1-lv_xnat                252   2 L--w    1    1      0 LVM-Mv9PDG4mg01sssx8uASu77CBsqMW8OcWbaDqnLrJNxgioU1RpZNreqKZilIxFKle
vg_volumen0-lv_home                252   5 L--w    1    1      0 LVM-SoCIVXDQ8tE5kFyx3v7kzl72t9LgO3nGdCsBCFP2jBNqg0XdLRdFkNKSdWiGz2of
vg_volumen0-lv_quarantine2         252   6 L--w    1    1      0 LVM-SoCIVXDQ8tE5kFyx3v7kzl72t9LgO3nG2GPhBkmZK1hs9tfF1yjlwJWXCMdaUQoY
vg_volumen0-lv_archive             252   4 L--w    1    2      0 LVM-SoCIVXDQ8tE5kFyx3v7kzl72t9LgO3nGDgxcd39Wr84O7cPQcntpW5jDcBL3bGKL
vg_volumen0-lv_quarantine--nouveau 252   7 L--w    1    1      0 LVM-SoCIVXDQ8tE5kFyx3v7kzl72t9LgO3nGDVTsIhMV0IFlO9Lif2NkKQo48bg91VL7
vg_volumen1-lv_alumni              252   1 L--w    1    2      0 LVM-Mv9PDG4mg01sssx8uASu77CBsqMW8OcW1g3HM21lncdQtG41rKT4BKRRIQmJIa7R
```

**Comment by josephdviviano** [comment]
Looks like I can't deactivate multipathing on HAL easily.

I've filtered `sdp` and `sdm`, and regenerated initrd. However, I don't really think it is worth any downtime to resolve this issue (the final step is to reboot tigrsrv), so I'm going to label this as 'maintenance' and unassign it. This should be done next time we go down for some sort of maintenance.

**Comment by pipitone** [comment]
Reboot of tigrsrv fixed all. I've removed this.
