### ISSUE TITLE
We need a clinical DICOM image packager

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#426]
As part of `datman`, we need a clinical DICOM packager that would include (if available) the T1, T2 / FLAIR, and PD images for each subject in DICOM format.

I propose: 

+ to wrap this into `xnat-export` as a separate exportinfo column (say, `export_clin`) 
+ this dumps the appropriate DICOM folders from xnat into a folder under `data/clinical-dicoms`
+ zips them up using a randomly-generated password. 
+ This password would then be written into a file stored on our filesystem. This will make it legal for us to transport the data in a variety of non-secure ways.

Thoughts? @pipitone @edickie

**Comment by pipitone** [comment]
What's the use case here? Is this for when we need to transfer data we have these zips at the ready?

Is it worth storing vs generating when needed with a single-use password?

**Comment by josephdviviano** [comment]
Apparently for some studies the MDs will want  the scans for every subject. This will only be for a few studies and just the anatomicals so I figured the hard disk demands would be low. On demand would work as well, I'm just trying to avoid chores (at the cost of hard disk space).

**Comment by josephdviviano** [comment]
OK -- We're not going to do this anymore, we're going to use XNAT for this. I've updated the documentation to handle casual users of XNAT on our [website](http://imaging-genetics.camh.ca/database/).
