### ISSUE TITLE
Finish setting up Stim PC for upstairs

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#436]
Last thing I need to do is figure out how to run multiple versions of eprime on the same machine.

**Comment by navonacalarco** [comment]
Multiple instances of the same version, or a single instance of multiple versions?

**Comment by josephdviviano** [comment]
Single instance of multiple versions .apparently some versions of eprime run some of our experiments, but not others, so we need to be able to switch between them.

**Comment by navonacalarco** [comment]
Yeah. Check with Colin, but I think we can _run _both with the newer version. I think the version issue becomes a deal only when attempting to edit experimental files, which maybe we won't need to do on the stim PC?

**Comment by josephdviviano** [comment]
OK -- I'm going to give to the folks upstairs as is, wait for trouble, and reopen this issue if it proves to be one.
