### ISSUE TITLE
make our website XNAT documentation good

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#443]
tomorrow. it begins.

**Comment by josephdviviano** [comment]
How to make helpful gifs:

http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

**Comment by josephdviviano** [comment]
Also, I've spruced up the aesthetics / rearranged the content of our website, which looks much more professional now IMHO.

**Comment by navonacalarco** [comment]
Looks great. And thanks for the link!

**Comment by josephdviviano** [comment]
All done!
