### ISSUE TITLE
STOPPD_CMH_460012_01 is missing SPRL and PDT2

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#444]
They were acquired and are in XNAT...
no run script errors related to them...
I'm stumped.

**Comment by josephdviviano** [comment]
@edickie Do you know how to figure this out? Files that are missing are missing because of `exportinfo.csv`.

**Comment by josephdviviano** [comment]
I'm going to leave this up to you... feel free to ask for help. I want to make sure you know how to solve these kinds of problems.

**Comment by edickie** [comment]
Change the exportinfo for the new PDT2 pattern..
The Spirals was an issue of the location of dm-link-sprl.sh in the run script... it was happening a day after qc generation...
