### ISSUE TITLE
Header difference for all SPINS MRC fMRI 

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#447]
/archive/data-2.0/SPINS/data/dcm/SPN01_MRC_0048_01/SPN01_MRC_0048_01_01_FMAP-6.5_11_field-map-TE-6.5ms-flipangle-45.dcm: header FlipAngle, expected = 60.0, actual = 45.0 [tolerance = None] 

This header difference is present for all fMRI as well as DTI and FMAPs

...gonna investigate how far this goes back...

**Comment by edickie** [comment]
the next participant from this site has a different header mismatch on all scans...urg...

/archive/data-2.0/SPINS/data/dcm/SPN01_MRC_0049_01/SPN01_MRC_0049_01_01_OBS_06_EPI-2x2x3xTR3-Observation.dcm: header NumberOfPhaseEncodingSteps, expected = 61, actual = 63 [tolerance = None]

**Comment by josephdviviano** [comment]
What is a phase encoding step?

As for the fMRI flip angle change... what did it change from and to? Their fieldmaps are strange... we get 3 back (only need two), I'm not sure what the flipangle-45 series are all about.

Could just ask Peter K about these.

**Comment by djoverton** [comment]
This is from ages ago, but have the appropriate people been notified for this/is it actually a problem (as per the conversation we had about many header differences being inconsequential)?

**Comment by navonacalarco** [comment]
I can't comment on if the appropriate people were ever notified. However, our new communication with Sofia about the importance/non-importance of given header differences (cc'd tigrlab@camh.ca) might soon illuminate the importance of this particular concern.

**Comment by edickie** [comment]
This is being addressed with the new header difference report communications with Sofia. We can file new issues with specifics header differences of importance going forward.
