### ISSUE TITLE
Investigate /projects/colin/archive/resting/STOPPD/24S018

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#451]
I'm not sure what `24S018` maps onto in our naming scheme, but there are SPIRALS associated with this subject in Colin's projects folder.

**Comment by josephdviviano** [comment]
DICOMs from this subject found here:

`/archive/data/STOP_PD_II/TO/24S018/Ex01756Se01`.

'PatientName' extracted from this is `24S007`. I think this subject maps onto this one from ``:

|FINAL|MR|MRID|SUBJID|TYPE|INITIALS|DATE|FOUND
-----------------------------------------------------------------------
|STOPPD_CMH_410010_02_01|2013_1010_VK028.zip|24S007|410010|Case|VK|2013-10-10|X

**Comment by pipitone** [comment]
Just removed the initials from your comment (PHI yada yada).
