### ISSUE TITLE
Fix the PRELAPSE data naming in xnat

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#453]
Subject with repeats in their folder
- [x] PRE01_MAS_06011_01
- [x] PRE01_TXS_38005_01
- [x] PRE01_PCE_S02014_01 

I'm downloading the repeat scans, reuploading them to the appropriate R (repeat) session, and then deleting the repeat scans from the initial upload, for each site.

**Comment by josephdviviano** [comment]
All done.
