### ISSUE TITLE
Update Slicer/nightly

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#454]
Hi,

I have been told that there were some recent fixes in Slicer. Could someone please get the newest version of Slicer/nightly?

Thanks.

**Comment by josephdviviano** [comment]
@sabashahab are you sure this is a good idea? the nightly slicer builds are going to be the most buggy.

**Comment by josephdviviano** [comment]
OK, I've swapped in the new version! Good luck :)

**Comment by sabashahab** [comment]
@josephdviviano Thank you! :)
