### ISSUE TITLE
SPIN up DBDC1MR study for Stephanie

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#455]
+ Get DBDC1MR SFTP password from Stephanie
+ DTIfit + Enigma QC
+ Initial PDF QC
+ Write DTIprep + UKF module for datman
+ RTFA test: is TE is less than 70, RTFA must be on
+ Protocol: 2x5 min rsfc, 2x5 min tasks, T1, DTI (RTFA + Dual Echo), fieldmaps

**Comment by josephdviviano** [comment]
![modern-fashion-party](https://cloud.githubusercontent.com/assets/4142570/13576019/8bfd5b8c-e459-11e5-97a6-37e00b661aa0.jpeg)

**Comment by pipitone** [comment]
I've set up the project in XNAT, and created the folder structure, run.sh script and metadata for the study. There is no data for this study on the MR FTP server, but once that arrives we can build the rest out.

**Comment by pipitone** [comment]
First subject has been through dtifit, enigma, and QC. Steph is going to confirm that the scans look okay.

**Comment by pipitone** [comment]
Done.
