### ISSUE TITLE
Outstanding training

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#463]
Actually found some of your research certificates. The only things I’m missing are below:

- [x] : GCP -- http://www.citicanada.org/
- [ ] : CAMH privacy training
- [ ] : Division 5 (not sure if you have to do this, so leave it for now and I’ll check with Dielle)
- [X] : Copy (signed and dated) of your CV

**Comment by pipitone** [comment]
What is this about?

**Comment by josephdviviano** [comment]
Sorry it's just for me.
