### ISSUE TITLE
rename STOPPD PMC subjects in XNAT

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#466]
ERROR: /mnt/xnat/spred/archive/STOPPD04/arc001/PMC_320045_00_01 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/STOPPD04/arc001/PMC_360012_01_01 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/STOPPD04/arc001/PMC_360013_01_01 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/STOPPD04/arc001/PMC_360014_01_01 folder is not named according to the data naming policy. Skipping

**Comment by edickie** [comment]
Now renamed

@josephdviviano is their someone we should email to remind of our data naming policy??

**Comment by josephdviviano** [comment]
@edickie if you check the google groups for stoppd, you could find some emails to send our new online guide to! Thanks :)
