### ISSUE TITLE
Figure out why fsl's slicer command hates /archive/data-2.0/PRELAPSE/qc/PRE01_NWN_37001_01/PRE01_NWN_37001_01_01_T2_08_t2-spc-sag-1mm-iso.png

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#467]
[qc-html.py] ERROR: Error 139 while executing: slicer /archive/data-2.0/PRELAPSE/data//nii/PRE01_NWN_37001_01/PRE01_NWN_37001_01_01_T2_08_t2-spc-sag-1mm-iso.nii.gz -S 2 1600 /archive/data-2.0/PRELAPSE/qc/PRE01_NWN_37001_01/PRE01_NWN_37001_01_01_T2_08_t2-spc-sag-1mm-iso.png
[qc-html.py] ERROR: stderr:
>       Segmentation fault (core dumped)
>

**Comment by josephdviviano** [comment]
@edickie segmentation faults are one of the most general types of errors out there. 

> Segfaults are caused by a program trying to read or write an illegal memory location.

Might not be worth your time unless you are very determined to figure this out... as it is likely a problem with FSL's C code, not your image. Does the data look OK in a viewer?

**Comment by edickie** [comment]
Giving up on this..
