### ISSUE TITLE
Write data-2.0 documentation on our documentation wiki

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#469]
Right now our data is pretty well organized, but there is no high level documentation on where to look for things. For example, Colin does not know what `scans.csv` is, and isn't likely to look into `datman` to figure it out.

Therefore I'm going to spend some time writing a set of web pages detailing how we organize our data, where to look for bits of information, and what our pipelines are up to.

**Comment by pipitone** [comment]
Great idea. Thanks J. Use the documentation wiki for that?

**Comment by navonacalarco** [comment]
This will be really helpful, and beneficial to me, too. Let me know if I can help!

**Comment by josephdviviano** [comment]
Hey @pipitone I think I'm going to try wrtitng it on our official site. As useful as the github wiki is I don't think our users frequent it very often. What do you think?

**Comment by pipitone** [comment]
> Hey @pipitone I think I'm going to try wrtitng it on our official
> site. As useful as the github wiki is I don't think our users frequent
> it very often. What do you think?

I don't think anyone frequents the website more than the wiki. :-) 

I'd prefer we stick our documentation in one place to make it possible
to find, so I'm +1 on the wiki. That said, if you do decide to put it up
on the website, can you put a link to the page or a copy of the content
on the wiki?

**Comment by josephdviviano** [comment]
Yes, or we could put all of the user-facing documentation on the website. It's just a bunch of markdown documents either way, but the website is easier to navigate than the wiki, I find.

**Comment by josephdviviano** [comment]
Navona raises a good point -- the website isn't accessible from within the CAMH network, so I'll add it to our documentation wiki for now. Since it's all markdown it will be easy to move over to the website it we feel the need.

**Comment by pipitone** [comment]
A few pages we already have that you should consider working from: 

https://github.com/TIGRLab/documentation/wiki/Introduction-to-the-Kimel-Lab
https://github.com/TIGRLab/documentation/wiki/Data-Naming

**Comment by josephdviviano** [comment]
Done ... for now https://github.com/TIGRLab/documentation/wiki/Data-Organization
