### ISSUE TITLE
CIVET failing

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#470]
CIVET doesn't seem to be running like it used too. Starting the pipeline gives me Eqw on the queue. I'm not quite sure what's happening. Hoping the processing geniuses can help me out with this one.

**Comment by josephdviviano** [comment]
Hi Melissa,

That's interesting, because I started having problems with the queue just recently too. This is the error from QMON: `Exec format error`.

Could you get us the exact command you're running?

**Comment by mlevesque82** [comment]
I've been running:

chmod -R ug+w output/
unset module
**these used to help some some issues.

Followed by the main command:

CIVET_Processing_Pipeline -sourcedir input -targetdir output -prefix ${prefix} -id-file file_ids.txt -run -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 -queue main.q -3Tesla -N3-distance 75

I'm running this in CIVET/1.1.10+Ubuntu_12.04 with CIVET-extras/1.0

**Comment by mlevesque82** [comment]
tbss_2 has been running fine on the queue by the way, so I don't think it's a generalized queue problem.

**Comment by josephdviviano** [comment]
Hi Melissa, does this command submit to the Queue? @pipitone I'm looking at the source but there isn't any `qsub` calls directly in the perl script.

**Comment by mlevesque82** [comment]
Yes it does. 
-queue sends it to the queue I think.

**Comment by josephdviviano** [comment]
Hey @mlevesque82 ,

Looks like CIVET's qsub thing is making the same mistake my code was making last week. Here's a solution:

Can you write a loop that writes out a single CIVET_Processing_Pipeline command for each subject with 

+ `-spawn` instead of `queue main.q` 
+ the subject at the end of the line instead of submitting `-id-file file_ids.txt`

to a text file? What we need is a list of individual commands. We can use `qbatch` to submit to the queue.

**Comment by mlevesque82** [comment]
Ok lets "pretend" I'm an idiot...

This would look like this?

for i in subjects;
do;
CIVET_Processing_Pipeline -sourcedir input -targetdir output -prefix ${prefix} -run -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 -spawn -3Tesla -N3-distance 75 -${subject}
end;

**Comment by pipitone** [comment]
That looks about right. 

You probably know this, but the trick is that your subject id is different from your image file names (e.g. `12315` vs `dti_12315_t1.mnc`) and you need to give the subject ID to `CIVET_Processing_Pipeline` not the file name. 

If you have your id-file handy, you can do something like this: 

```sh
cat id-file.txt | for i in subjects; do
    echo CIVET_Processing_Pipeline -sourcedir input -targetdir output -prefix ${prefix} \
        -run -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 \ 
        -spawn -3Tesla -N3-distance 75 ${subject}
end > civet
```

The `civet` file will have the list of civet commands in it. Try running one on the command line to make sure it works (you can stop it once you're sure it runs fine):

To submit all of the commands to the queue, try this: 

```sh 
module load SGE-extras
qbatch civet
```

`qbatch` creates a folder called `logs/` were all of the job log files go.

**Comment by edickie** [comment]
Hi everyone,

Also, you can also use the datman dm-proc-civet.py to run this...

**Comment by josephdviviano** [comment]
Hi Melissa,

How is this going?

**Comment by mlevesque82** [comment]
I tried running only one subject or not running on the queue but that doesn't work either. It's still sending to the queue.

CIVET_Processing_Pipeline -sourcedir input -targetdir output -prefix March2016 -run -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 -3Tesla -N3-distance 75 COGBDO_CMH_215501_01_01_T1_02_Sag-T1-BRAVO

How is the command above sending to the queue?

**Comment by pipitone** [comment]
It submits to the queue automatically unless you include the `-spawn` option.

**Comment by pipitone** [comment]
It does that automatically unless you include the -spawn option. :-)

Jon.

March 10 2016 3:17 PM, "Melissa Levesque"  wrote:

	I tried running only one subject or not running on the queue but that doesn't work either. It's still sending to the queue.

	CIVET_Processing_Pipeline -sourcedir input -targetdir output -prefix March2016 -run -animal -lobe_atlas -resample-surfaces -granular -VBM -thickness tlink 20 -3Tesla -N3-distance 75 COGBDO_CMH_215501_01_01_T1_02_Sag-T1-BRAVO

	How is the command above sending to the queue?

**Comment by mlevesque82** [comment]
but I tried that too... :(

**Comment by josephdviviano** [comment]
Hey @mlevesque82 let's look at this together tomorrow! I have some ideas about what is going on (feel free to grab me at any time).

**Comment by mlevesque82** [comment]
Sounds good. Thanks!

**Comment by josephdviviano** [comment]
OK -- We're going to start relying on the `dm-proc-freesurfer` module so that we don't have to think about this any longer. Testing on COGBDO. I'm going to check in on this Mon, and if it works, I'll spin it up for the remaining studies.

**Comment by josephdviviano** [comment]
Looks like this is working. I'm flipping the switch for COGBDY, SPINS, DTI, and RTMSWM.
