### ISSUE TITLE
XBRAIN slides for Aristotle

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#471]
+ 3 weeks away (Mar 21)
+ Needs 2-3 slides.
+ Demonstrating patient / control classification.

**Comment by josephdviviano** [comment]
@pipitone -- isn't the issue being assigned to me imply it is on my todo list?

**Comment by pipitone** [comment]
> @pipitone -- isn't the issue being assigned to me imply it is on my todo list?

I just wanted to keep the stuff that's only ever going to be on your
todo list (your personal stuff) marked. That okay?

**Comment by josephdviviano** [comment]
Yeah NP I just wanted to make sure I wasn't annoying you guys.

**Comment by pipitone** [comment]
Not at all. Is good.
