### ISSUE TITLE
SGE complains with "Exec format error" if command line is too long? 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#473]
@josephdviviano suspects that something has changed in the configuration of SGE such that jobs with long command lines submitted via qsub fail with this error. This wasn't happening before. 

Let's come up with a repeatable test case so we can explore this.

**Comment by pipitone** [comment]
@josephdviviano are you seeing this happen still?

**Comment by josephdviviano** [comment]
I don't submit commands like this any longer. You should be able to test it by echoing a very long string to qsub

**Comment by pipitone** [comment]
Turns out that this isn't due to long command lines, but that any non-binary (e.g. no `-b y` flag) submitted with fail unless it contains a shebang line. This is due to a change I incorporated from the cobralab config for `main.q`: I changed `shell_start_mode` from `posix_compliant` to `unix_behaviour`. I've changed it back. 

The upshot is this. There are three ways of submitting a job with qsub, and they each work slightly differently (when using `posix_compliant` now): 

- `echo command | qsub`: Your command (or commands if you pipe in several lines) is run from a bash shell. 
- `qsub command.sh`: You submit a file and it will be copied to the exec host and interpreted by bash as a script (even if it isn't bash :-))
- `qsub -b y command [args]`: Your command is run from a bash shell (similar to the first option but only a single command can be submitted).

**Comment by josephdviviano** [comment]
Hi @pipitone , thanks for looking into this. Does this mean it is impossible to submit a python script directly to `qsub` now?

**Comment by pipitone** [comment]
It's totally possible, just not by doing `qsub script.py`. That is, `echo ./script.py | qsub` and `qsub -b y ./script.py` both work.

**Comment by josephdviviano** [comment]
OK thanks.
