### ISSUE TITLE
Google Chrome is bad, blocking Ansible.

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#474]
TL;DR, GC 32bit was deprecated, our apt sources are invalid, Google hasn't fixed the bug yet.

+ `rm /etc/apt/sources.list.d/dl_google_com_linux_*`
+ Set `repo_reenable_on_distupgrade="false"` in `/etc/default/google-chrome`.
+ Explicitly set `[arch=amd64]` in the following files:

``` 
sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/google-chrome.list"
sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/opt/google/chrome/cron/google-chrome"
```

**Comment by josephdviviano** [comment]
Solution:
```
ansible -kKs -m command -a "/bin/bash -c 'rm /etc/apt/sources.list.d/dl_google_com_linux_*'" -i inventory workstations
ansible -kKs -m command -a "/bin/bash -c 'rm /etc/apt/sources.list.d/google*'" -i inventory workstations
```

It looks like google fixed the arch bug at some point, but ubuntu stored a bad version of this file in `sources.list.d`, so we just needed to remove them.

**Comment by pipitone** [comment]
Alternative solution: don't install Chrome. :-)
