### ISSUE TITLE
Switch to using the CAMH storage

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#475]
Once we've switched to using IPA (#446) for authentication we can do a final sync and then switch our mounts to the CAMH storage server.

**Comment by pipitone** [comment]
I'm doing a sync now: 

    sudo rsync -av /projects /external /archive /export/alumni /mnt/tigrlab/ --info=progress2

**Comment by pipitone** [comment]
For whatever reason, the mount I had on `tigrsrv:/mnt/tigrlab` craps out after a day or so (more specifically, it hangs and becomes unmountable... yay). This isn't true on `kandel`, where I also have the mount set up. I'm perplexed. 

I'll try the `rsync` on kandel and see how that goes.

**Comment by pipitone** [comment]
Update: The mount on `kandel` is fine. Andy is also seeing some NFS hangs on the SCC under rsync load. Suggestion is to try [nfs_automount](https://github.com/vwal/nfs_automount) on tigrsrv and see what comes out in the logs.

**Comment by pipitone** [comment]
I've set up nfs_automount on `tigrsrv` and `mrsdti`, with logging to `/var/log/nfs_automount.log`. I've started an rsync of `/projects`, `/archive`, and `/external` to the CAMH mount on tigrsrv so we'll see over the weekend whether it craps out and perhaps why.

**Comment by pipitone** [comment]
So far so good with automount.... no hangs.

**Comment by pipitone** [comment]
I think nfs_automount is a win. I'm going to add nfs_automount'ing of the tigrlab share to ansible and push this out to several machines. If there are no issues, then we can start switching to this storage incrementally.

**Comment by pipitone** [comment]
Okay, so far so good. I'm going to switch over `/external` shortly, and `/archive` over the weekend to the camh storage. I'll set the hal mounts as read-only and put them in `/mnt/hal`

**Comment by josephdviviano** [comment]
![ytmndog](https://cloud.githubusercontent.com/assets/4142570/14571456/515fa890-0317-11e6-942e-d66f77c3e277.jpg)

**Comment by pipitone** [comment]
Okay kids: `/external` and `/archive` are now mounts from CAMH storage. I'm syncing '/alumni` next. I suspect there are stacks of folders of dicoms in there which are making this take forever...

**Comment by josephdviviano** [comment]
@pipitone can you ping Jo from CompuCom to figure out where we stand with this?

**Comment by pipitone** [comment]
Okay, I've synced `/projects`. The sync takes about 2 hours if not much data is transferred (this is just the time it takes to inspect all of the files). This means we could actually use the CAMH storage as backup for `/projects` right now if we wanted, but we're still pretty good on space on `backup` for a little while longer. :-)

At this point, we have a complete copy of all of our data on the CAMH storage (keep in mind that `/projects`, and `/mnt/xnat` must be manually synced right now, and `/alumni` is not mounted from either tigrsrv or CAMH).

To keep all of this straight, I've updated the [Storage and Backup wiki page](https://github.com/TIGRLab/admin/wiki/Storage-and-Backup) with the latest on where all our data is and how it's being mounted on the workstations.

**Comment by josephdviviano** [comment]
+ I'm now using `/mnt/tigrlab` as a backup target.
+ No longer backing up to `backup` vm.
+ `backup` solely used for xnat going forward.
+ This ticket will be closed when we begin using `hal` as our backup target. At that point, people's daily work will happen on /mnt/tigrlab

**Comment by josephdviviano** [comment]
This is done.
