### ISSUE TITLE
scp fails

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#477]
Hi guys,

I have been trying to scp some files over to either my projects or scratch folder. But, I get the following error:

scp: /path/ Stale file handle

Is this temporary, or something that can't be resolved sometime soon?

Cheers,
Arash

**Comment by pipitone** [comment]
> I have been trying to scp some files over to either my projects or
> scratch folder. But, I get the following error: scp: /path/ Stale file
> handle

Can you try once more? If it still doesn't work, can you send me the
exact command you are running?

**Comment by arash-n** [comment]
#dumbmistake #mybad #non-issue!
