### ISSUE TITLE
Adjust project_settings.yml for DBDC

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#479]
There's a couple of things that should change but I wanted to double check with @pipitone or Steph about the protocol before setting anything.

Specific questions:
-Is there no NBK and no FLAIR planned?
-There's no DTI-29
-The count for RST should be 2
-Should the types of DTI she is doing be split into separate tags?
-what's EPI MID and EPI SID??

**Comment by pipitone** [comment]
Yeah, I just lazily copied the exportinfo from another project so that I could get data out for steph to see. Remind me again about where the `project_settings.yml` lives? 

Also, for reference, issue #455

**Comment by edickie** [comment]
inside the metadata/

**Comment by pipitone** [comment]
Done. I've updated `docs/` and the `README.md` with study information, and set the proper tag names in `exportinfo.csv` and `project_settings.yml`. At the moment, `qc-html` doesn't properly QC fMRI files if they are tagged unexpectedly, so MID/SID EPI task acquisitions don't show up in the QC doc.
