### ISSUE TITLE
buy SSDs for all of the workstations

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#482]
:dancer: :dancer: :dancer: :dancer: :dancer: :dancer:

**Comment by josephdviviano** [comment]
Hey @pipitone , we might not be able to do this easily unless you can sneak this onto the grant that expires at the end of the month. I don't think we have the money for this anywhere else. We would have to buy this tomorrow, basically, and then there’s a lot of work reinstalling every workstation. 

Do you think this is a good use of our time?

**Comment by MobileAppQueen** [comment]
I could always help out

**Comment by pipitone** [comment]
I'm closing this; doesn't seem worth the effort/benefit.
