### ISSUE TITLE
DTI QC paper for Sofia + Peter K

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#484]
+ Gather ENIGMA values for all participants in SPINS.
+ Run DTI QC pipeline on all participants in SPINS.
+ Get these values to PK by Thursday.

**Comment by josephdviviano** [comment]
Done!

**Comment by edickie** [comment]
Ummm, just wondering...did you look at the QC pages for these pipelines
before sending out the outputs?  I haven't QC any of these pipeline outputs
since the meeting last September...

**Comment by josephdviviano** [comment]
No I didn't. If you find anything you could let peter know... I'm sure a bad subject here or there won't wildly change peter's results.
