### ISSUE TITLE
The repeat scan RST scan for PRE07_MAS_R06013_01_01 is shorter than expected

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#485]
@josephdviviano was this intential - it's about ~170 TRs - which is a weird number

**Comment by josephdviviano** [comment]
@edickie Oh, that might be OK -- the repeat rest scans are ~ 5 minutes for prelapse. It looks like they scanned for slightly longer than necessary.

**Comment by edickie** [comment]
@josephdviviano @pipitone 

The variance in DTI signal looks a little funny (changes mid scan). I could use a second option...
/archive/data-2.0/PRELAPSE/qc/PRE01_CTN_TM14012_01/qc_PRE01_CTN_TM14012_01.html

**Comment by josephdviviano** [comment]
@edickie I agree this DTI scan looks funny.The SNR seems to jump in the second half of the scan. Furthermore it looks like they are collecting way too many B0s at the end (looks like an extra 9 B0s tacked on the the end ... we would prefer just 5 at the beginning), not to mention the B0s scattered throughout the scan. I'd bet they could get this scan done in significantly less time.

Could you please get in touch with them about this. Also, did they submit repeat scans?

**Comment by josephdviviano** [comment]
@edickie nevermind I'll write an email ccing you.

**Comment by josephdviviano** [comment]
Emails sent ... awaiting responses.
