### ISSUE TITLE
File /archive/data-2.0/JO-KNIGHT-GENES somewhere sensible

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#486]
What is this data? It needs some documentation and to be filed somewhere sensible. @edickie suspects it is related to the DTI study. Anyone know?

**Comment by josephdviviano** [comment]
@pipitone @edickie yes this is raw genetic data from DTI, evidence here:

```
libreoffice /archive/data-2.0/JO-KNIGHT-GENES/AV_2013W_B1-B4_AV01-93_HuGene1_RNAGeneChipReport.doc
```

I'm going to move this folder into DTI/CMH/data/genetics if everyone agrees?

**Comment by pipitone** [comment]
Yeah, that sounds about right. Thanks Joseph!

**Comment by josephdviviano** [comment]
Done/

**Comment by pipitone** [comment]
\o/
