### ISSUE TITLE
Make QC pages for tractography

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#488]
We need to make tractography QC html pages for VRMD. The QC should look at (1) bedpostx, (2) registration, (3) probtrackx and (4) BET on T1.

In addition to snapshots, we'd like something that will read the transformation parameter warning logs (e.g., "out of expected range") and display the transformed ROIs on the diffusion brain that are associated with the warning. This doesn't need to be tied into the processing scripts.

**Comment by pipitone** [comment]
![o rly](http://vignette3.wikia.nocookie.net/evchk/images/7/72/Orly.jpg)

**Comment by navonacalarco** [comment]
![image](https://cloud.githubusercontent.com/assets/13733654/14023418/a2d277ac-f1ba-11e5-94d2-deaf5a7ca2f1.png)

**Comment by josephdviviano** [comment]
Hey @navonacalarco , this is a pretty big ask. When do they need this by?

**Comment by navonacalarco** [comment]
Thanks for getting back to me. Ah, I didn't realize it was such a large task. I don't think that there's a super-pressing deadline, but it's definitely a priority in the lab. I'm going to try to figure out some things in the lab today (upstairs) that are related to this. Maybe we could meet at some point?

**Comment by josephdviviano** [comment]
Hi @navonacalarco , a priority in GFs lab, right? Is he willing to dedicated any personpower to this? I think we all have our plates full here, and the alternative method would be for one of his students to just QC their data.

**Comment by navonacalarco** [comment]
Yep, a priority in GF's lab, though AV is also involved in this project. OK- let's leave this open, but after talking to JDV, my next step is to figure out exactly what we want to look at in outputs of (1) bedpostx, (2) registration and (3) probtrackx.

**Comment by navonacalarco** [comment]
Thanks JDV- for some reason, I couldn't assign myself. 

If it's ok with the group, I'm going to try to install the "Spatial Anatomical" pipeline from [QAP package](http://preprocessed-connectomes-project.org/quality-assessment-protocol/) on Kimel or the SCC. It looks like we have all the dependencies to run it. 

Any thoughts you have on this would be very welcome, but I can take the lead. :)

**Comment by pipitone** [comment]
Take a look at the [qap branch of datman](https://github.com/TIGRLab/datman/tree/qap), I've created some helper code to make the input files needed for QAP from data-2.0-structured data/folders: https://github.com/TIGRLab/datman/blob/qap/assets/qap-subjectlist.py

**Comment by josephdviviano** [comment]
Hey Navona, does qap work on the bed port outputs

**Comment by navonacalarco** [comment]
@pipitone  thanks!

@josephdviviano  I haven't looked in detail at what it's doing behind the scenes, but I would think the QAP Anatomical would run bedpostx... however, QAP seems to be setup to work on raw files and generates all requisite files itself, so we wouldn't need to run bedpostx independently and then feed the output back in. I think. Let me take a closer look and get back to you.

**Comment by josephdviviano** [comment]
Hi @navonacalarco , OK sure, I'd read through the documentation though. I very much doubt the QC is run on the bestpostx part. I can't find any evidence from this: http://preprocessed-connectomes-project.org/quality-assessment-protocol/#spatial-functional

**Comment by navonacalarco** [comment]
Partial update: QAP is installed.

**Comment by navonacalarco** [comment]
Closing.
