### ISSUE TITLE
SSL Connection Error

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#489]
I couldn't open any webpages on Cajal on both Google Chrome and Firefox since I came back. I fixed this on Firefox by changing the proxy settings from manual proxy configurations to system proxy settings. I don't know how to make changes to Google Chrome and I really feel like using my favourite web browser!

**Comment by pipitone** [comment]
Hmm.. wonder why you have manual proxy settings? In any case, does this
help: https://support.google.com/chrome/answer/96815?hl=en

**Comment by josephdviviano** [comment]
@sabashahab is this still an issue?

Also we're not updating google chrome any longer. At some point it may be removed from our computers. Just a heads up.
