### ISSUE TITLE
DWIConvert Error: Size mismatch

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#499]
I get an error when I try to convert a subject's DICOM to Nrrd format using DWIConvert. I extracted the DICOM to my scratch folder and ran DWIConvert on that.

<b>Code:</b>

<code>DWIConvert -i /scratch/saba/Whole_Brain_Seeding/pt_AG06FEB1948 -o /scratch/saba/S047_dcmTonrrd/S047.nrrd</code>

<b>Error Message:</b>

<pre><code>Exception thrown while reading DICOM volume

itk::ExceptionObject (0x3e3b6f0)
Location: "unknown" 
File: /home/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
Line: 370
Description: itk::ERROR: ImageSeriesReader(0x17e317d0): Size mismatch! The size of  /scratch/saba/Whole_Brain_Seeding/pt_AG06FEB1948/E6977S4I1.MR is [256, 256, 1] and does not match the required size [128, 128, 1] from file /scratch/saba/Whole_Brain_Seeding/pt_AG06FEB1948/E6977S500I1.MR

Exception creating converter 
itk::ExceptionObject (0x3e3b6f0)
Location: "unknown" 
File: /home/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
Line: 370
Description: itk::ERROR: ImageSeriesReader(0x17e317d0): Size mismatch! The size of  /scratch/saba/Whole_Brain_Seeding/pt_AG06FEB1948/E6977S4I1.MR is [256, 256, 1] and does not match the required size [128, 128, 1] from file /scratch/saba/Whole_Brain_Seeding/pt_AG06FEB1948/E6977S500I1.MR</pre></code>

**Comment by josephdviviano** [comment]
Hi Saba, which subject is this? Does this happen for all subjects?

If the subject is in data-2.0, you shouldn't need to run DWIconvert by hand btw.

**Comment by sabashahab** [comment]
This subject is S047 - yes, this subject is in data-2.0. I'm not getting good tractography results for this subject and I want to see if there is a problem with the DICOM to Nrrd conversion so I'm re-doing the conversion for this subject. 

I just tried it on S081 and I get a completely different error:

W: DcmMetaInfo: Invalid Element (0008,1090) found in Meta Information Header
W: DcmMetaInfo: Invalid Element (0008,1140) found in Meta Information Header

**Comment by josephdviviano** [comment]
Please post your command.

**Comment by sabashahab** [comment]
DWIConvert -i /scratch/saba/Whole_Brain_Seeding/pt_TB25MAY1990/ --outputDirectory /scratch/saba/S163_dcmTonrrd/ -o S081.nrrd

**Comment by josephdviviano** [comment]
Hi Saba, I think you have all the dicoms for the different images mixed together in this folder (T1, T2, DTI, etc) Is that true? Where did you get these files?

If this is true, try downloading the raw data from xnat. I can set you up with an account if you need one.

**Comment by sabashahab** [comment]
I got the raw dicom from /archive/data-2.0/DTI/TGH/data/dicom/. Yes, it should be all the dicoms mixed together. 

Ok - I'll try downloading the raw data from xnat. Yes, please set up an account for me on xnat.

**Comment by sabashahab** [comment]
I downloaded the DTI dicom files from xnat and ran DWIConvert on them for S047. The nrrd files were created without any errors. Thanks Joe!

**Comment by josephdviviano** [comment]
My pleasure!
