### ISSUE TITLE
Problems with the queue

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#502]
I get an error message when I try to run the following code:

<b>Code:</b>

<code>while read SID; do sge_batch /projects/saba/Useful_Scripts/wma_applyToSubject.sh $SID /scratch/saba/S001_newCode_Test /scratch/saba/new_DTI1/wma_output/clustered_atlas_k500/iteration_00002/initial_clusters/atlas.vtp /scratch/saba/new_DTI1/wma_output/clustered_atlas_k500/iteration_00002/initial_clusters/clustered_tracts_display_100_percent_mod.mrml; done < /tmp/cluster</code>

<b>Error:</b>
<code><pre>
Unable to initialize environment because of error: can't resolve group
Exiting.
ERROR closing pipe to qsub: 

Unable to initialize environment because of error: can't resolve group
Exiting.
ERROR closing pipe to qsub: 

Unable to initialize environment because of error: can't resolve group
Exiting.
ERROR closing pipe to qsub: 

Unable to initialize environment because of error: can't resolve group
Exiting.

</code></pre>

**Comment by josephdviviano** [comment]
This sounds like an @pipitone problem.

**Comment by sabashahab** [comment]
qstat gives me the following message: "critical error: can't resolve group"

**Comment by sabashahab** [comment]
while read SID; do sge_batch sh /projects/saba/Useful_Scripts/wma_applyToSubject.sh $SID /scratch/saba/S001_newCode_Test /scratch/saba/new_DTI1/wma_output/clustered_atlas_k500/iteration_00002/initial_clusters/atlas.vtp /scratch/saba/new_DTI1/wma_output/clustered_atlas_k500/iteration_00002/initial_clusters/clustered_tracts_display_100_percent_mod.mrml; done < /tmp/cluster

**Comment by pipitone** [comment]
@sabashahab , can you run the following command (will take some time) and then rerun your code to see if this helps: 

    chgrp kimel -R /scratch/saba

**Comment by sabashahab** [comment]
Didn't help - still getting the same error

**Comment by pipitone** [comment]
Strangely, I just ran your code in `cajal:/scratch/saba` as `saba` and it submitted jobs just fine. I guess you were able to fix it?

**Comment by pipitone** [comment]
K, I'm closing this. Saba, reopen this issue if there is still a problem.

**Comment by sabashahab** [comment]
@pipitone, sorry for the late response - I just saw your message. Nope, it still doesn't work but I don't need it right now. I'll re-open this issue when I need to use the queue again.
