### ISSUE TITLE
stop ansible from opening all the slots on all of the machines on the queue

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#503]

**Comment by pipitone** [comment]
As a pointer, the config for a host happens in `roles/gridengine-exec/tasks/main.yml`.  It's currently set to use 4 slots per machine...

**Comment by josephdviviano** [comment]
That's what I just changed now. Before, it was set to 24 for some reason... the equation we had in there was not working properly.

Now im debugging why ssh is failing between all of the machines with ansible only, but not as a user.

**Comment by josephdviviano** [comment]
I've hard coded the number of slots on each machine to 4.

**Comment by pipitone** [comment]
Ah, we had it set to `# of hyperthreaded cores - 4` before.

**Comment by josephdviviano** [comment]
Yes, but I think it was reading the number of hyperthreaded cores off of tigrsrv, or something, because every machine received 24 slots, but I know for sure not all the machines have 24 hyperthreaded cores.
