### ISSUE TITLE
rsync from scinet to new storage not working for me yet

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#506]
I could be doing something not right...

rsync -av /scratch/a/arisvoin/edickie/ABIDE/fix_training_data edickie@192.197.205.74:/external/rprshnas01/tigrlab/scratch/edickie/ABIDE/fix_training_data
Password: 
sending incremental file list
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: mkdir "/external/rprshnas01/tigrlab/scratch/edickie/ABIDE/fix_training_data" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(576) [receiver=3.0.6]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]

**Comment by pipitone** [comment]
I suspect the node you are connecting to is not the management node.  Will have to talk with Andy about the possibility of mounting our storage on whatever node this is (I suspect login node).

**Comment by pipitone** [comment]
For future reference, the tigrlab folder on the login node is here: `/external/rprshnas01/tigrlab`
