### ISSUE TITLE
FSL 5.0.9

### ISSUE THREAD

**Issue by tina-roostaei** [TIGRLab/admin#507]
Hi, 
It recently occurred to me that there are some new scripts and options in FSL 5.0.9 that are useful for estimating FA from HCP data, subsetting the b=1000 values from their multi-shell diffusion data, ...; and there are also other scripts that I think might be useful to others too. 
I was wondering is there any chance that we can have FSL 5.0.9 on the Kimel cluster?
Thanks,
Tina

**Comment by pipitone** [comment]
> I was wondering is there any chance that we can have FSL 5.0.9 on the Kimel cluster?

Sure thing.

**Comment by pipitone** [comment]
Done.
