### ISSUE TITLE
Do we need anything in /external/filetransfer? 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#510]
@josephdviviano  would you mind having a look... there is some SPINS stuff in there you might recognize best.  I suspect it's all redundant at this point.

**Comment by pipitone** [comment]
Ditto with /external/camh_mr

**Comment by josephdviviano** [comment]
Hey @pipitone no problem doing it now. Looks like stuff that is over a year old approximately so far... all the filetransfer stuff was from the FTP server.

**Comment by josephdviviano** [comment]
I'm copying the files from /external/filetransfer/UHN/home/UHN into /archive/data-2.0/DTI/TGH/data/zips ... I don't think we have all of these data in xnat yet.

**Comment by josephdviviano** [comment]
@pipitone I've saved some missing scans from the uploads! You can safely delete those folders.

Except, I have no idea what is in `/external/filetransfer/transferuser/home/transferuser`. Can we store this for future searching?

**Comment by josephdviviano** [comment]
@pipitone I've just deleted `camh_mr`

**Comment by josephdviviano** [comment]
@pipitone I'm closing this ... all I ask is that you store the contents of `/external/filetransfer/transferuser/home/transferuser` somewhere safe for future snooping.

**Comment by pipitone** [comment]
er... that folder has nearly 450G of data in it... 

I've moved it to `/external/old_ftp_server_data`. I think we need @drotenberg and Steph to take a look. I'm going to reopen the issue until we have this nailed down.

**Comment by josephdviviano** [comment]
Hey @pipitone , curious if the majority of that data is the MEG data? That stuff is data Steph wanted me to analyze and we should have it in the Data-2.0 folder IF it isn't also there ... we might have a duplicate (worth an rsync to be sure).

**Comment by pipitone** [comment]
```
$ du -hs * | sort -hr
304G    Benchmark_Data
88G     MEG_RestingState
32G     Restricted/
16G     TBSS_POND_Ameis
515M    COGENT
1.6M    mr_protocols
```

Me thinks `Benchmark_Data` was used to evaluable the prospective CAMH storage options and can probably be deleted.

**Comment by josephdviviano** [comment]
@pipitone that makes sense, you reminded me about david asking for some arbitrary DICOM data.

**Comment by josephdviviano** [comment]
I think you know more about this than I do at this point, I'm not sure what to do :)

**Comment by pipitone** [comment]
![beleted](http://www.hrwiki.org/w/images/thumb/c/cc/deleted.PNG/180px-deleted.PNG)
