### ISSUE TITLE
USBs not automounting on hebb

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#513]
Melissa is seeing this on `hebb`.. GVFS doesn't seem to know about her USB, but I can mount manually.

**Comment by josephdviviano** [comment]
@pipitone having this same problem on tesla.

I've noticed this for years ... happens if people never log out.

One fix would be for us to reinstall Ubuntu's UI -- looks like this might be an `xfce` bug: https://bbs.archlinux.org/viewtopic.php?id=119992

**Comment by josephdviviano** [comment]
i just used teh rebootz
