### ISSUE TITLE
Certain users aren't able to login to laplace using lightdm 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#514]
This appears in the logs and they get booted back to the login screen: 

```
Apr 20 13:48:44 laplace lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "yuliya"
Apr 20 13:48:49 laplace lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost=  user=yuliya
Apr 20 13:48:53 laplace lightdm: pam_sss(lightdm:auth): authentication success; logname= uid=0 euid=0 tty=:0 ruser= rhost= user=yuliya
Apr 20 13:48:53 laplace lightdm: pam_unix(lightdm-greeter:session): session closed for user lightdm
Apr 20 13:48:53 laplace lightdm: pam_unix(lightdm:session): session opened for user yuliya by (uid=0)
Apr 20 13:48:53 laplace lightdm: pam_mkhomedir(lightdm:session): unknown option: mask=0077
Apr 20 13:48:53 laplace systemd-logind[815]: Removed session c47.
Apr 20 13:48:53 laplace systemd-logind[815]: New session c48 of user yuliya.
Apr 20 13:48:53 laplace systemd-logind[815]: Linked /tmp/.X11-unix/X0 to /run/user/648/X11-display.
Apr 20 13:48:53 laplace systemd-logind[815]: Removed session c48.
Apr 20 13:48:54 laplace lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Apr 20 13:48:54 laplace lightdm: PAM adding faulty module: pam_kwallet.so
Apr 20 13:48:54 laplace lightdm: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
Apr 20 13:48:54 laplace lightdm: pam_mkhomedir(lightdm-greeter:session): unknown option: mask=0077
Apr 20 13:48:54 laplace systemd-logind[815]: New session c49 of user lightdm.
Apr 20 13:48:54 laplace lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Apr 20 13:48:54 laplace lightdm: PAM adding faulty module: pam_kwallet.so
```

**Comment by josephdviviano** [comment]
I'm going to try updating the machine and restarting lightdm

**Comment by josephdviviano** [comment]
@pipitone any ideas? It does seem pam is misbehaving on multiple machines, including the home folder issue ... do you think these are related?

**Comment by pipitone** [comment]
This line seems to hint at the issue: 

    Apr 20 13:48:54 laplace lightdm: pam_mkhomedir(lightdm-greeter:session): unknown option: mask=0077

Google turns up [an old issue with lightdm](https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/956848). The have a fix to add `silent` in the pam config line. I'd first try to reproduce this problem, and then see if silent fixes it (seems a long shot considering how old the issue is). 

I was definitely able to log in a user without a home folder and have it created over the console but I didn't try over lightdm.

**Comment by pipitone** [comment]
Just tried this with lightdm on `mrsdti` and had no problems logging in: 

1. Logged out of my session
1. Logged in on the console
1. Moved my home folder out of the way: `mv /home/jpipitone /home/jpipitone.old`
1. Switched back to lightdm and logged in. My home folder was created.

I'm closing this but we can reopen if it reoccurs.
