### ISSUE TITLE
Move XNAT over to CAMH network

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#517]
As part of the move off the PET network (#476), the XNAT server needs to move, and can move immediately. Here's what I suggest: 

- [x] Verify with Qing/Andy/David that our external CAMH IP address will remain routed via the SCC firewall, or generally what the plan is, because there has been some talk of changing the SCC firewall situation (I'm just not sure exactly how). 
- [x] Clone the existing XNAT VM (or build a new, identical one) configured to use the CAMH network (there is a virtual switch for this), and mount a read-only copy of the xnat filesystem *from* `kimsrv` (this decouples us from tigrsrv, also). 
- [x] Prepare a backup process for syncing data from `kimsrv` to the CAMH storage via the CAMH network. 
- [x] After testing, cut over to the CAMH-network VM, and destroy the PET-network VM.

**Comment by josephdviviano** [comment]
Hi @pipitone, sounds like a foolproof plan to me, and I'd like to be involved.

**Comment by pipitone** [comment]
Great! Let me know if you need a hand with any of it. I'll dig up the routing info for our public IP address and stick it in `/projects/admin` somewhere.

**Comment by pipitone** [comment]
More info. Turns out I actually asked David about the static IP a few weeks ago. I asked whether it would be possible to move it over to the CAMH Research VLAN and his answer was: "It can certainly be arranged to make this change so that the external IP/ports are mapped to a new 'Research VLAN' static IP. The correct way to pursue and coordinate an IP change like this would be a direct email to 'service desk'" (check the tigrlab email for more info. 

So, the fact he didn't mention any changes to the SCC DMZ probably means we won't be affected in the near future. I'm marking that item as done.

**Comment by josephdviviano** [comment]
```
cat "It can certainly be arranged to make this change so that the external IP/ports are mapped to a new 'Research VLAN' static IP. The correct way to pursue and coordinate an IP change like this would be a direct email to 'service desk'" | tr 'dr' 'jdv'

> To map your external IP/ports to a research VLAN static IP, email IMG's service desk. 
```

**Comment by pipitone** [comment]
^ wut

In other news, I've updated `/projects/admin/secrets/servers.md` with the relevant routing info. You'll have to poke around esxi to find the CAMH switch (there may be a VM already configured).

**Comment by josephdviviano** [comment]
I'm translating rotenish.

**Comment by pipitone** [comment]
![:D](https://media.rbl.ms/image?u=%2Fhphotos-xtp1%2Fv%2Ft1.0-9%2F1918579_352342302244_2670650_n.jpg%3Foh%3D4323c37d496413acf950a5b1cb6a98b1%26oe%3D56087F89&ho=https%3A%2F%2Fscontent.xx.fbcdn.net&s=4&h=0864d64282c1b8027748cb067e3734866ed4ffdcfd66c4340c593e7544cfb343&size=980x&c=3561504832)

**Comment by josephdviviano** [comment]
I used this to clone the VM... http://www.dedoimedo.com/computers/vmware-esxi-clone-machine.html

**Comment by josephdviviano** [comment]
On srv-xnat (the clone and new version of xnat), I've disabled the RIC web connection:

MAC: `00:0c:29:f4:86:b9`
ADAPTOR: `WMXNET 3`
`eth0-RIC`

I'm going to take down xnat and remove the CAMH network adaptor too, so they can be online simultaneously without interfering with eachother.

**Comment by josephdviviano** [comment]
New plan ... im just moving the old VM over... easier.

However I dont think I have enough information to configure the network connections . This is what I have:

auto eth1
iface eth1 inet static
        address 192.168.216.2
        netmask 255.255.255.0
        network 192.168.216.0
        broadcast 192.168.216.255
        gateway 192.168.216.1
        dns-nameservers 172.28.216.52
        dns-search camhres.ca

**Comment by josephdviviano** [comment]
I think I need @pipitone to look at this *with* me, because the instructions left here aren't complete.

**Comment by pipitone** [comment]
Sure thing. Can you describe what you've done so far and what the problem is?

**Comment by pipitone** [comment]
Partially complete. We have the VM running on both networks now. Details can be found in `/projects/admin/secrets/servers.md` on exactly how we configured tomcat for the moment. This will change when we move over to the CAMH network, and when we have the appropriate ports (80/443) open externally.

**Comment by pipitone** [comment]
We have another issue: we cannot route to the research IT network so we cannot mount CAMH storage. Options: 

1. IIRC we have our own subnet on the SCC firewall that should route correctly. Will need to speak to Research IT bros to confirm
1. We could request a firewall change to allow routing.. if that is not possible (security-wise) then...
1. We can use storage local to kimsrv (e.g. we could mount the backup drives).

**Comment by pipitone** [comment]
IMG says we should be able to route to research IT from the webserver, but I cannot, and the routing table looks a-go-go. Will either open a ticket and/or try setting up a different nic on the same VLAN.

**Comment by pipitone** [comment]
As an update, I've filed an issue to get access from the the webserver to the CAMH storage.

**Comment by pipitone** [comment]
@josephdviviano mentioned some reluctance to access the CAMH storage from the webserver (the issue to allow this access is still wending its way through CAMH IT pipes), so another solution is to use our current backup ZFS drives as storage (and they would be local to kimsrv). I can see two ways to do this: 

1. Configure the backup server to share the ZFS `tank/xnat` filesystem over NFS, and mount that on the webserver in place of the one we're mounting from tigrsrv now. This share could be made available over a private network configured in ESXi between the webserver and backup machine. 

2. Move the ZFS drives from the `backup` machine to the webserver. I've documented how I've exposed the ZFS devices to an ESXi via "device passthrough" over [here on the wiki](https://github.com/TIGRLab/admin/wiki/EXSI:-Our-VMs-on-Kimsrv#exposing-zfs-to-the-backup-vm).

**Comment by pipitone** [comment]
Update: there is now access from the webserver to the CAMH storage.

**Comment by josephdviviano** [comment]
This is done.

I'm still mounting the `zfs` drives on srv-web via backup instead of having them all on the same VM. When we sort out the new backup scheme I'll look into this migration (Opening a new ticket for that particular issue).
