### ISSUE TITLE
Complete the IT plan so we can intelligently make CFI purchases

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#52]
https://docs.google.com/document/d/1svkjttCK8LT1DAMqFrTOgGlKUcafMDIl_qhGN2CkRuk/edit

**Comment by pipitone** [comment]
I perhaps didn't mention this, but in talking with Terry he confirms that the power supply on the rack in 107 is definitely *not* a UPS, so we will definitely need to buy our own.

**Comment by djrotenberg** [comment]
Thank you Jon! That is rather important. 

We are waiting on re-quotes on the IBM storage arrays and tape library (as they were certainly overvalued), but have approval for the SAS HBAs and can submit these at any time. I'll extend further requests for an UPS.

**Comment by pipitone** [comment]
We're going with CAMH storage, and we have a compute node on order. Closing this.
