### ISSUE TITLE
queue / ansible is STILL setting all machines to 24 slots

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#521]
@pipitone I think it is your turn to look at this.

**Comment by josephdviviano** [comment]
I might have found the culpurit ... `qconf -mq main.q` showed slots set to 24, I wonder if these global settings override the ones we have in ansible...

**Comment by josephdviviano** [comment]
@pipitone the change appears to have worked. Not sure if we want to ansible this (happy to talk about it).

**Comment by josephdviviano** [comment]
Turns out this is still a problem... had to edit this file in ansible to fix things:

`/projects/admin/ansible-playbooks/roles/gridengine-master/files/main.q.conf`

**Comment by pipitone** [comment]
Okay, I made a few changes that I think are going to work better in the long run: 
- set `main.q` slots to something large (100). This appears to be the maximum number of lots available to this queue and *not* slots per host (that is, I don't see more jobs running than there are slots specified in in the host's complexes (below), and when the queue's number of slots was 16, only 16 jobs could run in total)
- set the slots per host to *#cores / 2* (in ansible speak, it's `{{ (ansible_processor_cores*ansible_processor_count/2) | int }}`

**Comment by josephdviviano** [comment]
@pipitone cool, will see how this pans out. 

one thing I've noticed. With each run of ansible, a different subset of our total cluster is visible in qmon. So every time we run ansible, we take some subset of machines off of the queue. Not a showstopper, but odd.

**Comment by pipitone** [comment]
I'll have to check the ansible scripts to be sure but it wouldn't surprise me if running the sge master role nukes all of the host groups and then it's only when the hosts themselves are run (gridengine-exec role) that they are added back. The gridengine command line tools are notoriously hard to script around idempotently but I'm sure we can do better. If you want to take a stab at it I can walk you through the current process.
