### ISSUE TITLE
CAMH/PET unable to access to the lab website

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#523]

**Comment by josephdviviano** [comment]
email sent to qing and alan

**Comment by josephdviviano** [comment]
This was fixed. According to the email chain --

It looks like it is fixed.

Thanks,
Qing
________________________________________
From: Alan Tang [Alan.Tang@camh.ca]
Sent: Thursday, May 05, 2016 1:05 PM
To: Qing Chang
Cc: Joseph Viviano; TIGR Lab; Jon Pipitone
Subject: Re: http://imaging-genetics.camh.ca/ inaccesible from CAMH / PET network

Hi Qing,

We've had the Service desk fix the DNS entry. Can you test and see if this fixes the issue?

Thanks.

'''''''''''''''''''''''''''''''''''''''''''''
Alan Tang
Team Lead - Web & Portal
''''''''''''''''''''''''''''''''''''''''''''''''
