### ISSUE TITLE
MATLAB license error

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#524]
Hey guys,

It appears that MATLAB licenses don't work anymore. 

Here is the error I am getting:

License path: /home/arash/.matlab/R2012b_licenses:/opt/quarantine/matlab/R2012b/build/licenses/license.dat:/opt/qu
arantine/matlab/R2012b/build/licenses/network.lic 
Licensing error: -15,570. System Error: 115

Any help is highly appreciated.

Cheers,
Arash

**Comment by pipitone** [comment]
Sorry about that. I've started the license server.

**Comment by arash-n** [comment]
Thanks Jon!

:)

**Comment by josephdviviano** [comment]
Note to self: put this in crontab to do automatically on reboot

**Comment by pipitone** [comment]
I got ya bro: `/etc/cron.d/matlab-license-server`
