### ISSUE TITLE
backups are not running

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#525]
@pipitone could you please have a look? (same thing we talked about Friday).

**Comment by pipitone** [comment]
I ran the backup manually on Friday, so your project folder (and everyone elses) should have at least been backed up then. I'm still trying to figure out why the backup isn't running regularly -- the cronjob is there...

**Comment by pipitone** [comment]
I fixed the mounts on `backup`, and may have figured out why the backup wasn't running: the backup script bails if any of the source folders aren't mounted (since syncing an empty folder with `--delete` would be bad), but because `/archive` is now a symlink the backup script ditches early. 

I've rejigged the backup script and I'm rerunning it now.

**Comment by josephdviviano** [comment]
@pipitone nice, good find.

**Comment by pipitone** [comment]
Aaaaand `/mnt/tigrlab type nfs (rw,hard,intr,fg,tcp,timeo=5,retrans=5,actimeo=10,retry=5,vers=3)` is hung. 

<img src="https://media.giphy.com/media/xTiTnhatybqmUy5ZaE/giphy.gif" height="200px"/>

**Comment by pipitone** [comment]
A few notes. 

```sh
localadmin@backup:~$ sudo grep nfs /var/log/syslog 
May  3 09:30:47 backup kernel: [74505.779405] nfs: server rprshnas01.camh.ca not responding, still trying
May  3 09:37:49 backup kernel: [74928.221825] nfs: server rprshnas01.camh.ca not responding, still trying
May  3 09:39:20 backup kernel: [75018.923984] nfs: server rprshnas01.camh.ca not responding, still trying

localadmin@backup:~$ # but...
localadmin@backup:~$ sudo mount -t nfs rprshnas01.camh.ca:/tigrlab/tigrlab /mnt/tigrlab2
localadmin@backup:~$ ls /mnt/tigrlab2/
alumni  archive  external  projects  scratch  test  xnat
```

To read: [RHEL mount hangs: nfs: server [...] not responding, still trying](https://access.redhat.com/solutions/28211). 

Also: `backup` is not configured for IPA.

**Comment by pipitone** [comment]
Looks like the backup script fix did the trick. We didn't get an email last night because of how much rsync output there was. I've removed the `-v` flag.
