### ISSUE TITLE
Jobs not running on the queue

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#532]
My jobs have been on the 'qw' state for a long time now. This is what I get from "qstat -j 110076"

<code><pre>scheduling info:            queue instance "main.q@hebb.camhres.ca" is in suspend alarm: np_load_avg=1.777500 (= 1.777500 + 0.50 * 0.000000 with nproc=4) >= 1.0
                            queue instance "main.q@mansfield.camhres.ca" is in suspend alarm: np_load_avg=1.008125 (= 1.008125 + 0.50 * 0.000000 with nproc=16) >= 1.0
                            queue instance "main.q@golgi.camhres.ca" is in suspend alarm: np_load_avg=3.397500 (= 3.397500 + 0.50 * 0.000000 with nproc=4) >= 1.0
                            queue instance "main.q@crick.camhres.ca" dropped because it is disabled
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "franklin.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "davinci.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "talairach.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "nissl.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "compute01.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "penfield.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "cajal.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "kandel.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "lovelace.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "laplace.camhres.ca" because it offers only hc:h_vmem=3.618G
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "milner.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "tesla.camhres.ca" because it offers only hc:slots=0.000000
                            (-l h_vmem=6G,mem_free=6G) cannot run at host "mrsdti.camhres.ca" because it offers only hc:h_vmem=3.618G
</pre></code>

**Comment by josephdviviano** [comment]
hmm. I recently made some edits to the queue... should be 4 slots, not 0. let me have a look.

**Comment by josephdviviano** [comment]
They were / are running, just not fast enough for conference deadlines.
