### ISSUE TITLE
figure out why the blacklist is not working for ASDD

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#537]
Scans that I blacklist in ASDD keep showing up back on our file system...
I guess we should debug and figure out what's going on...

**Comment by edickie** [comment]
Wait..the run script isn't using the blacklist option..lolz...

**Comment by edickie** [comment]
Wait - we should fix this and re-blacklist stuffs...

**Comment by navonacalarco** [comment]
![image](https://cloud.githubusercontent.com/assets/13733654/15131860/babe84ec-1621-11e6-82fb-da8d9b9cb979.png)

**Comment by edickie** [comment]
The run scripts are not using the blacklist for this study...this will be fixed once we update the runscripts in moving to the scc
