### ISSUE TITLE
figure out why RESOURCES are missing for PACTMD_CMH_3060049_01

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#538]
We have no tech notes or SPIRALS for this scan..

**Comment by josephdviviano** [comment]
They're in the .zip from the MR server. I'm going to delete the subject from XNAT... should get re-uploaded tonight.

**Comment by josephdviviano** [comment]
They got regenerated... see here:

`/archive/data-2.0/PACTMD/data/RESOURCES/PACTMD_CMH_3060049_01_01/20160510_083933/20160421_Ex05318_PACT1MR_PALW100`

**Comment by edickie** [comment]
Thanks JDV we just need to regenerate the QC then...
