### ISSUE TITLE
delete duplicate STOPPD session

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#539]
It appears that STOPPD_NKI_16007_01 is  a mis-named duplicate of STOPPD_NKI_160007_01.

We should investigate and delete if so..

**Comment by josephdviviano** [comment]
Hey Erin, I think I've already deleted STOPPD_NKI_16007_01 from XNAT, if you want to clear them off the filesystem, they shouldn't get regenerated.

**Comment by edickie** [comment]
Cools thanks for letting me know!

**Comment by edickie** [comment]
done
