### ISSUE TITLE
Ask NWN why we still don't see repeats

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#541]

**Comment by josephdviviano** [comment]
@edickie please flesh this out with details (including funny scans i.e. leg scan lol)

**Comment by edickie** [comment]
another email sent

**Comment by djoverton** [comment]
@edickie Hey Erin, has this been resolved?

**Comment by edickie** [comment]
Sent an email again today.. I suspect that the last "missing" repeat was not collected. But I'll wait for them to confirm

**Comment by djoverton** [comment]
Can I close this?

**Comment by josephdviviano** [comment]
@edickie you are still leaving issues open ...

**Comment by edickie** [comment]
another email sent 3 days ago...this is not yet resolved

**Comment by josephdviviano** [comment]
@edickie how's this going?

**Comment by edickie** [comment]
We got confirmation  a while ago that we have all the data (some scans didn't really happen). Sorry for taking so long to remember to close this one.
