### ISSUE TITLE
come up with a system for keeping scan notes (normally in scan completed email)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#548]
We need some way of attaching one-off notes, that have typically been included in scan completed emails, to the XNAT uploads.

We also need a way to verify that all of the collected data has been uploaded to XNAT.

The proposed solution:

+ RAs no longer send scan completed emails.
+ RAs are responsible for logging into XNAT 1 week after upload to ensure the data makes it into XNAT.
+ RAs then paste the text we would normally receive in scan completed emails in this text field box:

![screenshot from 2016-05-11 15 17 46](https://cloud.githubusercontent.com/assets/4142570/15193375/a073e3c8-178b-11e6-96a5-dba0f7988411.png)

+ `datman` will extract this text into a markdown / similar file into `data-2.0`. This information could eventually be imported into a redcap or similar database.

Discussion below @pipitone @navonacalarco @edickie

**Comment by edickie** [comment]
I'm in favor of a sightly different solution:
+1 RA's no longer send scan completed emails
- RA's instead submit a RedCap database form
+ Short term: the RedCap database is periodically checked against our file system
- Long term: the RedCap data is automatically checked-against our file system
- Longer term: the RedCap data is automatically synced with XNAT
 
navona was kind enough to through the RedCap form together for us...
..maybe we should have RedCap send emails to people who like getting emails....?

**Comment by navonacalarco** [comment]
Here's the form: https://edc.camhx.ca/redcap/surveys/?s=TD3NWTLDXL

Theoretically, we can use the API to synced things with XNAT, though there's currently issues with the CAMH production API, and I'm not exactly sure how to set it up (but think it should be possible).

**Comment by josephdviviano** [comment]
@navonacalarco @edickie this scan completed form --- is this for all studies managed by AV? Or is there a different form for each study?

**Comment by navonacalarco** [comment]
@josephdviviano It's the same form for all studies managed by AV. 

![image](https://cloud.githubusercontent.com/assets/13733654/15255654/583bd526-190b-11e6-8595-919784587116.png)

**Comment by josephdviviano** [comment]
@navonacalarco Will the scientists be able to access this database easily?

**Comment by navonacalarco** [comment]
Sure! We can set something up so that they receive an email with the data each time a survey is completed (akin to the current 'scan completed' arrangement), or we could set up an automated weekly report, or they could go in to the database periodically on their own accord and review. We can also send information related only to the PIs own study, or all studies.

**Comment by josephdviviano** [comment]
@navonacalarco this does sound like a good solution... is this a new thing? I wasn't aware we had this.

**Comment by navonacalarco** [comment]
It's through REDCap. I hadn't fiddled around with the automated survey stuff before this month. But it looks like it should do what we need. I'm in the midst of setting up something similar for another project - I can show you guys what everything will look like before we go ahead.

**Comment by josephdviviano** [comment]
@navonacalarco , I think your redcap solution is best. I'm going to assign this issue to you but please ask for help if you need it.

**Comment by navonacalarco** [comment]
OK great. The REDCap form exists; as I see it, there are the next steps:

- [ ] 1. Make sure I have a correct list of each study's PI and RA, who will get an email confirming the survey submission when the scancompleted survey is submitted
- [ ] 2. Email all RAs on the scancompleted list to start using it instead
- [ ] 3. Set up a REDCap 'data entry trigger' to fill in the XNAT 'Additional Notes' box via the API. 

Unfortunately, the API is not working on the CAMH production server, and IMG is still sorting this out

Can we briefly look over the REDCap survey together before we send it out?

Thanks,
N.

**Comment by navonacalarco** [comment]
Update: everything is working on the CAMH REDCap API now, so we can/ should move forward with this.

**Comment by navonacalarco** [comment]
@djoverton Wondering if you want to help with this project, which is basically migrating our 'scan complete' emails to an online survey (hosted by REDCap), and having that survey data feed into our database (XNAT).

This can be done by something called a 'Data Trigger' in REDCap parlance, or by setting up a cron job. When we first discussed this idea, some of the survey functionality in REDCap wasn't working, but now everything seems good to go, so we just have to write the code. It can be in Python.

Are you interested?

**Comment by josephdviviano** [comment]
@navonacalarco where are we at with this? What has / has not been done?

**Comment by navonacalarco** [comment]
@josephdviviano I need help with the script to get REDCap to feed into XNAT.

But, we can go ahead with the REDCap portion now. Especially with the increasingly common linking of participant files, I think we need to get important info (like shared participant IDS) into a database, rather than those 'scan completed' emails.

I'll send around an example survey form for you guys later today!

**Comment by josephdviviano** [comment]
Aren't RAs doing that already (putting the scan completed info in the database).

**Comment by navonacalarco** [comment]
Nope.

**Comment by josephdviviano** [comment]
Ok so all of this still needs to happen:

- [ ] Make a redcap form.
- [ ] Get a correct list of each study's PI and RA, who will get an email confirming the survey submission when the scancompleted survey is submitted
- [ ] Email all RAs on the scancompleted list to start using it instead
- [ ] Set up a cronjob to run a simple REST command to push the notes field in REDCAP into the XNAT notes field.

We don't need the API for this, so long as we can auto download the redcap data as a CSV. Also, we really don't need to get the data from redcap into xnat, but we do need people to start using redcap. Can you can handle the first three steps on your own?

**Comment by navonacalarco** [comment]
We have the REDCap form and (perhaps now outdated) list of PIs and RAs, and I have a drafted email to start using this. So, that part is ready/ nearly ready to go.

Dawn is helping with the REST.

**Comment by navonacalarco** [comment]
OK, REDCap [survey]( http://tinyurl.com/scancompletedl) has been sent out and is being reviewed by RAs. Am going to close this issue; will make new issues with @DESm1th regarding REST command if arises.
