### ISSUE TITLE
Run script errors (clevis and PET centre not friends)

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#549]
There are many cases in today's run- script log (2016-06-13-run.log) of 
"Couldn't read packet: Connection reset by peer"

Does the PET centre hate clevis??

**Comment by pipitone** [comment]
Very probably. :-)

I'm going to try running this by hand to see if I can isolate the problem. It's probably with the pet/mr-ftp connection.

**Comment by pipitone** [comment]
Running the run.sh scripts by hand, as clevis, on tigrsrv, results in 0 errors. 

Conclusion: PET network hates us.

**Comment by pipitone** [comment]
Nevermind, rerunning the scripts several times causes trouble. I think we're being rate limited. Let me look into it.

**Comment by pipitone** [comment]
Hate confirmed. From Qing: 
> I have put in a firewall rule to deal with ssh brute force attack: with in a minute, if there are three connection attempts from the same IP to port 22, the fourth will be dropped and continue...

I've added some sleeps into the master run.sh script and the DTI/CMH script which makes two attempts for different booking codes. This should solve the problem.

Reopen if still happens. You can rerun these scripts by hand now, but leave a minute between attempts to avoid connection drops.

**Comment by josephdviviano** [comment]
@pipitone I was thinking fail2ban or similar?
