### ISSUE TITLE
Install SSD in riker properly

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#55]
Currently we have the SSD with the OS on it installed into one of the front bays of `riker` because there is place to mount it internally. We should find a way to mount it inside, and remount the SAS drive in the front bay so we can have more storage capacity. 

Ideas: 
- Buy the proper Dell rear backplane for the server (~$600)
- Mount the drive via the CDROM SATA connections

To do the latter, we'll need to get power to the drive somehow. There should be a way, but this might involve a call to Dell tech support or a close scan through the manual to find out how.

**Comment by josephdviviano** [comment]
Is this still an actual issue? It's 1.5 year old, and now seems irrelevant (and expensive) given how our storage capacity is going to work going forward. I'm closing, @pipitone reopen if you disagree.
