### ISSUE TITLE
biobank registration

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#556]
https://amsportal.ukbiobank.ac.uk/SitePages/Home.aspx

+ looks like I need to get Aristotle to register before we can submit a full application

**Comment by arash-n** [comment]
I just got my registration. Did you have any success having Aristotle registered.

Cheers,
Arash

**Comment by josephdviviano** [comment]
It's on the list of things to do -- I need him to register or something,
because I can't be the PI on this project.

JDV

**Comment by josephdviviano** [comment]
cv needed for registration: `/home/jviviano/documents/admin/`

**Comment by josephdviviano** [comment]
Registration submitted for AV. After approval we can move forward.

**Comment by josephdviviano** [comment]
@arash-n do you still need this?

**Comment by arash-n** [comment]
Yes....! It would be great if we could have this. There are many great imaging/genetics opportunities in there (n=5000 and growing).

**Comment by josephdviviano** [comment]
I'm leaving this in other's hands -- it's up to them to come up with a proposal and submit it.
