### ISSUE TITLE
files on scratch aren't immediately available to all machines on the queue

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#560]

**Comment by pipitone** [comment]
Are there specific machines you want it mounted on?

**Comment by josephdviviano** [comment]
not sure yet

**Comment by pipitone** [comment]
Hmm.. If you tell me more about what this issue is, I can take a look. 

At the moment, it looks like scratch is mounted on all of the workstations (except for kandel, nissl, dti, and lovelace which are currently not accessible over ssh), and servers except backup and srv-web. I determined this using ansible like so:

    ansible -m shell -a 'mount | grep scratch' all --one-line

**Comment by josephdviviano** [comment]
yeah i havent really looked into it except that it seems like running tbss_2_reg on the queue fails because the .commands folder generated on one machine isn't seen by all of the machines on the queue. 

could be a nfs not registering the files fast enough.

moving the files to projects fixed the problem.

**Comment by pipitone** [comment]
Gotcha

**Comment by josephdviviano** [comment]
wait plz reopen and let me look into this?

**Comment by pipitone** [comment]
> wait plz reopen and let me look into this?

Oops, my badsies. Did not mean to close the issue. 

Did you notice this with Sonja's run of tbss_2_reg?

**Comment by josephdviviano** [comment]
This doesn't seem to be totally reproducible, though we are continuing to have problems with clevis not being recognized on all machines on the queue. Not sure if this is a CAMH network issue or what, but I'm going to close this.
