### ISSUE TITLE
Port datman to the SCC

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#562]
- [x] Configure the necessary modules (see below)
- [x] Create a datman module
- [x] Configure run.sh scripts to use SCC paths (perhaps via an env variable in the datman module)
- [x] Modify datman to use `qbatch` when submitting jobs
- [x] Request a "clevis"-type user created for the SCC?

I've configured many of the needed modules (I got the list from searching for "module load" in the run scripts and datman code). Not all of the modules looked necessary, and some were already installed but have different versions. 

Modules installed on the SCC:
- `AFNI/2016.05.03`               was `AFNI/2014.12.16`
- `FSL/5.0.9`                     was `FSL/5.0.7`
- `hcp-pipelines/3.15.1`          was `hcp-pipelines/3.7.0`
- `minc-toolkit/1.0.07`           was `minc-toolkit/1.0.01`
- `mricron/30APR2016`             was `mricron/0.20140804`
- `python-extras/2.7.11`          was `python-extras/2.7.9`
- `python/2.7.10-anaconda-2.4.0`  was `python/2.7.9-anaconda-2.1.0-150119`
- `slicer/4.5.0`                  was `slicer/4.4.0`
- `R/3.2.4-*`                     was `R/3.1.1`
- `R-extras/3.2.4`                was `R-extras/3.1.1`
- `connectome-workbench/1.1.1`
- `FIX/1.061`
- `freesurfer/5.3.0`
- `ENIGMA-DTI/2015.01`

Not sure what to do with these guys (I don't think we need these right now):
- `/archive/data-2.0/code/datman.module`
- `/projects/edickie/privatemodules/datman/edickie`
- `CIVET-extras/1.0`
- `CIVET/1.1.10+Ubuntu_12.04`
- `CIVET/1.1.12`
- `datman/edickie`
- `use.own`

Won't install:
- `AFNI/2014.09.22.1635EDT`
- `freesurfer/5.3.0.2014_05_26`
- `matlab/R2013b_concurrent`
- `matlab/R2014a`
- `minc-toolkit-extras/1.0`
- `SGE-extras`

**Comment by pipitone** [comment]
Update. I've create a datman branch called "scc" and installed in as the module `datman/latest` on the SCC.

I've created a testing environment here: `/imaging/scratch/kimel/jpipitone/datman-test`. The interesting stuff (outside of the scc branch) is the adjusted `ANDT/bin/run.sh` script. Most of it the basic stuff up to the QCing seems to work at this point.

I've pinged Andy/David to follow Erin's request to have our CAMH storage folder mounted on all of the compute nodes.

**Comment by edickie** [comment]
I talked to David on Friday and he sounded serious about having us use
ramdisk for everything...He said something about the current hardware
set-up being to slow so most  basic i-o to compute nodes???

Maybe you need to chat with him about this...

**Comment by pipitone** [comment]
Okay, looks like the camh storage is now mounted on all of the SCC. :-)

**Comment by pipitone** [comment]
@edickie, how's this going?

**Comment by edickie** [comment]
getting there.

I'm still running the scripts manually right now. And we got a little bit
of weirdness in the way freesurfer is behaving (like as in different
outputs). I'm running some tests now to try to figure that out.

Once that's done. I could use some support with setting up the cron job and
the emails..

Thanks,
Erin

**Comment by pipitone** [comment]
Okay great. I guess keep this ticket updated and let me know where I can
jump in.

**Comment by josephdviviano** [comment]
@edickie just curious where this is at?

**Comment by edickie** [comment]
So it's pretty much done..accept for the syntax error with the cron job
(which i don' t know about).

I guess one questions it...do we want the pipelines to still be a cron job?
Or should we have navona submitt them manually when she's done QC?

**Comment by josephdviviano** [comment]
Hmm that's interesting. If the pipelines are run manually that might keep us more aware of whether we're up-tp-date with QC etc.

I'm happy either way!

**Comment by edickie** [comment]
pretty sure this is done
