### ISSUE TITLE
datman should not hardcode modules?

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#564]
Several of our datman scripts (see below) load modules as part of their operation but this makes it difficult to use outside of the tigrlab (e.g. #562, or any system that doesn't have environment-modules). What about: 

- Remove module loads and only *assert* that the necessary software is available when run
- Record environment (and/or loaded modules) when scripts are run (perhaps in a text file in the `logs/` folder, or as output in the log files)

List of datman scripts that load modules: 
- `bin/csv-outliers.py`
- `bin/dm-proc-CIVET.py`
- `bin/dm-proc-enigmadti.py`
- `bin/dm-proc-freesurfer.py`
- `bin/dm-proc-fs2wb.py`
- `bin/dm-proc-mncmean.py`
- `bin/doInd-enigma-dti.py`
- `bin/tigr-write-runsh.py`
- `bin/tigr-write-runsh_redux.py`
- `assets/141212-basic-task-6fwhm.sh`
- `assets/150409-compcor-nonlin-8fwhm.sh`
- `assets/151012-tedmethod-compcor-lowpass-nonlin-10fwhm.sh`
- `assets/999999-test.sh`
- `assets/gbss_single_shell.sh`

**Comment by josephdviviano** [comment]
+ on this, I've added abunch of modules loads to the datman.module file sourced by each run script.

**Comment by pipitone** [comment]
Great. I've done this also on the scc in datman/latest, but only for the
basics (gnu parallel, qbatch, etc..). I'm going to leave the specific
versions of FSL/FS/Slicer/minc/etc... up to the run.sh scripts to load
and unload because I seem to remember there a) being conflicts when
loading all of these at once, and b) some steps may require specific
versions to be loaded? Let me know if I'm wrong about these.
