### ISSUE TITLE
Page build warning on tigrlab/spins github pages

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#565]
From the email (my emphasis):
> The page build completed successfully, but returned the following warning:
>
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, **change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset**. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

**Comment by navonacalarco** [comment]
I think I watched you fix this for the workshop site. I can take a stab at it here, if you like. :)

**Comment by josephdviviano** [comment]
Hey Navona sorry I beat you to the punch:

changed line 6 of `/archive/data-2.0/SPINS/website/_config.yaml`
