### ISSUE TITLE
run script error - conflicting modules?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#568]
Do the version of AFNI in the datman.module conflict with one that's loaded in the PACTMD run script?

AFNI/2014.09.22.1635EDT(7):ERROR:150: Module 'AFNI/2014.09.22.1635EDT' conflicts with the currently loaded module(s) 'AFNI/2014.12.16'
AFNI/2014.09.22.1635EDT(7):ERROR:102: Tcl command execution failed: conflict AFNI

**Comment by pipitone** [comment]
This should be fixed now that the module loads are removed from the datman module.
