### ISSUE TITLE
Set XNAT up to listen on port 443

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#569]
We now have port 443 open from the outside. May also want to experiment with #553 but to do that we would likely want to install apache/nginx to handle requests (I suspect this is the preferred way to run tomcat in production anyway).

**Comment by josephdviviano** [comment]
I thought apache was running on our server already?

**Comment by pipitone** [comment]
Nope, only Tomcat AFAIK. le sad. Tomcat can listen on port 443 though..
I'm just not sure how it deals with certificates if we ever get there. 

Jon.

**Comment by pipitone** [comment]
It has been done. Let's not close this until the [XNAT wiki page](https://github.com/TIGRLab/admin/wiki/XNAT) and/or Ansible is updated with the XNAT/nginx/certbot configuration steps

**Comment by josephdviviano** [comment]
need to document following files:

http://webapp.org.ua/sysadmin/setting-up-nginx-ssl-reverse-proxy-for-tomcat/

https://loune.net/2016/01/https-with-lets-encrypt-ssl-and-nginx/

https://bjornjohansen.no/redirect-to-https-with-nginx

```
/home/localadmin/auto-renew
/home/localadmin/certbot-auto
/var/lib/tomcat7/conf/server.xml
/etc/nginx/sites-enabled/srv-web
```

**Comment by josephdviviano** [comment]
This is done. See 

http://www.viviano.ca/writing/xnat-nginx/

and 

https://github.com/TIGRLab/admin/wiki/XNAT
