### ISSUE TITLE
XNAT: Resetting your password fails 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#572]
Steps to reproduce: 
1. Go to the xnat site
2. Click the "Forgot login or password?" link, and enter your username
3. Be greeted with an "unknown error" page:
![#fail](http://i.imgur.com/TE1d5oP.png)

**Comment by josephdviviano** [comment]
My first guess on this issue is that XNAT is attempting to send a 'reset your password email', but failing. From `/var/lib/tomcat7/webapps/xnat/logs/turbine.log`:

```
2016-06-07 11:30:39,487 [http-bio-0.0.0.0-22022-exec-47] ERROR org.apache.turbine.Turbine - Turbine.handleException:
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: srv2.pet.utoronto.ca, port: 587;
  nested exception is:
        java.net.ConnectException: Connection timed out. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: srv2.pet.utoronto.ca, port: 587;
  nested exception is:
        java.net.ConnectException: Connection timed out; message exception details (1) are:
Failed message 1:
```

**Comment by josephdviviano** [comment]
@pipitone more info:

can attempt ssh from nissl to srv2.pet.utoronto.ca but cannot to srv2.pet.utoronto.ca. I'm guessing this is a firewall issue, but I'm not sure. I'll ping Sylvan about this.

**Comment by josephdviviano** [comment]
This was resolved, XNAT was not communicating with itself properly through localhost.
