### ISSUE TITLE
datman: ninet submodule doesn't have a .gitmodules entry

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#573]
Currently if you clone datman, and run submodule init: 

    $ git submodule init
    No submodule mapping found in .gitmodules for path 'assets/ninet'

This is an easy fix, but I'll need the URL is for the ninet git repo.. @josephdviviano?

**Comment by josephdviviano** [comment]
Hey, ninet is a dead project. No repository. Can we just leave that as
commited code for now that we can remove it in the future?

Joseph's Phone

**Comment by pipitone** [comment]
> Hey, ninet is a dead project. No repository. Can we just leave that as
> commited code for now that we can remove it in the future?

Sure, I'll grab the code from datman on tigrsrv.
