### ISSUE TITLE
shut down teamviewer

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#574]
- [ ] teamviewer is a mess
- [ ] teamviewer is a waste

**Comment by edickie** [comment]
Somebodies gotta break the news to Colin...

**Comment by josephdviviano** [comment]
Email sent to colin

**Comment by pipitone** [comment]
Teamviewer wasn't installed on any of the machines, but just in case I've removed any trace from the workstations via: 

    ansible -m apt -a 'name=teamviewer9:i386 state=absent purge=yes' all

That said, people may still have local copies installed.
