### ISSUE TITLE
civet outputs missing for certain subjects in archive

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#576]
There is no civet output files for the following subjects in archive/data/-2.0/

COGBDY: 
27B036
27B034

COGBDO:
209455
215002
215958

SPINS:
SPN0009

DTI:
H008
H037
S142

Was there a problem with those subjects? If no, would it be possible to add them?
Thanks!

**Comment by josephdviviano** [comment]
Hey @mlevesque82 I'll look into it. Likely just a failed run of the pipeline / the jobs were killed for an unrelated reason.

**Comment by mlevesque82** [comment]
Thanks, I appreciate it!

**Comment by pipitone** [comment]
Similar thing happening here as in #577, each of these scans has two T1 images, and so the CIVET script is refusing to run. We just need to blacklist and remove the bad T1 in each case and CIVET will run correctly.

**Comment by mlevesque82** [comment]
Thanks for looking into this. I really appreciate it!

**Comment by pipitone** [comment]
No problem. The way I figured this out was this: 

1. Load the datman module: `module load /archive/data-2.0/code/datman.module`
1. Check the `STUDY/bin/run.sh` (e.g. `COGBDY/bin/run.sh`) script for the command that runs the CIVET stage: `dm-proc-CIVET.py ${PROJECTDIR}/data/mnc ${PROJECTDIR}/data/civet COGBDY`
1. Run the stage with the `--debug` and `--dry-run` flags set so that I could see what the script is trying to do (without it actually taking any action):

    ```sh
PROJECTDIR=/archive/data-2.0/COGBDY
dm-proc-CIVET.py --debug --dry-run ${PROJECTDIR}/data/mnc ${PROJECTDIR}/data/civet COGBDY
```

**Comment by edickie** [comment]
Hi guys. Also, there a checklist.csv inside the civet output directory
which should contain a note about why it didn't run (i.e.because multiple
T1's were found). You can manually edit the checklist file with the
filename of the T1 you have chosen for the analysis, and civet should run
without need for blacklisting.

**Comment by mlevesque82** [comment]
OK, let me know when those subjects become available. Thanks!

**Comment by mlevesque82** [comment]
From the list, the following are now available (although no QC, would it be possible to run the QC script please?):

COGBDY 27B036
COGBDO 215002; 215958
DTI H037; S142

The following are still missing:
COGBDY 27B034
COGBDO 209455
SPINS SPN0009
DTI H008

Funny that the one still missing is the first participant (alphabetically) each time...

I have enough subjects in my analysis for Harvey Stancer Research Day but it would be great if I could eventually include these subjects.

Thanks for your help!
Melissa

**Comment by edickie** [comment]
I sent all of them on Friday...so it's weird that some are failing..

@pipitone @jdv can you guys look into this? I don't know if it is something
to do with the queue?? or the way the civet script is qsubbing

On Mon, Jun 13, 2016 at 11:07 AM, Melissa Levesque <notifications@github.com

**Comment by josephdviviano** [comment]
@pipitone @mlevesque82 @edickie ill look at it now

**Comment by josephdviviano** [comment]
Looks like clevis does not resolve on all of the machines. I'm guessing the sss_cache needs to be reset on all of our machines:

`sss_cache -E`

I'm running this on all machines via ansible, but it fails for most machines.

+ clevis does not exist on penfield, something wrong with sssd

**Comment by pipitone** [comment]
Troubling. Let's get Qing on this; he's had a lot more experience with SSSD. This looks like the same problem as when jviviano user wasn't found on davinci earlier today.

**Comment by josephdviviano** [comment]
Likely related. from logcheck:

`Jun 13 22:00:07 backup nfsidmap[452]: nss_getpwnam: name 'jviviano' not found in domain 'camhres.ca'`

**Comment by josephdviviano** [comment]
+ updating / restarting all machines (including restarting sssd) seems to have resolved the issue.

**Comment by josephdviviano** [comment]
+ also fixed for compute 01 (again ... this computer was very out of date).

On all of these machines, I updated something that overwrote a PAM configuration file. I wouldn't be surprised if that was part of the solution.

**Comment by josephdviviano** [comment]
@mlevesque82 just found something interesting ... rebooting your machine now, can you try logging in when it is finished?

**Comment by josephdviviano** [comment]
I'm going to close this for now ... new outputs should appear in the morning. @mlevesque82 can you please reopen if this is still a problem?
