### ISSUE TITLE
missing enigmaDTI files in archive/data-2.0

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#577]
I noticed that FA values in enigma ROI are not available in certain subjects, even though they are in dtifit.

Did something happen to those subjects?

SPINS: CMH_0003, CMH_0025
COGBDY: 27B029, 27B036
DTI: H001, H003, H004, H008, H012, H146, H147, H148, H149, H150, H151, S002, S010, S012, S017, S018, S139, S140, S142

**Comment by josephdviviano** [comment]
@mlevesque82 cool I'll look into this as well.

**Comment by mlevesque82** [comment]
Do you think you would have time to do it this week? I'm hoping to redo my analyses with these data for Harvey Stancer Day. If not no worries, I'll put in my old results.

**Comment by pipitone** [comment]
Melissa, I'm just taking a look at this now. The two SPINS subjects do not have DTI scans, so this explains why they don't have enigma values. I'm looking into the others now.

**Comment by pipitone** [comment]
Okay, in summary: 
- SPINS subjects do not have DTI acquisitions
- COGBDY subjects have 2 DTI60 acquisitions (an initial one, and a repeat), and enigmaDTI expects only one
- CMH_DTI subjects listed do not have any DTI acquisitions

In short, it's only the COGBDY subjects you could get enigma values for. Perhaps @edickie can help you figure out which of the repeats are worth using, and then kick off enigmaDTI.

**Comment by mlevesque82** [comment]
oups, I meant dtifit not enigmaDTI!

**Comment by mlevesque82** [comment]
I'm not sure I understand. There are enigmaDTI results for most of the SPINS, COGBDO and DTI subjects...

**Comment by pipitone** [comment]
Sorry, I should have been clearer: I'm referring only to the subjects you listed.

**Comment by pipitone** [comment]
Aaaand, one other bit of critical information: the enigmaDTI script expects only a single _FA map. When it finds more than one, it doesn't run. That explains why the COGBDY subjects are missing.

**Comment by josephdviviano** [comment]
@mlevesque82 I think what he's saying is that for SPINS and DTI, those subjects dont have a DTI scan (so you're not missing any data).

For the cogbdy subjects, our code failed because it saw two DTIs and itshould only see one. So @pipitone could just blacklist the bad DTI (likely the earlier one), remove those files, and rerun enigmaDTI. Though this is just in the service of 2 subjects, so you might as well go ahead with your analysis.

**Comment by pipitone** [comment]
Correct. I'd blacklist, but it's difficult for me to visually inspect the DTIs remotely. @josephdviviano  or @edickie, could you take a look?

**Comment by mlevesque82** [comment]
Gotcha, I'll remove those subjects. Thank you!

**Comment by josephdviviano** [comment]
@pipitone @edickie sure I can blacklist them.

**Comment by mlevesque82** [comment]
@edickie would you mind running the script to include COGBDY 029 and 036 into the summary (enigmaDTI-FA-reults.csv)? Thank you!!

**Comment by josephdviviano** [comment]
@mlevesque82 they're added now

**Comment by josephdviviano** [comment]
I've blacklisted and deleted the bad scans -- going to close this (reopen if you need).
