### ISSUE TITLE
Add ipaslave01 to sssd.conf

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#578]
From Qing:
> rprshipav01 (the main IPA server) will be taken off-line during the week for a while to add a pair of 10Gb cards to the host for testing Dell storage iSCSI functionality.
>
> Please change ipa_server line in /etc/sssd.conf to the following:
> `ipa_server = _srv_, rprshipav01.camhres.ca, ipaslave01.camhres.ca`
>
> Authentication will continue on ipaslave01 when rprshipav01 is off-line.

**Comment by qchang** [comment]
Jon,
Have you gotten a chance to complete this? I am hoping that I can add the cards this afternoon.

**Comment by pipitone** [comment]
I'm working on this right now. Should be fine for this afternoon.

**Comment by pipitone** [comment]
Done.

**Comment by pipitone** [comment]
p.s. I added a line to the ansible `ipa-client` role to record this change.

**Comment by qchang** [comment]
Thanks Jon.
