### ISSUE TITLE
Slicer: Error while loading shared libraries

### ISSUE THREAD

**Issue by rutwikb** [TIGRLab/admin#579]
I'm trying to run code which is supposed to extract FA AD MD values and it was working fine a few days ago but now gives this error.

/opt/quarantine/slicer/nightly/build/lib/Slicer-4.5/cli-modules/FiberTractMeasurements: error while loading shared libraries: libvtkSlicerTractographyDisplayModuleMRML.so: cannot open shared object file: No such file or directory

i've tried it with Slicer/nightly and Slicer 4.4.0 loaded together and separately.

**Comment by pipitone** [comment]
This is might be due to my change in #567. I'll take a look.

**Comment by pipitone** [comment]
Okay, fixed. I added back all of the library paths I had removed in #567 (it wasn't doing anything useful anyhow).
