### ISSUE TITLE
queue

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#580]
Is there something going on with the queue? It seems like my jobs keep failing.

**Comment by josephdviviano** [comment]
Can you post more details? What jobs are you submitting (exact command)

Joseph's Phone

**Comment by mlevesque82** [comment]
tbss_2_reg -T

I have tried FSL/5.0.7 and FSL 5.0.9

I don't know what's going wrong. I'm getting Eqw and S as status on qstat and qmon.

**Comment by mlevesque82** [comment]
I'm getting this as an error: "Error for job ######: can't get password entry for user "melissa". Either the user does not exist or NIS error!"

**Comment by josephdviviano** [comment]
Hi Melissa yes this is a known issue. It's why I asked you to restart your
machine when you are done work.

I've identified 3 machines where we see this error.

Joseph's Phone

**Comment by mlevesque82** [comment]
Ah ok good to know

**Comment by mlevesque82** [comment]
restarted davinci and same problem occurring

**Comment by josephdviviano** [comment]
Try again I think I fixed it.
