### ISSUE TITLE
DTIprep

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#581]
Hey guys,

I will be using DTIprep to preprocess PACTMD which requires nrrd files. I was wondering if you can convert the DICOMs for multi-shell data to nrrd. In addition, please let me know how we generally use DTIprep (e.g. a protocol, GUI vs. command line, etc.). 

Cheers,
Arash

**Comment by pipitone** [comment]
I've turned on nrrd export for the DTI images in PACTMD. They should be there tomorrow.

As for using DTIPrep, we use it something like this: 
https://gist.github.com/pipitone/f520d1a8ba68db9c94a4

i.e. simple use the default settings, and from the command line. I don't think people here use the GUI for proper QCing, but I could be wrong about that. If you have any better advice as to how to use it, I'm sure Saba, Amy, and Laura would like to know since they're running group clustering. :-)

**Comment by arash-n** [comment]
Thanks Jon. I was also thinking of using the defaults. I'll look into it. ;)

Cheers,
Arash

**Comment by arash-n** [comment]
Hi Jon,

Hope you are doing great. Do you mind pointing me to the .xml file for DTIPrep QC protocol that you are using.

Cheers,
Arash

**Comment by pipitone** [comment]
I don't use one. By that I mean, I just use the DTIPrep default one that it makes. :-/

**Comment by arash-n** [comment]
I am running DTIPrep now and it looks fine now. However, the nrrd files for the following DTI subjects is non-existent:
H001

H003

H004

H008

H010

H012

H013

H016

H034

H082

H146

H147

H148

H149

H150

H151

H152

H153

H155

H156

H157

H158

**Comment by pipitone** [comment]
Check the README in the project folder and try searching the closed issues if nothing is mentioned there. Some subjects don't have DTI acquisitions.

**Comment by arash-n** [comment]
These are the subjects that I already have their multi-shell diffusion images. I checked H001 for instance, although there is no nii and nrrd diffusion file available. However, DICOM files exist in data-2.0.

Cheers,

Arash

**Comment by josephdviviano** [comment]
@edickie @navonacalarco is the exportinfo file for DTI/CMH misconfigured?

**Comment by edickie** [comment]
Have these subject been blacklisted??

**Comment by edickie** [comment]
Here's what I see in the blacklist...

DTI_CMH_H001_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H001_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H001_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H003_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H003_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H003_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H004_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H004_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H004_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H008_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H008_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H008_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H010_02_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H010_02_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H010_02_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H012_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H012_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H012_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H013_02_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H013_02_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H013_02_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H016_02_01_DTI33-1000_15_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H016_02_01_DTI33-3000_14_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H016_02_01_DTI33-4500_13_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H034_02_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H034_02_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H034_02_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H082_02_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H082_02_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H082_02_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H146_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H146_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H146_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H147_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H147_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H147_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H148_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H148_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H148_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H149_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H149_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H149_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H150_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H150_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H150_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H151_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H151_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H151_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H152_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H152_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H152_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H153_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H153_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H153_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H155_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H155_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H155_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H156_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H156_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H156_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_H158_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_H158_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_H158_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S002_02_01_DTI33-1000_09_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S002_02_01_DTI33-3000_08_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S002_02_01_DTI33-4500_07_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S006_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S006_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S006_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S010_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S010_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S010_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S012_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S012_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S012_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S017_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S017_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S017_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S018_02_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S018_02_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S018_02_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S019_02_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S019_02_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S019_02_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S022_02_01_DTI33-1000_16_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S022_02_01_DTI33-3000_15_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S022_02_01_DTI33-4500_14_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S054_02_01_DTI33-1000_15_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S054_02_01_DTI33-3000_14_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S054_02_01_DTI33-4500_13_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S057_02_01_DTI33-1000_16_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S057_02_01_DTI33-3000_15_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S057_02_01_DTI33-4500_14_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S061_02_01_DTI33-1000_15_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S061_02_01_DTI33-3000_14_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S061_02_01_DTI33-4500_13_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S139_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S139_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S139_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S140_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S140_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S140_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S141_01_01_DTI33-1000_12_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S141_01_01_DTI33-3000_11_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S141_01_01_DTI33-4500_10_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S142_01_01_DTI33-1000_08_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S142_01_01_DTI33-3000_07_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S142_01_01_DTI33-4500_06_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S143_01_01_DTI33-1000_12_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S143_01_01_DTI33-3000_11_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S143_01_01_DTI33-4500_10_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S146_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S146_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S146_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S147_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S147_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S147_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S148_01_01_DTI33-1000_15_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S148_01_01_DTI33-3000_14_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S148_01_01_DTI33-4500_13_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S149_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S149_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S149_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S150_01_01_DTI33-1000_15_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S150_01_01_DTI33-3000_14_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S150_01_01_DTI33-4500_13_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S155_01_01_DTI33-1000_14_Ax-DTI-32+3-b1000  wrong-protocol
DTI_CMH_S155_01_01_DTI33-3000_13_Ax-DTI-32+3-b3000  wrong-protocol
DTI_CMH_S155_01_01_DTI33-4500_12_Ax-DTI-32+3-b4500  wrong-protocol
DTI_CMH_S157_01_01_DTI33-3000_13_Ax-DTI-33+2-b3000  wrong-protocol

**Comment by arash-n** [comment]
The list of the subjects that I had sent have a correct protocol. Most if not all have even the correct gradient directions. The only problem in some of them may be different voxel sizes across different b-values which may be an issue for concatenation in nrrd format.

**Comment by josephdviviano** [comment]
@arash-n see this file: /archive/data-2.0/DTI/CMH/README.md

We've been through this already and we're pretty sure the data isn't appropriate for data-2.0. You're welcome to work with the DICOMs if you want.

- Thu May  7 16:44:43 EDT 2015

  After discussion with @djrotenberg and @josephdviviano I think I can
  summarize the DTI situation as this:

  - Some subjects have 32 direction + 3 B0 DTI images which are the standard GE
    DTI acquisition, and these are a problem for us; they are mistakenly
    acquired after service to the scanner reset the configuration for our
    protocol.

  - The b=1000 33 direction + 2 B0 DTI images are what we should be acquiring
    as part of the DTIG protocol. This is according to Yogesh Rathi'ss
    specifications for doing multi-shell DTI properly.

  Therefore, all images that have 32 directions are probably garbage (since the
  60 direction DTI scan covers the same information, at least for b=1000). I've
  replaced the DTI/CMH gold standard with subject scan DTI_CMH_H011_02_01 since
  this was the first scan acquired correctly with 33 directions. All other 33
  direction DTI scans conform header/bvec/bval-wise to this scan (which is
  great news).

  I've also blacklisted all of the 32 direction scans, and removed them from
  the data folder.

  See also: https://github.com/TIGRLab/data/issues/28

  @jp

**Comment by arash-n** [comment]
Hey guys,

I can not confirm it but I just remembered something really important. The b-values are misleading and vary between the scans, as they are in and of themselves meaningless. The bvec is correct for all subjects (there are 0 columns that make the non-b0 values in bvals b0 images). I couldn't test this (unzip dicoms, dcm2nii, copy an paste bvec files in a spreadsheet) but I am pretty sure about this. Actually there are 5 b0 per each scan 3 at the beginning and 2 in the middle.

Cheers,
Arash

**Comment by josephdviviano** [comment]
Hey Arash,

Can you look into this definitively? We have a lot of other things on the good, already spent a bunch of time on this and made our decision based on what everyone, including David, Aristotle, and the MR unit told us.

**Comment by arash-n** [comment]
Hey Joe,

I still don't have a reliable internet connection at home. Once I have my internet set up, I will be able to do it. I may need to ask you for some help for the original DICOM files though.

My plan is to calculate average signal (on the masked brain) to detect B0 images from the actual data (using fslmeants). Look at the bvec/bvals after conversion of the DICOM files to .nii.

Cheers,

Arash

**Comment by josephdviviano** [comment]
Sure arash no problem, all of the raw Dicom data is neatly organised under
data/Dicom .happy to walk you through it next time you are in.

Joseph's Phone
