### ISSUE TITLE
Create the ASDN data-2.0 project

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#583]
See tigrlab@camh.ca email for more details.

**Comment by josephdviviano** [comment]
see `/archive/data-2.0/ASDN/docs`

**Comment by josephdviviano** [comment]
This should be set up to pull data into xnat (nothing else at the moment).

**Comment by edickie** [comment]
I'm pretty sure this is the study Steph new RA is on..there is prob data to pull now..

**Comment by josephdviviano** [comment]
OK -- everything up until QC is running for this project. Looks pretty complete, check the `exportinfo.csv` file for more. @edickie / @djoverton  / @navonacalarco  could you take it from here and get the analytic pipelines working?
