### ISSUE TITLE
We have run out of backup space

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#589]
ZFS is likely very unhappy, atm :-)

~~In addition to archiving `anne`'s projects folder (see #340)~~, we could also move the following projects folders to `hal:/alumni` and to `camh:/alumni`) to make space: 
- [x] tris
- [x] dan
- [x] julie

Heavy users we could pester include: 
```
2.2T    tina_r
2.0T    edickie
1.9T    nikhil
1.2T    colin
1.1T    arash
0.7T    saba
```

**Comment by josephdviviano** [comment]
Hey @pipitone, why don't we just start backing up to the next CAMH storage?

**Comment by pipitone** [comment]
We should move to doing this (and just use the backup server as our
third backup of critical data), but right now the transfer speeds with
CAMH storage aren't good enough to do nightly backups. This may be
better now that we are moving to mounting CAMH storage over a range of
IPs?

**Comment by pipitone** [comment]
FYI, I did a sync of the XNAT folder to the camh storage `tigrlab/xnat` and it took 4 hours. Not as bad as I thought.

**Comment by pipitone** [comment]
After moving Anne's project folder to tigrlab/alumni, and deleting the projects folder on `tigrsrv` and on `backup`, we should have around 600GB of freespace. I'm closing this issue for now.

**Comment by pipitone** [comment]
I'm reopening this because we've again run out (who knew half a TB would go by so fast). I'm going to move `tris` and `dan` to the alumni folders (see the [issue description](https://github.com/TIGRLab/admin/issues/589)).

**Comment by pipitone** [comment]
Done moving `dan` and `tris` to the alumni folders. There is approximately 1.2TB of free space now.
