### ISSUE TITLE
Setup xnat.imaging-genetics.camh.ca

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#590]
We'll need this to point to our XNAT server, especially when we move off the PET network #407

**Comment by pipitone** [comment]
I've emailed Alan; he's already set this up for external use, but not yet for inside CAMH.  We can temporarily work around this for internal machines by adding an entry to `/etc/hosts`.

**Comment by pipitone** [comment]
Added to `/etc/hosts` and applied it to all the machines:

    ansible-playbook playbooks/common.yml

**Comment by josephdviviano** [comment]
I think this is done. See:

http://www.viviano.ca/writing/xnat-nginx/

https://github.com/TIGRLab/admin/wiki/XNAT

**Comment by pipitone** [comment]
You might consider keeping this open until the url resolves internally at CAMH.

**Comment by josephdviviano** [comment]
Right, thanks @pipitone

**Comment by josephdviviano** [comment]
It does now.
