### ISSUE TITLE
Add srv-web's custom /etc/hosts entry for xnat.imaging-genetics.camh.ca

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#591]
See #575. In order to get the autorun script working I added an entry into /etc/hosts specifically for xnat that points to localhost. Since in #590 I added a general entry to /etc/hosts for that same address that points to the external IP address, ansible needs to be configured to treat srv-web as a special case when it generates the hosts file. 

~~This problem will go away when `xnat.imaging-genetics.camh.ca` resolves correctly inside CAMH.~~
**Correction:** this problem will not go away then. We will still need a custom entry for xnat as long as the external IP address is not accessible from the webserver.

**Comment by josephdviviano** [comment]
@pipitone : is this done? 

If so -- can you add a bit to the XNAT wiki about this so when I go to write an ansible role for all of this I have a clear understanding of why we needed to do this?

**Comment by pipitone** [comment]
I have not written an ansible role for this (which is what this issue is about), but I have added the following entry to srv-web:/etc/hosts (see #575):
 
    127.0.0.1 xnat.imaging-genetics.camh.ca

I've added a note to this effect on [the xnat wiki page](https://github.com/TIGRLab/admin/wiki/XNAT)

**Comment by josephdviviano** [comment]
NB: this issue is top priority -- ansible currently will mangle XNAT by propogating a 'bad' hosts file to it.

**Comment by josephdviviano** [comment]
also add:
    + sudo ufw allow http
    + sudo ufw allow https

to ansible...

**Comment by josephdviviano** [comment]
All added to the new 'webserver' role.
