### ISSUE TITLE
figure out how to get jessica turner on our system to see our QC system

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#592]

**Comment by edickie** [comment]
We're not just sending her zip files or pdfs?

**Comment by josephdviviano** [comment]
I sent her one, but if she wants to see the whole system well need to get
her a login. I've started the email chain with her already

Joseph's Phone

**Comment by pipitone** [comment]
We could stick this stuff on the web server? Set up a redirect for `xnat.imaging-genetics.camh.ca/qc` to point to a folder of QC stuffs?

**Comment by josephdviviano** [comment]
I think she's happy getting emails. This really should be an issue on dashboard improvements for our QC system.
