### ISSUE TITLE
gather any purchase quotes etc from JP before he becomes a surgeon

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#598]
Hey @pipitone 

Where are the PDFz in ur folders full of kewl CFI quotez?

I need them. For science.

**Comment by pipitone** [comment]
I don't think I have any quotes that matter any longer. I had a quote for a KVM that I sent to DL that never went anywhere (and I didn't follow up with) but that's about it.

**Comment by josephdviviano** [comment]
Hi @pipitone , so you never put together any quotes that were purchased?

**Comment by pipitone** [comment]
Hi @jdv. I don't think so. We had the second set of IBM storage arrays which I arranged quotes for, but we didn't purchase those. FYI, Dielle has copies of everything from DR's days in a folder on the T drive.

**Comment by josephdviviano** [comment]
OK great I just wanted to make sure. DL asked me earlier today and I wasn't definitive on the subject.
