### ISSUE TITLE
Split the repeats out of PRELASPE PCE participants 

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#600]
The two newest PRELASPE PCE have the repeats in the same folder as their time 1 scans..

Folders to split:
PRE01_PCE_S2020_01
PRE01_PCE_S2021_01

**Comment by josephdviviano** [comment]
You get to do this, I did it last time.

Also worth shooting them an email.

**Comment by navonacalarco** [comment]
I can help do this!@jdv, when you do this, do you download and then re-upload the data?

**Comment by josephdviviano** [comment]
Yeah, thats the best way I know how to do it. I usually download the files, delete everything, create new subjects, and then upload the split data to the new subject.

**Comment by edickie** [comment]
I'm adding PREO1_CTN_EH14014_01 to this list..

**Comment by navonacalarco** [comment]
This was done a long time ago - closing.
