### ISSUE TITLE
RMA drive for mansfield

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#602]
he frown

drive on my bookieshelf

**Comment by navonacalarco** [comment]
![22d05c4960c68fd8e1c4fd1aef323427dd84ab27cede9c6aa52cdcbc2b639f99](https://cloud.githubusercontent.com/assets/13733654/17345918/668dae28-58d6-11e6-9110-cbcdcf1c9cad.jpg)

**Comment by josephdviviano** [comment]
https://en.wikipedia.org/wiki/Return_merchandise_authorization

We actually have failed drives for 3 computers (all in 101). I think we can just call Dell and complain.

**Comment by navonacalarco** [comment]
Thanks @djoverton!
