### ISSUE TITLE
Can't download attachments from outlook

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#603]
I have tried both Firefox and Chrome. I can't download any attachments. I get this error on Chrome:

This web page is not available
DNS_PROBE_FINISHED_NXDOMAIN

I tried using several workstations but couldn't get attachments to download.

**Comment by josephdviviano** [comment]
Yes it looks like we're having some DNS trouble.

I'll contact qing about this.

**Comment by josephdviviano** [comment]
Resolution was to add 8.8.8.8 to resolv.conf --- contacted Qing and Alan about this. Will follow up in another ticket.

**Comment by pipitone** [comment]
Try adding ipaslave01's IP address as a nameserver also.  Worth a try because google public DNS won't resolve CAMH addresses properly (eg the scc)
