### ISSUE TITLE
weird run script error.. for sync with PET server 

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#604]
Unable to resume download of "/archive/data-2.0/COGBDY/data/zips/2014_0314_AM010.zip": local file is larger than remote

This is a weird one because the file is from a scan two years ago..

**Comment by josephdviviano** [comment]
This is due to my open issue regarding nicks data

Joseph's Phone

**Comment by josephdviviano** [comment]
Should be resolved.
