### ISSUE TITLE
another ambiguous run-log error: 06/24/16

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#605]
For the DTI CMH project...this is happening somewhere in between dm-check-headers and dm-proc-rest 

Unable to read script file because of error: ERROR! argument to -N option must not contain / 
ERROR closing pipe to qsub:

**Comment by josephdviviano** [comment]
If you run these commands interactively what do you find?

Joseph's Phone

**Comment by edickie** [comment]
with the set -x option we see:
+ sge_batch -o logs -k -J DTI/CMH_imob dm-proc-imob.py /archive/data-2.0/DTI/CMH /scratch/clevis /archive/data-2.0/code/datman/assets/150409-compcor-nonlin-8fwhm.sh /archive/data-2.0/DTI/CMH/metadata/design
Unable to read script file because of error: ERROR! argument to -N option must not contain / 
ERROR closing pipe to qsub:

**Comment by edickie** [comment]
I'm going to close this because the new run scripts use qbatch anyway...

**Comment by pipitone** [comment]
They may still fail is the job names are the same. The problem is that the jobs are being named DTI/CMH_imob. That slash is where the issue is, I'd guess.
