### ISSUE TITLE
Quarantine the latest slicer 4.5.0 nightly version

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#614]
@rutwikb and @sabashahab need dis.

**Comment by pipitone** [comment]
I've made two changes: 

1. Added the module `slicer/4.5.0-20160628`
2. Removed the module `slicer/nightly`, since I'm thinking this will just get confusing in the future, and it's easy enough for us to make more `slicer/4.x-<date>` modules if we need updated slicer versions. That okay by you all?

Please let me know if the new slicer module works.

**Comment by josephdviviano** [comment]
Sounds good to me!

**Comment by rutwikb** [comment]
Looks good, thanks
