### ISSUE TITLE
localadmin

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#617]

**Comment by josephdviviano** [comment]
should not be `/home/localadmin`

**Comment by pipitone** [comment]
What's the issue here?

**Comment by josephdviviano** [comment]
I thought we had localadmin under /var/local or something like that. I
can't find the reference in our documentation.

JDV

**Comment by pipitone** [comment]
I suspect we are inconsistent about this now. We used to do this when we
had a shared /home folder, but since we no longer do this some machines
have /home/localadmin

**Comment by josephdviviano** [comment]
I guess it's ok that localadmin's home folder in in the /home directory since it is local.
