### ISSUE TITLE
MRS masks -- update?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#620]
see this file: `/archive/data-2.0/STOPPD/docs/interpreting-MRS-160701.pdf`

from nancy: 

We discovered that ~500 exams (~1600 MRS voxels) were missed in our first sweep
of the database when we created the MRS masks in December 2015.

Those masks are now made, and will be put up onto the sFTP server this evening.
Directory naming is as before. For example: 20150716_Ex04058_HIST1MR_MRSROI

In each directory, you will find subdirectories indicating the MRS series#, the
T1-weighted image from which it was prescribed, and the MRS series name
&Pfile#.  For example: Ex03887_Se00006_Se00002_MRS_sgACC_Bilat-P29696_MRSROI

You may find a "DoubleCheckPlacement.txt" file in a subset of your directories -
it contains additional information for verifying the MRS voxel location.

Booking codes with the new masks include:

Anderson         MOOD1MR 
       
       
       
       
       
Bassett  PDDS1MR  FAAH1MR  OXYA1MR 
       
       
       
Boileau  FAAH1MR  OXYA1MR 
       
       
       
       
Graff    ADDA1MR  AMPT1MR  DOSE1MR  GLSZ1MR  TDCS1MR 
       
Hendershot       ALCO1MR 
       
       
       
       
       
Kish     DTBZ1MR  GHBP2MR 
       
       
       
       
LeFoll   HIST1MR 
       
       
       
       
       
Meyer    BIPM1MR  IMOX1MR  MADE1MR  MAOA1MR  MORA1MR  SERO1MR  TREA1MR
Mizrahi  COSZ1MR  DEME1MR  FESZ1MR  FLBS1MR  NISZ1MR  SINE1MR 
Rajji/Kumar      PASA1MR  PASS1MR  PASS2MR 
       
       
       
Strafella        TMSC1MR 
       
       
       
       
       
Voineskos        STOP1MR 
       
       
       
       
       

Sofia has recently written some instructions for using the masks to correct the
MRS data. That document is attached.

Please pass along this information to your staff who are analyzing the MRS data.

If you are still missing any MRS masks, please send to me: BookingCode, Exam#,
Exam Date, and I will create them.

**Comment by josephdviviano** [comment]
@edickie what's going on with this?

**Comment by edickie** [comment]
Aren't these all the timepoint 00 scans you added this summer?

**Comment by josephdviviano** [comment]
I don't remember, I guess I did this for you then.
