### ISSUE TITLE
Queue is down

### ISSUE THREAD

**Issue by sstojanovski** [TIGRLab/admin#621]
error: commlib error: got select error (Connection refused)
error: unable to send message to qmaster using port 6444 on host "srv-sge.camhres.ca": got send error

**Comment by josephdviviano** [comment]
This is likely due to the pet network now blocking all communications (which is why we had trouble last week). 

After the move to the CAMH network I'll be able to deal with this better.

**Comment by sstojanovski** [comment]
Sounds good! I'll check back tomorrow (?? or will the move take longer then one evening?)

**Comment by josephdviviano** [comment]
Hey sonja you're welcome to come back tomorrow, there's a chance things
will be running. By Thurs things will be running for sure.

JDV

**Comment by josephdviviano** [comment]
The queue is running now.

It's slow, for some reason. Looking into that, but since it works I'll consider this issue closed.
