### ISSUE TITLE
Did we add the new xnat address into datman??

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#623]
All the run-script logs have the following error..everywhere

error: commlib error: got select error (No route to host)
Unable to run job: unable to contact qmaster using port 6444 on host "srv-sge.camhres.ca".
Exiting.

**Comment by josephdviviano** [comment]
Hi Erin, this service is still offline (as I mentioned in my email last night).

This is also a duplicate of #621 so im closing it.
