### ISSUE TITLE
we are getting spammed like crazy due to /etc/nsswitch.conf

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#625]
The solution is to remove sss from 'sudoers'

http://superuser.com/questions/1086152/sudo-sending-annoying-alerts-issue-with-defaults-entries

Solution

This problem is caused by sudo looking for directives in a place it cannot find them: sss. Check the /etc/nsswitch.conf file and modify the sudoers entry.

sudoers:        files sss

The sss should not be there. The sssd-ad package adds itself there, but very few environments store sudoers directives in sss. It’s far more likely your directives are local, so you should have a /etc/nsswitch file entry like the following:

sudoers:        files

References

A user of RHEL6 had the same issue. https://bugzilla.redhat.com/show_bug.cgi?id=879633
The issue is solvable, including on Ubuntu 16.04 https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/1249777
https://bgstack15.wordpress.com/2016/06/06/solve-sudo-sending-useless-emails-problem-with-defaults-entries/
shareimprove this answer

**Comment by josephdviviano** [comment]
I think I took care of this with a line in the common ansible role.

**Comment by pipitone** [comment]
Check also the ipa-client role. It may be added there?
