### ISSUE TITLE
colin can't sign into any of the computers 

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#627]
science is hard

**Comment by josephdviviano** [comment]
Erin, can he sign into the terminal. You take care of this.

**Comment by edickie** [comment]
he can su on the terminal but he can't login from the blue screen or the black screen

**Comment by edickie** [comment]
From the black screen on davinci and telsa we see "Login incorrect"
but we can su to colin from the terminal of machines that other people are logged into.

**Comment by josephdviviano** [comment]
try clearing the sss_cache:

`sss_cache -E`

If that does not work contact Qing, his info might be wrong in IPA. I can't do that from here.

**Comment by josephdviviano** [comment]
Anyhow, let's change his username to 'chawko'. We need to get everyone over to SCC usernames.

**Comment by navonacalarco** [comment]
*chaw**c**o

**Comment by edickie** [comment]
There is a chawco already in the IPA server, it's cuz colin's already on the scc.. but I don' t think he can login with it.. confused

**Comment by josephdviviano** [comment]
Erin you know who to contact about this...

**Comment by edickie** [comment]
update: 
 + nobody other than localadmin can login to telsa
 + tesla is not connected to the internet (it can not ping www.google.com)
 + telsa does not have any of the drives mounted on it..

but the ethernet cable appears to be connected..and the little light beside the ethernet cable on the back it blinking as it should..

**Comment by josephdviviano** [comment]
Can you switch the ethernet cable to the other port on the back of tesla.

**Comment by josephdviviano** [comment]
the blinking does not mean anything

**Comment by edickie** [comment]
The switched to the other port and there is still not internet..

**Comment by josephdviviano** [comment]
ok well ill deal with it on monday colin can work on any number of machines.

**Comment by edickie** [comment]
wait I swtiched the port back and now there is internet.. and shared drives, but no one can login other than localadmin

**Comment by josephdviviano** [comment]
Sounds like you should replace the Ethernet cord

Joseph's Phone
