### ISSUE TITLE
tesla offline, users having trouble logging in

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#628]
wasnt last night. strange.

**Comment by edickie** [comment]
now online..ish, but no one can login to it other than local admin.

I wiggled some cables...

**Comment by edickie** [comment]
Tried   
+ sudo service sssd restart  
   + no effect

+ id colin (or id edickie)
   + output looks fine...
You could also try restarting the service that does username and password lookups -- it's called SSSD; as localadmin you would run:

  sudo service sssd restart

Would only have an effect if network access is stable. You can check whether logins are working by logging in or just doing a lookup on a username, like so:

  id jpipitone

It should return Info about my user ID and groups. If not SSSD is still not working and logins won't work so something else is up. 

Qing is your man for help with this stuff. 

Back to r and r for me. Hang in there,
Jon.

**Comment by DESm1th** [comment]
I'm not sure if this would have anything to do with any of the issues we're having (still learning Ansible), but the site.yml file in /projects/admin/ansible-playbooks/playbooks/ has a blank "hosts" field for the [ipa-client] roles entry and was last edited yesterday. Also, Grace is unable to log in to anything (it keeps saying wrong password) and Sonya was unable to log in to computers other than the one she normally uses. I think maybe something is up with the login server.

**Comment by josephdviviano** [comment]
Hi dawn, cN you send me a copy of the hosts file on your computer?

Has anyone gotten in touch with qing?

Joseph's Phone

**Comment by DESm1th** [comment]
Hi Joe,

I've attached the /etc/hosts file from golgi. Also, I just tried logging
into a few different computers. I had gotten an 'incorrect password' error
on Colin's earlier when we thought it was just his computer that was the
problem, but I just discovered I also get that problem on the computer
Melissa usually uses. I can log in to several other computers with no issue
though (even if I've never used them before and they shouldn't have my
credentials cached).. so maybe it's not the login server after all? Still
doesn't explain Grace's issue, but Sonya's login problem was also on
Melissa's computer. Very confusing.

Dawn

**Comment by DESm1th** [comment]
Oh er... I sent that via gmail, not sure if you can get the attachment that way. Also, I don't think we've told Qing yet.

**Comment by josephdviviano** [comment]
This might be related (another apparmor issue?) 

```
1 tigrsrv kernel: [275079.461252] type=1400 audit(1468123441.221:1658): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/var/lib/sss/pubconf/krb5.include.d/" pid=13455 comm="ldap_child" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by DESm1th** [comment]
I could be reading this wrong, but from the apparmor="ALLOWED" and denied_mask parts it looks like you guys have apparmor set to complain mode. If that's the case then it's announcing that based on the sssd profile the command ldap_child _shouldnt_ be able to read /var/lib/sss/pubconf/krb5.include.d/ but it's not actually preventing it from doing so. So there probably is a problem with the way the profile is configured, but apparmor isn't the source of our error (unless you guys wanted it to be blocked in this instance? still trying to understand things, sorry).

**Comment by josephdviviano** [comment]
Hey dawn no problem I also don't really understand yet. I remember us
having trouble with app armour for a very similar reason just recently,
which is why I left myself this note

Joseph's Phone

**Comment by qchang** [comment]
Hi Joseph, let me know when you are in so that we can have a look together, I am not clear the extent of the problem. I sounds like it is on the client site configuration. Maybe the config is not consistent across the network because ansible was not used for the move? 
BTW, I do not get any notifications on issues, I come here because of Erin's email...

**Comment by josephdviviano** [comment]
Looks like @qchang solved the issue: `ipaslave02` had a corrupted database. The following resolves the issue:

+ remove `172.26.216.31` from `/etc/network/interfaces` on all machines.
+ remove`ipaslave02` from `/etc/sssd/sssd.conf` (as an aside, also remove `_srv_` from that file).

We've both independently confirmed that this fixes the problem on two machines. I'm making the adjustments manually now.
