### ISSUE TITLE
find quote for george's computers

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#629]
2x Dell 7810 + Monitor + GPU (purchased separately).

**Comment by josephdviviano** [comment]
I found a huge store of David's quotes (now in `/projects/jviviano/documents/admin/purchases/david-quotes`). However I can't find any mention of a Dell Model 7810.

**Comment by josephdviviano** [comment]
I'm running this as root: `sudo grep -rnw '/mnt/tigrlab/archive/alumni/david' -e "7810" > /home/jviviano/possible-dells`

This should find ANY file containing the string 7810.... we'll see how useful that is.

**Comment by josephdviviano** [comment]
I found a more complete list of computers from David here `/mnt/tigrlab/archive/alumni/david/RAW_DATA/Documents/Kimel_Computers` but there's no quotes from George.

**Comment by josephdviviano** [comment]
David needs the approximate date of purchase from Dielle so we can get the quotes from Dell. We don't have copies on our computers.

**Comment by josephdviviano** [comment]
I have some potential quotes I located here:

`/projects/jviviano/documents/admin/purchases/george-computers` I have to run upstairs to verify though.

**Comment by josephdviviano** [comment]
It might also be the T5600 machines upstairs (mfg. 2011) instead of the 7810s, which were mfg 2015... 

I have no idea. I'm going to unassign myself from this one. I've wasted a lot of time with not much to go on.

**Comment by navonacalarco** [comment]
Not sure if it's relevant, but the VR lab has the following computers:

Dell Precision T3500
Dell Precision T7500   (x4)
Dell Precision T7810   (x2)
Dell Precision T7910

**Comment by josephdviviano** [comment]
Thanks. It isnt clear to me which of thse were purchased by brotenburg / rippatone.

**Comment by josephdviviano** [comment]
The trail went cold on this. I'm getting it off of my plate.
