### ISSUE TITLE
Matlab Distributed Computing and Compiler Installation

### ISSUE THREAD

**Issue by djrotenberg** [TIGRLab/admin#63]
Both the Matlab distributed computing license andMatlab compiler need to be installed according to our desired setup.

**Comment by josephdviviano** [comment]
The matlab folder needs to follow our conventions. Seems like I can handle that :D

**Comment by pipitone** [comment]
Update?

**Comment by josephdviviano** [comment]
Haven't had time to touch this.

**Comment by pipitone** [comment]
Yep, agreed. Was just wondering if it was done but still open. Carry on.

**Comment by pipitone** [comment]
@josephdviviano, this good now?

**Comment by josephdviviano** [comment]
I thinki so
