### ISSUE TITLE
clevis is not talking to XNAT properly

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#632]
The error we get with the run scripts is:
HTTPError: 404 Client Error: Not Found

I've been trying to run the REST API by hand...
The closest I got was to here:
 
curl -X PUT https://xnat.imaging-genetics.camh.ca/REST/projects/SPINS/subjects/SPN01_CMH_0076_01_01
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

I could be debugging this all wrong..

**Comment by DESm1th** [comment]
Hey Erin,

Do we have the ca-certificates package installed? curl is looking for it in /etc/pki/tls/certs/ca-bundle.crt and failing to find it.

**Comment by josephdviviano** [comment]
Hi dawn good catch,

I set up the new xnat install with let's encrypt

**Comment by josephdviviano** [comment]
here's a clue

echo -n | openssl s_client -showcerts -connect gitlab.viviano.ca:443 2>/dev/null  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

**Comment by josephdviviano** [comment]
echo -n | openssl s_client -showcerts -connect gitlab.viviano.ca:443 2>/dev/null  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

**Comment by josephdviviano** [comment]
^ lookie! a clue.

**Comment by edickie** [comment]
To do:
ssh clevis@tigrsrv
or
ssh clevis@tigrsrv.camhres.ca
sudo echo -n | openssl s_client -showcerts -connect xnat.imaging-genetics.camh.ca:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

**Comment by edickie** [comment]
from http://www.checkupdown.com/status/E504.html
> Fixing 504 errors - general
> 
> This problem is entirely due to slow IP communication between back-end computers, possibly including the Web server. Only the people who set up the network at the site which hosts the Web server can fix this problem.

**Comment by edickie** [comment]
Do we email research IT??

**Comment by josephdviviano** [comment]
@edickie can you post the contents of your /etc/resolv.conf file

I'm trying to replicate your error on my machine now.

**Comment by edickie** [comment]
> edickie@tigrsrv:/archive/data-2.0/SPINS/bin$ cat  /etc/resolv.conf
> # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
> #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
> 
> # Ansible managed: /projects/admin/ansible-playbooks/roles/common/templates/resolv.conf.head.j2 modified on 2016-07-06 18:00:08 by localadmin on tigrsrv.camhres.ca
> 
> nameserver 172.26.216.35
> nameserver 172.28.216.52
> search camhres.ca
> options single-request-reopen

**Comment by josephdviviano** [comment]
@edickie I think this is the issue:

```
localadmin@srv-web:~$ ssh tigrsrv@camhres.ca
ssh: Could not resolve hostname camhres.ca: No address associated with hostnam
```

**Comment by josephdviviano** [comment]
@edickie also you might want to reboot your machine if you have a chance and your internet is slow.

**Comment by edickie** [comment]
This is on tigrsrv..

**Comment by josephdviviano** [comment]
Yes I know. `srv-web` does not resolve `tigrsrv` for some reason.

**Comment by edickie** [comment]
So we shouldn't be running the run scripts in tigrsrv??

**Comment by josephdviviano** [comment]
@edickie err nevermind that wwas a stupid typo. No we should be running scripts on tigrsrv. There's just some sort of communication error at play here. External users have been OK uploading data so it's restricted to us.

**Comment by josephdviviano** [comment]
@edickie fixed the XNAT error. The hosts file was misconfigured thanks to anisible. Now I'm playing with turning up the 'timeout' settings to prevent the `504` errors.

**Comment by josephdviviano** [comment]
@edickie I'm not 100% on what's going on here. It looks like the files are making it through, and `nginx` is reporting a timeout.

Here's my hypothesis:

```
What's happening with each rest call:

    user sends data ---> nginx relays data --> tomcat does stuff [process takes minutes] --> 
                                       nginx times out waiting for tomcat --> user gets error --> tomcat finally finishes [sometimes minutes later].

```

Therefore I'll try making the `nginx` timeout to be equal to the tomcat timeout length. However this is very long. I'm not sure if that opens us up to some security holes.

**Comment by edickie** [comment]
I think we're right here. So we get an error message but the upload is actually working ok..

I'm going to close this for now.

**Comment by josephdviviano** [comment]
Nice, good work Erin. I think I'll assign myself this to see if I can get the 504 to go away, I have an idea.

**Comment by josephdviviano** [comment]
OK. On `srv-web:/etc/nginx/sites-enabled/srv-web`, I set the timeouts to be extreme large (and matched with XNAT). Let's see if the 504 errors go away.

**Comment by josephdviviano** [comment]
Looks like syncing the timeouts fixed the issue! XNAT just requires ungodly timeouts.
