### ISSUE TITLE
No Resources folders for new subjects in data-2.0

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#634]
Maybe this might have something to do with new XNAT config?? 

@josephdviviano how do you see the Resources on the XNAT website again? I'll see it this is an upload or download issue..or both.

**Comment by josephdviviano** [comment]
Hey, right hand side for a subject under 'manage files': there should be a 'scans' and 'resources' folder.

**Comment by josephdviviano** [comment]
I there is only a scans folder resources upload isnt working.

**Comment by edickie** [comment]
xnat-upload.py was programmed to exit if a HTTP error was seen. So it looks like this error was due to our original timeout (504) errors happening which means that the script was never getting to a Resources upload stage.

I changed the HTTP error handling in xnat-upload.py to log and error message but not fail. Now the resources are uploading fine.
