### ISSUE TITLE
Clevis' jobs on the scc not writing logs

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#635]
Clevis' jobs on the scc are running, but they are not generating logs..Plus clevis get super fun mail everytime this happens.

I would email Qing but my camh account is expired..

> From adm@mgmt2.scc.camh.net  Thu Jul 14 17:31:57 2016
> Return-Path: <adm@mgmt2.scc.camh.net>
> X-Original-To: clevis@login01.scc.camh.net
> 

> Delivered-To: clevis@login01.scc.camh.net
> To: clevis@login01.scc.camh.net
> Subject: PBS JOB 155095[36].mgmt2.scc.camh.net
> Precedence: bulk
> Date: Thu, 14 Jul 2016 17:31:57 -0400 (EDT)
> From: adm@mgmt2.scc.camh.net (root)
> Status: R
> 
> PBS Job Id: 155095[36].mgmt2.scc.camh.net
> Job Name:   dm_dtifit_20160714-172750-36
> Exec host:  node09/5
> An error has occurred processing your job, see below.
> Post job file processing error; job 155095[36].mgmt2.scc.camh.net on host node09/5
> 
> Unable to copy file /var/spool/torque/spool/155095-36.mgmt2.scc.camh.net.OU to clevis@login01.scc.camh.net:/external/rprshnas01/tigrlab/archive/data-2.0/STOPPD/pipelines/dtifit/logs/dm_dtifit_20160714-172750
> .o155095-36
> *** error from copy
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive).
> lost connection
> *** end error output
> Output retained on that host in: /var/spool/torque/undelivered/155095-36.mgmt2.scc.camh.net.OU
> 

> Message 297:
> From adm@mgmt2.scc.camh.net  Fri Jul 15 00:34:47 2016
> Return-Path: <adm@mgmt2.scc.camh.net>
> X-Original-To: clevis@login01.scc.camh.net
> Delivered-To: clevis@login01.scc.camh.net
> To: clevis@login01.scc.camh.net
> Subject: PBS JOB 155148.mgmt2.scc.camh.net
> Precedence: bulk
> Date: Fri, 15 Jul 2016 00:34:47 -0400 (EDT)
> From: adm@mgmt2.scc.camh.net (root)
> Status: R
> 
> PBS Job Id: 155148.mgmt2.scc.camh.net
> Job Name:   FS_20160714-172820_STOPPD_CMH_410031_01
> Exec host:  node24/0
> An error has occurred processing your job, see below.
> Post job file processing error; job 155148.mgmt2.scc.camh.net on host node24/0
> 
> Unable to copy file /var/spool/torque/spool/155148.mgmt2.scc.camh.net.OU to clevis@login01.scc.camh.net:/external/rprshnas01/tigrlab/archive/data-2.0/STOPPD/pipelines/freesurfer/logs/FS_20160714-172820_STOPP
> D_CMH_410031_01.o155148
> *** error from copy
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive).
> lost connection
> *** end error output
> Output retained on that host in: /var/spool/torque/undelivered/155148.mgmt2.scc.camh.net.OU
>

**Comment by pipitone** [comment]
There is a PBS option you can set to redirect mail (or not send it all). From the log below it looks like an ssh problem for the clevis user. Andy is your man for SCC issues.

**Comment by edickie** [comment]
email sent

**Comment by edickie** [comment]
Andy's on vacation but David did set clevis up with a proper home directory!!
dtifit appears to be running with logs!
