### ISSUE TITLE
ssh access

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#636]
Hey Guys,

It is Arash from Alcatraz! :D Hope you are doing great. 

I was wondering if there is any time table that we can ssh to the cluster.

Cheers,

Arash

**Comment by josephdviviano** [comment]
Hey Arash! Sorry to say nothing clear on that yet, we've put a request
through. I'll pester them about it next week.

Joseph's Phone

**Comment by josephdviviano** [comment]
Hi David,
Will Follow up and provide you update once I get.
Regards
Darshan Patel

From: David Rotenberg
Hi Darshan,
Could you please provide us with an update for **INC16497156**. It appears that this is still awaiting evidence.

**Comment by josephdviviano** [comment]
Looks like, with a VPN token, we can get laggy access via `remote.camh.ca`, however, I'm pushing for another port.

**Comment by josephdviviano** [comment]
I'm continuing on my quest for a direct port, however we also have an alternative method as detailed in the email I sent out today. @arash-n let me know if you didn't get it. I'm going to close this issue.
