### ISSUE TITLE
The scc says the tigrlab stoage is 100% full!

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#637]
wft?
```
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg.1-lv.root2
                       16G  7.8G  7.1G  53% /
tmpfs                  95G   80K   95G   1% /dev/shm
/dev/sda1             240M   57M  171M  25% /boot
/dev/mapper/vg.1-temp
                       26G  227M   24G   1% /tmp
/dev/mapper/vg.1-quarantine
                       30G   21G  9.5G  69% /local_quarantine
mgmt1:/archive/NEUROGENETICS/NEURO
                       16G  7.1G  7.8G  48% /NEUROGENETICS/NEURO
mgmt1:/archive/NEUROGENETICS_VINCENT
                       16G  7.1G  7.8G  48% /NEUROGENETICS_VINCENT
mgmt1:/archive/TEMERTY
                       16G  7.1G  7.8G  48% /TEMERTY
mgmt1:/core/KIMEL      11T  6.4T  4.0T  62% /KIMEL
mgmt1:/imaging/home    16G  7.1G  7.8G  48% /imaging/home
mgmt1:/imaging/scratch
                       16G  7.1G  7.8G  48% /imaging/scratch
mgmt1:/genome/home     16G  7.1G  7.8G  48% /genome/home
mgmt1:/genome/scratch
                       16G  7.1G  7.8G  48% /genome/scratch
mgmt1:/quarantine     296G  161G  120G  58% /quarantine
mgmt1:/install        300G   93G  208G  31% /install
tmpfs                 100G     0  100G   0% /export/ramdisk
mgmt1:/archive/EPIGENETICS/SCRATCH
                       33T   24T  9.4T  72% /EPIGENETICS/SCRATCH
rprshnas01:/tigrlab/tigrlab
                      100T  100T     0 100% /external/rprshnas01/tigrlab
```

**Comment by josephdviviano** [comment]
Yeah, I know. `external` is 50 TB of that I think. We might need to clear that out a bit.

I could delete scratch from there. I don't think we need a copy of scratch. But I can't do that until Monday.

**Comment by edickie** [comment]
no no no no!!! All my stuff is in scratch!!!

**Comment by edickie** [comment]
I'm pretty sure projects is only an old backup of projects but scratch is new data

**Comment by edickie** [comment]
I tried to delete new clevis pipeline outputs from the scc side but it errors out because "no space left on device"

**Comment by josephdviviano** [comment]
Ok let's talk about this on Monday. I cant do anything remotely anyhow.

We need to get everyones projects data over to tigrlab.

I'm going to turn tigrsrv into a massive pile of scratch.

Joseph's Phone

**Comment by edickie** [comment]
Will the full disk effect the way xnat functions?

**Comment by josephdviviano** [comment]
Hi Erin, no, the live XNAT data is in a datastore in the basement (where
our old backups used to be).

If you want to learn more there are a few open issues assigned to me
regarding how we will manage our data going forward.

I might suggest that we move the scratch stuff you need on tigrsrv to a
projects folder for clevis. I think it would be better if scratch wasn't on
/mnt/tigrlab at all in the long term. Scratch is not supposed to get backed
up.

JDV

**Comment by josephdviviano** [comment]
@edickie closing this as well since we have 7 T of breathing room now.
