### ISSUE TITLE
Deal with Erin's stuff in /mnt/tigrlab/scratch/edickie before doing anthing to tigrlab/scratch

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#638]
Hey this is my own to do list, but I thought I should make @josephdviviano aware of the issue before we start deleting things to make space in the /mnt/tigrlab storage...

I have pretty much everything I've been working on for the past 4 months sitting in /mnt/tigrlab/scratch/. Mostly because:

+ I've started doing everything on the scc or scinet and using storage that is mounted on the scc, but also on kimel machine was pretty ideal from that. 
+ Some of it is well organized and ready to go into projects, but I didn't put it in projects because projects was running out of space... 
+ And I didn't put it in /tigrlab/projects because I was afraid that that space would be overwritten when when tigrsrv projects is backed up..
+ .Also I thought that all research IT drives are supposed to be mirrored and backed-up by research IT so it seemed like a relatively safe place to put stuff..

But now we have a big problem. Because the drive is full and I can get onto the scc but I can't delete any files...(error message cannot rm: no room left on device)

Anyway here's and inventory of what is there...
611G    POND_RST/ - after finishing QC can document and move to project space
324G    VULDE_rest/ - completly a back-up can move to a backup space
18G    ABIDEII/ -
3.1T    ABIDE/ - including
109G    nii/ - can go because it should be copied to the public datasets folder
311G    freesurfer/ - can clean it (write README.md) add qc file up and have it move to public
1.4T     hcp/ -working out of this - but also could be moved to projects/public datasets

953G    epi-201604 - move to projects
206G    epi-fixtrain - move to projects
1.5G     fix_training_data - move to projects

795M   20160610_PINT_Yeo7-76v_rad4-8-12 - keep in scratch
795M   20160610_PINT_Yeo7-76v_rad6-6-12 - keep in scratch
795M   20160627_PINT_Yeo7-76v_rad8-8-12 - keep in scratch
13G   qc_20160610_PINT_Yeo7-76v_rad4-8-12.tar - keep
13G   qc_20160610_PINT_Yeo7-76v_rad6-6-12.tar - keep

ABIDE contents that can be deleted
716M   20160530_PINT_Yeo7-76v_rad4-8-12 - delete old algorithm
716M   20160530_PINT_Yeo7-76v_rad6-6-12-  delete old algorithm
abide_PINT - copied from projects for transfer (can delete)
117M  bin - can delete
13G   qc_20160610_PINT_Yeo7-76v_rad4-8-12 - reundant (delete)
13G   qc_20160610_PINT_Yeo7-76v_rad4-8-12-bkup - redundant (delete)
13G   qc_20160610_PINT_Yeo7-76v_rad6-6-12 - redundant (delete)
13G   qc_20160610_PINT_Yeo7-76v_rad6-6-12-bkup -redundant (delete)
test_6 - delete

The imob preprocesses data: (waiting for Navona's ICA labels): can probably remove intermediate file from all...
70G    COGBDY_CMH_imob/ -keep (
178G    DTI_CMH_imob/ - keep
276G    SPINS_CMH_imob/ - keep
59G    COGBDO_CMH_imob/ - keop

junk
SPINS_test
_CMH_imob

**Comment by edickie** [comment]
IP.S. I'm mostly freaking out because this post seems to say that the "cannot rm" error could be related to a currupted disk...

http://www.unix.com/linux/232591-no-space-left-device-when-using-rm.html

**Comment by josephdviviano** [comment]
Erin don't worry if you completely fill a disk you commonly get a cannot
remove error unknown work around.

Thanks for the details!

Joseph's Phone

**Comment by pipitone** [comment]
Btw one sneaky way around a completely full disk you can't rm from is to sacrifice a large file by doing "echo > file.dat". That frees up the space of the file without removing it and can often get you going again. 

- Jon on a bike north of Williamsford

**Comment by josephdviviano** [comment]
@edickie all of this stuff is in your projects folder now, so I'm closing this issue.
