### ISSUE TITLE
run script complain that su can't be run as cron job

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#639]
Hi guys,

So from this morinings email. None of the run scripts ran last night becuase it claims that su can't be run from the terminal??

Why are we using su in the master run script anyway?
>su -c "$project/bin/run.sh --quiet" - clevis

I'm currently running the run script manually..

**Comment by josephdviviano** [comment]
That's interesting, I believe I changed how the run script is run (owner
was root, I believe i changed it to clevis)

I'll change it back to root, see if the problem goes away.

Joseph's Phone

**Comment by josephdviviano** [comment]
Changing the cronjob to root made the problem go away.
