### ISSUE TITLE
dual regression

### ISSUE THREAD

**Issue by nhneufeld** [TIGRLab/admin#64]
I am able to run Dual Regression in FSL/5.0.6 using David's modified script dual_regression_DJR_B, however dual_regression does not work.

**Comment by pipitone** [comment]
I'm reopening this since Vincent is having trouble with this again.

**Comment by josephdviviano** [comment]
I've had a look through all of the fsl_sub scripts. They all reference `main.q`, so without more information, I'm not sure what to do.

**Comment by josephdviviano** [comment]
I'm going to close this because I'm not convinced this is a problem.
