### ISSUE TITLE
USB won't mount on some machines

### ISSUE THREAD

**Issue by lyoganathan** [TIGRLab/admin#640]
Hey,

When I try to mount my USB key, it says "unable to mount operation already pending" something along those lines. This happened on crick.

Thanks,
Laagi

**Comment by josephdviviano** [comment]
Hey Laagi,

This is an annoying issue we've never figured out. A reboot of your computer should fix it.

**Comment by lyoganathan** [comment]
Ah I see, Thanks Jo!
