### ISSUE TITLE
for datman: add MAGETBRAIN

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#643]
https://github.com/CobraLab/antsRegistration-MAGeT

^ this is the version Gabe recommends.

**Comment by pipitone** [comment]
Update: There are a few issues to work out (see CobraLab/antsRegistration-MAGeT#46, and CobraLab/antsRegistration-MAGeT#48), but for the moment I've created a working branch for the SCC here https://github.com/pipitone/antsRegistration-MAGeT/tree/scc, and installed this as the  module `MAGeT-Brain/20160728`. 

I'm running a test of MAGeT in `/imaging/scratch/kimel/jpipitone/mb_test`, and specifically running the SPINS T1s in the subfolder `SPINS`. The basic procedure for datman run script will be:

```sh
module load MAGeT-Brain/20160728
cp -l data/nii/*/*_T1_* pipelines/magetbrain/input/subject/
cd pipelines/magetbrain
mb.sh run
```

**Comment by josephdviviano** [comment]
Awesome!!

Joseph's Phone

**Comment by pipitone** [comment]
Okay, output segmentations from the SPINS run are here: 
`/imaging/scratch/kimel/jpipitone/mb_test/SPINS/pipelines/magetbrain/output/labels/majorityvote`

Have a look.

I've switched to using the latest ANTS version rather than the version bundled with minc-toolkit (we're operating on niftis anyhow).

I don't think there is anything to add to datman per se, unless we want to deal with intermediate files in some special way (for 63 SPINS T1 images the intermediate files take up a whopping 300G).

**Comment by josephdviviano** [comment]
Looks good. I don't think we would want to add anything to datman except for that we would want this to be run nightly on all of our participants. So a (very short) script that gets the inputs in order, runs maget brain, and puts the outputs in sorted folders that we could call from a `run.sh` would be needed. Could you help with that?

**Comment by pipitone** [comment]
Certainly. It's basically the snippet of bash I posted above that needs to be added to a run.sh script. Shall I do this for SPINS first?

**Comment by josephdviviano** [comment]
Yeah! The trick will be making it work with the input nifti directories, and making sure the outputs end up in nice datman-like folders (the outputs in majorityvote should be moved to another folder to be similar to our other datman pipelines). Not hard just a bit of doing.

**Comment by edickie** [comment]
Hey Jon,

All run scripts are being written by the run-script writter now.. so you
would need to add the bash snippet to config file (or
metadata/project_setting.yml)...

Any changes not in the config file will get deleted/overwirtten by
tigr-write-runsh.py when it runs...

**Comment by edickie** [comment]
Also..we are trying to do all the heavy processing on the scc...

**Comment by edickie** [comment]
Oh sorry disregard the last one...you are already doing this on the scc.

**Comment by pipitone** [comment]
Okay. Erin, I'll just set up MB in SPINS and run it manually for now. I'll let you know when there is something ready to be added to the run script writer and we can manage integration.

**Comment by josephdviviano** [comment]
Hey JP -- don't bother running maget brain manually. 

We don't need the data for the next few months, but we would like to have MB outputs on **all** of the data ready at-hand in the longer term, so the run-script stuff is useful.

 If you can create a command-line tool for MB that basically does what that little script above does, I'm sure erin can figure out how to put it in her run script wrtier (that thing is pretty easy to use, right?)

**Comment by pipitone** [comment]
Okeydokey.

**Comment by pipitone** [comment]
Alright, I've written a dm-proc script for maget brain here: 
https://github.com/TIGRLab/datman/commit/e1f458454f5c846ee5c9f6aa1e1c7fd730b60017

The commit message explains more about how it works.
