### ISSUE TITLE
get GI index running for ANDT

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#644]
Amy Miles asked:
>Is there an easy way to add this to the automated processing pipeline for my images?
>https://surfer.nmr.mgh.harvard.edu/fswiki/LGI

From https://surfer.nmr.mgh.harvard.edu/fswiki/LGI:

> recon-all -s <subj> -localGI
> 
> This will produce files named lh.pial_lgi and rh.pial_lgi in the subjects surf directory. These files can be loaded as overlays in tksurfer.
> 
> Important! Firstly, MATLAB is required to use the -localGI feature. Also, you will need their Image Processing Toolbox. Secondly, usage of the -localGI feature assumes that a subject has already been processed by the freesurfer {{{recon-all -s <subjid> -all}}} stream, such that the ?h.pial surface files exist in the subject's <subj>/surf directory (see the FsTutorial page). You will also need $FREESURFER_HOME/matlab in your matlab path set up in your ~/matlab/starup.m script.

**Comment by josephdviviano** [comment]
Hey @edickie , I know for `qdec` you can just re-run recon-all on an already-complete subject and it will add the qdec stuff, is this similar for `localGI`?

**Comment by edickie** [comment]
Yes, it looks like localGI is actually meant to be run that way... (i.e.
after freesurfer has completed)

If you add the localGI flag to a new recon-all run there are all the
fails...

I'm putting this issue on hold cuz it looks like a good thing for Amy to do
herself.
