### ISSUE TITLE
rerun pipeline output for freesurfer w/out FSL/5.0.9 loaded

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#645]
I'm writing this here for posterity,

We recently noticed that loading FSL/5.0.9 and freesurfer at the same time leads to less than ideal freesurfer performance. We are now working to regerate all the scc side freesurfer runs with a cleaner freesurfer enviroment..

**Comment by pipitone** [comment]
To stop this from happening in the future,, one thing you can do is add
a conflict statement to the freesurfer module, e.g. 

   conflict FSL

That way, when you attempt to load both modules you'll get an error.

**Comment by edickie** [comment]
The annoying thing is that many HCP and epitome pipelines use a combination
of FSL and freesurfer tools, so setting a conflict could cause more harm
than good. :-(

**Comment by pipitone** [comment]
womp womp

**Comment by edickie** [comment]
We now reran everything///I am done with this shizz
