### ISSUE TITLE
purkinje is missing the nvidia drivers

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#653]
For the Quadro M4000 nvidia says to use this driver: http://www.nvidia.com/download/driverResults.aspx/105343/en-us

I can do the install, but I'll wait on @josephdviviano in case he has plans in the works for something else.

**Comment by josephdviviano** [comment]
@pipitone go for it... maybe just install the driver from Ubuntu's 'additional drivers' interface.  the ansible run of installing nvidia drivers messed up a bunch of machines. I've removed that from ansible roles so this should not happen again... we're going to have to manage this manually given how heterogeneous the machines are.

**Comment by pipitone** [comment]
Done.
