### ISSUE TITLE
queue

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#654]
Is there a fix for the queue sending jobs to computers that don't exist? My jobs just stall and I don't know unless I check the queue.

**Comment by josephdviviano** [comment]
I'm looking into it. I don't really understand how Ansible is updating the Sun Grid Engine config.

**Comment by josephdviviano** [comment]
Hi Melissa,

I've just regenerated the queue from scratch. It looks like the missing machines aren't on the queue any longer. Maybe you want to give the queue a test drive to see if it does the right thing now?

Thanks for your patience.

**Comment by mlevesque82** [comment]
Thanks Joe! I'll let you know!


________________________________

**Comment by josephdviviano** [comment]
Hey @mlevesque82 I've reset the queue from scratch, the 'bad' machines appear to be gone. Maybe give it a test run?

**Comment by josephdviviano** [comment]
Hey @mlevesque82 -- looks like `com02` and `com03` weren't configured properly (they didn't know who 'melissa' was .. the nerve!) but I've fixed that ... want to try submitting the failed jobs again?

**Comment by mlevesque82** [comment]
just did, I'll let you know if it stops running


________________________________

**Comment by josephdviviano** [comment]
@mlevesque82 I think this is fixed, feel free to reopen the issue if you run into trouble!
