### ISSUE TITLE
Check machine times/timezones

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#656]
I just noticed that purkinje has the wrong timezone (CDT), so it might be worth double checking all of the new machines. From the command line: `date +%Z`

**Comment by josephdviviano** [comment]
Did you change it? It looks like Thu Aug  4 14:42:49 EDT 2016 now.

**Comment by pipitone** [comment]
I did

**Comment by josephdviviano** [comment]
Thanks, fixed.
