### ISSUE TITLE
cortical thickness in DTI 1.5T data

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#657]
Would it be possible to run all of the DTI TGH T1s through CIVET and then Mallar's script to get the averaged thickness in AAL ROIs? I've been trying to run it but it isn't finished and I don't think this is something I can do remotely. 

I have the scripts:
/projects/melissa/current/Scripts/CIVET/CIVET-processing/CIVET-processing_2_revised_AW&ML.txt
and
/projects/melissa/current/Scripts/CIVET/aal/get_aal_CT_SA.pl

I would really appreciate it!

**Comment by josephdviviano** [comment]
Erin isn't this part of datman already?

Joseph's Phone

**Comment by edickie** [comment]
Running CIVET is part of datman - but we haven't run it no the 1.5T data
because it's not in the nightly run scripts.

I never built the second AAL step into datman..

I thought this might be a nice learning experience for Dawson...

**Comment by josephdviviano** [comment]
I agree! Shouldn't be too hard for him. After he gets oriented we can assign him to this task.

**Comment by mlevesque82** [comment]
That would be amazing.


________________________________
