### ISSUE TITLE
queue is appending semicolon to user'

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#658]
A bunch of melissa's jobs are failing on the queue because it can't find the user 'Melissa'. I could never find the problem machine, but this entry in the log (below) suggests something is appending a semicolon to her username :

```
Security Events for su
=-=-=-=-=-=-=-=-=-=-=-
       0 Lines skipped (already processed)
       0 Patterns to ignore
       0 Ignored lines
       2 tigrsrv su: pam_mkhomedir(su:session): unknown option: mask=0077
       2 tigrsrv su: No passwd entry for user 'melissa;'
       2 tigrsrv su: FAILED su for melissa; by root
       1 tigrsrv su: - /dev/pts/24 root:melissa;
       1 tigrsrv su: - /dev/pts/29 root:melissa;
```

I should investigate.

**Comment by josephdviviano** [comment]
also might be related ... http://serverfault.com/questions/595176/pam-is-unable-to-make-users-home-directory

```
Security Events for su
=-=-=-=-=-=-=-=-=-=-=-
       0 Lines skipped (already processed)
       0 Patterns to ignore
       0 Ignored lines
       1 tigrsrv su: pam_mkhomedir(su:session): unknown option: mask=0077

```

**Comment by pipitone** [comment]
Looking at the logs on tigrsrv, I see the `melissa;` messages in the `auth.log.1` but the seem to be coinciding with ansible commands being run, e.g.:

```
Aug  5 16:05:44 tigrsrv sudo: localadmin : TTY=pts/24 ; PWD=/var/localadmin ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uhrybwbopdtcafkwrmbothwjniotfzhm; LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/env python /var/localadmin/.ansible/tmp/ansible-tmp-1470427543.98-620866032240/command; rm -rf "/var/localadmin/.ansible/tmp/ansible-tmp-1470427543.98-620866032240/" > /dev/null 2>&1
Aug  5 16:05:44 tigrsrv sudo: pam_unix(sudo:session): session opened for user root by localadmin(uid=0)
Aug  5 16:05:44 tigrsrv sudo: localadmin : TTY=pts/29 ; PWD=/var/localadmin ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jmhyypmlgpdekjlmoynoyrmsugexdwwa; LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/python /var/localadmin/.ansible/tmp/ansible-tmp-1470427544.31-209548009497277/command; rm -rf "/var/localadmin/.ansible/tmp/ansible-tmp-1470427544.31-209548009497277/" > /dev/null 2>&1
Aug  5 16:05:44 tigrsrv sudo: pam_unix(sudo:session): session opened for user root by localadmin(uid=0)
Aug  5 16:05:44 tigrsrv sudo:     root : TTY=pts/24 ; PWD=/var/localadmin ; USER=root ; COMMAND=/bin/su melissa; exit
Aug  5 16:05:44 tigrsrv sudo: pam_unix(sudo:session): session opened for user root by localadmin(uid=0)
Aug  5 16:05:44 tigrsrv su[8468]: No passwd entry for user 'melissa;'
Aug  5 16:05:44 tigrsrv su[8468]: FAILED su for melissa; by root
Aug  5 16:05:44 tigrsrv su[8468]: - /dev/pts/24 root:melissa;
```

I'll keep poking around and let you know if I find anything else relevant.

**Comment by pipitone** [comment]
The "unknown option: mask=0077" is coming from an incorrect setting we have in ansible when we configure `pam_mkhomedir` in `/etc/pam.d/common-session`, here: https://github.com/TIGRLab/ansible-playbooks/blob/master/roles/ipa-client/tasks/main.yml#L51

It should be `umask=0077`. I've tested this on purkinje and updated `ansible-playbooks/ipa-client/tasks/main.yml`. Since we've been running with this error for a while now I doubt it's the problem.

**Comment by josephdviviano** [comment]
Nice thanks @pipitone I'm applying that change across the board.

I'll keep looking into `auth.log`.

**Comment by josephdviviano** [comment]
This might coinside with the fact that I put a bunch of new machines on the queue and `SGE` does not make home folders.

I'm adding a make home directories for all users in ansible thing.

**Comment by pipitone** [comment]
You shouldn't need to do that though; I would expect a properly configured pam to do that.

**Comment by josephdviviano** [comment]
well if a user ssh's into a machine, the home folder is created.

but if they just run sge, and the job lands on that machine, it is not created. Is this a feature of PAM? I couldn't find any suggestion of that on Google.

**Comment by josephdviviano** [comment]
pam is working fine when ppl log in it's just SGE...

**Comment by josephdviviano** [comment]
I did it my way, it worked for `doverton`. @pipitone if you figure out a more elegant solution get back to me.

**Comment by pipitone** [comment]
FYI jobs run completely fine without a user's home folder (just tested it).

**Comment by josephdviviano** [comment]
Not true for all kinds of jobs. multiple jobs were failing at 'could not chdir to `/home/blah` :)
