### ISSUE TITLE
STOPPD_CMH_460004_01_01 is in SPINS in XNAT

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#659]
?

**Comment by navonacalarco** [comment]
Trying to move files via Actions> Edit > modify project name doesn't seem to work ("ERROR (409): Failed to modify project")

@josephdviviano Do you deal with this by downloading and then reuploading?

**Comment by josephdviviano** [comment]
I think so, not sure if this has ever happened before TBH.

**Comment by DESm1th** [comment]
This subject has reappeared in SPINS with two weird series. :( Where did these come from?

**Comment by josephdviviano** [comment]
@navonacalarco @DESm1th this is because the name of the patient in the dicom header must be named STOPPD_CMH_460004_01_01

Is this a STOPPD only scan, or a SPINS scan?

Perhaps the MR unit just put this file in the wrong folder on the MR server?

**Comment by navonacalarco** [comment]
This is a STOPPD only scan.

**Comment by josephdviviano** [comment]
So, seems likely the MR unit put it in the wrong folder.

**Comment by navonacalarco** [comment]
As far as I can tell (by reviewing exam IDs on the MR server), the MR unit did not put this in the wrong folder. But, the STOPPD data hasn't popped up in the SPINS folder for a while now, so going to close. Please reopen if you think that's shortsighted.
