### ISSUE TITLE
"Error: GDK_BACKEND does not match available displays"

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#661]
I get this error when using the new VPN/PuTTY arrangement to try to open a QC doc.

![screen shot 2016-08-08 at 9 16 48](https://cloud.githubusercontent.com/assets/13733654/17501524/a1abebc4-5dad-11e6-9018-b12ee51cd80b.png)

**Comment by edickie** [comment]
Hey Navona,

Are you trying this with X-forwarding?

**Comment by navonacalarco** [comment]
Hi Erin!

I thought so, but all I did was check a box:

![screen shot 2016-08-09 at 8 18 18 am](https://cloud.githubusercontent.com/assets/13733654/17516015/f52abae4-5e09-11e6-9d7c-e3eb3dbb40ca.png)

**Comment by josephdviviano** [comment]
This is what I tried too, it didn't work. I've let them know ... not sure
what they are going to do about it though.

JDV

**Comment by navonacalarco** [comment]
Thanks!

**Comment by josephdviviano** [comment]
I don't really think this is an outstanding issue given we have an alternative ssh method as detailed in my email. @navonacalarco let me know if you need help getting an scc or scinet account.

**Comment by navonacalarco** [comment]
I have both SCC and SciNet accounts... thanks for instructions!

**Comment by basiljose1** [comment]
**If it says Error: GDK_BACKEND does not match available displays then install pyvirtualdisplay:**

pip install pyvirtualdisplay selenium
You might need xvfb too:

sudo apt-get install xvfb
Then try adding this code:

from pyvirtualdisplay import Display
display = Display(visible=0, size=(800, 600))
display.start()
Full example:

from pyvirtualdisplay import Display
from selenium import webdriver

display = Display(visible=0, size=(800, 600))
display.start()

browser = webdriver.Firefox()
browser.get('http://www.python.org')

browser.close()
display.stop()

**Comment by gzhappysky** [comment]
I have encountered this problem, yesterday has been resolved.

call stack:  robot ... -> geckodriver -> firefox 

You make sure that both of the above are successful, we look at "geckodriver.log”, and location firefox failed to start:

> Error: GDK_BACKEND does not match the available display


You can run firefox in terminal:
sudo firefox
Error: GDK_BACKEND does not match the available display

So following are the steps to solve this issue:

setp 1: install Xvfb
apt-get install Xvfb

setp 2: run Xvfb
nohup sudo Xvfb: 10 - ac &

step 3: set the terminal 
export DISPLAY =: 1

**Comment by josephdviviano** [comment]
@basiljose1 @gzhappysky thanks for your help with this!!
@navonacalarco , maybe give this a shot? I've installed `Xvfb` on your machine.

**Comment by Dhana005** [comment]
export DISPLAY=:10 There should not be space between : and 10
