### ISSUE TITLE
scinet resource allocation due MID SEPT

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#663]
https://www.computecanada.ca/research-portal/accessing-resources/resource-allocation-competitions/

**Comment by djoverton** [comment]
FYI:

RPP Notice of Intent submission, opens: Early September, due: Sep 22, 2016.

**Comment by djoverton** [comment]
The deadline is fast approaching; are we planning on applying for anything?

**Comment by josephdviviano** [comment]
I don't think so, we don't have enough users hammering scinet for it to matter.
