### ISSUE TITLE
Make image file for participant SPN01_CMH_0080_01_01

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#668]
Participant asked for "colourful picture". Maybe also give a GIF?

Send to Judy <judy.kwan@camh.ca> and Jess <Jessica.DArcey@camh.ca>

**Comment by josephdviviano** [comment]
Try opening the image using AFNI -- easy to make colourful pics :-D

**Comment by navonacalarco** [comment]
Yay! Coloured images and gifs! :dancers:

**Comment by josephdviviano** [comment]
:whale: :whale: :whale:
