### ISSUE TITLE
fix classifiers (1 for MRC, ZHH, CMH) for SPINS

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#674]
As a part of #561, we're going to transition to using FIX to classify noise in our fMRI data.

To do this, we're going to need to use a single classifier for each scanner. We have hand-labeled data for the IMOB task at each site, so we're going to make our classifiers out of 50% IM and 50% OB ICA labels.

- [x] MRC
- [x] ZHH
- [x] CMH

**Comment by josephdviviano** [comment]
When those .Rdata files are generated, please point me to them so I can go about making the epitome scripts required to run them (and testing this out on the SCC).

**Comment by edickie** [comment]
If you want to start building some rough code.. you can use the epicTIGR.Rdata as a place holder for the fix classifiers we want..

/projects/edickie/analysis/epicTIGR/epicTIGR.RData

Info about the preprocessing pipeline pre ICA (which will match the one for the new classifiers)
/projects/edickie/analysis/epicTIGR/epicTIGR_README.md

**Comment by josephdviviano** [comment]
@edickie @navonacalarco where are we at with this?

**Comment by navonacalarco** [comment]
@josephdviviano @edickie Are we planning to meet to discuss anything related to this before JDV leaves? I'm free after 3.

**Comment by josephdviviano** [comment]
@edickie can you please post the path to those ICA classifiers

**Comment by edickie** [comment]
/projects/edickie/analysis/201607_IMOB/SPINS_CMH_imob/epi-20160520
R data files are named:
CMHOBS24.RData
MRCOBS24.RData
ZHHOBS24.RData

**Comment by josephdviviano** [comment]
Thanks! They're here now:

`/archive/data/assets`
