### ISSUE TITLE
SPINS DTI-60Dir-5B0-ColFA being exported and T1 exported as DTI?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#677]
Note: the file ending in "Col-FA" are processed files we should not be downloading..
Maybe we need to change the regex in export-info.csv..

> Error 1 while executing: DWIConvert -i /mnt/xnat/spred/archive/SPN03/arc001/SPN01_MRC_P001_01_01/SCANS/24/DICOM --conversionMode DicomToNrrd -o SPN01_MRC_P001_01_01_DTI60-1000_24_DTI-60Dir-5B0-ColFA.nrrd --outputDirectory /archive/data-2.0/SPINS/data/nrrd/SPN01_MRC_P001_01
> stderr: 
> >	E: DcmElement: Unknown Tag & Data (3f3c,6d78) larger (1702240364) than remaining bytes in file
> >	Exception thrown while reading DICOM volume
> >	
> >	itk::ExceptionObject (0x187bbe0)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	Exception creating converter 
> >	itk::ExceptionObject (0x187bbe0)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	
> Error 1 while executing: DWIConvert -i /mnt/xnat/spred/archive/SPN03/arc001/SPN01_MRC_P002_01_01/SCANS/23/DICOM --conversionMode DicomToNrrd -o SPN01_MRC_P002_01_01_DTI60-1000_23_DTI-60Dir-5B0-ColFA.nrrd --outputDirectory /archive/data-2.0/SPINS/data/nrrd/SPN01_MRC_P002_01
> stderr: 
> >	E: DcmElement: Unknown Tag & Data (3f3c,6d78) larger (1702240364) than remaining bytes in file
> >	Exception thrown while reading DICOM volume
> >	
> >	itk::ExceptionObject (0x2638250)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	Exception creating converter 
> >	itk::ExceptionObject (0x2638250)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	
> Error 1 while executing: DWIConvert -i /mnt/xnat/spred/archive/SPN03/arc001/SPN01_MRC_P003_01_01/SCANS/23/DICOM --conversionMode DicomToNrrd -o SPN01_MRC_P003_01_01_DTI60-1000_23_DTI-60Dir-5B0-ColFA.nrrd --outputDirectory /archive/data-2.0/SPINS/data/nrrd/SPN01_MRC_P003_01
> stderr: 
> >	E: DcmElement: Unknown Tag & Data (3f3c,6d78) larger (1702240364) than remaining bytes in file
> >	Exception thrown while reading DICOM volume
> >	
> >	itk::ExceptionObject (0x121bd70)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	Exception creating converter 
> >	itk::ExceptionObject (0x121bd70)
> >	Location: "unknown" 
> >	File: /home/kitware/Dashboards/Package/Slicer-440-package/ITKv4/Modules/Core/Common/include/itkMatrix.h
> >	Line: 249
> >	Description: itk::ERROR: Singular matrix. Determinant is 0.
> >	
> >	
> >	

Also, this suggests that T1 files are being converted to nrrd?? or exported as DTI??
> [dm-check-bvec] ERROR: No gold standard .bvec file for tag T1
> [dm-check-bvec] ERROR: No gold standard .bval file for tag T1

**Comment by navonacalarco** [comment]
T1 files were indeed being converted to nrrd in exportinfo.csv. We changed that, now @DESm1th and I are figuring out the regex. :boom:

**Comment by navonacalarco** [comment]
Changed regex; will check tomorrow to see if it works.

**Comment by navonacalarco** [comment]
Actually, I need some help figuring out how to check if this actually works. 

@DESm1th It would be awesome to get your insight, if you have a bit of time to look at this together.

**Comment by navonacalarco** [comment]
![funny-face-cat](https://cloud.githubusercontent.com/assets/13733654/17788801/592e3336-655d-11e6-8ad4-1ad628666162.jpg)

Closing for now. We'll see.
