### ISSUE TITLE
DTI scan.csv need to be updated

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#680]
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2012_0910_001SP.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2012_0910_002CM.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2012_0910_003DB.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2012_0910_004JW.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2012_0910_005JK.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2014_0716_MF030.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/DTI/CMH/data/zips/2015_0606_CJ097.zip: Cannot find scan id. Skipping

**Comment by josephdviviano** [comment]
+first 5 are in the SPN00 project (these are the original human phantoms) ... ignoring.

**Comment by josephdviviano** [comment]
+ 2014_0716_MF030.zip is a COGBDO scan david has in the wrong folder and I saved. Deleting.

**Comment by josephdviviano** [comment]
+ 2015_0606_CJ097.zip also improperly named. Deleting.
