### ISSUE TITLE
add an EMP gold standard to SPINS

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#682]
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_11_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_12_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_13_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_12_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_13_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_14_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'

**Comment by josephdviviano** [comment]
Interesting case since these are `DTI` participant who are also doing the `SPINS` protocol (?).  Anyhow I added the gold standard.
