### ISSUE TITLE
DTI CMH is exporting many many files as DTI....

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#683]
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_S071_02/DTI_CMH_S071_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H152_02/DTI_CMH_H152_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_11_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_12_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H127_02/DTI_CMH_H127_02_01_EMP_13_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_12_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_13_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H157_02/DTI_CMH_H157_02_01_EMP_14_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H136_02/DTI_CMH_H136_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_12_AxEPI-EATask3.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_10_AxEPI-EATask1.dcm: No matching standard for tag 'EMP'
[dm-check-headers] WARNING: /archive/data-2.0/DTI/CMH/data/dcm/DTI_CMH_H122_02/DTI_CMH_H122_02_01_EMP_11_AxEPI-EATask2.dcm: No matching standard for tag 'EMP'

**Comment by djoverton** [comment]
dm-check-headers.py disabled for this project.
