### ISSUE TITLE
manually update scans.csv for RTMSWM..

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#684]
ERROR: /archive/data-2.0/RTMSWM/data/zips/20160629_Ex05645_RTMSB1MR_RTFT096.zip: Cannot find scan id. Skipping
ERROR: /archive/data-2.0/RTMSWM/data/zips/20160803_Ex05814_RTMSB1MR_RTFT098.zip: Cannot find scan id. Skipping

**Comment by navonacalarco** [comment]
@edickie what script is giving this error? :confused:

**Comment by DESm1th** [comment]
It's datman/bin/link.py . The error should pop up when there's no entry for that .zip in the scans.csv metadata

**Comment by djoverton** [comment]
File naming convention wasn't being followed (one had an extra underscore and another used a dash instead of an underscore). Added the lines in scans.csv to fix this.

**Comment by navonacalarco** [comment]
Sweet, thanks.
