### ISSUE TITLE
COGBDY run-script error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#685]
Unable to resume download of "/archive/data-2.0/COGBDY/data/zips/2014_0314_AM010.zip": local file is larger than remote

@josephdviviano you new what this was about...how do we address this error?

**Comment by josephdviviano** [comment]
Just try a `rm /archive/data-2.0/COGBDY/data/zips/2014_0314_AM010.zip` so we can get the most up-to-date data from the MR center downstairs..

**Comment by djoverton** [comment]
Removed the file; we'll see if this error disappears next time it is downloaded.
