### ISSUE TITLE
COGBDY xnat-upload failed

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#686]
Maybe we need to try to re-upload manually??

> [xnat-upload.py] ERROR: COGBDY_CMH_27B009_02_01 http client error dicom data upload: 400
> [xnat-upload.py] ERROR: ERROR uploading file 20160812_Ex05860_BDCD2MR_BDJM040/Ex05860Se00009_gradOrs.txt
> [xnat-upload.py] ERROR: Error communicating with XNAT
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 154, in <module>
>     main()
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 138, in main
>     raise e
> HTTPError: 404 Client Error: Not Found for url: https://xnat.imaging-genetics.camh.ca:443/data/archive/projects/COGBDYY/subjects/COGBDY_CMH_27B009_02_01/experiments/COGBDY_CMH_27B009_02_01/files/20160812_Ex05860_BDCD2MR_BDJM040/Ex05860Se00009_gradOrs.txt?inbody=true

**Comment by edickie** [comment]
@josephdviviano we tried uploading this manually after deleting the subject from xnat and still we get the same erros

**Comment by edickie** [comment]
I think this might be the same issue?? the error messages look identical

> [xnat-upload.py] ERROR: STOPPD_CMH_410045_01_01 http client error dicom data upload: 400
> [xnat-upload.py] ERROR: ERROR uploading file 20160810_Ex05850_STOP1MR_STGH079e1/TechNotes5850.pdf
> [xnat-upload.py] ERROR: Error communicating with XNAT
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 154, in <module>
>     main()
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 138, in main
>     raise e
> HTTPError: 404 Client Error: Not Found for url: https://xnat.imaging-genetics.camh.ca:443/data/archive/projects/STOPPD01/subjects/STOPPD_CMH_410045_01_01/experiments/STOPPD_CMH_410045_01_01/files/20160810_Ex05850_STOP1MR_STGH079e1/TechNotes5850.pdf?inbody=true

**Comment by tomwright01** [comment]
Multiple session UID's in archive. Data manually added from prearchive.
