### ISSUE TITLE
STOPPD dcm2nii error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#688]
Maybe this one is from empty folders??

Error 1 while executing: dcm2nii -x n -g y  -o /tmp/tmpnCEqH5 /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_210036_01_01/SCANS/0/DICOM
stdout: 
>	Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
>	reading preferences file /home/clevis/.dcm2nii/dcm2nii.ini
>	Data will be exported to /tmp/tmpnCEqH5/
>	Validating 23 potential DICOM images.
>	Unable to find any DICOM files in the path /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_210036_01_01/SCANS/0/DICOM/STOPPD_MAS_210036_01_01.PR.STOPPD02.0.1.20150505.175535.lmsg0l.dcm
>	
Error 1 while executing: dcm2nii -x n -g y  -o /tmp/tmpihA3Nr /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_260009_01_01/SCANS/0/DICOM
stdout: 
>	Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
>	reading preferences file /home/clevis/.dcm2nii/dcm2nii.ini
>	Data will be exported to /tmp/tmpihA3Nr/
>	Validating 20 potential DICOM images.
>	Unable to find any DICOM files in the path /mnt/xnat/spred/archive/STOPPD02/arc001/STOPPD_MAS_260009_01_01/SCANS/0/DICOM/scan_0-OT7_secondary_catalog.xml
>

**Comment by josephdviviano** [comment]
This is just garbage in xnat:

![screenshot from 2016-08-18 12 36 10](https://cloud.githubusercontent.com/assets/4142570/17782186/5ca3af7c-6540-11e6-9582-d376db7a70f5.png)

I'm just deleting all the sessions starting with 0...

**Comment by josephdviviano** [comment]
Done.
