### ISSUE TITLE
rename PRELASPE awesomeness in xnat

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#690]
ERROR: /mnt/xnat/spred/archive/PRE02/arc001/PRE01_IWA_04012_01 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__01_JULY_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__06_JULY_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__13_JULY_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__15_JUN_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__20_JULY_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__22_JUN_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__29_JUN_2016 folder is not named according to the data naming policy. Skipping
ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__8_JUN_2016 folder is not named according to the data naming policy. Skipping
ERROR: Multiple export patterns match for /mnt/xnat/spred/archive/PRE04/arc001/PRE01_GRD_15018_01_01/SCANS/15/DICOM, descr: T2_SPACE_FLAIR_p2_ISO, tags: ['T2', 'FLAIR']

**Comment by navonacalarco** [comment]
Done.
