### ISSUE TITLE
New xnat-extract/py error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#693]
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 416, in <module>
>     main()
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 196, in main
>     extract_archive(exportinfo, archivepath, datadir, blacklist)
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 242, in extract_archive
>     exportdir, blacklist)
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 276, in export_series
>     series_list = blacklist.columns.tolist()[0]
> AttributeError: 'str' object has no attribute 'columns'

**Comment by DESm1th** [comment]
... whoops. That one is on me. I broke a thing while fixing the blacklist thing yesterday.

**Comment by DESm1th** [comment]
Ok. I moved everything related to blacklist reading and error handling into a new function. I tested everything and it seems good, but if anything blacklist related breaks blame me and I'll figure it out.
