### ISSUE TITLE
look at necessity of XNAT "Site-wide Anonymization Enabled"

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#695]
I *think* the reason that renaming files takes so long in XNAT is because the anonymization script (https://xnat.imaging-genetics.camh.ca/app/template/Configuration.vm) runs even for what XNAT calls  "label modification".

@josephdviviano Does it make any sense to try to figure out how/if we could disable this in cases of label modification?

**Comment by josephdviviano** [comment]
@navonacalarco You're welcome to look into it. I'm pretty sure the main reason things are so slow is because XNAT stores all of the DICOM files unpacked, which is very hard on the filesystem.

**Comment by josephdviviano** [comment]
@navonacalarco we also legally need anonymization turned on because XNAT isn't NIH approved (whatever that's called). Redcap is.

**Comment by navonacalarco** [comment]
@josephdviviano  Ah, OK, that settles that, then. Thanks :)
