### ISSUE TITLE
Ensure no Matlab credentials are posted on github

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#700]
We got a strange email yesterday...

Hello Amirhosein,

Thank you for contacting MathWorks. You have requested a license file for license 8xxxxx0 at release R2015a. This license is only eligible for releases up to R2014a. In order to gain access to a later release, the maintenance on this license must be renewed. 

Aristotle Voineskos is the Administrator and End User for license 838860. Please follow up with Aristotle who I have copied on this email.

I don't think anyone knows who Amirhosein is..

Can we check to make sure we don't have credentials on github anywhere?

**Comment by DESm1th** [comment]
Hey guys, I just did a quick skim through and it was in the readme file of TIGRLab/quarantine/matlab. I removed it and will send you both the removed text in a sec for your records. Might be worth a look through the rest of the licensed programs in quarantine just in case any others have private info like that.

**Comment by DESm1th** [comment]
Oh.. er. Someone else will have to delete the old commit with the license info from our commit history. I can't get in remotely to do it at the moment.

**Comment by navonacalarco** [comment]
Thanks @DESm1th. Added the info from the README to the password manager under 'Kimel MATLAB / MathWorks'.

**Comment by josephdviviano** [comment]
Thanks Dawn! I'm without wireless at the moment but when I can I'll remove
the data from our git history.

Joseph's Phone

**Comment by DESm1th** [comment]
Just as an update: I tried to purge the commit history today, but our /opt/quarantine doesn't even use git anymore. I can't figure out where the original repo is stored (if it still exists), and I don't think there's any way to clean up the commit history on github. Maybe it's just best to delete the whole readme file to get the info off the internet?

**Comment by josephdviviano** [comment]
Hi Dawn, I agree, let's delete the repor from the internet and rebuild it
from scratch.

Sorry I haven't been more helpful. WiFi is very close :)

Joseph's Phone

**Comment by DESm1th** [comment]
No worries Joe! Sorry we're bugging you on your vacation. So it's ok if I just permanently delete the whole opt/quarantine repo from github?

**Comment by josephdviviano** [comment]
got wifi! let me take care of it now.

**Comment by josephdviviano** [comment]
I've saved a local copy of the quarantine on my machine here. I've deleted the quarantine repo. We can talk about whether we should reinstate it when I return (I'm not so hot on the idea ... if we are going to put it back online somewhere, we should put it in the private CAMH gitlab program so this does not happen again).

**Comment by DESm1th** [comment]
I agree with you. I was also thinking that maybe our ansible folder should be a private repo as well? Maybe I'm just unnecessarily paranoid, but I was thinking that if someone wanted to do something malicious it might not be a good idea to have all our software/version info and workstation information publicly available. Also, if anyone commits our current ansible folder the printer.conf file with your login details will be public.

**Comment by josephdviviano** [comment]
Hi @DESm1th I agree RE: ansible. For this sort of thing i think it is better to air on the side of caution so we can write exactly what we need to get our jobs done (passwords, ip addresses, etc) without worrying about security.

**Comment by josephdviviano** [comment]
Can you take care of that @DESm1th ?

**Comment by DESm1th** [comment]
Done! I also committed all your uncommitted changes to the new private repo.
