### ISSUE TITLE
Printer issues v2.0

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#701]
Saba is unable to print on any computer and Golgi (which was able to print after Joe tested it) cannot communicate with the printer.

**Comment by josephdviviano** [comment]
This is because I had to change my password yesterday. I'll fix it now.

Joseph's Phone

**Comment by DESm1th** [comment]
Ahh ok! Thanks Joe.

**Comment by josephdviviano** [comment]
I'm propagating the new password now. Can you reopen this issue and @ me if she continues to have trouble (wait ~20 minutes before trying again).
