### ISSUE TITLE
missing 1pg of tech notes PACTMD_CMH_0110036_01

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#703]
Follow up with Anusha.

**Comment by navonacalarco** [comment]
Never mind. Complete tech notes are in RESOURCES folder. So, figure out why not being read in by html. :fearful:

**Comment by DESm1th** [comment]
I'll keep an eye out for that issue. I'm working with qc-html right now for Colin's thing anyway.

**Comment by navonacalarco** [comment]
Never mind again. I can't copy and paste. It was an upload issue - emailing Anusha.

**Comment by navonacalarco** [comment]
Done.
