### ISSUE TITLE
Remove 3 TRs from Sprl Restingstate?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#704]
Hey @josephdviviano @edickie 

Could use your expertise on this issue. The Tech Notes for PACTMD_CMH_3070033_02 advise to drop 3 TRs (101, 102, 103) from the Sprl Restingstate scan: apparently, the MR table itself moved.

I'm not sure if transcribing the note to remove these TRs would get missed on the checklist.csv, but am also not sure what removing them would mean for all potential analyses (or even how to go about removing them).

What do you think?

**Comment by josephdviviano** [comment]
I wouldn't do this to the RAW data. I have some code (see trdrop in epitome) that basically does this based on head motion, so it's not hard to do, but I honestly wouldn't bother with it for now.

In the raw data, can you see any head motion?

**Comment by navonacalarco** [comment]
In the raw data, head motion can be seen.

Upon @josephdviviano's advice, I did not drop the 3 TRs; instead, made a note in checklist.csv. @edickie Please let me know if you have any additional thoughts.

**Comment by josephdviviano** [comment]
There are pre processing methods for doing this, not wise to remove itfrom
the raw data.

Joseph's Phone
