### ISSUE TITLE
change /etc/bash.bashrc to NOT autoload module with terminal start

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#706]
In cases where we lose NFS connections with the CAMH storage, no terminals will open because they are all programmed to auto-load the module system. This can lock us out of being able to do anything to debug.

A better solution would be for the module system to be loaded with a command run by the user (this command could be added to your personal `.bashrc` file if desired, but it would open you up to this problem).

I'mm do this when I return. Let me know if there are any other solutions you can think of.

**Comment by DESm1th** [comment]
Hey Joe,

Maybe we could conditionally load the modules only if /mnt/tigrlab is mounted? Something like this:

if mount | grep /mnt/tigrlab > /dev/null
then
    source /etc/profile.d/modules.sh
    source /etc/profile.d/quarantine.sh
fi

**Comment by tomwright01** [comment]
First access to /mnt/tigrlab is the `module load` command in quarantine.sh
Switch could go here

if [ -e /opt/quarantine/modules/quarantine ]
then
 module load /opt/quarantine/modules/quarantine
else
 echo "Quarantine not available skipping module config."
fi

**Comment by josephdviviano** [comment]
Hey Dawn good idea, do you want to take a stab adding it to the ansible
role for workstations?

Joseph's Phone

**Comment by DESm1th** [comment]
Ok! I'll give it a shot tomorrow morning.

**Comment by josephdviviano** [comment]
Awesome! I'll be back around lunchtime :)

Joseph's Phone

**Comment by josephdviviano** [comment]
@DESm1th wrote an addition to the ansible role for quarantine that is now propagated to the appropriate machines.
