### ISSUE TITLE
Ubuntu not getting along with internal CAMH sites (directly or via Citrix)?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#707]
I've noticed that since we moved to the CAMH network, there's a lot of problems using internal CAMH websites (e.g., Insite). This is the case if we try to access the website directly or remotely (via remote.camh.ca).

Most obvious is the inability to enter data into any fillable form. For example, I presently can't enter into an IMG request form.

Any idea what to do to fix this?

**Comment by josephdviviano** [comment]
Make sure Firefox isn't blocking citrix

Joseph's Phone

**Comment by navonacalarco** [comment]
I think Firefox should be ok: Here's Preferences > Applications:

![screenshot - 08292016 - 11 08 17 am](https://cloud.githubusercontent.com/assets/13733654/18056236/1618e4ae-6dd9-11e6-8b36-38ae1af49134.png)

**Comment by navonacalarco** [comment]
Update thanks to @DESm1th : it's actually just that the click catchment area is off by about 2 inches to the left. So, if I just need to shift my field of vision a bit. 
![index](https://cloud.githubusercontent.com/assets/13733654/18056868/b7e84dcc-6ddb-11e6-9190-3ffeda8e7006.jpeg)

**Comment by DESm1th** [comment]
It turns out this is a bug in the linux citrus receiver. Changing the citrux settings from 'seamless' to any other size fixes it. (see here: http://discussions.citrix.com/topic/98680-published-app-opening-in-blue-window/)

**Comment by navonacalarco** [comment]
![index1](https://cloud.githubusercontent.com/assets/13733654/18057591/9b64e928-6dde-11e6-86ef-bcac6e55be5c.jpeg)
