### ISSUE TITLE
Moderate wrapping in PACTMD_CMH_0100024_01_01

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#709]
Seeing some wrapping isn't infrequent, but it's drifting closer to the important stuff, e.g.:

![screenshot - 08302016 - 01 23 28 pm](https://cloud.githubusercontent.com/assets/13733654/18099530/f71feb2e-6eb4-11e6-94a8-ecc2b548b8c4.png)

@josephdviviano @edickie should I contact Anusha about FOV settings?

**Comment by josephdviviano** [comment]
No that looks expertly done to me, maximum amount of information available in that image (we would complain if the nose goes INTO the brain).

**Comment by navonacalarco** [comment]
OK perfect, thanks!
