### ISSUE TITLE
add new machines to localadmin's passwordless acceess tigrsrv

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#711]

**Comment by DESm1th** [comment]
Hey Joe, 

Here's the recap from ansible:

PLAY RECAP *********************************************************************
bulbasaur.camhres.ca       : ok=66   changed=14   unreachable=0    failed=0   
cajal.camhres.ca           : ok=66   changed=16   unreachable=0    failed=0   
com01.camhres.ca           : ok=41   changed=7    unreachable=0    failed=0   
com02.camhres.ca           : ok=41   changed=7    unreachable=0    failed=0   
com03.camhres.ca           : ok=41   changed=8    unreachable=0    failed=0   
crick.camhres.ca           : ok=66   changed=15   unreachable=0    failed=0   
darwin.camhres.ca          : ok=0    changed=0    unreachable=1    failed=0   
davinci.camhres.ca         : ok=66   changed=14   unreachable=0    failed=0   
franklin.camhres.ca        : ok=66   changed=15   unreachable=0    failed=0   
golgi.camhres.ca           : ok=66   changed=14   unreachable=0    failed=0   
hebb.camhres.ca            : ok=66   changed=15   unreachable=0    failed=0   
kandel.camhres.ca          : ok=66   changed=15   unreachable=0    failed=0   
laplace.camhres.ca         : ok=66   changed=14   unreachable=0    failed=0   
lovelace.camhres.ca        : ok=66   changed=14   unreachable=0    failed=0   
mansfield.camhres.ca       : ok=66   changed=15   unreachable=0    failed=0   
mendel.camhres.ca          : ok=66   changed=14   unreachable=0    failed=0   
milner.camhres.ca          : ok=20   changed=1    unreachable=0    failed=1   
mrsdti.camhres.ca          : ok=66   changed=14   unreachable=0    failed=0   
nissl.camhres.ca           : ok=66   changed=15   unreachable=0    failed=0   
penfield.camhres.ca        : ok=66   changed=15   unreachable=0    failed=0   
purkinje.camhres.ca        : ok=0    changed=0    unreachable=1    failed=0   
srv-sge.camhres.ca         : ok=35   changed=11   unreachable=0    failed=0   
srv-web.camhres.ca         : ok=16   changed=3    unreachable=0    failed=1   
strangelove.camhres.ca     : ok=66   changed=15   unreachable=0    failed=0   
talairach.camhres.ca       : ok=0    changed=0    unreachable=1    failed=0   
tesla.camhres.ca           : ok=66   changed=14   unreachable=0    failed=0   
tigrsrv.camhres.ca         : ok=45   changed=2    unreachable=0    failed=0

**Comment by djoverton** [comment]
To my knowledge this has been done.
