### ISSUE TITLE
dashboard database

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#712]
we need to:
- build an interface to push and pull from an SQL database
- track down all of the pipelines and their metrics from:
  - fMRI (task + rest)
  - DTI
  - T1
  - phantom fMRI
  - phantom T1
- build a script that will run the pipelines above, store the appropriate QC metrics (along with patient ID and scan date) in the database, and delete any intermediate outputs from the above pipelines.

**Comment by josephdviviano** [comment]
Tom suggests using the following technologies to build the dashboard:

+ [flask](http://flask.pocoo.org/)
+ [SQLAlchemy](http://www.sqlalchemy.org/)
+ [D3](https://d3js.org/)
    + if we give up on this, we can use [shiny](https://rstudio.github.io/shinydashboard/structure.html) instead.

**Comment by tomwright01** [comment]
Creating the database, what should the relationship be between scan types (e.g. DTI, FMRI etc.) and metric types? I assume scan types will have more than one metric (i.e. 1 - many), however will some metrics (e.g. motion measures) will be applicable to multiple scan types (many-many)? 

The later relationship only makes sense if the expected values of the metric are the same across multiple scan types.

**Comment by djoverton** [comment]
Not an expert, but I assume there will be crossover between metrics of similar scan types (e.g., T1 and T2) that would warrant a many-many relationship.

**Comment by josephdviviano** [comment]
Actually there will be very few measures that are similar across
modalities. For this reason I think it will be simpler to just maintain
them independently, even if a few end up getting repeated across tables.

Joseph's Phone

On 2 Sep 2016 10:11 am, "djoverton" <notifications@github.com> wrote:

Not an expert, but I assume there will be crossover between metrics of
similar scan types (e.g., T1 and T2) that would warrant a many-many
relationship.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/TIGRLab/admin/issues/712#issuecomment-244385671>, or mute
the thread

**Comment by tomwright01** [comment]
created a database definition file 
populated it with some sample (random) data

Still needed:
People definitions

I've put a copy of the work so far in /projects/twright/dashboard
Feedback appreciated.

**Comment by josephdviviano** [comment]
list of QC scripts we need to amalgamate
----------------------------------------------------------
**dti-phantoms**

+ Sofia's QC code: `/archive/data/code/phantom-qc/analyze_dti_phantom.m`

**fmri-phantoms**

+

**t1-phantoms**

+

**dti**

+
+
+

**t1**

+
+
+

**fmri**

+ 
+
+

**Comment by josephdviviano** [comment]
As a part of #723 and this issue, I am testing all of my code on the following subject:

SPN01_CMH_0001_01_01

every single QC output will appear in this folder:

`/archive/data-2.0/SPINS/qc/SPN01_CMH_0001_01`

@tomwright01 and @djoverton could take these outputs and build the piece that places them in the database

**Comment by josephdviviano** [comment]
Removing references to QAP -- we're going to roll our own solutions for a few of these metrics.

**Comment by josephdviviano** [comment]
OK -- QCmon v0.1 is done.

I'm moving the outstanding QC pipeline tasks (T1 measures + human fbirn) to the issues tracker for QCmon because they are non urgent.

Next step is to modify `qc-html.py` to call `qcmon` (and generate the report).

**Comment by josephdviviano** [comment]
My bit is done. `dm-qc-report.py` now generates the QC metrics needed for the database, as well as the HTML reports. It runs on the queue and should be able to handle all of our studies going forward.

**Comment by djoverton** [comment]
My code to traverse the filesystem looking for the appropriate .csv files is more or less working; I need to fix a couple of bugs but we should be able to proceed with plotting the data shortly.

A couple of things:

- [ ] .csv files do not exist for a large number of subjects. I'm currently only picking up ~130 that can be added to the database.
- [ ] A few .csv files do not contain data. I'm skipping them currently, but could this indicate that the pipeline failed for this subject?
- [ ] Some of the relationships between studies and scantypes haven't been manually added to the database yet; I can handle this.

**Comment by josephdviviano** [comment]
Hi @djoverton 

+ yes, apparently 'batch mode' for `dm-qc-report.py` still isn't working, I'm fixing it now.
+ I'm sure you're right about that. I'm guessing those processes were killed (either by the queue or by me). I'll clear them out and regenerate them as soon as the above is fixed.

**Comment by josephdviviano** [comment]
Batch mode is working fine, it's the queue that is the issue.

The QC program will generate each main stats file if it does not exist. I'll just add a bit that removes empty files.

**Comment by josephdviviano** [comment]
we need the following metrics:

humans
----------
**dti**

+ tsnr_bx
+ meanRELrms?
+ ndirs
+ spikecount

**fmri**

+ mean_fd
+ mean_sfnr
+ scanlength

phantoms
-------------
**adni T1**

+ the last 4 values (S2/S1, S3/S1. S4/S1. S5/S1)

**FBIRN fmri**

+ sfnr
+ rdc

**FBIRN dti**

+ nyqratio AVE +/- STD
+ rad pixel shift
+ col pixel shift
+ SNR /- STD (for dwi only, ignore b0)

**Comment by josephdviviano** [comment]
Let's close this and open issues about specific things as they arise.
