### ISSUE TITLE
Remove Field Maps from RTMSWMs

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#714]
As far as I can tell, RTMSWM's protocol does not include Field Maps:

> PULSE SEQUENCE:
> i. 3 Plane Localizer
> ii. ASSET Calibration
> iii. Sagittal T1 FSPGR
> iv. Axial EPI DTI 60 + 5
> v. Axial T2 FSE-XL ASSET
> vi. Oblique Axial T2 FLAIR 

However, Field Maps are expected by the QC pages/ project_settings.

Can this be adjusted?

**Comment by DESm1th** [comment]
The expected scans are based on exportinfo.csv and project_settings.yml. If the lines that match the field map patterns are deleted new qc pages will stop looking for them.

**Comment by navonacalarco** [comment]
Done. Thanks @DESm1th :)
