### ISSUE TITLE
STOPPD QC - odd TechNotes, etc

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#715]
There's quite a few 'new' STOPPD scans to be QC'd - I *think* because of recent MRS upload (?). Things look a bit off, but I'm not familiar with any historic factors at play here (e.g., did naming convention change?)

@josephdviviano When you have time, could we look at a couple of things here together?

**Comment by josephdviviano** [comment]
Yes come grab me after 2:30
