### ISSUE TITLE
remote access via VPN + cryptokey

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#716]
working on this now with Ricardo

+ install on linux: http://ask.xmodulo.com/install-shrew-soft-ipsec-vpn-client-linux.html 
+ crypto key in tigrlab email

Needs 'shrew soft ipsec vpn client'.

**Comment by tomwright01** [comment]
CAMH DNS servers *.*.*.69 *.*.*.35 Will not resolve name requests coming over the VPN, ssh connections need to use the IP address. 
This seems to be a configuration problem with the DNS servers, a potential solution could be to distribute a hosts file.

**Comment by josephdviviano** [comment]
I think this is a solved problem. Some bugs to work out with OSX but multiple users are working remotely now.
