### ISSUE TITLE
ASDD - T2 has been added without any notice....

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#717]
- [x] get protocol from Stephanie (Erin)
- [x] update scans.csv and export info csv (Navona) 
- [x] delete and regenated QC pages since May 2016 (Tom)
- [x] review T2 section of new QC 
- [ ] delete backup in 'bak' folder

**Comment by tomwright01** [comment]
QC files to check:

- [ ] qc_ASDD_CMH_EF025_01.html
- [ ] qc_ASDD_CMH_EF027_01.html
- [ ] qc_ASDD_CMH_EF028_02.html
- [ ] qc_ASDD_CMH_EF032_01.html
- [ ] qc_ASDD_CMH_EF034_01.html
- [ ] qc_ASDD_CMH_EF035_02.html
- [ ] qc_ASDD_CMH_EF037_01.html
- [ ] qc_ASDD_CMH_HEF015_01.html
- [ ] qc_ASDD_CMH_EF025_02.html
- [ ] qc_ASDD_CMH_EF027_02.html
- [ ] qc_ASDD_CMH_EF030_02.html
- [ ] qc_ASDD_CMH_EF032_02.html
- [ ] qc_ASDD_CMH_EF035_01.html
- [ ] qc_ASDD_CMH_EF036_01.html
- [ ] qc_ASDD_CMH_HEF014_01.html

**Comment by navonacalarco** [comment]
:)))))))))))

**Comment by navonacalarco** [comment]
@djoverton :((((((((((

**Comment by djoverton** [comment]
Finished checking the outstanding scans.
