### ISSUE TITLE
Set up log of header differences to be sent to Sofia weekly

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#718]
I asked Sofia what header difference warnings between the protocol and an incoming scan we should be tolerant of (related to issue  ##702).

Here is here response:

> In general, once a protocol is fixed on the scanner, the values
> shouldn't be changing from scan to scan so any variation is something to
> look into. In the case below, we had our replacement tech scanning and we have no
> idea why you got those parameters but she must have done something
> differently. Still, this is why we ask the RAs that come with the subjects to the
> scanner to double-check all parameters as it is easy for a tech
> (specially one that it is not always here) to make a mistake. 
> 
> Fortunately, I don't think the varied FOV will matter in the case below but 
> you should still flag any instances of this as it is not the way the scan is supposed 
> to be scanned! and we need to know this so that we can make sure the technologist 
> is aware of this.
> 
> If you see flags of this sort quite often, the best thing to do would be
> to create a weekly list and send it to me and I can check it for you to
> understand the source and importance of the change.

@josephdviviano @edickie  Is there an easy way to pull these flags, across studies, into a csv that we could send every week?

**Comment by josephdviviano** [comment]
Hi Navona:

A simple script that can accomplish this is [here](https://github.com/TIGRLab/datman/blob/master/bin/compile-logs).

A specific script that runs the exact command you need is here `/archive/data/code/bin/generate-reports`.

This is installed in `clevis`'s crontab on `tigrsrv`.

The outputs are placed at `/archive/data-2.0/logs`, timestamped. An example output (with all header differences going back to the beginning of time for all studies) is this one: `2016-09-01-check-headers.log`

**Comment by navonacalarco** [comment]
Figure out where these logs have moved to.

**Comment by josephdviviano** [comment]
I thought you found them

Joseph's Phone

**Comment by navonacalarco** [comment]
Nope. Do you know where it is?

**Comment by josephdviviano** [comment]
/archive/data/logs ...

Joseph's Phone

**Comment by navonacalarco** [comment]
Ok, we have a response from Sofia, based on the first log we sent (/projects/navona/Kimel_lab/2016-09-11-check-headers.csv).

Going to make a new issue to make the changes - posting here just for posterity.
