### ISSUE TITLE
Python module loading outdated libraries

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#720]
At least one library (scikit-learn) is outdated in the Python module. Currently the only versioning we have in this module is the version of Python itself. Am I correct in assuming that for a given version of Python, all of the libraries we choose to load should be the latest versions? If so, I will fix this myself.

**Comment by josephdviviano** [comment]
Hey @djoverton ,

No we want the quarantine to function as 'snapshots' in time. This allows us to reproduce old results even if software changes / improves. 

Therefore if you want a new python environment that is up-to-date, I'd say that calls for a new `python-extras` module.
