### ISSUE TITLE
merge xnat-extract.py, dm-link-sprl.sh, dm-link-vn-sprl.sh into a single script

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#722]
We should have a single script that exports data from XNAT into a datman-usable format.

**Comment by tomwright01** [comment]
dm-link-sprl.sh and dm-link-vn-sprl.sh are effectively the same, only the name of the resultant file is different (according to the tag variable).
dm-link-sprl.sh      is part of the STOPPD project (at least).
dm-link-vn-sprl.sh not found (yet)

**Comment by josephdviviano** [comment]
Hi tom good plan, deleting and renaming files shouldn't be any trouble very
few users are actively interacting with the data.

Joseph's Phone

**Comment by josephdviviano** [comment]
+ `xnat-extract.py` is in good working order. 

We're moving towards using a 'type' field in the exportinfo dict to determine which scans should be linked.

After this is done, it should be easy to wrap the link scripts into this program.
