### ISSUE TITLE
Merge a bunch of scripts into a single QC program

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#723]
The following scripts should be merged for ease-of-use and clarity:

+ dm-build-web.py
+ dm-check-bvecs.py
+ dm-check-headers.py
+ dm-check-protocols.py
+ qc-html.py
+ qc-phantom.py
+ qc-report.py
+ scan-date-report.py
+ web-build.py

This program will implement the following pipeline:

+ Determine what kind of data an incoming file is (using the datman 'tag')
+ Run the appropriate set of pipelines on that data to generate useful metrics (see #712  for a list)
+ Save all appropriate metrics into a QC database.
+ Generate a web-friendly dashboard with QC images (of raw data), and longitudinal graphs (across subjects).

**Comment by josephdviviano** [comment]
@edickie just making you aware of this change.

**Comment by josephdviviano** [comment]
OK new plan -- @edickie and @tomwright01 want more modularity in our how QC system works, so I'm going to do this:

to keep:

+ qc-html.py -- will construct an HTML report out of all available (known) qc metrics in the single-subject qc folder (i.e., all files available in `/archive/data/SPINS/qc/SPN01_CMH_0001_01`)
+ qc-report.py                   <-- can likely merge.
+ scan-date-report.py       <-/


to put in the `qcmon` project:

+ dm-check-bvecs.py 
+ dm-check-headers.py 
+ dm-check-protocols.py
+ qc-phantom.py

to be replaced with the dashboard:

+ web-build.py
+ dm-build-web.py

**Comment by josephdviviano** [comment]
Update:

[qcmon](https://github.com/josephdviviano/qcmon) is done, it contains all of the qc pipelines we run on our data (and some new ones). Going forward, `datman` will only call `qcmon` to generate metrics, it will not calculate any on it's own.

A decent number of qc programs have been removed from `datman`, and the `qc-html` program is now the do-everything `dm-qc-report.py` program.

**Comment by navonacalarco** [comment]
![57020843](https://cloud.githubusercontent.com/assets/13733654/18567711/710e30da-7b67-11e6-98f7-f2904e0f8324.jpg)

**Comment by josephdviviano** [comment]
Plan for `dm-qc-report.py`:

+ usage: `dm-qc-report.py <niftis> <dicoms> <qc>`, where each points to a folder full of subject folders.
    + for most subjects this will look like:
        + `${projectDir}/data/nii`
        + `${projectDir}/data/dcm`
        + `${projectDir}/qc`
+ location of each site's gold standards will be kept in `project_settings.yml`:
        + under `Sites / ${site} / StandardsDir`
        + this solution isn't the best, but this file is already being used to ensure we receive the full protocol from `xnat`, so we might as well use it?
+ location of each scan's expected length will be kept in `project_settings.yml`:
        + under `Sites / ${site} / ExportInfo / Length`
+ QC values, and, if human, HTML reports, will end up in `${projectDir}/qc/${subject}/`

**Comment by tomwright01** [comment]
Since niftis, dicom and QC are all under the same project folder what is
the requirement for separating the arguments?

**Comment by josephdviviano** [comment]
Really just so I don't have to assume we keep the same folder structure going forward... Could just make it one path if we are going to assume the directory structure underneath will never change.

Since we're relying on the yaml file I could just put all of the paths in there. What do you think?

**Comment by tomwright01** [comment]
I think I like that idea, flexibility and simplicity. I assume you're
talking project_settings.yml not tigr_config?

**Comment by josephdviviano** [comment]
Yes that's right, project_settings.yaml

Ok deal, everything goes in the config file!

Joseph's Phone

**Comment by josephdviviano** [comment]
First working version of `dm-qc-report.py` is pushed up to github -- having trouble with phantom data at the moment.

@tomwright01 and @djoverton  have a look here for the full output from one subject:

`/archive/data/SPINS/qc/SPN01_CMH_0001_01`

**Comment by josephdviviano** [comment]
scratch that --- above folder did not regenerate properly. give this one a shot: `/archive/data/SPINS/qc/SPN01_CMH_0062_01`

**Comment by josephdviviano** [comment]
I think the reason these aren't regenerated is that I'm running the pipeline serially for a large number of subjects. It's actually kind of slow, maybe 15-20 mins per subject. However I don't see this as a problem because after we get up to speed, won't be getting very many new subjects per day.

**Comment by josephdviviano** [comment]
OK this works for both humans and phantoms. It needs specific upgrades, but is otherwise done.

See `dm-qc-report.py` and `qcmon` for the final products.
