### ISSUE TITLE
resolve differences between PRELAPSE in XNAT and file system

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#725]
| SITE | nSUBJ | nSUBJ XNAT | nREPEATS | nREPEATS XNAT | nPHA | nPHA XNAT |
| --- | --- | --- | --- | --- | --- | --- |
| BRG | 1 | 1 | 1 | 1 | 15 | 16 |
| CRY | 4 | 5 | 4 | 5 | 13 | 13 |
| CTN | 3 | 3 | 1 | 1 | 10 | 10 |
| GRD | 1 | 1 | 0 | 0 | 22 | 22 |
| IWA | 3 | 5 | 1 | 1 | 15 | 16 |
| MAS | 6 | 4 | 6 | 4 | 13 | 13 |
| MCH | 5 | 6 | 5 | 5 | 29 | 29 |
| NWN | 5 | 5 | 2 | 2 | 12 | 11 |
| PCE | 6 | 6 | 4 | 4 | 67 | 67 |
| SFD | 3 | 3 | 2 | 2 | 5 | 5 |
| TXS | 8 | 8 | 1 | 1 | 16 | 16 |

**Comment by edickie** [comment]
Many of the PRELASPE subjects appear to be misnamed in xnat

> ERROR: Multiple export patterns match for /mnt/xnat/spred/archive/PRE11/arc001/PRE01_TXS_38008_01_01/SCANS/501/DICOM, descr: B0-Map, tags: ['FMAP-8.5', 'FMAP-6.5']
> ERROR: /mnt/xnat/spred/archive/PRE12/arc001/PRE01-MCH-36002-02-01 folder is not named according to the data naming policy. Skipping
> ERROR: /mnt/xnat/spred/archive/PRE12/arc001/PRE01_MCH_36009 folder is not named according to the data naming policy. Skipping
> ERROR: /mnt/xnat/spred/archive/PRE02/arc001/20160803 folder is not named according to the data naming policy. Skipping
> ERROR: /mnt/xnat/spred/archive/PRE02/arc001/PRE01_IWA_04012_01 folder is not named according to the data naming policy. Skipping
> ERROR: /mnt/xnat/spred/archive/PRE02/arc001/PRE01_IWA_04013_01 folder is not named according to the data naming policy. Skipping
> ERROR: /mnt/xnat/spred/archive/PRE04/arc001/COTES__29_JUN_2016 folder is not named according to the data naming policy. Skipping
> ERROR: Multiple export patterns match for /mnt/xnat/spred/archive/PRE04/arc001/PRE01_GRD_15018_01_01/SCANS/15/DICOM, descr: T2_SPACE_FLAIR_p2_ISO, tags: ['T2', 'FLAIR']
> Error 1 while executing: dcm2nii -x n -g y  -o /tmp/tmp6Ev0LJ /mnt/xnat/spred/archive/PRE04/arc001/PRE01_GRD_15018_01_01/SCANS/13/DICOM
> stdout: 
> >	Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
> >	reading preferences file /home/clevis/.dcm2nii/dcm2nii.ini
> >	Data will be exported to /tmp/tmp6Ev0LJ/
> >	Validating 2 potential DICOM images.
> >	Unable to find any DICOM files in the path /mnt/xnat/spred/archive/PRE04/arc001/PRE01_GRD_15018_01_01/SCANS/13/DICOM/PRE01_GRD_15018_01_01.MR.PSYCHIATRY_-_COTES_PRELAPSE_XNAT.0013.0001.2016.08.05.06.42.04.808502.286209429.IMA
> >

**Comment by navonacalarco** [comment]
Reassigning due to new QC assignments. :)

**Comment by josephdviviano** [comment]
Isn't this done? This was opened 2 months ago. Things would have changed dramatically by now.

**Comment by navonacalarco** [comment]
Wasn't done by me. I'd expect there might be new issues, but wouldn't these ones still exist?

**Comment by edickie** [comment]
I (think) I resolved a bunch of these two weeks ago... but I check over
these today

**Comment by josephdviviano** [comment]
@edickie thanks -- if you resolve this can you also close the issue so it does not creep back up on us again.

**Comment by josephdviviano** [comment]
@edickie I'm assuming this is done. Let's try to keep the issues clean...
