### ISSUE TITLE
email MAS & PMC to get gold standards for STOPPD

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#726]

**Comment by josephdviviano** [comment]
Just use an early STOPPD scan

Joseph's Phone

**Comment by navonacalarco** [comment]
Ok, will do.

@josephdviviano Ideally, should we have a protocol pulled from their scanner, or is comparing the headers in all of the relevant files equivalent and/or sufficient?

**Comment by josephdviviano** [comment]
There's no real way to do this, we just trust that early Dicoms are correct
.

Joseph's Phone
