### ISSUE TITLE
Tesla is dead in the water

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#728]
Adrift. Floundering. Capsizing. Not working well, is the general drift I am trying to get across. 

Matlab just took 20 minutes to open. ls takes 40 seconds. Everything is very slow, and htop indicates all CPUs and most RAM is available, no big jobs running.

**Comment by josephdviviano** [comment]
On it.

**Comment by josephdviviano** [comment]
@colinhawco I just loaded matlab in ~60 seconds? Was it just a temporary blip?
