### ISSUE TITLE
Dell warranty extensions

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#729]
We have a line item on our CFI to buy extended warranties for our workstations. Since a number of our workstations are approaching 5 years, we should extend those ones first.

The older workstations are all of model `T7500`. In order to extend their warranties, we need to supply a vendor with the 'service tag' number found on the top of the machines.

Can someone email me the service tags for these machines (please don't post on github as this is a public forum). I'll go through the motions of doing the purchase req.

Thanks!

**Comment by navonacalarco** [comment]
Done.

**Comment by DESm1th** [comment]
Just a note: Dell said this is not possible for any machine over 5 years. These machines did NOT get an extended warranty
