### ISSUE TITLE
PASD not uploading to xnat

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#730]
> [xnat-upload.py] ERROR: PASD_CMH_PASD6_01_01 http client error at folder creation: 422
> [xnat-upload.py] ERROR: PASD_CMH_PASD6_01_01 http client error dicom data upload: 500
> [xnat-upload.py] ERROR: ERROR uploading file 20160824_Ex05914_ASDN1MR_ASPP005/Ex05914Se00012_gradOrs.txt
> [xnat-upload.py] ERROR: Error communicating with XNAT
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 154, in <module>
>     main()
Maybe we can't have project and folder names for match??

>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 138, in main
>     raise e
> HTTPError: 404 Client Error: Not Found for url: https://xnat.imaging-genetics.camh.ca:443/data/archive/projects/PASD01/subjects/PASD_CMH_PASD6_01_01/experiments/PASD_CMH_PASD6_01_01/files/20160824_Ex05914_ASDN1MR_ASPP005/Ex05914Se00012_gradOrs.txt?inbody=true
> [xnat-upload.py] ERROR: PASD_CMH_PASD8_01_01 http client error at folder creation: 422
> [xnat-upload.py] ERROR: PASD_CMH_PASD8_01_01 http client error dicom data upload: 500
> [xnat-upload.py] ERROR: ERROR uploading file 20160824_Ex05915_ASDN1MR_ASGA006/Ex05915_Se00004_MRSPOM-Glu-ACC/Ex05915_Se00004_P25088.7
> [xnat-upload.py] ERROR: Error communicating with XNAT
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 154, in <module>
>     main()
>   File "/archive/data-2.0/code/datman/bin/xnat-upload.py", line 138, in main
>     raise e
> HTTPError: 404 Client Error: Not Found for url: https://xnat.imaging-genetics.camh.ca:443/data/archive/projects/PASD01/subjects/PASD_CMH_PASD8_01_01/experiments/PASD_CMH_PASD8_01_01/files/20160824_Ex05915_ASDN1MR_ASGA006/Ex05915_Se00004_MRSPOM-Glu-ACC/Ex05915_Se00004_P25088.7?inbody=true
> A

**Comment by tomwright01** [comment]
Looks like this was broken by #719
