### ISSUE TITLE
add gold standards to PRELAPSE

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#731]
To add:

- [x] GRD
- [x] CRY
- [x] PCE
- [x] TXS

Remember: DTI gold standards need a .bval and .bvec as well

**Comment by edickie** [comment]
Did as much as I could find
We will continue to have a errors because two different types of FMAP's have the same tag (because they all have the same SeriesDescription in the header) So header comparison' s for this series are not that appropriate..
This is true of sites:
PCE and IWA GRD and CTN

**Comment by josephdviviano** [comment]
@edickie are the series descriptions exactly the same?

**Comment by edickie** [comment]
yup.
PCE - "Field_map-Bold.sw" (AWP45348 SIEMENS Skyra)
IWA  - "PHASE MAP" (MRC35267 SIEMENS TrioTim)
GRD  - "field_map - BOLD" ( MRC35025 SIEMENS Prisma_fit)
CTN - "FIELD_MAP-BOLD" (AWP45841 SIEMENS Skyra)

It's seem like something that SEIMENS scanner like to do..
On the plus side, the two scans are of different length - so there might be some way to script around this..in the long run
