### ISSUE TITLE
List of computer IPs in `lab layout: computers` is off

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#733]
e.g.,

IP for Laplace -> Milner
IP for Franklin -> Tesla
IP for Crick -> Manfield 

Not sure how important this is. Will investigate / update sheet if required.

**Comment by josephdviviano** [comment]
Where is this list? The only list that would be authoritative would be in `/etc/hosts`

**Comment by navonacalarco** [comment]
You and I made this spreadsheet a while back, before new computers arrives - it's a shared google doc. I thought it was the basis of /etc/hosts. (?)

**Comment by josephdviviano** [comment]
Yes things evolved since then, when I was actually getting stuff set up.

You could update that sheet with the contents of `/etc/hosts`, however I'm pretty sure some of the computers have also migrated rooms.

**Comment by navonacalarco** [comment]
As long as /etc/hosts is accurate, I'll just use that - can we delete this shared spreadsheet or is it of use to you?

**Comment by josephdviviano** [comment]
Nope, no need for me. Thanks!
