### ISSUE TITLE
Make XNAT and file system accounts for Dr. Ameis' students/staff

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#734]
Name | Study
------------ | -------------
Rachael.Lyon@camh.ca | DBDC
Avideh.Gharehgazlou@camh.ca | DBDC PASD
Mark.Oreilly@camh.ca  |  ASDD

**Comment by tomwright01** [comment]
Xnat accounts created.
@josephdviviano I need admin access to IPA for the filesystem accounts.

**Comment by josephdviviano** [comment]
Hi @tomwright01 that's Qing's purview. 

I'm adding them now. Their temp passwords are 'passwd-1-2-3-4', you will need to walk them through setting up their real passwords. ( @djoverton  has watched me do this a few times ).

**Comment by josephdviviano** [comment]
I've already made Mark an account.

**Comment by josephdviviano** [comment]
K, done, you can go about setting up their passwords.
