### ISSUE TITLE
build a QAP module

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#735]
It turns out QAP is a real PITA to get installed. I think it conflicts with other modules in our system.

I'm attempting to build a module that will run alone (no anaconda's python or python extras allowed).

However if this continues to be a problem, I'm going to suggest we abandon QAP. We have the most important SNR / Quality measures without it (and with it, we will have far too many).

**Comment by josephdviviano** [comment]
I'm abandoning this -- this software conflicts with all of our other python modules, and even when run totally independently is buggy and fails to run. I think we will survive without their metrics (or can hand roll a few of them as needed).

**Comment by DESm1th** [comment]
Hey Joe,

Right before he left Jon created a qap module for Erin and I (qap/1.0.5/module). Is there a reason why that one isn't being used?

**Comment by josephdviviano** [comment]
I made that on Friday :)

It's very buggy

Joseph's Phone

**Comment by DESm1th** [comment]
Oh oops! What happened to the qap/20160104 module that Jon mentioned in the last comment here? https://github.com/TIGRLab/admin/issues/642

It sounds like he got that one working.

**Comment by josephdviviano** [comment]
Not sure, I haven't seen that module.

Joseph's Phone
