### ISSUE TITLE
2016-09-12 log errrors

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#736]
COGBDO/data/zips/2014_0604_CM015.zip: Cannot find scan id. Skipping

Added scan ID to scans.csv

**Comment by tomwright01** [comment]
Unable to resume download of "COGBDY/data/zips/2014_0314_AM010.zip": local file is larger than remote

Deleted local file

**Comment by tomwright01** [comment]
----------------------------------------------------------------------
 CMH                                            09/15/16 03:11:17
----------------------------------------------------------------------
[dm-check-bvec] ERROR: No gold standard .bvec file for tag RST

Moved DTI_CMH_S148_01//DTI_CMH_S148_01_01_RST_08_Ax-EPI-RestingState.bvec

to /scratch/twright

**Comment by josephdviviano** [comment]
Hey @tomwright01 -- quick note -- resting state (or any fMRI data in general) should not have a `.bvec` or `.bval` file --- those are reserved for DTI scans. So this seems like a bug.

**Comment by tomwright01** [comment]
[xnat-upload.py] ERROR: STOPPD_CMH_410045_01_01 http client error dicom data upload: 400

Manually uploaded from prearchive

**Comment by tomwright01** [comment]
@josephdviviano Talking with @edickie seems it was a known bug, thought to have been fixed in most cases, I'll keep watch to see if it comes back.

**Comment by tomwright01** [comment]
ERROR: Multiple export patterns match for /mnt/xnat/spred/archive/PRE11/arc001/PRE01_TXS_38002_01_01/SCANS/801/DICOM, descr: B0-Map, tags: ['FMAP-8.5', 'FMAP-6.5']

modified exportinfo-BRG-CRY-SFD-TXS-MCH.csv to include this map

**Comment by tomwright01** [comment]
I think the only errors remaining are header checks. I'll check again on Monday and close if all is good.

**Comment by tomwright01** [comment]
Logs seem pretty clean, except dicom-header errors. Closing
