### ISSUE TITLE
Set up dictionaries for MRP and ZHP sitecodes

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#739]

**Comment by navonacalarco** [comment]
It seems that some of the file naming for DTI also changed at MRC.  We're getting DTI-60Dir-5B0 (which is what we want), but also: 

- DTI-60Dir-5B0-**ADC** 
- DTI-60Dir-5B0-**TRACEW**
- DTI-60Dir-5B0-**FA**
- DTI-60Dir-5B0-**ColFA**

I don't think that we need these ^ in the QC pages. 

I'm not sure what should be modified. Is it still project_settings, or export_info?

**Comment by edickie** [comment]
Now project settings..
