### ISSUE TITLE
Talairach not configured

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#741]
Talairach (in room 102) is not connected to the internet or otherwise correctly configured.

**Comment by josephdviviano** [comment]
Hey @DESm1th, want to give this one a go?

**Comment by DESm1th** [comment]
Sure!

**Comment by josephdviviano** [comment]
:D

**Comment by DESm1th** [comment]
Done, but it still has that persistent problem detecting the second monitor. I'll try to fix that on Monday.

**Comment by josephdviviano** [comment]
Thanks @DESm1th  -- might want to chat with @tomwright01 about the monitor issue. He RMA'ed one of the mishbehaving monitors and it seems to have fixed the problem!
