### ISSUE TITLE
SFNR map for SPN01_MRP_P003_03 QC page not rendering

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#742]
I can look into this myself later in the week, but if anyone else has a chance before then, help would be very appreciated - would be nice to distribute the QC page of a human phantom on MRC's PRISMA before the SPINS call at 4pm today.

**Comment by josephdviviano** [comment]
Where's the data?

**Comment by josephdviviano** [comment]
I can't help with this right now. You need to give me error messages.

**Comment by edickie** [comment]
I think we filed an issue about this in th qcmon repo too

**Comment by josephdviviano** [comment]
Link?

Joseph's Phone

**Comment by edickie** [comment]
https://github.com/josephdviviano/qcmon/issues/2

**Comment by josephdviviano** [comment]
Well, i think you meant the corr map, not the sfnr map (and the corr map isn't very important). SFNR generates fine.

Here's the commit that fixes the corr issue:

https://github.com/josephdviviano/qcmon/commit/a42aab357b881eaff7ba1a892a4d0ea88a7100f8
