### ISSUE TITLE
identify source of artifact in SFNR

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#744]
@josephdviviano Do you happen to know what might cause this sort of image in a resting state SFNR map?

![screenshot - 09192016 - 11 20 28 am](https://cloud.githubusercontent.com/assets/13733654/18638253/654214ee-7e5d-11e6-888a-623078faa737.png)

It doesn't appear to be motion related. This particular example is from PRE01_IWA_04014_01_01_RST_04_fMRI-Resting-State.nii.gz

**Comment by josephdviviano** [comment]
The stuff in the brain looks good to me

Joseph's Phone

**Comment by navonacalarco** [comment]
@jdv. I agree that the stuff in the brain looks good. However, I'm wondering what might cause the distortion we see outside of the brain (doesn't seem to be motion). Do you know?

**Comment by josephdviviano** [comment]
no, you could ask Sofia. I don't think it matters.

**Comment by navonacalarco** [comment]
Will do, thank you.
