### ISSUE TITLE
need a way of linking scans across projects

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#745]
We have a subject:

`SPN01_CMH_0096_01_01` whose data is being shared with `PNS_CMH_0017_01_01` . We need a good way of mapping this data between projects (just some sort of dictionary that the scientists can look up should be fine.

**Comment by josephdviviano** [comment]
@edickie what would you suggest?

**Comment by edickie** [comment]
Didn't we already contain an extra metadata file for this situation?

**Comment by josephdviviano** [comment]
Can you elaborate?

Joseph's Phone

**Comment by tomwright01** [comment]
Please tell me you did!
Assuming its only the occasional subject I was going to write a linking script, perhaps with another config file. If its more common perhaps we should consider deeper changes.

**Comment by edickie** [comment]
There was only one case were we I remember doing this. It was between a
VIPR and SPINS subject I believe.

Here's the old discussion about that
https://github.com/TIGRLab/admin/issues/406

**Comment by josephdviviano** [comment]
Thanks Erin.

@tomwright01 have a look at https://github.com/TIGRLab/admin/issues/406, looks like there is an `external-links.csv` file we can use to maintain this mapping, but we also need to create some softlinks on the filesystem?

**Comment by tomwright01** [comment]
@josephdviviano @edickie @djoverton 
Solution in `/archive/data/code/datman/bin/dm-link-project-scans.py`.
If anyone would like to do a code review please feel free, otherwise closing.

**Comment by navonacalarco** [comment]
This is great! Now, I think we can go through the old 'scan completed' emails to pull out the respective study IDs of the shared participants (I believe there's quite a few more than just 2).
