### ISSUE TITLE
Project_settings.yml files aren't formatted correctly

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#746]
I'm not going to fix this immediately because it may break other scripts, but the issue is that we have dictionaries nested within lists, making certain kinds of parsing ugly/difficult. For example, in the SPINS project_settings:

Sites:
  - CMH:
      XNAT_Archive: '${XNAT_ARCHIVEDIR}/SPINS/arc001'
      Phantoms: Y
      ExportInfo:
        - T1:         { Pattern: {'T1','BRAVO'},      Count: 1}
        - FMAP-6.5:   { Pattern: { 'TE6.5' },         Count: 2}
        - FMAP-8.5:   { Pattern: { 'TE8.5' },         Count: 2}
        - RST:        { Pattern: {'Resting', 'Rest'}, Count: 1}
        - OBS:        { Pattern: 'Observ',            Count: 1}
        - IMI:        { Pattern: 'Imitat',            Count: 1}
        - EMP:        { Pattern: 'EA',                Count: 3}
        - DTI60-1000: { Pattern: { 'DTI', '60' },     Count: 1}
        - PDT2:       { Pattern: {'T2.DE', 'T2-DE'},  Count: 1}
        - FLAIR:      { Pattern: FLAIR,               Count: 1}

  - ZHH :
      XNAT_Archive: '${XNAT_ARCHIVEDIR}/SPN02/arc001'
      Phantoms: Y
      ExportInfo:
        - T1:         { Pattern: {'FSPGR'},   Count: 1}
        - RST:        { Pattern: {'Resting'}, Count: 1}
        - OBS:        { Pattern: 'Observ',    Count: 1}
        - IMI:        { Pattern: 'Imitat',    Count: 1}
        - EMP:        { Pattern: 'Emp',       Count: 3}
        - FMAP-6.5:   { Pattern: { 'MAP65' }, Count: 1}
        - FMAP-8.5:   { Pattern: { 'MAP85' }, Count: 1}
        - DTI60-1000: { Pattern: { 'DTI', '60' }, Count: 1}
        - PDT2:       { Pattern: {'FSE.XL'},  Count: 1}
        - FLAIR:      { Pattern: FLAIR,       Count: 1}

data["Sites"][0]["CMH"] instead of data["Sites"]["CMH"] will access the CAMH data, data["Sites"][1]["ZHH"] for the next site, and so on. In the future, only bottom-level data should be preceded with a "-" in config files.

**Comment by josephdviviano** [comment]
Hey @djoverton why don't we just fix this right away and then see how the code breaks, and go straight into fixing that? It might be a little more rough and tumble but it will get us on track the fastest ?

**Comment by edickie** [comment]
The lists were intentional. For both site and scantypes we wanted to
preserve an order.

The reason for having sites as an ordered lists all related to
qc-phantoms.py so we could probably do away with that..

The scantypes order is important though. It relates to the order in which
the scans are collected for each project. The rows of the table at the top
of the qc page are in this order so that it is easy to tell if a scan is
missing from the middle or the end of the session. If you do away with the
list format, you need to code the scan order in the dictionary some other
way...

**Comment by djoverton** [comment]
Hey @edickie, could you elaborate on why sites need to be an ordered list for qc-phantoms.py (or is that just the way the script was written)?

For scantype order, I wasn't aware that the relative time the scan was performed was coded into its position in the list. I could come up with a workaround for the purposes of getting the data in the QC database, but I wonder if it might be better to specify order more explicitly if it's important to know.

**Comment by josephdviviano** [comment]
@djoverton check the latest datman commits by yours truly, `qc-phantoms.py` does not exist any longer. So we don't need to order sites.

**Comment by djoverton** [comment]
@edickie I noticed that the items under PipelineSettings were also written the same way (dictionaries within lists); is this how datman knows in which order to run the pipelines? And is the order important?

**Comment by tomwright01** [comment]
Not sure where to stick this but here's a way of concatenating strings in yaml
http://stackoverflow.com/questions/5484016/how-can-i-do-string-concatenation-or-string-replacement-in-yaml

**Comment by edickie** [comment]
Yes, the list order in PipelineSettings is the order in which the Pipeline
Steps are run. This is important because many steps do need to happen
before other one's (i.e. data download and goes before qc page
generation...and so on)

**Comment by edickie** [comment]
@djoverton Knowing the order is pretty useful for the QC for a couple of
reasons.
1.Missing scans in the middle of the expected sequence are a sign of  a
data transfer problem...while a missing scan at the end is usually just
because the scan was never collected.
2. it's good to look at the amount the amount of motion across time in one
subject.
3. It makes the order in which QC information is presented consistent
across all subjects in one project.

However, I'm completly in favour of coding the order in another way (i.e.
an extra subfield in the dictionary?) The current way it is set up does not
accomadate when one scantype appears in two different places in the order.
(Like the case of VIPR, where the order is DTI, SPRL-VR, SPRL-VR, SPRL-VR,
T1, SPRL-VR, SPRL-VR, SPRL-VR)

**Comment by djoverton** [comment]
Yes, in general it's much better to make this sort of thing explicit rather than implicit, especially since it'll make parsing easier anyway.

I've removed the order from sites, since I don't think that's meaningful and it isn't being relied on. I'll keep the order for the PipelineSettings for now, although this might not be necessary in the future (there is a push to use datman only to run independent pipelines and not download/generate QC). For scans, I suggest replacing "Count" with a list of "Indices", which would tell you both how many of each scan and the order they happen. Let me know what you think.

**Comment by edickie** [comment]
@djoverton sounds good to me

**Comment by djoverton** [comment]
Alright, all the project_settings.yml files have been changed according to my previous post. I also noticed a few errors in some of the files (patterns not in quotes, for example), which may have been causing some incidental errors.

For tags that had a count >1, I just assumed they happened sequentially, which I realize might not be correct, but this is no less precise than what we had before and can be fixed later. @edickie I also noticed the "Pattern" attribute was called "Resource" in some cases... I renamed them all to Pattern, will that cause a problem?

**Comment by josephdviviano** [comment]
I've moved us back to the 'count' system because it much easier to work with, and harder to make a typo.

In the QC pages, scans are printed in order of their series number, followed by the missing scans.

@djoverton : any outstanding reformatting needed?

**Comment by josephdviviano** [comment]
Ah one thing: we can remove the 'phantoms' argument. That's in the upload file names, so the phantoms option does not do anything.

**Comment by josephdviviano** [comment]
I'm closing this -- I'm assuming we've rectified the major formatting issues given the number of changes that has happened to the `.yml` files.
