### ISSUE TITLE
Task data not processed for SPINS

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#748]
The script dm-proc-ea.py should be run on spins data, currently not happening.

**Comment by josephdviviano** [comment]
Yes, you will need to look at 'stage-epitome', I believe. When I wrote dm-proc-ea it was a self-contained script, but it's been broken into pieces since then (likely for the best, but I haven't familiarized myself with how they work).

**Comment by edickie** [comment]
Tom got the old dm-proc-ea.py working so that Colin could get the outputs.

Moving forward. This is gettting delt with as part of issue #765
