### ISSUE TITLE
Naming scheme for internal study data

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#75]
As part of #56 we need a naming system for our imaging (and other?) data. I'm opening this issue to hold our discussion. I'm assigning myself to make the initial proposal. 

Proposal here: https://github.com/TIGRLab/data-internal/wiki/Imaging-Data-Naming

**Comment by pipitone** [comment]
K, I've moved things around a bit and updated the documentation to reflect recent discussions. Please have a quick read and let me know if this is clear. 

I've put the protocol for generally naming study data here: 
https://github.com/TIGRLab/admin/wiki/Data-Naming-Protocol

I've put notes on how the DTI study identifiers are handled here: 
https://github.com/TIGRLab/admin/wiki/Study-Data-Identification

That last document is just a stub, and we should continue to flesh it out for SPINS and the other studies, I just wanted to capture our decisions for the DTI study from our recent discussion to start.

**Comment by AristotleVoineskos** [comment]
Hi Jon,

This is excellent. Thank you.

One edit is that the SPINS study cutoff is at 50 years of age (i.e. DTI is 51 and above).

One question: is Dielle on the admin list ? If not could you include her (if you reply)...I wonder what she thinks (and if OK with you) about the value (or not) about a 30 min orientation session led by you with any RA working on these studies to familiarize themselves with this approach...Mikko, Judy, and Laura are the key RAs, but there are times when other RAs cover who might benefit from knowing this...

AV
________________________________

**Comment by pipitone** [comment]
Okay I'll patch up the age range. 

Yes I do think an orientation makes really good sense. Especially because after talking with David and Joe, we'd like the RAs to use this naming scheme as the PatientName at the scanner (eg they'd use the patient name DTI_CMH_H157_01_01 rather than just H157 or initials+birth year). 

Happy to do this orientation.

Jon.

**Comment by pipitone** [comment]
Ran the orientation yesterday. All went well. Closing this issue.
