### ISSUE TITLE
add framewise displacement plots using D3 to HTML reports

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#752]
I have a working solution in my inbox.

links for myself:
- https://github.com/d3/d3/blob/master/API.md
- https://leanpub.com/D3-Tips-and-Tricks
- https://gist.github.com/d3noob/4414436#file-data-csv

**Comment by djoverton** [comment]
Just checking in; this is not relevant anymore, correct? Or do you still want these plots on individual pages?

**Comment by josephdviviano** [comment]
Hey Dawson, I think this is still relevant -- @edickie finds them useful when trying to blacklist participants. Would you like to take this on?

**Comment by djoverton** [comment]
Sure.

**Comment by djoverton** [comment]
After speaking with @edickie about this, she felt that simply displaying Scanlength on the QC pages would allow easy spotting of truncated scans and would be about as useful as an FD plot. I added this to the individual QC pages and am closing this issue for now.

**Comment by josephdviviano** [comment]
Nice, I agree that this is the better solution. I think looking at the FD plots on a single-subject basis can be misleading, and has led to problems in the past.
