### ISSUE TITLE
move as many functions in datman to the modules

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#755]
Testing datman is tricky because a majority of the code in it resides in `bin/`.

@tomwright01 @DESm1th and I think we could come up with a two-pronged approach to writing tests:

1) `nosetests` for everything in the datman module.
2) output checking of test data for everything in `bin/`.

To do this, we should move as many functions as possible from inside the `bin/` command line tools and into an appropriate module.

**Comment by tomwright01** [comment]
Its worth documenting the datman modules, `checklist.py` is a set of functions for managing a yaml blacklist.

**Comment by josephdviviano** [comment]
OK to make this concrete, I'm going to go through all of the modules and add a docstring if they don't exist, and then group similar functions within each module (I doubt we will have similar functions across modules since they are all logically separated). This will give me a hit list of all the modules that have likely duplicates.

**Comment by josephdviviano** [comment]
This seems to be happening naturally, so I'm going to close the 'issue'.
