### ISSUE TITLE
add content to https://github.com/TIGRLab/documentation/wiki/QC

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#760]

**Comment by navonacalarco** [comment]
@DESm1th @josephdviviano @tomwright01 @edickie @djovertoncmh 

OK! We have a draft. Still a bit to be added, but can you please look over [https://github.com/TIGRLab/documentation/wiki/QC](https://github.com/TIGRLab/documentation/wiki/QC) and let me know if anything needs to be added/removed/changed.

Feel free to edit any small issues yourself.

Thanks!

**Comment by navonacalarco** [comment]
Hey guys, I know everyone is very busy, but I was hoping to send around the link to the QC documentation to Dr. Ameis' RAs on Monday. If you have a moment before then, could you look it over and see if anything should be changed?

**Comment by DESm1th** [comment]
Ah sorry! I forgot. I'll look at it now.

**Comment by josephdviviano** [comment]
Looks good to me. Likely too much detail but maybe some people prefer that.
