### ISSUE TITLE
Make EA file parsing a step of the data transfer and QC pipeline

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#765]
There are two main motivations for setting this up:

1) To separate the EA log file parsing from the preprocessing pipeline so that the parsed onsets can be retained when we decided to rerun the preprocessing pipeline with new options.

2) To treat EA behavioural file checking as a QA step. (i.e. to build in flags for behavioural files that are missing or not of the expected length)

4) To outputs some of the other information that Colin was asking for.
(i.e. onset of all button presses).

3) To store the parsed information in a place where Colin can easily find it.

**Comment by tomwright01** [comment]
I'll take on splitting the dm-proc-ea.py (I already started).

**Comment by edickie** [comment]
Following up from another discussion. It might be cool to store some of this information in .json following the BIDS specification.
http://bids.neuroimaging.io/bids_spec1.0.0.pdf

Disclaimer: I'm NOT suggesting that we rearrange the whole filesystem to follow BIDS. but adding a .json file might be a useful baby step.

**Comment by josephdviviano** [comment]
@edickie are you suggesting storing all of the onsets etc as .json file? Why not a .csv?

**Comment by edickie** [comment]
yup, it appears that this .json thing (for the onsets, but also for the stuff in the dicom header that doesn't translate to the nifti header) is becoming part of the kewl new international standards for neuroimaging data management. Writing the onsets in this way could be a good exersize for learning more about BIDS.

**Comment by josephdviviano** [comment]
@edickie we should have a longer discussion about whether we want to buy into BIDS. A JSON file is substantially harder for people to work with than a csv, colin wouldn't know how to parse a JSON file on his own, and I think we are better off keeping things simple so we can get our work done instead of future proofing something as specific as the EA task timing files.

**Comment by josephdviviano** [comment]
I was made aware of `BIDS` at HBM 2015, and while they do a nice sales pitch I'm not sure that it's going to be an international standard so much as **wants** to be one.

**Comment by tomwright01** [comment]
My reading of the standard indicates the actual data should be stored in .tsv files. The .json files are optional for storing data dictionaries and key:value pairs

**Comment by josephdviviano** [comment]
yeah we really don't need `.json`.

Also, Tom, can you please not change how this program spits out the data. I built it to perfectly replicate the original paper and we need to retain that functionality. We can chat about this at the systems meeting tomorrow in detail.

I'm all in favor of breaking out the behavioural parser, however.

**Comment by tomwright01** [comment]
Talk about it tomorrow, but should be easy to build two outputs, original and extended.

**Comment by josephdviviano** [comment]
Yeah that would be great. I can add in FSL-style outputs as well, so you get AFNI timing files, full .csv (or .ssv or .tsv or whatever) and a FSL timing file.

**Comment by josephdviviano** [comment]
This is essentially done.
