### ISSUE TITLE
followup with pre-post PRISMA MRP and ZHP comparisons

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#767]
Just filing an issue here so that we remember. Before the SPINS call, AV asked we run select scans through any pipelines that would be informative.

There are two scans to review on their own and two comparisons:

- [x] SPN01_MRP_0071_01_01 
- [ ] SPN01_MRP_0073_01_01 
- [x] SPN01_ZHH/MRC/CMH_P003_02  vs SPN01_MRP_P003_03 (Dr. Buchanan human phantom)
- [x] SPN01_ZHH_00??_01_01 vs SPN01_ZHH_00??_01_01 (control scanned on old and new, **coming this Thursday** --- should be named 0060?)

Will fill in the info as we get it.

**Comment by navonacalarco** [comment]
UPDATE: AV just dropped by and wants some kind of comparison of the Buchanan PRISMA scan (SPN01_MRP_P003_03) to the most recent phantom from *all* sites  (SPN01_ZHH_P003_02, SPN01_CMH_P003_02, SPN01_MRC_P003_02) by Thursday. 

![cat-halp-1-1](https://cloud.githubusercontent.com/assets/13733654/18891338/c8238950-84d2-11e6-948e-b531738b19b2.jpg)

**Comment by josephdviviano** [comment]
@navonacalarco can either you remind me to do this, or get erin to do this, tomorrow? She doesn't have much on her plate at the moment.

**Comment by navonacalarco** [comment]
OK! Thanks. 

@edickie Can we talk about this when you have a sec tomorrow? I can work through it if you help me understand what sort of thing should be done here. :)

**Comment by navonacalarco** [comment]
Update: finished Buchanan comparisons; still waiting for other scans to come in from both MRC and ZHH.

**Comment by navonacalarco** [comment]
Closing - we have these scans in XNAT now.
