### ISSUE TITLE
Remove 'DATMAN_ASSETS' environment variable and replace it with an internal reference in the code

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#773]
A few scripts we have in `datman` require access to the `assets/` folder. This is because, in some cases, our command-line tools are simple wrappers for already-built pipelines.

However, there's no reason for us to ever move the `assets/` folder. We currently let our scripts know about the location of these assets via a manually-set `DATMAN_ASSETS` environment variable. A more elegant solution would be something like this directly in our python scripts (example taken from https://github.com/josephdviviano/qcmon/blob/master/bin/qc-fmri):

```
assets_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir, 'assets/')
os.environ['PATH'] += os.pathsep + assets_path
```

This would work for any script `bin/script.py` that relies on any asset `assets/file.sh` being on the path, or whatever.

We could also access assets directly:

```
atlas = os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir, 'assets/shen_2mm_268_parcellation.nii.gz')
```

@tomwright01 @DESm1th @djoverton @edickie thoughts? If no objections I think we should go ahead and swap this out.

**Comment by edickie** [comment]
This works when using a clone of the repository, but the scc install of
datman actually uses the setup.py script...which doesn't put the assets in
the same place.  This is why Jon introduced the DATMAN_ASSETS environment
variable.

**Comment by josephdviviano** [comment]
Where does assets end up when you use setup.py?

**Comment by josephdviviano** [comment]
OK! We'll stick with this. It will be useful to use it for the global configuration file, anyhow.
