### ISSUE TITLE
SPINS data uploaded to ASDD

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#779]
Due to an incorrect MRUser setting in `projects_settings.yaml` SPINS data has been uploaded into the ASDD project on XNAT.

Solution:

- [x] Fix project_settings.yaml
- [x] Fix run_data_kimel.sh
- [x] Delete incorrect files from data/zips
- [x] Delete incorrect records from XNAT

**Comment by josephdviviano** [comment]
@tomwright01 I know a few XNAT tricks I can show you, when you get to that part.
