### ISSUE TITLE
QC list not generating

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#780]
I'm filing this as an issue so we can track progress, though I think everyone already knows about the difficulty. In short, the list generated by dm-qc-todo.py list is not accurate. 

Currently, we see dozens of "No QC doc generated for..." ASDD, DTI3T, SPINS, and STOPPD. But there are no "QC doc not signed off on" entries.

This has been the case for the past week (since last Monday). I'll try to do the QC for the scans for which we've received 'scan completed' emails, but this is not comprehensive - I think perhaps some staff email @josephdviviano instead of tigrlab@camh.ca (?). 

Is there an ETA on when this will be fixed? Dr. Ameis' students/staff are now helping with the QC for her studies, and I'd like to give them a concrete timeline, if possible.

**Comment by josephdviviano** [comment]
Adding @edickie and @tomwright01 because they're working on it as well.

**Comment by navonacalarco** [comment]
Thanks so much everyone. Sorry I'm not as helpful as others with this - let me know if there's something I can/ should do.

**Comment by josephdviviano** [comment]
@edickie : qc-report.py might need to be added to the run scripts after we get everything up to speed. I'm guessing that is what generates the qc todo files?

**Comment by tomwright01** [comment]
All the html files (well all the ones I checked) seem to have been created. For a while there was no method to add them to `checklist.csv`, this is why we are seeing the *No qc doc generated*.
Moving forward new entries should be made by a line in `dm-qc-report.py`. `dm-qc-checklist.py` should backfill the missing entries, for some reason it's not working. Looking into that now.

**Comment by navonacalarco** [comment]
Thanks @tomwright01!

**Comment by josephdviviano** [comment]
Hey @tomwright01  -- does that mean that dm-qc-checklist is going to be run as a separate process, or are you building it into dm-qc-report?

**Comment by tomwright01** [comment]
It should just be a one-off to fix the missing entries in `checklist.csv`.

**Comment by josephdviviano** [comment]
Got it -- but are you going to add a feature to dm-qc-report to add entries to the checklist as well?

**Comment by navonacalarco** [comment]
Looks like everything is working today! I'll update the other RAs doing QC about the updated commands.

There's a couple of cases of "No checklist entry for...." that Tom is taking care of.

@JDV I noticed there's a new metric for DTI. At some point, can you please teach me how to interpret this, and I'll update our documentation. Thanks!

**Comment by navonacalarco** [comment]
Closing as this is done. Thanks again.
