### ISSUE TITLE
Some behavioural data missing

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#788]
SPN01_CMH_0040_01
SPN01_CMH_0063_01
SPN01_ZHH_0057_01

**Comment by tomwright01** [comment]
Data found for CMH recordings, still missing ZHH

**Comment by josephdviviano** [comment]
Email sent to John Chowlea

**Comment by josephdviviano** [comment]
We have the ZHH data, see `SPN01_ZHH_0057_01_02` in XNAT.
