### ISSUE TITLE
MRtrix3

### ISSUE THREAD

**Issue by tina-roostaei** [TIGRLab/admin#791]
Hi, 

I was wondering whether we can have the latest version of MRtrix3 (http://mrtrix.readthedocs.io/en/latest/installation/linux_install.html) installed. As I have checked we now have MRtrix3/0.3.12.

Thanks :)
-Tina

**Comment by josephdviviano** [comment]
On it!

**Comment by josephdviviano** [comment]
Installed --- not functional on all machines, but should be functional on most.?
