### ISSUE TITLE
Figure out why PRELAPSE IWA not being pulled from XNAT

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#794]
subjects: 
PRE01_IWA_04013_01
PRE01_IWA_04014_01

**Comment by edickie** [comment]
The newer phantoms from IWA are not being pulled either

**Comment by edickie** [comment]
And PHA_ADN0014 is missing from XNAT

**Comment by josephdviviano** [comment]
@edickie are you looking into this?

**Comment by edickie** [comment]
Still doing the easy clean-up first..
We also have a similar issue for TXS, but I think the TXS problem is in the
export-info

**Comment by edickie** [comment]
It was an export-info issue
