### ISSUE TITLE
new account: Avi Gharehgazlou (Dr. Ameis RA)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#796]
Whenever you have time, could you please make Avi Gharehgazlou a computer account. She will need read permissions to PASD01, and write permissions to the metadata folder.

She does not need an XNAT account.

Thanks!
N.

**Comment by josephdviviano** [comment]
She apparently already has an account. I've added her to the `kimel_data` group.

If she needs help with her password I can reset it, otherwise, done.

**Comment by navonacalarco** [comment]
Thanks. 

Is her username 'agharehgazlou'? What is the temporary password? Should she reset her password herself at https://rprshipav01.camhres.ca/ipa/ui/?

**Comment by josephdviviano** [comment]
I don't know, I didn't just set this up (must have before?)

Im not aware of a way she can reset the password by herself, do you know of
one? I can reset it for her assuming she does not remember her password

JDV

**Comment by navonacalarco** [comment]
Ok. Confirmed her name is 'agharehgazlou' and she's a member of kimel, kimel_data, and tigrlab. The IPA link seems she has a 6 digit password - but she didn't not set one up - she's never logged in. I'll send her to you to reset. 

I am not aware of how one can reset a password themselves - I believe someone with sufficient privileges needs to do so from  https://rprshipav01.camhres.ca/ipa/ui/.
