### ISSUE TITLE
Relax header difference criteria for (unexpectedly) repeated acquistions (?)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#801]
Hi guys,

I'm still keeping in touch with Sophia about the header differences we see pop up during the QC of CAMH scans. Gradually, we're putting together a list of differences that aren't important and that we can ignore.

One case I'm not sure how to deal with is (unexpectedly) repeated scans that might need to be sped up for lack of time. For example, a T1 in PACTMD originally has a `NumberOfAverages` of 1 and `PercentSampling` of 100, but these parameters changed in a recent repeat to .75 and 75, respectively, and thus threw an error.

Is there a way that we can write things so that if the acquisition isn't at the expected point in the series the header differences are flagged differently? Or is that a ton of work for what is a relatively uncommon occurrence?

**Comment by josephdviviano** [comment]
Are those important parameters? We can just ignore them entirely.

Joseph's Phone

**Comment by navonacalarco** [comment]
I *think* these are important. Both are related to number of excitations (NEX).

**Comment by edickie** [comment]
I feel like it might be better to keep these flags, but to teach people to
ignore them in certain cases... (i.e. if it is a repeated image, because
somebody got out and went to the bathroom).

I think the person doing the QC needs to make the judgement call because
sometimes scans are repeated with the expectation that the original version
will be blacklisted (in which case - different paramenters are a no-no) and
some are repeated with the understanding that the first scan can be kept...

**Comment by josephdviviano** [comment]
I agree with @edickie , the header checking was meant to be more for humans to interpret .. it's too blunt of an instrument to be made fully automatic.

**Comment by navonacalarco** [comment]
Ok, great. I agree keeping these flags, and teaching people how to interpret. 

I'm having a bit of a hard time gaining much insight from the correspondence with Sophia about the importance of certain differences only because we aren't seeing very many header differences in CAMH scans - the issues are always with other sites. 

Can we  create a shared spot (QC documentation page, or google doc, or perhaps a github issue tag) where we share flags and our decisions? That way, we can learn from others and be consistent. Where do you think is the best place to do this?

**Comment by josephdviviano** [comment]
@navonacalarco that's a good idea.

I'd put that stuff on github issues and or wiki because google docs is a very messy interface (my preference).

**Comment by navonacalarco** [comment]
Thanks!

@josephdviviano @edickie @DESm1th @djoverton @DESm1th I've added a `header differences` label to our issues page. Let's use this label to tag any discussion of header differences from this point forward. And, as Joseph suggested last week, let's open (and close) any header differences here for posterity. 

I'll review issues under the label and update [https://github.com/TIGRLab/documentation/wiki/QC](https://github.com/TIGRLab/documentation/wiki/QC) as required.

Thanks,
N.
