### ISSUE TITLE
STOPPD (MAS): Update project_settings.yml regex for T1 and DTI

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#802]
Essentially, don't bring in anything with 'SENSE'.

See STOPPD_MAS_210012_01_01 as example.

**Comment by DESm1th** [comment]
Hey Navona, I updated the project_settings for the T1s to filter out those SENSE files but it looks like the DTIs should already not be matching the pattern. I'm not sure why some of them have gotten through...

**Comment by navonacalarco** [comment]
Thanks Dawn! Strange. Let's keep on eye on the DTIs. Close for now and reopen if we see them again?
