### ISSUE TITLE
Compare ZHH repeat control on old and new scanner

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#804]
SPN01_ZHH_0060_01_01  from March 15, 2016 (old)

SPN01_ZHH_0060_01_02 from October 11, 2016 (new)

**Comment by edickie** [comment]
Should the site code here be ZHP??

**Comment by navonacalarco** [comment]
Yes, which is why I didn't see it. I emailed them.

**Comment by navonacalarco** [comment]
Added to report with Dr. Buchanan and Miklos, to be sent out this week.
