### ISSUE TITLE
Install Microsoft office suite

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#807]
Please install the Microsoft office suite on the Windows computers, thanks!

**Comment by navonacalarco** [comment]
Not sure if this is on the table - but if it is - could we get PowerPoint 2016 on one of those machines? 

It would make the favourite part of my job a bit easier. :roll_eyes:

**Comment by josephdviviano** [comment]
@djoverton can you please figure out how to buy this software, and buy it.

**Comment by djoverton** [comment]
Hey Saba, any particular reason you need to use Office 2016, or will the older versions of Office on the CAMH machines suffice?

**Comment by navonacalarco** [comment]
I think I was the one that requested Powerpoint 2016 because it can do cool things more easily - but if it's not possible, that's ok.

**Comment by sabashahab** [comment]
I'm fine with older versions. I just need MS Word for writing papers.
