### ISSUE TITLE
SPN01_ZHH_0032 QC missing fMRI images

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#809]
But it's been signed off on. 

Find images.

**Comment by josephdviviano** [comment]
The images most likely don't exist. FSL slicer randomly fails on some subjects (rarely).

Easiest solution is just to visually inspect these data using fslview.

Harder solution is moving back to a custom-build plotting tool instead of fsl slicer.

**Comment by navonacalarco** [comment]
Ah. I see. Thanks!
