### ISSUE TITLE
Correct expected scans for DTI3T

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#813]
Looks like the expected scans for DTI are off. 

See DTI_CMH_H122_02 as an example:

1. Add second FMAP-6.5 as expected
2. Add second FMAP-8.5 as expected
3. Remove DTI33-4500 as expected
4. Remove DTI33-3000 as expected
5. Remove DTI33-1000 as expected
6. Remove SPRL as expected

**Comment by josephdviviano** [comment]
Wait a second:

+ doesn't DTI have SPRL scans?
+ are we noit collecting multi shell data any more?

**Comment by navonacalarco** [comment]
That's right,  DTI no longer has SPRL or multishell data. It did at one point, but Erin advises that there's been an effort to make it  identical (or nearly identical) to the SPINS protocol.

I am not sure the exact date when this decision was made - but the DTI_CMH_H122_02 participant I was looking at is from ~8 mths ago. Would it be helpful to identify the exact date?

**Comment by josephdviviano** [comment]
Got it, nevermind!

**Comment by navonacalarco** [comment]
Done.
