### ISSUE TITLE
QC report for DTI_CMH_H127_02  in dm-qc, despite signed off on.

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#814]
:frowning_woman:

**Comment by josephdviviano** [comment]
What does this mean?

**Comment by DESm1th** [comment]
dm-qc-report is writing duplicate checklist entries, so it was still being flagged as 'not signed off on' despite being signed off on. I'm working on fixing the code now.

**Comment by navonacalarco** [comment]
Tom deleted all lines of checklist.csv that were not signed off on. Will see what that does.

**Comment by DESm1th** [comment]
I've fixed the code responsible for this, so this shouldn't happen again.
