### ISSUE TITLE
SPINS phantoms exist in ASDD folder

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#815]
These should be deleted (and we should figure out how it happened).

**Comment by djoverton** [comment]
Looks like it's not limited to ASDD actually; one in PNSC, possibly others as well.

**Comment by navonacalarco** [comment]
I think JDV may have (had?) a practice of adding scans - including phantoms - in XNAT as a sort of initialization / test.

**Comment by josephdviviano** [comment]
Thanks @navonacalarco but I think this one is a goof.

**Comment by josephdviviano** [comment]
OK I deleted those mentioned.
