### ISSUE TITLE
xnat-extract may not be parsing complex regex expressions correctly

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#816]
Navona and I have been noticing that the more files are being downloaded than what we would expect from the regex expressions we have programmed into the export settings in *_settings.yml.

This is especially a case when a "^" or "$" character is being used in the regex expressions to exclude unwanted scans.

An example is SPINS (MRP) site, where a "$" is being used to exclude processed DTI images, another example is PRELAPSE IWA where a '^' is needed to resolve a conflict.

**Comment by DESm1th** [comment]
For both projects it looks like the current regexs were added after the issue popped up, but the wrongly extracted data just wasn't deleted. I've deleted those outputs, and corrected a small (different) bug with the SPINS MRP regexs.

**Comment by DESm1th** [comment]
xnat-extract is still exporting the wrong SPINS dti scans for MRP. I _think_ it's because it's not checking sites correctly. Investigating it now.

**Comment by DESm1th** [comment]
xnat-extract was using both the MRP and MRC site dicts to extract everything in that archive folder. The export info for MRC has been updated with the same regular expressions as MRP to fix this.

**Comment by edickie** [comment]
check PRE01_IWA_04013_01 (pulled in extra resting state and no DTI)
PRE01_IWA_04014_01 (did not pull DTI)

**Comment by josephdviviano** [comment]
@edickie to be clear, I believe the code itself is parsing the regex expressions properly, they just might not be properly configured in the `settings.yml` file

**Comment by DESm1th** [comment]
@edickie, your changes to the project_settings should have done the trick. Joe is right, the regex parsing itself is fine so these errors have all just been the result of weird series descriptions not matching (or unexpectedly matching) our settings.

**Comment by DESm1th** [comment]
I just checked and the problem for PRELAPSE IWA scans has gone away, so the project_settings appear to be correct now.
