### ISSUE TITLE
Nyquist artifact noted by Tech not visible in QC

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#818]
The Tech Notes for COGBDY_CMH_27B009_02  note the Nyquist artifact is visible in DTI33-1000 (series 10), but this isn't evident to me in the QC pages. 

I'm not sure if this is a result of new QC plots (smaller size), or if this is just chance. However, this is the first time in my memory that the Tech Notes have noted an artifact that is not visible on QC pages.

I'm filing an issue so (i) we can discuss if QC pages should have caught this, and independent of that (ii) so everyone knows of this possibility.

File is COGBDY_CMH_27B009_02_01_DTI33-3000_10_Ax-DTI-33plus2-b3000.nii.gz

**Comment by navonacalarco** [comment]
@josephdviviano @edickie @djoverton @tomwright01 @DESm1th 

Just wanted to follow up with this - does this matter to us, or is this something we're ok with?

**Comment by josephdviviano** [comment]
I'm looking at the raw data now and I don't see much to worry about.

I think our quantitative measures on the dashboard will pick up stuff like this better than the visual QC.
