### ISSUE TITLE
Some projects missing QC output files

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#820]
- ANDT: 63 subjects in total, presumably all should have 3 output files, but only one has 3 files and 14 have one file (below are the files that exist)

./qc/ANDT_CMH_116_01/ANDT_CMH_116_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_stats.csv
./qc/ANDT_CMH_116_01/ANDT_CMH_116_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_spikecount.csv
./qc/ANDT_CMH_116_01/ANDT_CMH_116_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascripts_dti.csv
./qc/ANDT_CMH_406_01/ANDT_CMH_406_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_221_01/ANDT_CMH_221_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_121_01/ANDT_CMH_121_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_120_01/ANDT_CMH_120_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_223_01/ANDT_CMH_223_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_408_01/ANDT_CMH_408_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_311_01/ANDT_CMH_311_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_310_01/ANDT_CMH_310_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_222_01/ANDT_CMH_222_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_119_01/ANDT_CMH_119_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_407_01/ANDT_CMH_407_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
./qc/ANDT_CMH_224_01/ANDT_CMH_224_01_01_DTI60-1000_04_Ax-DTI60plus5-20iso_qascript_dti.csv
- COGBDO: Only 2 subjects have output files
- COGBDY: Only 13 subjects have output files
- RTMSWM: Only 12 subjects have output files
- VRMD: None of the subjects have output files

The larger studies may be missing some data too, but I am listing the above because a large number of subjects (the majority) have no data.

**Comment by DESm1th** [comment]
This is because ASDD  uses the older style QC pages, which don't have those files. The people in those studies who do have them are pages that I regenerated due to broken images, or data that was added after the original pages were made.

**Comment by djoverton** [comment]
I didn't actually notice a problem with ASDD; just the ones listed above (ANDT, COGBDO, COGBDY, RTMSWM, VRMD). It's possible ASDD is missing some, but I only listed the ones that looked like "most" of the data was missing.

**Comment by DESm1th** [comment]
Oh whoops. I meant ANDT. Those studies that are missing those files all use (mostly or entirely) the original style QC pages. The missing files that you're seeing are all outputs from dm-qc-report.py so any qc pages generated before that won't have them.

**Comment by djoverton** [comment]
We learned last week that re-running the dm-qc-report with the "rewrite" argument created the .csv files for sessions that already had an HTML file generated (previously, they were only getting created for sessions that didn't, since the script interpreted them as "new" scans). The missing files have already been created for ANDT, and I am now doing the same for other affected studies.
