### ISSUE TITLE
blacklist all DTI collected on CMH scanner 2016-10-26 or 2016-10-27

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#821]
There is an issue with the scanner effecting the quality of DTI sequences.  All DTI will probably be flagged as unusable in the technotes, but just in case, I am adding this note.

**Comment by navonacalarco** [comment]
Based on Scan Completed emails, this will include:

- [ ] PACTMD_CMH_0110044_01_01
- [ ] ASDD_CMH_EF043_01_01
- [ ] PACTMD_CMH_0110043_01_01

Of course, could be others for which survey not completed.

**Comment by DESm1th** [comment]
Hey Navona,

I can't find that ASDD participant's data anywhere. I manually ran the script to grab new data and add it to xnat etc. but it's still not there or in our archive.

**Comment by navonacalarco** [comment]
Ah! Ok, maybe it will show up tomorrow. Let's check then.

**Comment by navonacalarco** [comment]
@DESm1th  Based on Tom's work on #824, the ASDD scans are now in dm-qc-todo.py! If unusable, we should notify PI and RA, in case they want to bring the participant back in.

**Comment by navonacalarco** [comment]
@DESm1th Just following up - has everyone been contacted about this, that needs to be?

**Comment by navonacalarco** [comment]
This is done.
