### ISSUE TITLE
PACTMD scans not making it into our system from MR server 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#827]
Hi guys,

When following up with issue #821 (check the DTI scans closely over the past couple of days), I noticed that there seems to be PACTMD scans that have not made it into our system.

If you compare the 'Scan Completed' survey data (accessible through REDCap) or the files on the MR server with what's in XNAT, you'll see that several participants' data hasn't made it in. (This is also the case for ASDD as per #824).

I'm assigning you because this is your study for QC, but I'd be happy to help.

**Comment by djoverton** [comment]
Finished QC for the outstanding PACTMD scans.

**Comment by navonacalarco** [comment]
Great, thanks! Now we should compare the files on the MR server with those in XNAT/our system.

**Comment by navonacalarco** [comment]
@djoverton @tomwright01

As mentioned at meeting, just wanted to follow up re: 
PACTMD_CMH_0110044_01_01 (6183)
PACTMD_CMH_0110043_01_01 (6181)
PACTMD_CMH_0110036_02_01 (6166)

These are the PACTMD scans collected on the days last week when the DTI was on the fritz.
The good news is these files now exist in our system. though we only have a QC page for PACTMD_CMH_0110043_01_01.

If the FSLview video shows the digital-type artifact JDV showed us, we should email AV and Dr. Mulsant, and cc tigrlab@camh.ca.

**Comment by djoverton** [comment]
It appears that PACTMD_CMH_0110044_01_01 (6183) and PACTMD_CMH_0110043_01_01 (6181) do indeed have very severe artifacts. PACTMD_CMH_0110036_02_01 (6166) and PACTMD_CMH_0100024_02_01 (6203) don't appear to be on the filesystem yet, despite existing on the MR server. Will look into why this is.

**Comment by navonacalarco** [comment]
@djoverton Just following up - has everyone been contacted about this, that needs to be?

**Comment by djoverton** [comment]
Hi Navona, sorry, yes -- I checked the two remaining scans that weren't on our system last week (they were both also unusable), and have notified Aristotle and Benoit.

**Comment by navonacalarco** [comment]
Thank you very much! :D
________________________________
