### ISSUE TITLE
Rename all SPINS MRC scans in XNAT/ file system  :raised_hands: 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#828]
It's just become evident that SPINS site MPRC has been assigning scan IDs perfectly sequentially, even when those scan IDs do not match with the participant's study ID (due to ineligibility, drop-out, etc).

So, for example, the scan for participant SPN01_MRC_0004 is named in XNAT as SPN01_MRC_0003, because participant SPN01_MRC_0003 did not receive a scan.

This explains why MPRC's imaging data wasn't looking so good. 

We'll have to:

- [x] communicate with MPRC RAs to re-explain naming convention
- [x]  confirm mapping between all MPRC REDCap and XNAT IDS
- [x]  rename all files in XNAT 
- [x] delete files from our file system
- [x] delete all QC pages
- [ ] ~~rename all EA task files~~~
- [ ] correct metadata/checklist.csv and blacklist.csv as required  
- [x] correct REDCap data

**Comment by navonacalarco** [comment]
[mprc.txt](https://github.com/TIGRLab/admin/files/562878/mprc.txt)

**Comment by navonacalarco** [comment]
Emailed MPRC about SPN01_MRC_0002_01_01 and SPN01_MRC_0018_01_01 : scans that exist in XNAT, but do not have a corresponding clinical ID indicated by 'mri_subject_id' REDCap variable.

**Comment by navonacalarco** [comment]
Got a response from MPRC RA today, but question was misunderstood - should hear back soon.

**Comment by navonacalarco** [comment]
Ok, we have some updates. In short, one of our questions is resolved, the other still outstanding:

(1)
CAMH Q: Clinical ID SPN01_MRC_0019 is indicated as MRI ID SPN01_MRC_0018_01_01. But, we don't have a record for SPN01_MRC_0018_01_01 in the XNAT database. So, we need to track down the SPN01_MRC_0018_01_01 scan. Is it possible it wasn't uploaded?

**MPRC A: SPN01_MRC_0018_01_01 is legitimately missing - ID was recorded in REDCap, but shouldn't have been.** 

_Status: resolved_ 

----

(2)
CAMH Q: We do not have a MRI ID for SPN01_MRC_0002_01_01 listed in the REDCap 'mri_study_id' column. However, we do have a record for SPN01_MRC_0002_01_01 in XNAT. So the question here is, who does this SPN01_MRC_0002_01_01 scan belong to?

**MPRC A: This participant was too large for the scanner so it was never completed.**

_Status: Not yet resolved._ Trying to figure out who XNAT data labelled SPN01_MRC_0002_01_01 belongs to as it's a full series (no missing scans). MPRC is checking old study logs for clues, and I'll check pipeline outputs to see if identical to another subjects (i.e., if data from another participant was accidentally duplicated here).

**Comment by navonacalarco** [comment]
Emailed re: XNAT data labelled SPN01_MRC_0002_01_01 again.

**Comment by navonacalarco** [comment]
Ok, and we have an update on that last point question

> CAMH Q: We do not have a MRI ID for SPN01_MRC_0002_01_01 listed in the REDCap 'mri_study_id' column. However, we do have a record for SPN01_MRC_0002_01_01 in XNAT. So the question here is, who does this SPN01_MRC_0002_01_01 scan belong to?

MPRC A: XNAT ID SPN01_MRC_0002_01_01 actually belongs to clinical ID SPN01_MRC_0002. However, SPN01_MRC_0002 dropped out of the study, and was later re-enrolled, and completed a second scan (labelled in XNAT as SPN01_MRC_0049_01_01). **So, the scan in XNAT labeled SPN01_MRC_0002_01_01 should be removed/deleted, as it has been replaced with SPN01_MRC_0049_01_01.**

@josephdviviano Thanks for your patience sorting this out. We can now move forward with renaming. Final mapping attached. 

[mprc_final.txt](https://github.com/TIGRLab/admin/files/617283/mprc_final.txt)

**Comment by navonacalarco** [comment]
@josephdviviano confirmed that the last entry on our spreadsheet  (clinical ID SPN01_MRP_0083; XNAT ID SPN01_MRP_0075_01_01 is indeed the last _doublet_ to be rename; i.e., no other new, properly named scans exist in XNAT.

**Comment by josephdviviano** [comment]
All of the subject names are correct,

all of the session names are **wrong**. 

I don't have a good solution for this and Tom can't remember if this matters, so I'm just going to leave it as is. The export tool **should** just use the subject name.

**Comment by navonacalarco** [comment]
@josephdviviano Thanks. Can you please leave open until we complete all of the following:

- [x]  rename all files in XNAT
- [ ] delete files from our file system
- [ ] delete all QC pages
- [ ] rename all EA task files
- [ ] correct metadata/checklist.csv and blacklist.csv as required
- [ ] correct REDCap data

**Comment by josephdviviano** [comment]
OK I did some of them.

**Comment by josephdviviano** [comment]
@navonacalarco we don't need to rename the EA task files, fyi

**Comment by navonacalarco** [comment]
@josephdviviano I think that, based on our csv, we should have a record in XNAT named SPN01_MRP_0078_01_01 (this would have formerly been named SPN01_MRP_0072_01_01). But, we don't. Any idea what happened to this scan?

**Comment by josephdviviano** [comment]
I'm guessing we never had it you could ask them to upload it.

Joseph's Phone

**Comment by navonacalarco** [comment]
Ok - I will. Just wanted to confirm that it's possible that SPN01_MRP_0072_01_01 never existed - or, put otherwise, your XNAT API script wouldn't have failed or thrown an error the scan it was looking to rename to SPN01_MRP_0078_01_01 didn't exist (?)

**Comment by josephdviviano** [comment]
I forget the ID but I deleted some subject that had an entry but no data -- MRC said the subject was never scanned. I asked why there was an entry and they never wrote back.

Don't worry about it until someone tells you to worry about it.

**Comment by navonacalarco** [comment]
Need to rename a few scans in XNAT that continued to be improperly named:

REDCap ID  | XNAT ID
------------|--------------
![image](https://cloud.githubusercontent.com/assets/13733654/21530122/863ea600-cd0c-11e6-9dd2-ff891539ffaf.png) | ![image](https://cloud.githubusercontent.com/assets/13733654/21530150/a8c351a8-cd0c-11e6-92ea-a5ff1a57f390.png)

**Comment by navonacalarco** [comment]
There's a temporary checklist_bac.csv and blacklist_bac.csv, but it looks like everything is correct.

![screenshot - 12292016 - 01 47 17 pm](https://cloud.githubusercontent.com/assets/13733654/21552106/57e55440-cdcd-11e6-90d8-48ea69a202a8.png)
