### ISSUE TITLE
Preprocessing fMRI scans for 3T data

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#832]
@josephdviviano

There are no jobs currently running on the queue and only 5 subjects have non-empty folders inside  /archive/data/DTI3T/pipelines/fmri/rest/. Could you please re-run the preprocessing pipeline or look into why the subjects were not preprocessed? Thank you!!

**Comment by josephdviviano** [comment]
For the ones that are done do they look complete

Joseph's Phone

**Comment by sabashahab** [comment]
No - they have most of the files but a few are missing. The SPINS fmri/rest/subID folder has 40 files whereas the DTI3T fmri/rest/subID folder only has 37 files. The two csv files are missing from the 3T dataset.

**Comment by josephdviviano** [comment]
Looks like they're getting stuck with imitate observe for an unknown
reason... I'll figure that out later, but am running the rest data now

Joseph's Phone

**Comment by sabashahab** [comment]
Thanks!!

**Comment by sabashahab** [comment]
@josephdviviano I noticed that all the jobs you were running on the queue today are all marked as complete. The subject folders in the /archive/data/DTI3T/pipelines/fmri/rest/ directory are all empty though..... there may be another issue that may be unrelated to imob if you ran this one exclusively on the resting state scans.

**Comment by josephdviviano** [comment]
@sabashahab confirmed that it is a bug with the resting state pipeline introduced over the last week or so -- are you OK waiting a few days while you work on the analysis of the SPINS data?

Thanks

**Comment by sabashahab** [comment]
Thanks for looking into this. Yes, I can definitely wait a few days! :)

**Comment by josephdviviano** [comment]
Note to self -- also run on STOPPD spirals for Nick.

**Comment by josephdviviano** [comment]
Hey Saba -- should be there. Some subject aren't making it through, which I'm looking at, but you should be able to begin the analysis.
