### ISSUE TITLE
datman's dm-proc-enigma.py may be broken, use with caution

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#834]
Erin and I were refactoring and starting to write tests for this script, but it's temporarily being left for more urgent issues. In the meantime it may not actually work, so use with caution (and come bug me if it borks and you need it). I'll close this issue when I have made sure it's functional again.

**Comment by edickie** [comment]
The version of datman on the scc is quite old (intentionally) so that
dm-proc-enginma and dm-proc-freesurfer are still working the way they have
since July..

Will look more into testing this later this week

**Comment by DESm1th** [comment]
I've gotten this working again so I'm closing this issue, but it's still in need of refactoring and some tests. I'll work on this later, as soon as I get a bit more time.
