### ISSUE TITLE
Reset Avi XNAT password

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#842]

**Comment by navonacalarco** [comment]
@josephdviviano Need your help with this one. 

This is Avi's user name as displayed by tigrlab:

![a](https://cloud.githubusercontent.com/assets/13733654/20071005/b8f5c784-a4f0-11e6-90fe-239de3d185a1.png)

But, when she tries to reset her password (which doesn't work) here:

![1](https://cloud.githubusercontent.com/assets/13733654/20071030/d52f5294-a4f0-11e6-9f4a-e518dc59f461.png)

We see:

![2](https://cloud.githubusercontent.com/assets/13733654/20071036/dad810b4-a4f0-11e6-83ad-ace3071ba9a9.png)

Do you know what's going on here?

**Comment by josephdviviano** [comment]
Check your email

**Comment by navonacalarco** [comment]
Thanks
