### ISSUE TITLE
fix Rachael and Lee write access to metadata folder (DBDC ASDD)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#844]
DBDC ASDD for RL, DBDC for LP

**Comment by tomwright01** [comment]
TLDR; Moving QC processing to web interface will solve this problem

Solving this with file systems permissions is not simple, it would involve
- creating a group for each project e.g. RA_DBDC
- adding the kimel-data group to the new groups
- adding Rachael and Lee to the relevant new group
- giving group ownership on checklist.csv and blacklist.csv to the new group

Alternately the web interface allows updating checklist and blacklist, edits are made by the user running the web interface.

**Comment by navonacalarco** [comment]
OK, thanks. Let's leave open for now so we remember that all external people (without kimel_data) can't actually sign off on QC.

**Comment by navonacalarco** [comment]
@tomwright01 Just ran into Rachael and we just wanted to make sure that this will not be an issue when we move to the dashboard - later this week?

**Comment by tomwright01** [comment]
Think we are good with entries through dashboard. Closing, feel free to reopen if required.
