### ISSUE TITLE
PACTMD uploads to xnat failing

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#847]
zip archives for:
PACTMD_CMH_3070047_01_01.zip 
PACTMD_CMH_0100029_02_01.zip

fail to upload with error: Upload included files for multiple imaging sessions.

**Comment by josephdviviano** [comment]
If these came from the MRI FTP server directly it mean's they have done some surgery downstairs. Is that so?

**Comment by tomwright01** [comment]
The 'Upload included files for multiple imaging sessions' is a common error. Often occurs on 'secondary' type files which have a different session id. The uploads end up in prearchive, scans are grouped according to session UID. Archives can be manually pushed into Xnat, Xnat will label the session with the session UID from the last group of files imported.

Cant over-ride the upload, these files will still need manual moving from pre-archive. This will show up as a 'failed to upload' error in the nightly log file. dm2-xnat-upload.py now checks if the Xnat session id matches any of the scans in an archive before warning about this situation for further runs.
