### ISSUE TITLE
SCC runall_pipelines_scc.sh requires a password for each study

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#857]
Not sure if this is an issue or not, because I'm not entirely familiar with how the process worked before.

However, I seem to remember that once the run_pipelines_scc.sh pipeline script was initiated, it would run through each study in sequence.

Now, it stops and asks for a password after each study is completed. For e.g., after running the script, I'm asked for a password for ANDT, and then ASDD, and so forth.

Is that by design or am I doing something wrong? I am acting as Clevis.

**Comment by josephdviviano** [comment]
Are you running this script on the SCC?

**Comment by navonacalarco** [comment]
Yes

**Comment by josephdviviano** [comment]
Which line in the script is prompting you for a password? There should be no SSHing involved.

Unless @edickie added in a feature that copies logs between machines. This will only work if you have ssh-keys between the login node and all of the dev nodes.

**Comment by edickie** [comment]
oh this makes sense, Tom changed runall_pipelines_scc.sh so that it is
intended to be run from tigrsrv...It now does an ssh to the scc for each
project

**Comment by edickie** [comment]
we added this so that runall_pipelines_scc.sh could be added to the crontab
on tigrsrv

**Comment by navonacalarco** [comment]
OK great. Just in case this is relevant to anyone else (and for a record for myself):

1. It will soon be the case that the overnight pipelines are run automatically - won't be a need to push off manually
2. If we need to run for a particular study before the automatic overnight pipelines, do so from the given study's **bin** folder, from the SCC

Thanks all!
