### ISSUE TITLE
write standard README for all burned MR CDs (for radiologists/ physicians)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#858]
@josephdviviano I can do this! Just wondering if anything is in existence/ if there's anything you think needs to be included

**Comment by josephdviviano** [comment]
Hi @navonacalarco what might be useful would be to include a folder with DICOM viewer tools for windows and mac on the CDs as well as a basic readme on how to install them. Most radiologists should know how to do this but we've had one or two questionable back-and-forths with radiologists who don't know how to open dicom files (actually).

**Comment by navonacalarco** [comment]
Ok will do. Thanks!

**Comment by navonacalarco** [comment]
Alright, we've had a second imaging centre/ group of doctors say they can't open our dicoms. I'm going to find a DICOM view tool today.

Where in the file system makes sense to keep such a thing?

**Comment by josephdviviano** [comment]
We typically keep stuff like that in `/projects/admin/software`

**Comment by navonacalarco** [comment]
Done! There's a reader for Mac, Windows, and Unix (Mango), as well as a pdf of instructions and a standard `README` in `/projects/admin/software`.
