### ISSUE TITLE
SPINS phantom IDs

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#859]
At all sites:
1. AV
2. Miklos
3. Bob

Does this need to go anywhere other than metadata/human-phantom-IDs.csv?

**Comment by josephdviviano** [comment]
No that should be enough

**Comment by navonacalarco** [comment]
OK great. Going to leave this open until we actually have the scans.

At the moment, XNAT has

CAMH
SPN01_CMH_P001_03_01  AV
SPN01_CMH_P002_03_01  Miklos
SPN01_CMH_P003_03_01  Bob

MRC
SPN01_MRP_P001_03_01     AV
SPN01_MRP_P003_03_01     Bob
SPN01_MRP_P003_03_02     Bob
SPN01_MRP_P005_01_01    Miklos??

ZHH
upload not yet present

**Comment by josephdviviano** [comment]
@navonacalarco what do I need to do?

**Comment by navonacalarco** [comment]
Nothing - just assigned to you and me so we don't let this one slip. AV asked on the call to let us know when the uploads are done / clarify the naming, and I bet that the Techs will email you.

**Comment by josephdviviano** [comment]
Great! After we get everything in I can take care of the analysis with you



JDV

**Comment by navonacalarco** [comment]
Emailed ZHH and ZHP appear to be not yet uploaded.

**Comment by navonacalarco** [comment]
Alright, we have ZHH's ZHP scans:
SPN01_ZHP_P001_03_01 AV
SPN01_ZHP_P002_03_01 Miklos
SPN01_ZHP_P003_03_01 Bob
