### ISSUE TITLE
Possible exclusion of PACTMD_CMH_0110043_01

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#860]

**Comment by navonacalarco** [comment]
Hey @djoverton 

What you did looks right to me!

Two things that I would add: (i) in addition to indicating the scan name of problematic scans, indicate the associated series number (to eliminate any confusion about which acquisition you're talking about), and (ii) indicate that the artifacts are the result of motion (and possibly the type of motion as indicate on Tech Notes; hand, legs, and coughing).

**Comment by djoverton** [comment]
Thanks; added these details to the checklist, and will not be excluding this scan.
