### ISSUE TITLE
discuss final voxel size for fMRI outputs

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#868]
@josephdviviano I noticed that the voxel sizes of the fMRI pipeline outputs are different for RST and SPRL outputs from STOPPD. 

For the current pilot analysis, Nick's pooling the acute phase scans across the 4 sites, so we need the same voxel sizes for both.

For now, I think I will rerun the last steps of the pipeline (after filtered..for only the STOPPD SPRL, with eh RST voxel size, into a separate folder (my projects), so that Nick can do his pilot analysis on Monday.

Should we consider changing dims settings for the SPRL pipeline?

**Comment by josephdviviano** [comment]
Hi Edickie, you could just resampling the data post analysis. Look at
'3dResample'

We could reslice everything to the same resolution as well, it just
increases our multiple comparisons problem in cases where we don't care
about combining data. Typically you want to keep your data as close to
native resolution as possible to mitigate multiple comparisons problems and
reduce the autocorrelation of the data.

Joseph's Phone

**Comment by josephdviviano** [comment]
OK -- ED convinced me and all scans are being re-run to be output at 3mm^3.
