### ISSUE TITLE
take the keyboard away from robo-Tom :p

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#885]
![screen shot 2016-11-18 at 4 26 12 pm](https://cloud.githubusercontent.com/assets/13733654/20447253/de771684-adab-11e6-849f-2b59c7dee679.png)

**Comment by djoverton** [comment]
#wontfix

**Comment by tomwright01** [comment]
ur no fun!!!

**Comment by josephdviviano** [comment]
but what will I read?

**Comment by navonacalarco** [comment]
hahahahah
