### ISSUE TITLE
Followup midweek with Miklos' SPINS scans

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#889]
- Peter to upload early in week.

- Ensure we have 1 SPINS scan on the old GE scanner (2/12/2015), and 2 on the new Siemens Prisma (9/30 and 10/31). So, there should be 1 '_ZHH_' and '2 _ZHP_'.

- Ensure incorrect scans deleted.

**Comment by navonacalarco** [comment]
Emailed again.

**Comment by djoverton** [comment]
Hey @navonacalarco, any updates on this?

**Comment by navonacalarco** [comment]
Nope, other than I emailed another time.

**Comment by navonacalarco** [comment]
Response from MPRC - will do this midweek, this week. Leaving open so don't forget.

**Comment by navonacalarco** [comment]
Update from PK:

>I have not yet had a chance to find and restore these old MRI exams, and make new copies for John.  We have had many time-consuming requests about old data, on top of new MRI scans and trying to figure out the new Siemens Prisma.  I will try to get to this early next week.

John:
If you can send someone over to NSUH to dig through my records and archive discs and make the new copies before I get a chance, I will be happy to point that person in the direction of the relevant information.

Leaving open to make sure this actually happens.

**Comment by navonacalarco** [comment]
PK emailed saying errors with DVD, very laborious - forwarded to AV. Dr. Malhotra has asked Miklos to ask Ivana to help.

**Comment by navonacalarco** [comment]
Tried to follow up ... no response from anyone for several days. I think we're going to treat this as abandoned. We have the other PIs' data, and this was technically an "extra".
