### ISSUE TITLE
rename SPINS ZHH EA tasks from 1-3 (instead of n +1 +1)?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#890]
Right now, the number in the file name reflects series. It would be much better if, like CMH and MRC, the number in the file name was 1-3. It's a bit of a nuisance.

Do you guys agree this is worth doing?

If so, perhaps we can use API after JDV figures it out for the SPINS MPRC renaming - should be a similar process, I think.

**Comment by josephdviviano** [comment]
@navonacalarco no this isn't worth doing. None of the scripts that analyse these data rely on those numbers.

**Comment by navonacalarco** [comment]
Ok!
