### ISSUE TITLE
datman should assert valid subject IDs, and fail gracefully if required, before trying to do anything else with a subject

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#898]
```
jviviano@nissl:/archive/data/DTI3T/data/nii/DTI_CMH_H149_01$ dm2-xnat-extract.py DTI3T DTI_CMH_H149_01

ERROR:datman.xnat:No records returned from xnat server to query:https://xnat.imaging-genetics.camh.ca:443/data/archive/projects/None/subjects/DTI_CMH_H149_01?format=json
WARNING:datman.xnat:Session:DTI_CMH_H149_01 not found in study:None
```

**Comment by josephdviviano** [comment]
@tomwright01 any insights?

**Comment by josephdviviano** [comment]
We figured this out: 

`dm2-xnat-extract.py DTI3T DTI_CMH_H149_01` produces an error because `DTI_CMH_H149_01` is not a subject, but `DTI_CMH_H149_01_01` is. 

A better organisation would assert that the session id submitted is valid before trying anything else, so that we don't get errors that distract from the submitted subject ID being incorrect.

**Comment by tomwright01** [comment]
Problem with this is when it is called to process more than one subject. Don't want it to fail on a single bad name. Changed code to raise a more informative error.
