### ISSUE TITLE
SGE enable all FSL versions

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#90]

**Comment by josephdviviano** [comment]
What is going on with this issue? Are there still non-sge compatible versions?

**Comment by pipitone** [comment]
> What is going on with this issue? Are there still non-sge compatible versions? 

I'm not sure. I believe you were handling this one.

**Comment by josephdviviano** [comment]
Right, I'll figure it out. Just forgot the details as this was a while back and wasn't sure if someone with a better memory had it :-).

Is Tris still having issues?

**Comment by trislett** [comment]
None at all.

**Comment by josephdviviano** [comment]
I remember fixing at least one of the versions... I'll go through them to make sure all are fixed and close this.

**Comment by pipitone** [comment]
As you go through this, can you fix #109 at the same time. Should be an easy fix.

**Comment by josephdviviano** [comment]
This has been accomplished by re-writing fsl_sub in all versions of FSL.

It now checks to see if SGE_ON == 'true'. If so, it will submit to the queue. Users can go to sequential submission by setting the SGE_ON variable to anything else (maybe 'false').
