### ISSUE TITLE
scc pipeline fail with syntax error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#902]
/bin/sh: 1: Syntax error: EOF in backquote substitution

**Comment by josephdviviano** [comment]
@edickie this isn't enough information to solve the problem. Which script has a syntax error?

**Comment by edickie** [comment]
email subject line: Cron <clevis@tigrsrv>
/archive/code/bin/runall_pipelines_scc.sh 2>&1 | tee
/archive/logs/`/bin/date +%Y-%m-

email contents:
/bin/sh: 1: Syntax error: EOF in backquote substitution

**Comment by tomwright01** [comment]
missing escape character in ansible copy of data.cron. Fixed
