### ISSUE TITLE
printer stopped working

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#903]
From MRSDTI. I'm using the `camh/` prefix. It did work before.
![screenshot - 11252016 - 04 10 26 pm](https://cloud.githubusercontent.com/assets/13733654/20635334/e89af65c-b329-11e6-98c5-4a35956f975d.png)

**Comment by josephdviviano** [comment]
you should be using camh\ not camh/

JDV

**Comment by navonacalarco** [comment]
![screen-shot-2013-03-15-at-6-55-34-pm](https://cloud.githubusercontent.com/assets/13733654/20672866/c4867998-b550-11e6-9aad-c65299298392.png)
