### ISSUE TITLE
Set up tDCS study (PI: Dr. Foussias) in XNAT and file system

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#906]
Just found out that first scan was _last_ week:

ID: tdcs_cmh_001
DATE: Wednesday November 23
TIME: 1pm

I made a study folder `TDCS` and `docs` folder and dropped the protocol in there, as it contains the sFTP login and password. It looks similar to the ViPR protocol (one noticeable difference: switched from spiral to EPI+fieldmaps).

@edickie @josephdviviano I haven't set up a study before; what all needs to be done?

**Comment by josephdviviano** [comment]
Do we have a PDF from the MR lab with our SFTP login / password etc? If not, we need that to begin.

I can walk you through the process in person.

**Comment by navonacalarco** [comment]
Yep : 

> I made a study folder TDCS and docs folder and dropped the protocol in there, as it contains the sFTP login and password.

:+1:

**Comment by navonacalarco** [comment]
Reopening as I still have some stuff to do here.

**Comment by navonacalarco** [comment]
- [ ] in `bin` folder, do we need `run_pipelines_scc.sh`?
- [ ] in `bin` folder, do we need `run_data_kimel.sh`?
- [ ] do we need anything in `code` (currently empty)
- [ ] in `data` folder, do we need a number of folders (bkup, civet, hcp, msn, ndar, nrrd)
- [ ] how do we get `logs` going?
- [ ] how do we get `pipelines` going?

**Comment by navonacalarco** [comment]
Thanks @josephdviviano

**Comment by josephdviviano** [comment]
np
