### ISSUE TITLE
COGBDY_CMH_27B009_01_01 Zip archive doesn't match XNAT

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#911]
The dicoms in zip file COGBDY_CMH_27B009_01_01.zip do not match those on XNAT for the same session.

xnat session uid:  1.2.840.113619.2.25.4.1443961.1471014129.731
zip session uid:    1.2.840.113619.6.336.159596117309642899209725123842087134514

xnat acquisition date: 20160812
zip acquisition date:   20130814

**Comment by josephdviviano** [comment]
Might have been a manual error. 2013 would be before the MRFTP thing was set up, everything was organised by hand.

Could confirm other relevant details in this spreadsheet: `/archive/data/COGBDY/metadata/raw/cogbdy-log.xls`

**Comment by tomwright01** [comment]
Session has two experiments in xnat. Experiment BDJM040 contains secondary files. Deleting.
