### ISSUE TITLE
documentation: how to set up new study in XNAT and file system 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#912]
Will get to this when I can; stub is [here.](https://github.com/TIGRLab/documentation/wiki/Study-Setup) 

@josephdviviano and @tomwright01 and whoever else is free to fill in the gaps.

:)

**Comment by josephdviviano** [comment]
Hey @navonacalarco I can take care of this but I think it would be better for you to give it a shot, it should help you remember for the future.

**Comment by navonacalarco** [comment]
Hey @djoverton, just wondering how the setup of the "new" studies is going, and if you have anything to add to the documentation stub?

**Comment by djoverton** [comment]
Hey Navona, they are set up (minus a couple of persistent errors, but they don't affect all subjects and most QC pages are generated). And yes, I will add to that documentation.

**Comment by djoverton** [comment]
I have added most of the pertinent information to this. There might be a few small things missing, but closing this for now.
