### ISSUE TITLE
write up documentation for Monday lauch of QC dashboard!

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#913]
Stub here: https://github.com/TIGRLab/documentation/wiki/QC---dashboard

Plus, whoever else wants to pitch in. :)

**Comment by josephdviviano** [comment]
Hey @navonacalarco I can take care of this but I think it would be better for you to give it a shot, it should help you remember for the future.

**Comment by navonacalarco** [comment]
@josephdviviano Tom and I are taking care of this, just wanted to give you (and others) the opportunity to add anything you think might be useful.....

Do you think I need to "remember for the future" because you, in fact, are commenting from the future? :p 
![screen shot 2016-11-29 at 1 13 15 am](https://cloud.githubusercontent.com/assets/13733654/20720525/764abf04-b62d-11e6-9170-07f01df6d4c7.png)

**Comment by josephdviviano** [comment]
Sorry I meant this for another issue...

**Comment by navonacalarco** [comment]
Alright, this is coming together. But, we need to flesh out 2 things (I've written 'NEED HELP HERE' directly above):

On the `Phantoms ` tab, describe:
FMRI:
:black_small_square: rdc
:black_small_square:sfnr
DTI:
:black_small_square:AVENyqratio
T1:
:black_small_square:c1
:black_small_square:c2
:black_small_square:c3
:black_small_square:c4 
 
On the `Subjects` tab, describe:
FMRI
:black_small_square:ScanLength
:black_small_square:mean_fd
:black_small_square:mean_sfnr
DTI
:black_small_square:#ndirs
:black_small_square:meanRELrms
:black_small_square:tsnr_bX 

@djoverton @tomwright01 @edickie @josephdviviano could you please add a sentence or two of what these metrics are / what to look for. 

https://github.com/TIGRLab/documentation/wiki/QC---dashboard

**Comment by navonacalarco** [comment]
@josephdviviano Got his info from the SPINS annual meeting slides - just need phantom T1 c1-4.

**Comment by navonacalarco** [comment]
Email has been set to Drs. Ameis' and Foussias' staff/students! Thanks everyone.

**Comment by josephdviviano** [comment]
Done! Documentation looks stellar Navona!
