### ISSUE TITLE
missing IMOBs data in p[iplines

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#917]
The following cases do not have data in the /archive/data/SPINS/pipelines/fmri/imob/ directory even though my records seem to indicate they should have good usable IMOBs scans. 

SPN01_CMH_0006_01
SPN01_CMH_0009_01
SPN01_CMH_0010_01
SPN01_CMH_0018_01
SPN01_CMH_0032_01
SPN01_CMH_0035_01
SPN01_CMH_0037_01
SPN01_CMH_0045_01
SPN01_CMH_0049_01
SPN01_CMH_0053_01
SPN01_CMH_0064_01
SPN01_CMH_0071_01
SPN01_CMH_0074_01
SPN01_CMH_0077_01
SPN01_CMH_0078_01
SPN01_CMH_0081_01
SPN01_CMH_0082_01
SPN01_CMH_0083_01
SPN01_CMH_0084_01
SPN01_CMH_0085_01
SPN01_CMH_0088_01
SPN01_CMH_0089_01
SPN01_CMH_0090_01
SPN01_CMH_0092_01
SPN01_CMH_0098_01
SPN01_MRC_0018_01
SPN01_ZHH_0016_01
SPN01_ZHH_0026_01
SPN01_ZHH_0027_01
SPN01_ZHH_0035_01
SPN01_ZHH_0040_01
SPN01_ZHH_0041_01
SPN01_ZHH_0042_01
SPN01_ZHH_0046_01
SPN01_ZHH_0050_01
SPN01_ZHH_0051_01
SPN01_ZHH_0055_01
SPN01_ZHH_0058_01
SPN01_ZHH_0059_01

**Comment by josephdviviano** [comment]
Looks like the queue has been broken for the last few weeks.

**Comment by colinhawco** [comment]
We can close this off. There was some sort of error in my matlab mapping between file names and lsit of excluded participants. I'll see if I can adjust it and confirm for those for whom I know we should have data we do have data, but so far I don't see any issues.
