### ISSUE TITLE
Add redcap-xnat linking to run scripts

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#919]
The script has been ready to go for a while, but isn't being run automatically yet. It needs to be added to each project's run script.

**Comment by DESm1th** [comment]
The change to the config files forces a bit of a rewrite to the xnat-linking script. Working on that now.

**Comment by navonacalarco** [comment]
@DESm1th just FYI, `tigrlab` now has a token for the 'Scan Completed' survey! Can be found in REDCap under Applications > API.

:)

**Comment by DESm1th** [comment]
Thanks Navona!

**Comment by DESm1th** [comment]
This is done now.
