### ISSUE TITLE
Set up server UPSes to shutdown servers on low battery

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#92]
See #67, but this issue is for servers.

**Comment by josephdviviano** [comment]
@pipitone are any of our servers on UPSs? I know `tigrsrv` isn't, but `hal` has this built in. That leaves `kimsrv`.

**Comment by pipitone** [comment]
kimsrv is, yes.

**Comment by josephdviviano** [comment]
I'm not sure this is possible on our ESXI system http://serverfault.com/questions/462993/vmware-esxi-shutdown-triggered-by-apc-ups-connected-via-usb
