### ISSUE TITLE
SPN01_ZHH_P003, SPN01_ZHH_P002, SPN01_ZHH_P001

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#930]
Session has wrong name in archive SPN01

Session also appears in archive SPN02 and SPN03 with the correct name.

I assume the session in archive SPN02 is correct and the others can be deleted?

Assigning Dawn as these sessions in SPN01 and SPN03 are shared. Should SPN02 be shared?

**Comment by josephdviviano** [comment]
Removed all of these shared subjects. They've been there a long time (years) and were just links to files in other projects.
