### ISSUE TITLE
Checklist entries still being duplicated

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#934]
Noticed qc_PACTMD_CMH_0100001_01.html was duplicated again in PACTMD. Not sure yet if it's a dm-qc-report issue or a problem with the way Dashboard is adding to the checklist.

**Comment by DESm1th** [comment]
I just checked a few other files and it looks like the first line of several checklists (at least ANDT, COGBDO, and ASDD) has been duplicated.

Also, I just re-ran my tests and then manually checked the part of dm-qc-report that updates checklists and I'm very sure it's not causing the duplicate issue.

**Comment by tomwright01** [comment]
In all of these cases the inital entry is a .pdf while the duplicate entry
is .html

**Comment by DESm1th** [comment]
Yeah. I wasn't able to reproduce any duplication with dm-qc-report though. If any of the dashboard scripts are modifying the checklists I think that's the source of the issue.

**Comment by DESm1th** [comment]
Ok, the duplication was coming from dashboard/utils.py in the update_checklist method. When the first entry was checked the index was set to 0, which was causing it to be written each time the script was run. I've fixed this on our archive copy, and I'll delete the new duplicates now.

**Comment by tomwright01** [comment]
Perfect, great catch. Thank you.
