### ISSUE TITLE
Pre-set Dashboard study permissions for each RA

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#936]

**Comment by navonacalarco** [comment]
Name|  GitHub alias | study access
--------|----------|---------------------------
Stephanie Ameis | shameis |  DBDC, PASD, ASDD
Avideh Gharehgazlou | avidehg | DBDC, PASD
Rachael Lyon | rachaellyon |  ASDD, DBDC
Mark Oreilly  | | ASDD
George Foussias | | TDCS, VIPR, VRMD
Jessica D'Arcey | | TDCS, VIPR
Sarah Sapiera | | TDCS, VIPR
Ishraq Siddiqui  | | TDCS, VIPR, VRMD

**Comment by djoverton** [comment]
Excellent, thanks. Can I assume the others without a GitHub account will be "assigned" a name of the form <first letter of first name><last name>, with a number 2 added if the name is taken? I.e., moreilly2, gfoussias (looks like he has an account already, if that's him), jdarcey2, ssapiera, isiddiqui (looks like he has an account too)?

**Comment by navonacalarco** [comment]
No problem! 

As soon as I realized some of the obvious names were taken (by imposters!) I thought we should let them choose in case they have a go-to; emailed them just now and think we'll hear back pretty soon. Is that ok? Sorry for delay.

**Comment by djoverton** [comment]
Alright, in the meantime have added Stephanie, Avideh, and Rachael to the database and set permissions.

**Comment by navonacalarco** [comment]
@djoverton All all there! Thanks so much.

**Comment by djoverton** [comment]
Permissions set for all the remaining users.
