### ISSUE TITLE
Change "Can't read" in html QC pages 'scan length'?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#941]
Hi Dawson,

Not urgent, but would it be easy to change "can't read" for various 'scan length' entries on the html QC pages to something like "not applicable" (for T1, FMAPS, etc)? 

I ask because I think that, with external people now involved with QC, "can't read" will be interpreted as a problem rather than intrinsic property.

Thanks!

**Comment by djoverton** [comment]
Good point; done.
