### ISSUE TITLE
Add new MRP and ZHP dicom header nomenclature to the ignore list

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#942]
@josephdviviano can you please remind me where this list lives?

**Comment by josephdviviano** [comment]
Currently the list lives inside of https://github.com/josephdviviano/qcmon/blob/master/bin/qc-headers

Are the values to be ignored in the QC pages for those sites?

**Comment by navonacalarco** [comment]
Thanks @josephdviviano, sorry I missed your response at the time. 

Yes, the values to be ignored are on the QC pages for those sites. For example, from MRP:

![screenshot - 12282016 - 10 41 24 am](https://cloud.githubusercontent.com/assets/13733654/21525274/3d1473be-ccea-11e6-8bbc-2f062a1d0188.png)

Would you prefer me to add to your code directly or send you a list of additional tags?

**Comment by navonacalarco** [comment]
[List here](https://docs.google.com/spreadsheets/d/1aeB_NLKSauNS-Nv6ZOWW7IULdoCiDnxPoCZaSqmITJY/edit?usp=sharing).

**Comment by josephdviviano** [comment]
No problem --

It's in `bin/qc-headers` in `qcmon`.

I've added these entries to the ignore dictionary.

**Comment by navonacalarco** [comment]
Thank you!

**Comment by navonacalarco** [comment]
@josephdviviano  I noticed that the ZHP entries weren't added to the ignore dictionary /archive/code/qcmon/bin/qc-headers. I can add them but just wanted to make sure that that's ok and I'm in the right place.

Thanks!

**Comment by navonacalarco** [comment]
Finally, I think we have all of the tags from the new scanners included here.

**Comment by navonacalarco** [comment]
LOL, why I think this is done?

For ZHP, add:
Allergies
RepetitionTime

**Comment by navonacalarco** [comment]
Added the headers we can safely ignore. Going to keep an eye on the others; will leave open until we get a few more ZHP scans.

**Comment by navonacalarco** [comment]
Looking good.
