### ISSUE TITLE
Add other sites' 'Session' data to the Dashboard for SPINS

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#951]
For SPINS, it seems that only CMH data appears on the `Sessions` tab (or at least, the first 100 entries - which seems to be the maximum selectable - are all CAMH). 

However, the other sites' data is visible the `Phantoms` and `Subjects` tab, so I assume that this is an error?

**Comment by navonacalarco** [comment]
Sorry - just noticed that sorting via the arrow keys displays the ZHH scans, so I guess everything is indeed in there - I think we just need to be able to display more than 100 at a time, as sorting never gets us to MPRC scans in the middle.

**Comment by tomwright01** [comment]
There is a search function, not sure if it supports wildcards at the moment but that could be added.

**Comment by navonacalarco** [comment]
Great. Or, is there a way to display more than 100 entries, or navigate between "pages" of entries?

**Comment by tomwright01** [comment]
Think this is fixed. I had to 'hard reload' the webpage to get the css files to refresh.
