### ISSUE TITLE
GitHub authentication timing out without prompting user to sign back in

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#954]

**Comment by djoverton** [comment]
I believe this is fixed; will re-open if it happens again.

**Comment by navonacalarco** [comment]
![urgh](https://cloud.githubusercontent.com/assets/13733654/21017186/86ae682c-bd36-11e6-8b53-f1fae70823f5.png)

**Comment by djoverton** [comment]
Fix wasn't updated on live server; should be now.
