### ISSUE TITLE
try glusterFS (for a distributed filesystem)

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#957]
last one guys, promise.

**Comment by josephdviviano** [comment]
Success! See https://github.com/TIGRLab/admin/wiki/gluster and #750

**Comment by tomwright01** [comment]
Seems gluster has a problem with rsync.
Symptoms: Tigrsrv runs real slowwww; multiple rsync processes get stuck in state D on tigrsrv.

Seems [this thread](http://nongnu.13855.n7.nabble.com/GlusterFS-FUSE-client-hangs-on-rsyncing-lots-of-file-td207437i20.html) may be relevant, looking into it.

**Comment by josephdviviano** [comment]
Hi @tomwright01 , gluster did not have a problem before though it was very slow (I think we should expect gluster to be slow since it is sitting on top of hardware RAID). It does a tonne of journalling etc.

The issue is, last time I just threw a tonne of folders into the `brick` folder BEFORE instantiating the gluster (since we had almost everything on the drives already), so there were no journals for the majority of the files. This time I'm doing things properly (from scratch) so we're rsyncing an enormous number of files (likely take over 24 hrs, or much longer, to get it all written down the first time).

I imagine we have rsync jobs piling up night after night because of this.

However, tigrsrv running slow does not check out, unless the gluster processes are eating up all of the RAM and CPU. I've not seen that before but its possible that the journalling of millions of files is taxing. The external drives used for backups are not shared with anything else. If tigrsrv is slow, it's also possible that the nightly run scripts that are causing that?

**Comment by tomwright01** [comment]
No one has complained in the last couple of days so perhaps this isn't such a problem. 

There are currently 6 rsync processes to /mnt/backup/xnat and /mnt/backup/projects.
`ps -eo pid,state,time,args |grep rsync`

There is only one management script running
`ps -eo pid,state,time,args |grep python`

I'm only reporting this so we can keep an eye on it next time people start complaining.

**Comment by DESm1th** [comment]
> No one has complained in the last couple of days

It was super slow yesterday and Wednesday, and we were all complaining on slack (which is why all the sloth gifs were being posted). It's ok today though, so hopefully things will work alright now?

**Comment by josephdviviano** [comment]
Tigrsrv's performance shouldn't affect any of the other machines. Are you
confusing network speed and tigrsrv's speed? Or was everyone trying to work
on tigrsrv?

All of those rsync jobs would surely affect the network in a way we can't
really fix, but after everything gets synced over once, we'll be through
the woods

Joseph's Phone

**Comment by tomwright01** [comment]
As gluster is gone, replaced with LVM closing this issue.
