### ISSUE TITLE
formalize process re: how we handle re-uploaded TechNotes 

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#960]
So everyone is on the same page: the problem is that, at times, an original data  zip from the MR server does not contain TechNotes (or contains the wrong TechNotes, or is missing a page, etc).

Instead of deleting and reuploading all the data with the corrected TechNotes, the MR Unit is adding a separate zip file, named exactly the same as the data file, with `Technotes` appended at the end of the file name.

The question is how to treat this new file when it arrives in our system. Namely, we want to make sure that the correct version of the TechNotes is what will be linked to the html QC pages (and referred to by QC staff).

**Comment by navonacalarco** [comment]
Sorry, should have added that the topical case is 20161123_Ex06307_VRNS1MR_VRMO001_Technotes.zip

**Comment by tomwright01** [comment]
Manually replaced Technotes on xnat
Deleted technotes from data/Resources/
Added new archive to metadata/scans as <ignore>
Re-ran XXX_management.sh
