### ISSUE TITLE
note to self: create TDCS gold standards and update regex when get first full scan

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#961]

**Comment by navonacalarco** [comment]
Update: there've been delays and next scan should be next week or week following. Leaving open so don't forget.

**Comment by navonacalarco** [comment]
Update: the first participant was just run, but still not a full scan (several sequences not completed), so leaving open. Next participant booked within a couple weeks.

**Comment by DESm1th** [comment]
The existing regex catches everything so no changes needed. Gold standards are now there for each tag. Ran dm-qc-report once on a subject and everything appears to be set up correctly.
