### ISSUE TITLE
SPRL scans not being linked

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#965]
SPRL scans are uploaded as nifti files, thus are exported directly to the resources/ directory structure. `dm-link-sprl.sh` and `dm-link-vn-sprl.sh` used to link these files to the nii/ folder. Since moving to new format these have not been run.

**Comment by josephdviviano** [comment]
I believe they just need to be added to the run scripts.

**Comment by tomwright01** [comment]
They haven't been converted to the new config format yet. Fixing....

**Comment by tomwright01** [comment]
dm2-link-sprl.py has been converted to new config format. Currently added to the STOPPD management script where it seems to be running correctly.

Which other studies collect SPRL scans?
