### ISSUE TITLE
SPINS MRC_0017 has extra IMOBS

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/admin#967]
MRC_0017 has two imitate and observe scans. The extras are copies of MRC_0018. 

It appears that in the pipelines, the data from MRC_0018 was used for MRC_0017. So the pipelines will need rerunning for that case.

**Comment by josephdviviano** [comment]
Looks like the problem goes deeper than that ... might be my renaming of all of their subjects interacting with an old version to Tom's code. 

I'm going to delete all of  MRC's data and regenerate now.

**Comment by josephdviviano** [comment]
OK they're deleted. At least some of the outputs should be generated tomorrow. Can you check to make sure there's no funny business and get back to me if there is? Thanks.
