### ISSUE TITLE
add link to https://github.com/TIGRLab/documentation/wiki/QC---dashboard from Dashboard

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#979]

**Comment by navonacalarco** [comment]
Maybe link to QC manual as well (though it's in documentation)

**Comment by djoverton** [comment]
Added a "Help" tab at the top of the page, where there are links to the Dashboard wiki and the QC manual.

**Comment by navonacalarco** [comment]
Sweet!
