### ISSUE TITLE
set up Dr. Tarek Rajji's `PASS` study

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#983]
We have some data, but no qc docs, etc.

Can whoever ultimately does this please add to our wiki page [https://github.com/TIGRLab/documentation/wiki/Study-Setup]( https://github.com/TIGRLab/documentation/wiki/Study-Setup). I unfortunately don't remember all the details from the last time 'round.

**Comment by djoverton** [comment]
According to Tom, the following steps need to occur:

- [ ] Create study folders
- [ ] Create project on XNAT (and ensure Clevis has ownership)
- [ ] Create project_settings
- [ ] Create project_management
- [ ] Add project to run.sh
- [ ] Add gold standards

I am working on these now.

**Comment by navonacalarco** [comment]
Ok, more background after talk with AV and some investigation.

It sounds like there's 3 similar-sounding studies:

PASS
- in file system in folder 'PASS'
- likely Melissa's project - cross reference with whatever is in her folder
- PASS folders contain only T1
- this can be ignored

PASAD

- about plasticity in AD, involves TMS, probably early AZ patients and maybe controls
- this study is complete
- maybe started in 2012?
- should be same MRI protocol as RTMSAD
- all scans at CAMH

RTMSAD

- this is - or was - a pilot treatment
- also about TMS in AZ
- contact: Sanjeev (sp?)
- originally had funding for baseline scan, and the second scan was added recently - in past year
- this study would have no controls
- might have scan 1 and 2 for some subjects
- should be same MRI protocol as PASAD
- all scans at CAMH

**Comment by djoverton** [comment]
PASAD:

- [x] Create study folders
- [ ] Create project on XNAT (and ensure Clevis has ownership)
- [x] Create project_settings
- [x] Create project_management
- [ ] Add project to run.sh
- [ ] Add gold standards

RTMSAD:

- [x] Create study folders
- [ ] Create project on XNAT (and ensure Clevis has ownership)
- [x] Create project_settings
- [x] Create project_management
- [ ] Add project to run.sh
- [ ] Add gold standards

- [x] Add projects to tigrlab_config.yaml

**Comment by djoverton** [comment]
Also need mrftppass.txt in each metadata folder; have added those for PASAD and RTMSAD.

**Comment by tomwright01** [comment]
Just for the record (when we get round to writing all this up), mrftppass
is only required for studies where the scanning is performed at CAMH.
Should probably document who to talk to about obtaining the MRUser,
mrftppass and mrfolders settings (Nancy?)

**Comment by djoverton** [comment]
Those need to be requested from the PIs themselves apparently (which I have already done for PASAD and RTMSAD; both CAMH studies).

**Comment by djoverton** [comment]
This has been done for a while and the "Study Setup" wiki page outlines what needs to be done for a new study in the future.
