### ISSUE TITLE
Dashboard: add link to RA notes (Scan Completed survey)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#988]
@DESm1th @tomwright01 

I said I would figure out the REDCap half of this a week ago but got sidetracked. Just posting so we don't forget

**Comment by tomwright01** [comment]
I've added a listener to my dev version of dashboard (http://hebb.camhres.ca:5001/redcap)
Currently it just logs incoming requests with some info about their content. 
If you can setup a redcap Data Entry Trigger to this URL we can take it from there.

**Comment by navonacalarco** [comment]
Update: REDCap DAT can't verify camh res addresses http://hebb.camhres.ca:5001/redcap or srv-dashboard.camhres.ca/. It's not an SSL thing and other addresses work - seems like they're just blocking camhres IPs (?).

Emailed CAMH REDCap server people to see if this is intentional.

**Comment by josephdviviano** [comment]
Not a bad idea to ping Alan Tang about this as well.

**Comment by navonacalarco** [comment]
That's who we pinged! :100:

**Comment by navonacalarco** [comment]
@tomwright01 sent request to poke small holes in the firewall for both the Dashboard and the development server. We've been given a form to fill out, and the change will be considered in the new year.

So, I think if we plan to use the REDCap Data Entry Trigger to link the Scan Completed survey to the Dashboard, we'll have to wait a bit. Shouldn't be too big of an issue as the external RAs doing MRI QC are all the same people who actually fill out this survey (at present), and they have access to it if they request and click through REDCap.

Closing and will re-open in January if necessary.

**Comment by navonacalarco** [comment]
Sent follow up email.

**Comment by navonacalarco** [comment]
Update: Alan tells us this has been implemented (he thinks), but it's not working. Investigating. :shipit:

**Comment by navonacalarco** [comment]
Alan made the following changes:

![screen shot 2017-02-05 at 3 04 51 pm](https://cloud.githubusercontent.com/assets/13733654/22629456/90a7ee6e-ebb4-11e6-879a-de442c012635.png)

@tomwright01 Are these IP address incorrect?

**Comment by navonacalarco** [comment]
Update: REDCap can communicate with http://hebb.camhres.ca:5000/redcap ! :champagne: 

Now, we can get back to planning _how_ to use the REDCap Data Entry Trigger to link the Scan Completed survey to the Dashboard...

**Comment by edickie** [comment]
Hooray!!

**Comment by navonacalarco** [comment]
Tom did this a while ago, and it's working wonderfully. Closing.
