### ISSUE TITLE
Extra header in QC doc??

### ISSUE THREAD

**Issue by rachaellyon** [TIGRLab/admin#990]
NBK (n-back task) appears twice in header-- is this deliberate? Appears as a missing file for this participant

**Comment by DESm1th** [comment]
Hi Rachael, Which QC doc is having this problems with extra NBK headers?

**Comment by rachaellyon** [comment]
I was seeing it in ASDD EF040_02 and EF041_02... not sure if it is in all of the headers going back though?

**Comment by DESm1th** [comment]
The project settings for ASDD said to expect 2 NBK tasks, which is why that was happening. So it was in all the headers. I've changed this to 1, and I'll regenerate the pages.
