### ISSUE TITLE
Mising Tech Notes

### ISSUE THREAD

**Issue by rachaellyon** [TIGRLab/admin#991]
Tech notes have not been linked to QC doc

**Comment by DESm1th** [comment]
Hi Rachael, Which page (or pages) are missing their tech notes?

**Comment by rachaellyon** [comment]
Apologies, I thought issues were linked to the page (I will make sure to cite the page/file going forward). ASDD HEF018_01_01

**Comment by DESm1th** [comment]
Hi Rachael,

This has been fixed now. Sorry for the delay, it turned out to be caused by a well hidden bug that took a while to fix :)
