### ISSUE TITLE
SPN_ZHP_0068_01_01: swap timing files for IM/OBs

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#994]
From ZHH:

> ...accidentally used the NimFace02_NoIFIS_ImtFirst_HS.ebs2 file. As an even number, I should have used NimFace02_NoIFIS_ObsFirst_HS.ebs2 instead. However, as per my instruction, the participant DID observe first and imitate second.

So, we need to swap the timing files when this data arrives in XNAT.

**Comment by josephdviviano** [comment]
No, there's nothing we can do. We need to manually run the GLM for this subject when it comes time to do the analysis.

**Comment by josephdviviano** [comment]
We can do this by manually swapping the IMI and OBS tags, but XNAT will create problems for us in the future, so we should only do this when we finally go to analyse the subjects. I.e., we should just get the scientists to do this for themselves.
